
import { Lesson, QuestionType, Section } from '../types';

const ielts18ReadingPassage1Test3 = `Concrete is everywhere, but it’s bad for the planet, generating large amounts of carbon dioxide – alternatives are being developed

A. Concrete is the second most used substance in the global economy, after water – and one of the world’s biggest single sources of greenhouse gas emissions. The chemical process by which cement, the key ingredient of concrete, is created results in large quantities of carbon dioxide. The UN estimates that there will be 9.8 billion people living on the planet by mid-century. They will need somewhere to live. If concrete is the only answer to the construction of new cities, then carbon emissions will soar, aggravating global warming. And so scientists have started innovating with other materials, in a scramble for alternatives to a universal commodity that has underpinned our modern life for many years.

B. The problem with replacing concrete is that it is so very good at what it does. Chris Cheeseman, an engineering professor at Imperial College London, says the key to its success is the extent to which concrete is used around the world, and is likely to continue to be used. ‘Concrete is not a high-carbon product. Cement is high carbon, but concrete is not. But it is the scale on which it is used that makes it high carbon. The sheer scale of manufacture is so huge, that is the issue.’

C. Not only are the ingredients of concrete relatively cheap and found in abundance in most places around the globe, the stuff itself has marvellous properties: Portland cement, the vital component of concrete, is mouldable and pourable, but quickly sets hard. Cheeseman also notes another advantage: concrete and steel have similar thermal expansion properties, so steel can be used to reinforce concrete, making it far stronger and more flexible as a building material that it could be on its own. According to Cheeseman, all these factors together make concrete hard to beat. ‘Concrete is amazing stuff. Making anything with similar properties is going to be very difficult.’

D. A possible alternative to concrete is wood. Making buildings from wood may seem like a rather medieval idea, but climate change is driving architects to turn to treated timber as a possible resource. Recent years have seen the emergence of tall buildings constructed almost entirely from timber. Vancouver, Vienna and Brumunddal in Norway are all home to constructed tall, wooden buildings.

E. Using wood to construct buildings, however, is not straightforward. Wood expands as it absorbs moisture from the air and is susceptible to pests, not to mention fire. But treating wood and combining it with other materials can improve its properties. Cross-laminated timber is engineered wood. An adhesive is used to stick layers of solid-sawn timber together, crosswise, to form building blocks. This material is light but has the strength of concrete and steel. Construction experts say that wooden buildings can be constructed at a greater speed than ones of concrete and steel and the process, it seems, is quieter.

F. Stora Enso is Europe’s biggest supplier of cross-laminated timber, and its vice-president Markus Mannström reports that the company is seeing increasing demand globally for building in wood, with climate change concerns the key driver. Finland, with its large forests, where Stora Enso is based, has been leading the way, but the company is seeing a rise in demand for its timber products across the world, including in Asia. Of course, using timber in a building also locks away the carbon that it absorbed as it grew. But even treated wood has its limitations and only when a wider range of construction projects has been proven in practice will it be possible to see wood as a real alternative to concrete in constructing tall buildings.

G. Fly ash and slag from iron ore are possible alternatives to cement in a concrete mix. Fly ash, a byproduct of coal-burning power plants, can be incorporated into concrete mixes to make up as much as 15 to 30% of the cement, without harming the strength or durability of the resulting mix. Iron-ore slag, a byproduct of the iron-ore smelting process, can be used in a similar way. Their incorporation into concrete mixes has the potential to reduce greenhouse gas emissions.

But Anna Surgenor, of the UK’s Green Building Council, notes that although these waste products can save carbon in the concrete mix, their use is not always straightforward. ‘It’s possible to replace the cement content in concrete with waste products to lower the overall carbon impact. But there are several calculations that need to be considered across the entire life cycle of the building – these include factoring in where these materials are being shipped from. If they are not transported over long distances, using these alternative materials might not make sense from an overall carbon reduction perspective.’

H. While these technologies are all promising ideas, they are either unproven or based on materials that are not abundant. In their overview of innovation in the concrete industry, Felix Preston and Johanna Lehne of the UK’s Royal Institute of International Affairs reached the conclusion that ‘Some novel cements have been discussed for more than a decade within the research community, without breaking through. At present, these alternatives are rarely as cost-effective as conventional cement, and they face raw-material shortages and resistance from customers.’`;

const ielts18ReadingPassage2Test3 = `The successes and failures of the Doble brothers and their steam cars

A. When primitive automobiles first began to appear in the 1800s, their engines were based on steam power. Steam had already enjoyed a long and successful career in the railways, so it was only natural that the technology evolved into a miniaturized version which was separate from the trains. But these early cars inherited a steam engine’s weaknesses along with its strengths. The boilers were so heavy that they were hard to fit by hand, and they required about twenty minutes to build up pressure before they could be driven. Furthermore, their water reservoirs only lasted for about thirty self-propelled carriages offered quick replenishment. Despite such shortcomings, by the early 1900s it was not uncommon to see such machines shuttling wealthy citizens around town.

B. But the glory days of steam cars were few. A new technology called the Internal Combustion Engine soon appeared, which offered the ability to drive down the road just moments after starting up. At first, these noisy gasoline cars were unpopular because they were more complicated to operate and they had difficult hand-crank starters, which were known to break arms when the engines backfired. But in 1912 General Motors introduced the electric starter, and over the following few years steam power was gradually phased out.

C. Even as the market was declining, four brothers made one last attempt to rekindle the technology. Between 1906 and 1909, while still attending high school, Abner Doble and his three brothers built their first steam car in their parents’ basement. It comprised parts taken from a wrecked early steam car but reconfigured to drive an engine of their own design. Though it did not run well, the Doble boys went on to build a second and third prototype in the following years. Though the Doble boys’ third prototype, nicknamed the Model B, drew the attention of automobile trade magazines due to its numerous improvements over previous steam cars. The Model B proved to be superior to gasoline automobiles in many ways. Its high-pressure steam drove the engine pistons in virtual silence, in contrast to clattering gas engines which emitted the aroma of burned hydrocarbons. Perhaps most impressively, the Model B was amazingly swift. It could do zero to sixty miles per hour in just fifteen seconds, a feat described as ‘remarkable acceleration’ by Automobile magazine in 1914.

D. The following year Abner Doble drove a Model B from Massachusetts to Detroit in order to seek investment in his automobile design, which he used to open the General Engineering Company. He and his brothers immediately began working on the Model C, which they intended to expand upon the innovations of the Model B. The added features such as a key-based ignition in the cabin, eliminating the need for the operator to manually ignite the boiler. With these enhancements, the Dobles’ new car company promised a steam vehicle that would provide all of the convenience of a gasoline car, but with much greater speed. By the following April, the General Engineering Company had received 5,390 deposits for Doble Detroits, which were scheduled for delivery in early 1918.

E. Later that year Abner Doble delivered unhappy news to those eagerly awaiting the delivery of their modern new cars. Those buyers who received the handful of completed cars complained that the vehicles were sluggish and erratic, sometimes going in reverse when they should go forward. The new engine design, though innovative, was still plagued with serious glitches.

F. The brothers made one final attempt to produce a viable steam automobile. In early 1924, the Doble brothers shipped a Model E to New York City to be road-tested by the Automobile Club of America. After sitting overnight in freezing temperatures, the car was pushed out into the road and left to sit for over an hour in the frosty morning air. At the turn of the key, the boiler lit and reached its operating pressure inside of forty seconds. As they drove the test vehicle further, they found that its evenly distributed weight lent it surprisingly good handling, even though it was so heavy. As the new Doble steamer was further developed and tested, its maximum speed was pushed to over a hundred miles per hour, and it achieved about fifteen miles per gallon of kerosene with negligible emissions.

G. Sadly, the Dobles’ brilliant steam car never was a financial success. Priced at around $18,000 in 1924, it was popular only among the very wealthy. Plus, it is said that no two Model Es were quite the same, because Abner Doble tinkered endlessly with the design. By the time the company folded in 1931, fewer than fifty of the amazing Model E steam cars had been produced. For his whole career, until his death in 1961, Abner Doble remained adamant that steam was at least equal to gasoline, if not superior. Given the evidence, he may have been right. Many of the Model E Dobles which have survived are still in good working condition, some having been driven over half a million miles with only normal maintenance. Astonishingly, an unmodified Model E runs so clean it can pass the emissions laws in California today, and they are nearly silent. It is true that technology poses some difficult problems, but you cannot help but wonder how efficient a steam car might be with the benefit of modern materials and computers. Under the current pressure to improve automotive performance and reduce emissions, it is not unthinkable that the steam car may rise again.`;

const ielts18ReadingPassage3Test3 = `Picture this scene. It’s an English literature lesson in a UK school, and the teacher has just read an extract from Shakespeare’s Romeo and Juliet with a class of 15-year-olds. He’s given some of the students copies of No Fear Shakespeare, a kid-friendly translation of the original. For the students, even these literacy demands are beyond them. Another girl can simply can’t focus and her pens and paper to draw. The teacher can ask the No Fear group to identify the key characters and maybe provide a tentative plot summary. He can ask most of the class about character development, and so on, and some of them might be able to support their statements with textual evidence. Now two curious students are wondering whether Shakespeare advocates living a life of moderation or one of passionate engagement.

As a teacher myself, I’d think my lesson went as described above. But wouldn’t this kind of class work better if there weren’t such a huge gap between the top and the bottom? If we put all the kids who needed literacy support into one class, and all the students who want to discuss the virtue of moderation into another?

The practice of ‘streaming’, or ‘tracking’, involves separating students into classes depending on their diagnosed levels of attainment. At a macro level, it requires the establishment of academically selective schools for the brightest students, and comprehensive schools for the rest. Within schools, it means selecting students into a ‘stream’ of general ability or ‘sets’ of subject-specific ability. The practice is intuitively appealing to almost every stakeholder.

I have heard the mixed-ability model attacked by way of analogy: a group hike. The fittest in the group take the lead and set a brisk pace, only to have to stop and wait every 20 minutes. This is frustrating and their enthusiasm wanes. Meanwhile, the slowest ones are not only embarrassed but physically struggling to keep up. What’s worse, they never get a long enough break. They honestly just want to quit. Hiking, they feel, is not for them.

Mixed-ability classes bore students, frustrate parents and burn out teachers. The brightest ones will never summit Mount Qomolangma, and the stragglers won’t enjoy the lovely stroll in the park they are perhaps more suited to. Individuals suffer at the demands of the collective, mediocrity prevails. So: is learning like hiking?

The current pedagogical paradigm is arguably that of constructivism, which emerged out of the work of psychologist Lev Vygotsky. In the 1930s, Vygotsky emphasised the importance of targeting a student’s specific ‘zone of proximal development’ (ZPD). This is the gap between what they can achieve only with support – teachers, textbooks, worked examples, parents and so on – and what they can achieve independently. The purpose of teaching is to provide and then gradually remove this ‘scaffolding’ until they are autonomous. If we accept this model, it follows that streaming students with similar ZPDs would be an efficient and effective solution. And that forcing everyone on the same hike – regardless of aptitude – would be madness.

Despite all this, there is limited empirical evidence to suggest that streaming results in better outcomes for students. Professor John Hattie, director of the Melbourne Education Research Institute, notes that ‘tracking has minimal effects on learning outcomes’. What is more, streaming appears to significantly – and negatively – affect those students assigned to the lowest sets. These students tend to have much higher representation of low socioeconomic class. Less significant is the small benefit for those lucky clever students in the higher sets. The overall result is that the smart stay smart and the dumb get dumber, further entrenching the social divide.

In the latest update of Hattie’s influential meta-analysis of factors influencing student achievement, one of the most significant factors is the teachers’ estimate of achievement. Streaming students by diagnosed achievement automatically limits what the teacher feels the student is capable of. Meanwhile, in a mixed environment, teachers’ estimates need to be more diverse and flexible.

While streaming might seem to help teachers effectively target a student’s ZPD, it can underestimate the importance of peer-to-peer learning. A crucial aspect of constructivist theory is the role of the MKO – ‘more-knowledgeable other’ – in knowledge construction. While teachers are traditionally the MKOs in classrooms, the value of knowledgeable student peers must not go unrecognised either.

I find it amazing to watch students get over an idea to their peers in ways that I would never think of. They operate with different language tools and different social tools from teachers and, having just learnt it themselves, they possess similar cognitive structures to their struggling classmates. There is also something exciting about passing on skills and knowledge that you yourself have just mastered – a certain pride and zeal, a certain freshness to the interaction between ‘teacher’ and ‘learner’ that is often lost by the expert for whom the steps are obvious and the joy of discovery forgotten.

Having a variety of different abilities in a collaborative learning environment provides valuable resources for helping students meet their learning needs, not to mention improving their communication and social skills. And today, more than ever, we need the many to flourish – not suffer at the expense of a few bright stars. Once a year, I go on a hike with my class, a mixed bunch of students. It is challenging. The fittest students realise they need to encourage the reluctant. There are lookouts who report back, and extra items to carry for others. We make it – together.`;

export const ielts18Test3Lessons: Lesson[] = [
  // Test 3
  {
    id: 'b18-t3-l0',
    title: 'Test 3: Listening P1-2',
    section: Section.LISTENING,
    parts: [
      { // Part 1
        questions: [
          { id: 'b18t3lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the form below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t3-p1.mp3', questionText: 'Home address: 52 1 ___ Street, Peacetown', correctAnswers: ['Marrowfield'], transcript: "OK, so what’s the house number and street? It’s 52 Marrowfield Street. Is that M-A-double R-O-W-F-I-E-L-D? That’s right.", transcriptHighlight: "Marrowfield" },
          { id: 'b18t3lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the form below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t3-p1.mp3', questionText: 'Heard about us: from a 2 ___', correctAnswers: ['relative'], transcript: "So how did you hear about our club? Did you look on the internet? I usually do that, but I was talking to a relative the other day and he suggested it.", transcriptHighlight: "relative" },
          { id: 'b18t3lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the form below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t3-p1.mp3', questionText: 'Reasons for joining: to enter competitions, to 3 ___', correctAnswers: ['socialise', 'socialize'], transcript: "I enjoy entering those. Right. Anything else? Well, I also like to socialise with other photographers.", transcriptHighlight: "socialise" },
          { id: 'b18t3lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the form below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t3-p1.mp3', questionText: 'Type of membership: 4 ___ membership (£30)', correctAnswers: ['full'], transcript: "That’s great. So what type of membership would you like? What are the options? It’s £30 a year for full membership or £20 a year if you’re an associate. I’ll go for the full membership, then.", transcriptHighlight: "full membership" },
          { id: 'b18t3lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write NO MORE THAN TWO WORDS.', audioUrl: 'ielts-18/t3-p1.mp3', questionText: "Title of competition: 5 '___'", correctAnswers: ['Domestic Life'], transcript: "Well, the theme was entitled ‘Domestic Life’.", transcriptHighlight: "Domestic Life" },
          { id: 'b18t3lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write NO MORE THAN TWO WORDS.', audioUrl: 'ielts-18/t3-p1.mp3', questionText: 'Instructions: Scene must show some 6 ___', correctAnswers: ['clouds'], transcript: "Oh, sunsets. That’s a great theme. Yes. The instructions were to capture the clouds as well – it couldn’t just be blue sky and a setting sun.", transcriptHighlight: "capture the clouds" },
          { id: 'b18t3lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write NO MORE THAN TWO WORDS.', audioUrl: 'ielts-18/t3-p1.mp3', questionText: 'Feedback to Dan: The 7 ___ was wrong.', correctAnswers: ['timing'], transcript: "I see. So the timing wasn’t right? Yes.", transcriptHighlight: "timing wasn’t right" },
          { id: 'b18t3lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write NO MORE THAN TWO WORDS.', audioUrl: 'ielts-18/t3-p1.mp3', questionText: "Title of competition: 8 '___'", correctAnswers: ['Animal Magic'], transcript: "And then the third competition I entered was called ‘Animal Magic’.", transcriptHighlight: "Animal Magic" },
          { id: 'b18t3lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write NO MORE THAN TWO WORDS.', audioUrl: 'ielts-18/t3-p1.mp3', questionText: 'Instructions: Scene must show 9 ___', correctAnswers: ['(animal) movement'], transcript: "I’m sure – because animals move all the time. That’s what we had to show – there had to be some movement in the scene.", transcriptHighlight: "some movement" },
          { id: 'b18t3lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write NO MORE THAN TWO WORDS.', audioUrl: 'ielts-18/t3-p1.mp3', questionText: 'Feedback to Dan: The photograph was too 10 ___', correctAnswers: ['dark'], transcript: "I got a great shot of a cat in the end. But I took it at night and, well, I suspected that it was a bit dark, which is what I was told.", transcriptHighlight: "a bit dark" },
        ],
      },
      { // Part 2
        questions: [
          { id: 'b18t3lq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO warnings does Dan give about picking mushrooms?', maxSelections: 2, audioUrl: 'ielts-18/t3-p2.mp3', questionText: 'Choose TWO letters, A-E.', options: ["A Don't pick more than one variety of mushroom at a time.", "B Don't pick mushrooms near busy roads.", "C Don't eat mushrooms given to you.", "D Don't eat mushrooms while picking them.", "E Don't pick old mushrooms."], correctAnswers: ["B Don't pick mushrooms near busy roads.", "C Don't eat mushrooms given to you."], transcript: "you should never consume mushrooms picked by friends or neighbours... The other thing to avoid is mushrooms growing beside busy roads for obvious reasons.", transcriptHighlight: "never consume mushrooms picked by friends or neighbours... mushrooms growing beside busy roads" },
          { id: 'b18t3lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO ideas about wild mushrooms does Dan say are correct?', maxSelections: 2, audioUrl: 'ielts-18/t3-p2.mp3', questionText: 'Choose TWO letters, A-E.', options: ['A Mushrooms should always be peeled before eating.', 'B Mushrooms eaten by animals may be unsafe.', 'C Cooking destroys toxins in mushrooms.', 'D Brightly coloured mushrooms can be edible.', 'E All poisonous mushrooms have a bad smell.'], correctAnswers: ['B Mushrooms eaten by animals may be unsafe.', 'D Brightly coloured mushrooms can be edible.'], transcript: "Some edible mushrooms are bright red, for example... Just because you see deer or squirrels eat a particular mushroom doesn’t mean that you can.", transcriptHighlight: "Some edible mushrooms are bright red... Just because you see deer or squirrels eat a particular mushroom doesn’t mean that you can" },
          { id: 'b18t3lq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t3-p2.mp3', questionText: 'What advice does Dan give about picking mushrooms in parks?', options: ['A Choose wooded areas.', "B Don't disturb wildlife.", 'C Get there early.'], correctAnswers: ['C Get there early.'], transcript: "But you need to be there first thing in the morning, as there’s likely be a lot of competition – not just from people but from wildlife too.", transcriptHighlight: "first thing in the morning" },
          { id: 'b18t3lq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t3-p2.mp3', questionText: 'Dan says it is a good idea for beginners to', options: ['A use a mushroom app.', 'B join a group.', 'C take a reference book.'], correctAnswers: ['B join a group.'], transcript: "If you’re a complete beginner, I wouldn’t recommend going alone... If possible, you should go with a group led by an expert", transcriptHighlight: "go with a group led by an expert" },
          { id: 'b18t3lq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t3-p2.mp3', questionText: 'What does Dan say is important for conservation?', options: ['A selecting only fully grown mushrooms', 'B picking a limited amount of mushrooms', 'C avoiding areas where rare mushroom species grow'], correctAnswers: ['B picking a limited amount of mushrooms'], transcript: "You should never pick all the mushrooms in one area – collect only enough for your own needs.", transcriptHighlight: "collect only enough for your own needs" },
          { id: 'b18t3lq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t3-p2.mp3', questionText: 'According to Dan, some varieties of wild mushrooms are in decline because there is', options: ['A a huge demand for them from restaurants.', 'B a lack of rain in this part of the country.', 'C a rise in building developments locally.'], correctAnswers: ['C a rise in building developments locally.'], transcript: "There’s been a decline in some varieties of wild mushrooms in this part of the country. Restaurants are becoming more interested... but the biggest problem is that so many new houses have been built in this area in the last ten years.", transcriptHighlight: "so many new houses have been built" },
          { id: 'b18t3lq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t3-p2.mp3', questionText: 'Dan says that when storing mushrooms, people should', options: ['A keep them in the fridge for no more than two days.', 'B keep them in a brown bag in a dark room.', 'C leave them for a period after washing them.'], correctAnswers: ['A keep them in the fridge for no more than two days.'], transcript: "as soon as you get home, put them in the fridge. They’ll be fine for a couple of days", transcriptHighlight: "fine for a couple of days" },
          { id: 'b18t3lq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t3-p2.mp3', questionText: 'What does Dan say about trying new varieties of mushrooms?', options: ['A Experiment with different recipes.', 'B Expect some to have a strong taste.', 'C Cook them for a long time.'], correctAnswers: ['A Experiment with different recipes.'], transcript: "So everybody knows what a mushroom tastes like, right? Well, you’ll be surprised by the huge variety of wild mushrooms there are. Be adventurous! They’re great in so many dishes – stir fries, risottos, pasta.", transcriptHighlight: "Be adventurous! They’re great in so many dishes" },
        ],
      }
    ]
  },
  {
    id: 'b18-t3-l1',
    title: 'Test 3: Listening P3-4',
    section: Section.LISTENING,
    parts: [
      { // Part 3
        questions: [
          { id: 'b18t3lq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO opinions about the Luddites do the students express?', maxSelections: 2, audioUrl: 'ielts-18/t3-p3.mp3', questionText: 'Choose TWO letters, A-E.', options: ['A Their actions were ineffective.', 'B They are still influential today.', 'C They have received unfair criticism.', 'D They were proved right.', 'E Their attitude is understandable.'], correctAnswers: ['A Their actions were ineffective.', 'E Their attitude is understandable.'], transcript: "Yes, and ultimately, they didn’t achieve anything. And anyway, industrialisation created more jobs than it destroyed. Yes, that’s true – but it probably didn’t seem a positive thing at the time. I can see why the Luddites felt so threatened.", transcriptHighlight: "didn’t achieve anything... I can see why the Luddites felt so threatened" },
          { id: 'b18t3lq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO predictions about the future of work are the students doubtful about?', maxSelections: 2, audioUrl: 'ielts-18/t3-p3.mp3', questionText: 'Choose TWO letters, A-E.', options: ['A Work will be more rewarding.', 'B Unemployment will fall.', 'C People will want to delay retiring.', 'D Working hours will be shorter.', 'E People will change jobs more frequently.'], correctAnswers: ['B Unemployment will fall.', 'D Working hours will be shorter.'], transcript: "And what about lower unemployment? I’m not so sure about that... For example, I can’t see how people are about to have more leisure time, when all the evidence shows people are spending longer than ever at work.", transcriptHighlight: "lower unemployment? I’m not so sure about that... can’t see how people are about to have more leisure time" },
          { id: 'b18t3lq25', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about each of the following jobs?", audioUrl: 'ielts-18/t3-p3.mp3', questionText: '25 Accountants', options: ['A These jobs are likely to be at risk.', 'B Their role has become more interesting in recent years.', 'C The number of people working in this sector has fallen dramatically.', 'D This job will require more qualifications.', 'E Higher disposable income has led to a huge increase in jobs.', 'F There is likely to be a significant rise in demand for this service.', 'G Both employment and productivity have risen.'], correctAnswers: ['G Both employment and productivity have risen.'], transcript: "in fact there are more of them than ever. They’re still really in demand and have become far more efficient.", transcriptHighlight: "more of them than ever... become far more efficient" },
          { id: 'b18t3lq26', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about each of the following jobs?", audioUrl: 'ielts-18/t3-p3.mp3', questionText: '26 Hairdressers', options: ['A These jobs are likely to be at risk.', 'B Their role has become more interesting in recent years.', 'C The number of people working in this sector has fallen dramatically.', 'D This job will require more qualifications.', 'E Higher disposable income has led to a huge increase in jobs.', 'F There is likely to be a significant rise in demand for this service.', 'G Both employment and productivity have risen.'], correctAnswers: ['E Higher disposable income has led to a huge increase in jobs.'], transcript: "Yeah because people’s earning power has gone up so they can afford to spend more on personal services like that.", transcriptHighlight: "earning power has gone up so they can afford to spend more" },
          { id: 'b18t3lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about each of the following jobs?", audioUrl: 'ielts-18/t3-p3.mp3', questionText: '27 Administrative staff', options: ['A These jobs are likely to be at risk.', 'B Their role has become more interesting in recent years.', 'C The number of people working in this sector has fallen dramatically.', 'D This job will require more qualifications.', 'E Higher disposable income has led to a huge increase in jobs.', 'F There is likely to be a significant rise in demand for this service.', 'G Both employment and productivity have risen.'], correctAnswers: ['B Their role has become more interesting in recent years.'], transcript: "Really boring compared to these days, when they’re given much more responsibility and higher status.", transcriptHighlight: "given much more responsibility and higher status" },
          { id: 'b18t3lq28', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about each of the following jobs?", audioUrl: 'ielts-18/t3-p3.mp3', questionText: '28 Agricultural workers', options: ['A These jobs are likely to be at risk.', 'B Their role has become more interesting in recent years.', 'C The number of people working in this sector has fallen dramatically.', 'D This job will require more qualifications.', 'E Higher disposable income has led to a huge increase in jobs.', 'F There is likely to be a significant rise in demand for this service.', 'G Both employment and productivity have risen.'], correctAnswers: ['C The number of people working in this sector has fallen dramatically.'], transcript: "the 1871 census showed that roughly 25% of the population worked on the land... Now it’s less than 0.2%.", transcriptHighlight: "Now it’s less than 0.2%" },
          { id: 'b18t3lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about each of the following jobs?", audioUrl: 'ielts-18/t3-p3.mp3', questionText: '29 Care workers', options: ['A These jobs are likely to be at risk.', 'B Their role has become more interesting in recent years.', 'C The number of people working in this sector has fallen dramatically.', 'D This job will require more qualifications.', 'E Higher disposable income has led to a huge increase in jobs.', 'F There is likely to be a significant rise in demand for this service.', 'G Both employment and productivity have risen.'], correctAnswers: ['F There is likely to be a significant rise in demand for this service.'], transcript: "They barely existed in the 19th century as people’s lifespan was so much shorter. But now of course this sector will see huge growth.", transcriptHighlight: "will see huge growth" },
          { id: 'b18t3lq30', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about each of the following jobs?", audioUrl: 'ielts-18/t3-p3.mp3', questionText: '30 Bank clerks', options: ['A These jobs are likely to be at risk.', 'B Their role has become more interesting in recent years.', 'C The number of people working in this sector has fallen dramatically.', 'D This job will require more qualifications.', 'E Higher disposable income has led to a huge increase in jobs.', 'F There is likely to be a significant rise in demand for this service.', 'G Both employment and productivity have risen.'], correctAnswers: ['A These jobs are likely to be at risk.'], transcript: "The future looks quite bleak for bank clerks... they can certainly make most of the jobs they do now redundant, I think.", transcriptHighlight: "make most of the jobs they do now redundant" },
        ]
      },
      { // Part 4
        questions: [
          { id: 'b18t3lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t3-p4.mp3', questionText: 'would aim to set up legal and 31 ___ ways of improving safety.', correctAnswers: ['technical'], transcript: "we’d need to have a set of legal measures, and we’d also have to develop the technical systems to enable us to prevent such accidents.", transcriptHighlight: "technical" },
          { id: 'b18t3lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t3-p4.mp3', questionText: 'Satellites are now quite 32 ___ and therefore more widespread', correctAnswers: ['cheap'], transcript: "Well, for one thing, satellites are relatively cheap these days, compared with how they were in the past", transcriptHighlight: "cheap" },
          { id: 'b18t3lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t3-p4.mp3', questionText: '(e.g. there are constellations made up of 33 ___ of satellites).', correctAnswers: ['thousands'], transcript: "whole constellations, consisting of thousands of them designed to work together.", transcriptHighlight: "thousands" },
          { id: 'b18t3lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t3-p4.mp3', questionText: 'At present, satellites are not required to transmit information to help with their 34 ___ .', correctAnswers: ['identification'], transcript: "it doesn’t have to send back any information to Earth to allow its identification.", transcriptHighlight: "identification" },
          { id: 'b18t3lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t3-p4.mp3', questionText: 'There are few systems for 35 ___ satellites.', correctAnswers: ['tracking'], transcript: "at present we don’t have anything like enough proper ways of tracking them.", transcriptHighlight: "tracking" },
          { id: 'b18t3lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t3-p4.mp3', questionText: 'Operators may be unwilling to share details of satellites used for 36 ___ or commercial reasons.', correctAnswers: ['military'], transcript: "a satellite may be designed for military purposes, or it may have been launched for commercial reasons", transcriptHighlight: "military" },
          { id: 'b18t3lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t3-p4.mp3', questionText: 'It may be hard to collect details of the object’s 37 ___ at a given time.', correctAnswers: ['location'], transcript: "Details are needed about the object itself, as well as about its location at a particular time", transcriptHighlight: "location" },
          { id: 'b18t3lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t3-p4.mp3', questionText: 'Scientists can only make a 38 ___ about where the satellite will go.', correctAnswers: ['prediction'], transcript: "all that the scientists can do is to put forward a prediction concerning where the satellite is heading next.", transcriptHighlight: "prediction" },
          { id: 'b18t3lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t3-p4.mp3', questionText: 'The information should be combined in one 39 ___ .', correctAnswers: ['database'], transcript: "that will involve creating a single database on which it can be entered.", transcriptHighlight: "database" },
          { id: 'b18t3lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t3-p4.mp3', questionText: 'A coordinated system must be designed to create 40 ___ in its users.', correctAnswers: ['trust'], transcript: "it’s also essential that this system is one that establishes trust in the people that use it", transcriptHighlight: "trust" },
        ]
      }
    ]
  },
  {
    id: 'b18-t3-r2',
    title: 'Test 3: Reading P1',
    section: Section.READING,
    parts: [{
      questions: [
        { id: 'b18t3rq1', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which section contains the following information?', passage: ielts18ReadingPassage1Test3, questionText: '1 an explanation of the industrial processes that create raw materials for concrete', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['G'], passageHighlight: "Fly ash, a byproduct of coal-burning power plants... Iron-ore slag, a byproduct of the iron-ore smelting process" },
        { id: 'b18t3rq2', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which section contains the following information?', passage: ielts18ReadingPassage1Test3, questionText: '2 a reference to the various locations where high-rise wooden buildings can be found', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['D'], passageHighlight: "Vancouver, Vienna and Brumunddal in Norway are all home to constructed tall, wooden buildings." },
        { id: 'b18t3rq3', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which section contains the following information?', passage: ielts18ReadingPassage1Test3, questionText: '3 an indication of how widely available the raw materials of concrete are', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['C'], passageHighlight: "ingredients of concrete relatively cheap and found in abundance in most places around the globe" },
        { id: 'b18t3rq4', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which section contains the following information?', passage: ielts18ReadingPassage1Test3, questionText: '4 the belief that more high-rise wooden buildings are needed before wood can be regarded as a viable construction material', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['F'], passageHighlight: "only when a wider range of construction projects has been proven in practice will it be possible to see wood as a real alternative" },
        { id: 'b18t3rq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1Test3, questionText: 'Wood is a traditional building material, but current environmental concerns are encouraging 5 ___ to use wood in modern construction projects.', correctAnswers: ['architects'], passageHighlight: "climate change is driving architects to turn to treated timber" },
        { id: 'b18t3rq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1Test3, questionText: 'Using wood, however, has its challenges. For example, as 6 ___ in the atmosphere enters wood, it increases in size.', correctAnswers: ['moisture'], passageHighlight: "Wood expands as it absorbs moisture from the air" },
        { id: 'b18t3rq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1Test3, questionText: 'In one process, 7 ___ of solid wood are glued together to create building blocks.', correctAnswers: ['layers'], passageHighlight: "stick layers of solid-sawn timber together" },
        { id: 'b18t3rq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1Test3, questionText: 'Experts say that wooden buildings are an improvement on those made of concrete and steel in terms of the 8 ___ with which they can be constructed and how much noise is generated by the process.', correctAnswers: ['speed'], passageHighlight: "can be constructed at a greater speed... and the process, it seems, is quieter" },
        { id: 'b18t3rq9', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct person, A, B, C or D.', passage: ielts18ReadingPassage1Test3, questionText: '9 The environmental advantage of cement alternatives may not be as great as initially assumed.', options: ['A Chris Cheeseman', 'B Markus Mannström', 'C Anna Surgenor', 'D Felix Preston and Johanna Lehne'], correctAnswers: ['C Anna Surgenor'], passageHighlight: "using these alternative materials might not make sense from an overall carbon reduction perspective." },
        { id: 'b18t3rq10', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct person, A, B, C or D.', passage: ielts18ReadingPassage1Test3, questionText: '10 It would be hard to create a construction alternative to concrete that offers so many comparable benefits.', options: ['A Chris Cheeseman', 'B Markus Mannström', 'C Anna Surgenor', 'D Felix Preston and Johanna Lehne'], correctAnswers: ['A Chris Cheeseman'], passageHighlight: "Making anything with similar properties is going to be very difficult." },
        { id: 'b18t3rq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct person, A, B, C or D.', passage: ielts18ReadingPassage1Test3, questionText: '11 Worries about the environment have led to increased interest in wood as a construction material.', options: ['A Chris Cheeseman', 'B Markus Mannström', 'C Anna Surgenor', 'D Felix Preston and Johanna Lehne'], correctAnswers: ['B Markus Mannström'], passageHighlight: "the company is seeing increasing demand globally for building in wood, with climate change concerns the key driver." },
        { id: 'b18t3rq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct person, A, B, C or D.', passage: ielts18ReadingPassage1Test3, questionText: '12 Expense has been a factor in the negative response to the development of new cements.', options: ['A Chris Cheeseman', 'B Markus Mannström', 'C Anna Surgenor', 'D Felix Preston and Johanna Lehne'], correctAnswers: ['D Felix Preston and Johanna Lehne'], passageHighlight: "At present, these alternatives are rarely as cost-effective as conventional cement" },
        { id: 'b18t3rq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct person, A, B, C or D.', passage: ielts18ReadingPassage1Test3, questionText: '13 The environmental damage caused by concrete is due to it being produced in large quantities.', options: ['A Chris Cheeseman', 'B Markus Mannström', 'C Anna Surgenor', 'D Felix Preston and Johanna Lehne'], correctAnswers: ['A Chris Cheeseman'], passageHighlight: "it is the scale on which it is used that makes it high carbon." },
      ]
    }]
  },
  {
    id: 'b18-t3-r3',
    title: 'Test 3: Reading P2-3',
    section: Section.READING,
    parts: [
      { // Reading Passage 2
        questions: [
          { id: 'b18t3rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match the correct heading for each paragraph from the list of headings below.', passage: ielts18ReadingPassage2Test3, questionText: '14 Paragraph A', options: ['i A period in cold conditions before the technology is assessed', 'ii Marketing issues lead to failure', 'iii Good and bad aspects of steam technology are passed on', 'iv A possible solution to the issues of today', 'v Further improvements lead to commercial orders', 'vi Positive publicity at last for this quiet, clean, fast vehicle', 'vii A disappointing outcome for customers', 'viii A better option than the steam car arises'], correctAnswers: ['iii Good and bad aspects of steam technology are passed on'], passageHighlight: "But these early cars inherited a steam engine’s weaknesses along with its strengths." },
          { id: 'b18t3rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match the correct heading for each paragraph from the list of headings below.', passage: ielts18ReadingPassage2Test3, questionText: '15 Paragraph B', options: ['i A period in cold conditions before the technology is assessed', 'ii Marketing issues lead to failure', 'iii Good and bad aspects of steam technology are passed on', 'iv A possible solution to the issues of today', 'v Further improvements lead to commercial orders', 'vi Positive publicity at last for this quiet, clean, fast vehicle', 'vii A disappointing outcome for customers', 'viii A better option than the steam car arises'], correctAnswers: ['viii A better option than the steam car arises'], passageHighlight: "A new technology called the Internal Combustion Engine soon appeared" },
          { id: 'b18t3rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match the correct heading for each paragraph from the list of headings below.', passage: ielts18ReadingPassage2Test3, questionText: '16 Paragraph C', options: ['i A period in cold conditions before the technology is assessed', 'ii Marketing issues lead to failure', 'iii Good and bad aspects of steam technology are passed on', 'iv A possible solution to the issues of today', 'v Further improvements lead to commercial orders', 'vi Positive publicity at last for this quiet, clean, fast vehicle', 'vii A disappointing outcome for customers', 'viii A better option than the steam car arises'], correctAnswers: ['vi Positive publicity at last for this quiet, clean, fast vehicle'], passageHighlight: "The Model B proved to be superior to gasoline automobiles in many ways... amazingly swift." },
          { id: 'b18t3rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match the correct heading for each paragraph from the list of headings below.', passage: ielts18ReadingPassage2Test3, questionText: '17 Paragraph D', options: ['i A period in cold conditions before the technology is assessed', 'ii Marketing issues lead to failure', 'iii Good and bad aspects of steam technology are passed on', 'iv A possible solution to the issues of today', 'v Further improvements lead to commercial orders', 'vi Positive publicity at last for this quiet, clean, fast vehicle', 'vii A disappointing outcome for customers', 'viii A better option than the steam car arises'], correctAnswers: ['v Further improvements lead to commercial orders'], passageHighlight: "the General Engineering Company had received 5,390 deposits for Doble Detroits" },
          { id: 'b18t3rq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match the correct heading for each paragraph from the list of headings below.', passage: ielts18ReadingPassage2Test3, questionText: '18 Paragraph E', options: ['i A period in cold conditions before the technology is assessed', 'ii Marketing issues lead to failure', 'iii Good and bad aspects of steam technology are passed on', 'iv A possible solution to the issues of today', 'v Further improvements lead to commercial orders', 'vi Positive publicity at last for this quiet, clean, fast vehicle', 'vii A disappointing outcome for customers', 'viii A better option than the steam car arises'], correctAnswers: ['vii A disappointing outcome for customers'], passageHighlight: "buyers who received the handful of completed cars complained that the vehicles were sluggish and erratic" },
          { id: 'b18t3rq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match the correct heading for each paragraph from the list of headings below.', passage: ielts18ReadingPassage2Test3, questionText: '19 Paragraph F', options: ['i A period in cold conditions before the technology is assessed', 'ii Marketing issues lead to failure', 'iii Good and bad aspects of steam technology are passed on', 'iv A possible solution to the issues of today', 'v Further improvements lead to commercial orders', 'vi Positive publicity at last for this quiet, clean, fast vehicle', 'vii A disappointing outcome for customers', 'viii A better option than the steam car arises'], correctAnswers: ['i A period in cold conditions before the technology is assessed'], passageHighlight: "After sitting overnight in freezing temperatures" },
          { id: 'b18t3rq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match the correct heading for each paragraph from the list of headings below.', passage: ielts18ReadingPassage2Test3, questionText: '20 Paragraph G', options: ['i A period in cold conditions before the technology is assessed', 'ii Marketing issues lead to failure', 'iii Good and bad aspects of steam technology are passed on', 'iv A possible solution to the issues of today', 'v Further improvements lead to commercial orders', 'vi Positive publicity at last for this quiet, clean, fast vehicle', 'vii A disappointing outcome for customers', 'viii A better option than the steam car arises'], correctAnswers: ['iv A possible solution to the issues of today'], passageHighlight: "it is not unthinkable that the steam car may rise again" },
          { id: 'b18t3rq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test3, questionText: '21 What point does the writer make about the steam car in Paragraph B?', options: ['A Its success was short-lived.', 'B Not enough cars were made.', 'C Car companies found them hard to sell.', 'D People found them hard to drive.'], correctAnswers: ['A Its success was short-lived.'], passageHighlight: "But the glory days of steam cars were few." },
          { id: 'b18t3rq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test3, questionText: '22 When building their first steam car, the Doble brothers', options: ['A constructed all the parts themselves.', 'B made written notes at each stage of the construction.', 'C needed several attempts to achieve a competitive model.', 'D sought the advice of experienced people in the car industry.'], correctAnswers: ['C needed several attempts to achieve a competitive model.'], passageHighlight: "Though it did not run well, the Doble boys went on to build a second and third prototype in the following years." },
          { id: 'b18t3rq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test3, questionText: '23 In order to produce the Model C, the Doble brothers', options: ['A moved production to a different city.', 'B raised financial capital.', 'C employed an additional worker.', 'D abandoned their earlier designs.'], correctAnswers: ['B raised financial capital.'], passageHighlight: "drove a Model B from Massachusetts to Detroit in order to seek investment" },
          { id: 'b18t3rq24', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD AND/OR A NUMBER.', passage: ielts18ReadingPassage2Test3, questionText: 'A later version of the Model E raised its 24 ___ while keeping its emissions extremely low.', correctAnswers: ['speed'], passageHighlight: "its maximum speed was pushed to over a hundred miles per hour... with negligible emissions" },
          { id: 'b18t3rq25', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD AND/OR A NUMBER.', passage: ielts18ReadingPassage2Test3, questionText: 'Under 25 ___ cars were produced before the company went out of business.', correctAnswers: ['fifty', '50'], passageHighlight: "fewer than fifty of the amazing Model E steam cars had been produced" },
          { id: 'b18t3rq26', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD AND/OR A NUMBER.', passage: ielts18ReadingPassage2Test3, questionText: 'They are straightforward to maintain, and they satisfy California’s 26 ___ emissions laws.', correctAnswers: ['strict'], passageHighlight: "an unmodified Model E runs so clean it can pass the emissions laws in California today, and they are nearly silent." },
        ]
      },
      { // Reading Passage 3
        questions: [
          { id: 'b18t3rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage3Test3, questionText: '27 The writer describes the Romeo and Juliet lesson in order to demonstrate', options: ['A how few students are interested in literature.', 'B how a teacher handles a range of learning needs.', 'C how unsuitable Shakespeare is for most teenagers.', 'D how weaker students can disrupt their classmates’ learning.'], correctAnswers: ['B how a teacher handles a range of learning needs.'], passageHighlight: "The teacher can ask the No Fear group to identify the key characters... He can ask most of the class about character development... Now two curious students are wondering" },
          { id: 'b18t3rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage3Test3, questionText: '28 What does the writer say about streaming in the third paragraph?', options: ['A It has a very broad appeal.', 'B It favours cleverer students.', 'C It is relatively simple to implement.', 'D It works better in some schools than others.'], correctAnswers: ['A It has a very broad appeal.'], passageHighlight: "The practice is intuitively appealing to almost every stakeholder." },
          { id: 'b18t3rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage3Test3, questionText: '29 What idea is suggested by the reference to Mount Qomolangma in the fifth paragraph?', options: ['A students following unsuitable paths', 'B students attempting interesting tasks', 'C students not achieving their full potential', 'D students not being aware of their limitations'], correctAnswers: ['C students not achieving their full potential'], passageHighlight: "The brightest ones will never summit Mount Qomolangma" },
          { id: 'b18t3rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage3Test3, questionText: '30 What does the word ‘scaffolding’ in the sixth paragraph refer to?', options: ['A the factors which prevent a student from learning effectively', 'B the environment where most of a student’s learning takes place', 'C the assistance given to a student in their initial stages of learning', 'D the setting of appropriate learning targets for a student’s aptitude'], correctAnswers: ['C the assistance given to a student in their initial stages of learning'], passageHighlight: "The purpose of teaching is to provide and then gradually remove this ‘scaffolding’ until they are autonomous." },
          { id: 'b18t3rq31', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–I.', passage: ielts18ReadingPassage3Test3, questionText: 'According to Professor John Hattie of the Melbourne Education Research Institute, there is very little indication that streaming leads to 31 ___ .', options: ['A wrong classes', 'B lower expectations', 'C average learners', 'D bottom sets', 'E brightest pupils', 'F disadvantaged backgrounds', 'G weaker students', 'H higher achievements', 'I positive impressions'], correctAnswers: ['H higher achievements'], passageHighlight: "tracking has minimal effects on learning outcomes" },
          { id: 'b18t3rq32', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–I.', passage: ielts18ReadingPassage3Test3, questionText: 'He points out that, in schools which use streaming, the most significant impact is on those students placed in the 32 ___ , especially where a large proportion of them have 33 ___ .', options: ['A wrong classes', 'B lower expectations', 'C average learners', 'D bottom sets', 'E brightest pupils', 'F disadvantaged backgrounds', 'G weaker students', 'H higher achievements', 'I positive impressions'], correctAnswers: ['D bottom sets'], passageHighlight: "streaming appears to significantly – and negatively – affect those students assigned to the lowest sets." },
          { id: 'b18t3rq33', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–I.', passage: ielts18ReadingPassage3Test3, questionText: 'He points out that, in schools which use streaming, the most significant impact is on those students placed in the 32 ___ , especially where a large proportion of them have 33 ___ .', options: ['A wrong classes', 'B lower expectations', 'C average learners', 'D bottom sets', 'E brightest pupils', 'F disadvantaged backgrounds', 'G weaker students', 'H higher achievements', 'I positive impressions'], correctAnswers: ['F disadvantaged backgrounds'], passageHighlight: "These students tend to have much higher representation of low socioeconomic class." },
          { id: 'b18t3rq34', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–I.', passage: ielts18ReadingPassage3Test3, questionText: 'Meanwhile, for the 34 ___ , there appears to be only minimal advantage.', options: ['A wrong classes', 'B lower expectations', 'C average learners', 'D bottom sets', 'E brightest pupils', 'F disadvantaged backgrounds', 'G weaker students', 'H higher achievements', 'I positive impressions'], correctAnswers: ['E brightest pupils'], passageHighlight: "Less significant is the small benefit for those lucky clever students in the higher sets." },
          { id: 'b18t3rq35', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–I.', passage: ielts18ReadingPassage3Test3, questionText: 'A further issue is that teachers tend to have 35 ___ of students in streamed groups.', options: ['A wrong classes', 'B lower expectations', 'C average learners', 'D bottom sets', 'E brightest pupils', 'F disadvantaged backgrounds', 'G weaker students', 'H higher achievements', 'I positive impressions'], correctAnswers: ['B lower expectations'], passageHighlight: "Streaming students by diagnosed achievement automatically limits what the teacher feels the student is capable of." },
          { id: 'b18t3rq36', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer?', passage: ielts18ReadingPassage3Test3, questionText: '36 The Vygotsky model of education supports the concept of a mixed-ability class.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "If we accept this model, it follows that streaming students with similar ZPDs would be an efficient and effective solution." },
          { id: 'b18t3rq37', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer?', passage: ielts18ReadingPassage3Test3, questionText: '37 Some teachers are uncertain about allowing students to take on MKO roles in the classroom.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'] },
          { id: 'b18t3rq38', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer?', passage: ielts18ReadingPassage3Test3, questionText: '38 It can be rewarding to teach knowledge which you have only recently acquired.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "There is also something exciting about passing on skills and knowledge that you yourself have just mastered" },
          { id: 'b18t3rq39', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer?', passage: ielts18ReadingPassage3Test3, questionText: '39 The priority should be to ensure that the highest-achieving students attain their goals.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "we need the many to flourish – not suffer at the expense of a few bright stars." },
          { id: 'b18t3rq40', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer?', passage: ielts18ReadingPassage3Test3, questionText: '40 Taking part in collaborative outdoor activities with teachers and classmates can improve student outcomes in the classroom.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'] },
        ]
      }
    ]
  },
  {
    id: 'b18-t3-w4',
    title: 'Test 3: Writing T1-2',
    section: Section.WRITING,
    parts: [
      {
        questions: [{
          id: 'b18t3wq1',
          type: QuestionType.WRITING_TASK,
          prompt: 'You should spend about 20 minutes on this task.',
          imageUrl: 'ielts-18/ielts-18-t3-w1-diagram.png',
          task: "The diagram below shows the floor plan of a public library 20 years ago and how it looks now.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\nWrite at least 150 words.",
          sampleAnswer: "This model has been prepared by an examiner as an example of a very good answer. The diagrams show Central Library before and after changes were made to its layout. Clearly, the library has been updated to include dedicated spaces for events and now has an open space in the centre.\n\nTwenty years ago, to the left of the entrance there was a reading room with newspapers and magazines and to the right there was an enquiry desk. Now there’s a computer room on the left and a café where the information desk once was. Adult fiction has moved to the right-hand side of the room and all reference books are now on the left. There is a smaller information desk with self-service machines in what once was the adult non-fiction section.\n\nThere was a room at the back left-hand corner that had computer games, CDs and videos that has since been enlarged and houses children’s fiction. It has a space with two sofas where storytelling events are held. There is a lecture room in the back right-hand corner where children’s books used to be.",
          examinerComment: "This response covers the main changes that have occurred over the 20-year period. An overview is presented in the second paragraph which is quite general: it refers to the [dedicated spaces for events] but this could be improved by giving a summary of the key changes (dedicated spaces for events, self-service facilities and a café).\n\nIdeas are arranged logically: the changes to the front of the library are presented in the third paragraph and the changes to the back section in the final paragraph. This shows a logical approach to reporting the changes and there is some good cohesion [once was | now on the left | has since been].\n\nThere is a good range of vocabulary. In this kind of task, vocabulary from the floor plan needs to be used to report the changes, but the use of different words shows some flexibility and precision [been updated | dedicated spaces | houses].\n\nIn terms of grammar, there are error-free sentences and some variation in structures used when describing changes [has been updated | what once was | has since been enlarged].\n\nThe response could be improved by extending the overview to include more of a summary of the main changes but overall, this response captures the main changes in a logical way."
        }]
      },
      {
        questions: [{
          id: 'b18t3wq2',
          type: QuestionType.WRITING_TASK,
          prompt: "You should spend about 40 minutes on this task. Write about the following topic:",
          task: "In many countries around the world, rural people are moving to cities, so the population in the countryside is decreasing.\n\nDo you think this is a positive or a negative development?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.",
          sampleAnswer: "This model has been prepared by an examiner as an example of a very good answer. Statistics show that the world’s population is increasing rapidly. It is expected that most of us will be living in cities within the next few decades. The question of whether urbanisation is a positive or negative development remains controversial.\n\nA rapid influx of people moving from rural to urban areas is bound to cause problems. Firstly, pressure on resources such as housing and transportation intensifies. It is becoming difficult for many people to afford adequate housing in cities. A by-product of this is the creation of slums causing low-income families to group together in neglected parts of the city. These people often become trapped in a cycle of poverty that is difficult to escape.\n\nAs mentioned above, the growth of urban areas can also lead to severe traffic congestion and more and more vehicles travel into the city from the suburbs. This has many knock-on effects, such as problems with air quality. It also leads many city dwellers to experience mental health issues because travelling across large cities is tiring and stressful.\n\nAll of this being said, I don’t believe that urbanisation is a wholly negative development. There are advantages to living in large cities that are well managed. For example, there are more schools which means more education opportunities. Access to higher-quality health care is often better in cities. Some cities have also introduced ride-sharing, e-bikes and park and ride services that reduce environmental problems.\n\nMy opinion is that many of the problems associated with urbanisation are avoidable but dealing with increasing populations in cities is a formidable challenge. How governments, businesses and society respond to this challenge will dramatically affect the future of our world.",
          examinerComment: "This response addresses both sides of the question and presents a position, that the movement to cities is not a [wholly negative development]. The second and third paragraphs lay out the problems that can be caused by a [rapid influx] of people to urban areas [housing | transportation | traffic congestion] and the fourth paragraph presents some of the advantages [education opportunities | higher-quality health care | environmental transport initiatives].\n\nHowever, the part of the question about ‘the population in the countryside ... decreasing’ is not covered. The candidate would need to include it to provide a full answer to this question.\n\nInformation and ideas are logically organised and there is a clear progression, starting with the challenges and ending with a range of advantages."
        }]
      }
    ]
  },
  {
    id: 'b18-t3-s5',
    title: 'Test 3: Speaking P1-3',
    section: Section.SPEAKING,
    parts: [
      {
        questions: [{
          id: 'b18t3sq1',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 1: Example',
          question: 'Online shopping\n\n- How often do you buy things online? [Why?]\n- What was the last thing you bought online?\n- Do you ever see things in shops and then buy them online? [Why/Why not?]\n- Do you think the popularity of online shopping is changing your town or city centre? [Why/Why not?]',
          sampleAnswer: `**1. How often do you buy things online?**\n"I probably buy things online a few times a month. It’s just so convenient to have things delivered directly to my door, and the range of products available is much wider than in local shops. I use it for everything from groceries to clothes and electronics."\n\n**2. What was the last thing you bought online?**\n"The last thing I bought was a new pair of running shoes. My old ones were worn out, and I found a good deal on a specific model I wanted. I was able to compare prices on different websites and read reviews, which was really helpful before making the purchase."\n\n**3. Do you ever see things in shops and then buy them online?**\n"Yes, I do that quite often, especially for bigger purchases like electronics or clothes. I like to go to a physical shop to see the item, check the quality or try it on for size. But then I'll often check online to see if I can find it cheaper, which is usually the case."\n\n**4. Do you think the popularity of online shopping is changing your town or city centre?**\n"Absolutely. I’ve noticed a lot more empty shops in the town centre over the last few years as more people shift to online shopping. It’s a bit sad to see, as it changes the character of the town. However, some areas are adapting by focusing more on experiences like cafes, restaurants, and entertainment rather than just retail."`
        }]
      },
      {
        questions: [{
          id: 'b18t3sq2',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 2: Cue Card',
          question: 'Describe a time when you enjoyed visiting a member of your family in their home.\nYou should say:\n- who you visited and where they lived\n- why you made this visit\n- what happened during this visit\n- and explain what you enjoyed about this visit.',
          sampleAnswer: `I'd like to talk about a visit I made to my grandparents' home last summer. They live in a small, quiet village in the countryside, which is a lovely contrast to the busy city where I live.\n\nI made the visit because it was my grandmother's 80th birthday, and the whole family gathered there to celebrate with her. It was a special occasion and I hadn't seen some of my cousins for a couple of years, so it was a great opportunity to catch up.\n\nDuring the visit, we had a big family lunch in their garden. My grandfather had spent all morning barbecuing, and my grandmother had baked her famous birthday cake. We spent the afternoon just talking, laughing, and playing some games with the younger children. The weather was beautiful, so it was a perfect day for it.\n\nWhat I enjoyed most about the visit was the warm, relaxed atmosphere. It was wonderful to see all my family together in one place, especially after a long time. My grandparents' home is always so welcoming, and being in their garden surrounded by family felt very special and comforting. It was a simple day, but full of happiness and good memories.`
        }]
      },
      {
        questions: [{
          id: 'b18t3sq3',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 3: Discussion topics',
          question: 'Family occasions\n- When do families celebrate together in your country?\n- How do families celebrate together in your country?\n- Why is it that some people might not enjoy attending family occasions?\n\nEveryday life in families\n- Do you think it is a good thing for parents to help their children with schoolwork?\n- How important do you think it is for families to eat together at least once a day?\n- Do you believe that everyone in a family should share household tasks?',
          sampleAnswer: `**Family occasions**\n\n**1. When do families celebrate together in your country?**\n"In my country, families typically get together for major holidays like Christmas and Easter. Big birthdays, anniversaries, and weddings are also very important family occasions. Essentially, any significant personal milestone or national holiday is a reason for a family gathering."\n\n**2. How do families celebrate together in your country?**\n"The celebration almost always revolves around a big meal. People will cook special dishes, and everyone gathers around the table to eat, talk, and spend time together. There might be an exchange of gifts, especially for birthdays or Christmas, but the shared meal is the central part of the celebration."\n\n**3. Why is it that some people might not enjoy attending family occasions?**\n"Well, family dynamics can be complicated. Sometimes there are underlying tensions or disagreements between family members, which can make these gatherings stressful rather than enjoyable. Also, for some people, especially introverts, large, noisy gatherings can just be overwhelming and draining."\n\n**Everyday life in families**\n\n**4. Do you think it is a good thing for parents to help their children with schoolwork?**\n"Yes, I think it's a very good thing, up to a point. It shows the child that their education is important and provides them with support if they're struggling. However, I think it's crucial that parents guide their children to find the answers themselves, rather than just giving them the solution. The goal should be to foster independence."\n\n**5. How important do you think it is for families to eat together at least once a day?**\n"I think it's extremely important. It's often the only time in a busy day when everyone can sit down, switch off their screens, and actually talk to each other. It’s a vital time for communication, for sharing what happened during the day, and for strengthening family bonds. It creates a sense of routine and togetherness."\n\n**6. Do you believe that everyone in a family should share household tasks?**\n"Absolutely. I believe it's essential for fairness and for teaching responsibility. When everyone contributes, it lessens the burden on any single person, usually the mother. For children, doing chores teaches them important life skills and the value of being part of a team. It fosters a sense of mutual respect and cooperation within the family."`
        }]
      }
    ]
  }
];
