
import { Lesson, QuestionType, Section } from '../types';

const ielts17ReadingPassage1Test3 = `The thylacine

The extinct thylacine, also known as the Tasmanian tiger, was a marsupial that bore a superficial resemblance to a dog. Its most distinguishing feature was the 13-19 dark brown stripes over its back, beginning at the rear of the body and extending onto the tail. The thylacine’s average noseto-tail length for adult males was 162.6 cm, compared to 153.7 cm for females.

The thylacine appeared to occupy most types of terrain except dense rainforest, with open eucalyptus forest thought to be its prime habitat. In terms of feeding, it was exclusively carnivorous, and its stomach was muscular with an ability to distend so that it could eat large amounts of food at one time, probably an adaptation to compensate for long periods when hunting was unsuccessful and food scarce. The thylacine was not a fast runner and probably caught its prey by exhausting it during a long pursuit. During long-distance chases, thylacines were likely to have relied more on scent than any other sense. They emerged to hunt during the evening, night and early morning and tended to retreat to the hills and forest for shelter during the day. Despite the common name ‘tiger’, the thylacine had a shy, nervous temperament. Although mainly nocturnal, it was sighted moving during the day and some individuals were even recorded basking in the sun.

The thylacine had an extended breeding season from winter to spring, with indications that some breeding took place throughout the year. The thylacine, like all marsupials, was tiny and hairless when born. Newborns crawled into the pouch on the belly of their mother, and attached themselves to one of the four teats, remaining there for up to three months. When old enough to leave the pouch, the young stayed in a lair such as a deep rocky cave, well-hidden nest or hollow log, whilst the mother hunted.

Approximately 4,000 years ago, the thylacine was widespread throughout New Guinea and most of mainland Australia, as well as the island of Tasmania. The most recent, well-dated occurrence of a thylacine on the mainland is a carbon-dated fossil from Murray Cave in Western Australia, which is around 3,100 years old. Its extinction coincided closely with the arrival of wild dogs called dingoes in Australia and a similar predator in New Guinea. Dingoes never reached Tasmania, and most scientists see this as the main reason for the thylacine’s survival there.

The dramatic decline of the thylacine in Tasmania, which began in the 1830s and continued for a century, is generally attributed to the relentless efforts of sheep farmers and bounty hunters with shotguns. While this determined campaign undoubtedly played a large part, it is likely that various other factors also contributed to the decline and eventual extinction of the species. These include competition with wild dogs introduced by European settlers, loss of habitat along with the disappearance of prey species, and a distemper-like disease which may also have affected the thylacine.

There was only one successful attempt to breed a thylacine in captivity, at Melbourne Zoo in 1899. This was despite the large numbers that went through some zoos, particularly London Zoo and Tasmania’s Hobart Zoo. The famous naturalist John Gould foresaw the thylacine’s demise when he published his Mammals of Australia between 1848 and 1863, writing, ‘The numbers of this singular animal will speedily diminish, extermination will have its full sway, and it will then, like the wolf of England and Scotland, be recorded as an animal of the past.’

However, there seems to have been little public pressure to preserve the thylacine, nor was much concern expressed by scientists at the decline of this species in the decades that followed. A notable exception was T.T. Flynn, Professor of Biology at the University of Tasmania. In 1914, he was sufficiently concerned about the scarcity of the thylacine to suggest that some should be captured and placed on a small island. But it was not until 1929, with the species on the very edge of extinction, that Tasmania’s Animals and Birds Protection Board passed a motion protecting thylacines only for the month of December, which was thought to be their prime breeding season. The last known wild thylacine to be killed was shot by a farmer in the north-east of Tasmania in 1930, leaving just captive specimens. Official protection of the species by the Tasmanian government was introduced in July 1936, 59 days before the last known individual died in Hobart Zoo on 7th September, 1936.

There have been numerous expeditions and searches for the thylacine over the years, none of which has produced definitive evidence that thylacines still exist. The species was declared extinct by the Tasmanian government in 1986.`;

const ielts17ReadingPassage2Test3 = `Palm oil

A. Palm oil is an edible oil derived from the fruit of the African oil palm tree, and is currently the most consumed vegetable oil in the world. It’s almost certainly in the soap we wash with in the morning, the sandwich we have for lunch, and the biscuits we snack on during the day. Why is palm oil so attractive for manufacturers? Primarily because its unique properties – such as remaining solid at room temperature – make it an ideal ingredient for long-term preservation, allowing many packaged foods on supermarket shelves to have ‘best before’ dates of months, even years, into the future.

B. Many farmers have seized the opportunity to maximise the planting of oil palm trees. Between 1990 and 2012, the global land area devoted to growing oil palm trees grew from 6 to 17 million hectares, now accounting for around ten percent of total cropland in the entire world. From a mere two million tonnes of palm oil being produced annually globally 50 years ago, there are now around 60 million tonnes produced every single year, a figure looking likely to double or even triple by the middle of the century.

C. However, there are multiple reasons why conservationists cite the rapid spread of oil palm plantations as a major concern. There are countless news stories of deforestation, habitat destruction and dwindling species populations, all as a direct result of land clearing to establish oil palm tree monoculture on an industrial scale, particularly in Malaysia and Indonesia. Endangered species – most famously the Sumatran orangutan, but also rhinos, elephants, tigers, and numerous other fauna – have suffered from the unstoppable spread of oil palm plantations.

D. ‘Palm oil is surely one of the greatest threats to global biodiversity,’ declares Dr Farnon Ellwood of the University of the West of England, Bristol. ‘Palm oil is replacing rainforest, and rainforest is where all the species are. That’s a problem.’ This has led to some radical questions among environmentalists, such as whether consumers should try to boycott palm oil entirely. Meanwhile Bhavani Shankar, Professor at London’s School of Oriental and African Studies, argues, ‘It’s easy to say that palm oil is the enemy and we should be against it. It makes for a more dramatic story, and it’s very intuitive. But given the complexity of the argument, I think a much more nuanced story is closer to the truth.’

E. One response to the boycott movement has been the argument for the vital role palm oil plays in lifting many millions of people in the developing world out of poverty. Is it desirable to have palm oil boycotted, replaced, eliminated from the global supply chain, given how many low-income people in developing countries depend on it for their livelihoods? How best to strike a utilitarian balance between these competing factors has become a serious bone of contention.

F. Even the deforestation argument isn’t as straightforward as it seems. Oil palm plantations produce at least four and potentially up to ten times more oil per hectare than soybean, rapeseed, sunflower or other competing oils. That immensely high yield – which is predominantly what makes it so profitable – is potentially also an ecological benefit. If ten times more palm oil can be produced from a patch of land than any competing oil, then ten times more land would need to be cleared in order to produce the same volume of oil from that competitor. As for the question of carbon emissions, the issue really depends on what oil palm trees are replacing. Crops vary in the degree to which they sequester carbon – in other words, the amount of carbon they capture from the atmosphere and store within the plant. The more carbon a plant sequesters, the more it reduces the effect of climate change. As Shankar explains: ‘[Palm oil production] actually sequesters more carbon in some ways than other alternatives. [...] Of course, if you’re cutting down virgin forest it’s terrible – that’s what’s happening in Indonesia and Malaysia, it’s been allowed to get out of hand. But if it’s replacing rice, for example, it might actually sequester more carbon.’

G. The industry is now regulated by a group called the Roundtable on Sustainable Palm Oil (RSPO), consisting of palm growers, retailers, product manufacturers, and other interested parties. Over the past decade or so, an agreement has gradually been reached regarding standards that producers of palm oil have to meet in order for their product to be regarded as officially ‘sustainable’. The RSPO insists upon no virgin forest clearing, transparency and regular assessment of carbon stocks, among other criteria. Only once these requirements are fully satisfied is the oil allowed to be sold as certified sustainable palm oil (CSPO). Recent figures show that the RSPO now certifies around 12 million tonnes of palm oil annually, equivalent to roughly 21 percent of the world’s total palm oil production.

H. There is even hope that oil palm plantations might not need to be such sterile monocultures, or ‘green deserts’, as Ellwood describes them. New research at Ellwood’s lab hints at one plant which might make all the difference. The bird’s nest fern (Asplenium nidus) grows on trees in an epiphytic fashion (meaning it’s dependent on the tree only for support, not for nutrients), and is native to many tropical regions, where as a keystone species it performs a vital ecological role. Ellwood believes that reintroducing the bird’s nest fern into oil palm plantations could potentially allow these areas to recover their biodiversity, providing a home for all manner of species, from fungi and bacteria, to invertebrates such as insects, amphibians, reptiles and even mammals.`;

const ielts17ReadingPassage3Test3 = `Building the Skyline: The Birth and Growth of Manhattan’s Skyscrapers

Katharine L. Shester reviews a book by Jason Barr about the development of New York City

In Building the Skyline, Jason Barr takes the reader through a detailed history of New York City. The book combines geology, history, economics, and a lot of data to explain why business clusters developed where they did and how the early decisions of workers and firms shaped the skyline we see today. Building the Skyline is organized into two distinct parts. The first is primarily historical and addresses New York’s settlement and growth from 1609 to 1900; the second deals primarily with the 20th century and is a compilation of chapters commenting on different aspects of New York’s urban development. The tone and organization of the book changes somewhat between the first and second parts, as the latter chapters incorporate aspects of Barr’s related research papers.

Barr begins chapter one by taking the reader on a ‘helicopter time-machine’ ride – giving a fascinating account of how the New York landscape in 1609 might have looked from the sky. He then moves on to a subterranean walking tour of the city, indicating the location of rock and water below the subsoil, before taking the reader back to the surface. His love of the city comes through as he describes various fun facts about the location of the New York residence of early 19th-century vice-president Aaron Burr as well as a number of legends about the city.

Chapters two and three take the reader up to the Civil War (1861–1865), with chapter two focusing on the early development of land and the implementation of a grid system in 1811. Chapter three focuses on land use before the Civil War. Both chapters are informative and well researched and set the stage for the economic analysis that comes later in the book. I would have liked Barr to expand upon his claim that existing tenements* prevented skyscrapers in certain neighborhoods because ‘likely no skyscraper developer was interested in performing the necessary “slum clearance”’. Later in the book, Barr makes the claim that the depth of bedrock** was not a limiting factor for developers, as foundation costs were a small fraction of the cost of development. At first glance, it is not obvious why slum clearance would be limiting, while more expensive foundations would not.

Chapter four focuses on immigration and the location of neighborhoods and tenements in the late 19th century. Barr identifies four primary immigrant enclaves and analyzes their locations in terms of the amenities available in the area. Most of these enclaves were located on the least valuable land, between the industries located on the waterfront and the wealthy neighborhoods bordering Central Park.

Part two of the book begins with a discussion of the economics of skyscraper height. In chapter five, Barr distinguishes between engineering height, economic height, and developer height — where engineering height is the tallest building that can be safely made at a given time, economic height is the height that is most efficient from society’s point of view, and developer height is the actual height chosen by the developer, who is attempting to maximize return on investment.

Chapter five also has an interesting discussion of the technological advances that led to the construction of skyscrapers. For example, the introduction of iron and steel skeletal frames made thick, load-bearing walls unnecessary, expanding the usable square footage of buildings and increasing the use of windows and availability of natural light. Chapter six then presents data on building height throughout the 20th century and uses regression analysis to ‘predict’ building construction. While less technical than the research paper on which the chapter is based, it is probably more technical than would be preferred by a general audience.

Chapter seven tackles the ‘bedrock myth’, the assumption that the absence of bedrock close to the surface between Downtown and Midtown New York is the reason for skyscrapers not being built between the two urban centers. Rather, Barr argues that while deeper bedrock does increase foundation costs, these costs were neither prohibitively high nor were they large compared to the overall cost of building a skyscraper. What I enjoyed the most about this chapter was Barr’s discussion of how foundations are actually built. He describes the use of caissons, which enable workers to dig down for considerable distances, often below the water table, until they reach bedrock. Barr’s thorough technological history discusses not only how caissons work, but also the dangers involved. While this chapter references empirical research papers, it is a relatively easy read.

Chapters eight and nine focus on the birth of Midtown and the building boom of the 1920s. Chapter eight contains lengthy discussions of urban economic theory that may serve as a distraction to readers primarily interested in New York. However, they would be well-suited for undergraduates learning about the economics of cities. In the next chapter, Barr considers two of the primary explanations for the building boom of the 1920s – the first being exuberance, and the second being financing. He uses data to assess the viability of these two explanations and finds that supply and demand factors explain much of the development of the 1920s; though it enabled the boom, cheap credit was not, he argues, the primary cause.

In the final chapter (chapter 10), Barr discusses another of his empirical papers that estimates Manhattan land values from the mid-19th century to the present day. The data work that went into these estimations is particularly impressive. Toward the end of the chapter, Barr assesses ‘whether skyscrapers are a cause or an effect of high land values’. He finds that changes in land values predict future building height, but the reverse is not true. The book ends with an epilogue, in which Barr discusses the impact of climate change on the city and makes policy suggestions for New York going forward.`;

export const ielts17Test3Lessons: Lesson[] = [
    {
        id: 'b17-t3-l0',
        title: 'Test 3: Listening P1-2',
        section: Section.LISTENING,
        parts: [
            { // Part 1
                questions: [
                    { id: 'b17t3lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t3-p1.mp3', questionText: 'Recommends surfing for 1 ___ holidays in the summer', correctAnswers: ['family'], transcript: "I think it’s the kind of holiday all the family can enjoy together.", transcriptHighlight: "family" },
                    { id: 'b17t3lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t3-p1.mp3', questionText: 'Need to be quite 2 ___ .', correctAnswers: ['fit'], transcript: "I’ve heard you need to be pretty fit.", transcriptHighlight: "fit" },
                    { id: 'b17t3lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t3-p1.mp3', questionText: 'Lahinch has some good quality 3 ___ and surf schools', correctAnswers: ['hotels'], transcript: "Are there good hotels there? Yes – some very nice ones", transcriptHighlight: "hotels" },
                    { id: 'b17t3lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t3-p1.mp3', questionText: 'Good surf school at 4 ___ beach', correctAnswers: ['Carrowniskey'], transcript: "There’s a good surf school at Carrowniskey beach.", transcriptHighlight: "Carrowniskey" },
                    { id: 'b17t3lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t3-p1.mp3', questionText: 'Surf camp lasts for one 5 ___ .', correctAnswers: ['week'], transcript: "Three hours every day for a week.", transcriptHighlight: "week" },
                    { id: 'b17t3lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t3-p1.mp3', questionText: 'Can also explore the local 6 ___ by kayak', correctAnswers: ['bay'], transcript: "to rent some kayaks to have a look around the bay which is nearby.", transcriptHighlight: "bay" },
                    { id: 'b17t3lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t3-p1.mp3', questionText: 'Best month to go: 7 ___ .', correctAnswers: ['September'], transcript: "September’s my favourite month because the water is warmer then.", transcriptHighlight: "September" },
                    { id: 'b17t3lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t3-p1.mp3', questionText: 'Average temperature in summer: approx. 8 ___ degrees', correctAnswers: ['19', 'nineteen'], transcript: "The average temperature is about 19 degrees", transcriptHighlight: "19" },
                    { id: 'b17t3lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t3-p1.mp3', questionText: 'Wetsuit and surfboard: 9 ___ euros per day', correctAnswers: ['30', 'thirty'], transcript: "You can expect to pay a daily rate of about 30 euros for the hire of a wetsuit and board", transcriptHighlight: "30" },
                    { id: 'b17t3lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t3-p1.mp3', questionText: 'Also advisable to hire 10 ___ for warmth', correctAnswers: ['boots'], transcript: "And make sure you also get boots. They keep your feet warm", transcriptHighlight: "boots" },
                ]
            },
            { // Part 2
                questions: [
                    { id: 'b17t3lq11', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: "Choose TWO letters, A-E.", audioUrl: 'ielts-17/t3-p2.mp3', questionText: "Which TWO facts are given about the school's extended hours childcare service?", options: ['A It started recently.', 'B More children attend after school than before school.', 'C An average of 50 children attend in the mornings.', 'D A child cannot attend both the before and after school sessions.', 'E The maximum number of children who can attend is 70.'], correctAnswers: ['B More children attend after school than before school.', 'E The maximum number of children who can attend is 70.'], transcript: "I think we generally expect around 50-60 children for the afternoon sessions and about half that number for the breakfast sessions... We are insured to provide care for up to 70 children", transcriptHighlight: "50-60 children for the afternoon sessions and about half that number for the breakfast sessions... up to 70 children" },
                    { id: 'b17t3lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t3-p2.mp3', questionText: 'How much does childcare cost for a complete afternoon session per child?', options: ['A £3.50', 'B £5.70', 'C £7.20'], correctAnswers: ['C £7.20'], transcript: "For the afternoon sessions, which run from 3.30 until 6 p.m., it’s £7.20.", transcriptHighlight: "£7.20" },
                    { id: 'b17t3lq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t3-p2.mp3', questionText: 'What does the manager say about food?', options: ['A Children with allergies should bring their own food.', 'B Children may bring healthy snacks with them.', 'C Children are given a proper meal at 5 p.m.'], correctAnswers: ['C Children are given a proper meal at 5 p.m.'], transcript: "At 5 p.m. children are given something more substantial, such as pasta or a casserole.", transcriptHighlight: "something more substantial" },
                    { id: 'b17t3lq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t3-p2.mp3', questionText: 'What is different about arrangements in the school holidays?', options: ['A Children from other schools can attend.', 'B Older children can attend.', 'C A greater number of children can attend.'], correctAnswers: ['A Children from other schools can attend.'], transcript: "they’ll get the chance to make new friends with children from other schools – spaces are available for them", transcriptHighlight: "children from other schools" },
                    { id: 'b17t3lq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose FIVE answers from the box and write the correct letter, A-G.', audioUrl: 'ielts-17/t3-p2.mp3', questionText: '16 Spanish', options: ['A has limited availability', 'B is no longer available', 'C is for over 8s only', 'D requires help from parents', 'E involves an additional fee', 'F is a new activity', 'G was requested by children'], correctAnswers: ['E involves an additional fee'], transcript: "This is the only activity which we have to make an extra charge for", transcriptHighlight: "extra charge" },
                    { id: 'b17t3lq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose FIVE answers from the box and write the correct letter, A-G.', audioUrl: 'ielts-17/t3-p2.mp3', questionText: '17 Music', options: ['A has limited availability', 'B is no longer available', 'C is for over 8s only', 'D requires help from parents', 'E involves an additional fee', 'F is a new activity', 'G was requested by children'], correctAnswers: ['D requires help from parents'], transcript: "We do rely on parental support for this", transcriptHighlight: "parental support" },
                    { id: 'b17t3lq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose FIVE answers from the box and write the correct letter, A-G.', audioUrl: 'ielts-17/t3-p2.mp3', questionText: '18 Painting', options: ['A has limited availability', 'B is no longer available', 'C is for over 8s only', 'D requires help from parents', 'E involves an additional fee', 'F is a new activity', 'G was requested by children'], correctAnswers: ['G was requested by children'], transcript: "children kept asking if they could do some art and so we finally gave in.", transcriptHighlight: "children kept asking" },
                    { id: 'b17t3lq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose FIVE answers from the box and write the correct letter, A-G.', audioUrl: 'ielts-17/t3-p2.mp3', questionText: '19 Yoga', options: ['A has limited availability', 'B is no longer available', 'C is for over 8s only', 'D requires help from parents', 'E involves an additional fee', 'F is a new activity', 'G was requested by children'], correctAnswers: ['F is a new activity'], transcript: "Yoga is something that we’ve been meaning to introduce for some time but haven’t been able to find anyone available to teach it – until now that is.", transcriptHighlight: "until now" },
                    { id: 'b17t3lq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose FIVE answers from the box and write the correct letter, A-G.', audioUrl: 'ielts-17/t3-p2.mp3', questionText: '20 Cooking', options: ['A has limited availability', 'B is no longer available', 'C is for over 8s only', 'D requires help from parents', 'E involves an additional fee', 'F is a new activity', 'G was requested by children'], correctAnswers: ['C is for over 8s only'], transcript: "we’ve decided to restrict this to the over 8s", transcriptHighlight: "over 8s" },
                ]
            }
        ]
    },
    {
        id: 'b17-t3-l1',
        title: 'Test 3: Listening P3-4',
        section: Section.LISTENING,
        parts: [
            { // Part 3
                questions: [
                    { id: 'b17t3lq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t3-p3.mp3', questionText: 'Holly has chosen the Orion Stadium placement because', options: ['A it involves children.', 'B it is outdoors.', 'C it sounds like fun.'], correctAnswers: ['B it is outdoors.'], transcript: "it’s the fresh air that attracts me – organising something indoors doesn’t have the same appeal", transcriptHighlight: "fresh air that attracts me" },
                    { id: 'b17t3lq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t3-p3.mp3', questionText: 'Which aspect of safety does Dr Green emphasise most?', options: ['A ensuring children stay in the stadium', 'B checking the equipment children will use', 'C removing obstacles in changing rooms'], correctAnswers: ['A ensuring children stay in the stadium'], transcript: "your main priority will be not to lose anyone!", transcriptHighlight: "not to lose anyone" },
                    { id: 'b17t3lq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t3-p3.mp3', questionText: 'What does Dr Green say about the spectators?', options: ['A They can be hard to manage.', 'B They make useful volunteers.', "C They shouldn't take photographs."], correctAnswers: ["A They can be hard to manage."], transcript: "And that’s not always easy, especially when a proud parent’s trying to get a snap of their child and you want them to move elsewhere.", transcriptHighlight: "not always easy" },
                    { id: 'b17t3lq24', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t3-p3.mp3', questionText: 'What has affected the schedule in the past?', options: ['A bad weather', 'B an injury', 'C extra time'], correctAnswers: ['B an injury'], transcript: "and I was thinking about what to do if someone got hurt as well. I know that last year that caused a terrible delay.", transcriptHighlight: "someone got hurt" },
                    { id: 'b17t3lq25', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose SIX answers from the box and write the correct letter, A-H.', audioUrl: 'ielts-17/t3-p3.mp3', questionText: '25 Communication', options: ['A being flexible', 'B focusing on details', 'C having a smart appearance', 'D hiding your emotions', 'E relying on experts', 'F trusting your own views', 'G doing one thing at a time', 'H thinking of the future'], correctAnswers: ['C having a smart appearance'], transcript: "if you meet someone face-to-face and want to persuade them to be a sponsor, for example ... Oh, I’ll dress up for that! Sure.", transcriptHighlight: "dress up" },
                    { id: 'b17t3lq26', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose SIX answers from the box and write the correct letter, A-H.', audioUrl: 'ielts-17/t3-p3.mp3', questionText: '26 Organisation', options: ['A being flexible', 'B focusing on details', 'C having a smart appearance', 'D hiding your emotions', 'E relying on experts', 'F trusting your own views', 'G doing one thing at a time', 'H thinking of the future'], correctAnswers: ['A being flexible'], transcript: "I guess it’s being prepared to make changes that matters. That’s right. You may have to make an on-the-spot change", transcriptHighlight: "make changes" },
                    { id: 'b17t3lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose SIX answers from the box and write the correct letter, A-H.', audioUrl: 'ielts-17/t3-p3.mp3', questionText: '27 Time management', options: ['A being flexible', 'B focusing on details', 'C having a smart appearance', 'D hiding your emotions', 'E relying on experts', 'F trusting your own views', 'G doing one thing at a time', 'H thinking of the future'], correctAnswers: ['D hiding your emotions'], transcript: "I know I’ve got to look calm even if I’m in a panic. Just think to yourself – no one must know I’m under pressure.", transcriptHighlight: "look calm" },
                    { id: 'b17t3lq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose SIX answers from the box and write the correct letter, A-H.', audioUrl: 'ielts-17/t3-p3.mp3', questionText: '28 Creativity', options: ['A being flexible', 'B focusing on details', 'C having a smart appearance', 'D hiding your emotions', 'E relying on experts', 'F trusting your own views', 'G doing one thing at a time', 'H thinking of the future'], correctAnswers: ['B focusing on details'], transcript: "it’s up to the events manager to think of all the fine points that go to making it work. Right, so I need to listen carefully to that idea and then fill in all the gaps.", transcriptHighlight: "fine points" },
                    { id: 'b17t3lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose SIX answers from the box and write the correct letter, A-H.', audioUrl: 'ielts-17/t3-p3.mp3', questionText: '29 Leadership', options: ['A being flexible', 'B focusing on details', 'C having a smart appearance', 'D hiding your emotions', 'E relying on experts', 'F trusting your own views', 'G doing one thing at a time', 'H thinking of the future'], correctAnswers: ['F trusting your own views'], transcript: "it’s a nice idea, but you have the ultimate responsibility. So, believe in what you think best.", transcriptHighlight: "believe in what you think best" },
                    { id: 'b17t3lq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose SIX answers from the box and write the correct letter, A-H.', audioUrl: 'ielts-17/t3-p3.mp3', questionText: '30 Networking', options: ['A being flexible', 'B focusing on details', 'C having a smart appearance', 'D hiding your emotions', 'E relying on experts', 'F trusting your own views', 'G doing one thing at a time', 'H thinking of the future'], correctAnswers: ['H thinking of the future'], transcript: "I guess that will help me when I apply for a real job. Exactly – think ahead – remember what your ambitions are and keep them in mind.", transcriptHighlight: "think ahead" },
                ]
            },
            { // Part 4
                questions: [
                    { id: 'b17t3lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t3-p4.mp3', questionText: 'It was believed that birds hibernated underwater or buried themselves in 31 ___ .', correctAnswers: ['mud'], transcript: "Another theory for the regular appearance and disappearance of birds was that they spent winter hidden in mud", transcriptHighlight: "mud" },
                    { id: 'b17t3lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t3-p4.mp3', questionText: 'In autumn he observed that redstarts experience the loss of 32 ___', correctAnswers: ['feathers'], transcript: "He observed that in the autumn, small birds called ‘redstarts’ began to lose their feathers", transcriptHighlight: "feathers" },
                    { id: 'b17t3lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t3-p4.mp3', questionText: '...because the two species of birds had a similar 33 ___ .', correctAnswers: ['shape'], transcript: "These assumptions are understandable given that this pair of species are similar in shape", transcriptHighlight: "shape" },
                    { id: 'b17t3lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t3-p4.mp3', questionText: 'Charles Morton popularised the idea that birds fly to the 34 ___ in winter.', correctAnswers: ['moon'], transcript: "He wrote a surprisingly well-regarded paper claiming that birds migrate to the moon", transcriptHighlight: "moon" },
                    { id: 'b17t3lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t3-p4.mp3', questionText: 'In 1822, a stork was killed in Germany which had an African spear in its 35 ___ .', correctAnswers: ['neck'], transcript: "This particular stork made history because of the long spear in its neck", transcriptHighlight: "neck" },
                    { id: 'b17t3lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t3-p4.mp3', questionText: '- previously there had been no 36 ___ that storks migrate to Africa', correctAnswers: ['evidence'], transcript: "This was a truly defining moment... because it was the first evidence that storks spend their winters in sub-Saharan Africa.", transcriptHighlight: "evidence" },
                    { id: 'b17t3lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t3-p4.mp3', questionText: 'Little was known about the 37 ___ and journeys of migrating birds until the practice of ringing was established.', correctAnswers: ['destinations'], transcript: "very little information was available about the actual destinations of particular species", transcriptHighlight: "destinations" },
                    { id: 'b17t3lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t3-p4.mp3', questionText: '...incapable of travelling across huge 38 ___ .', correctAnswers: ['oceans'], transcript: "it seemed impossible that small birds weighing only a few grams could fly over vast oceans.", transcriptHighlight: "oceans" },
                    { id: 'b17t3lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t3-p4.mp3', questionText: "Ringing depended on what is called the 39 '___' of dead birds.", correctAnswers: ['recovery'], transcript: "relies upon what is known as ‘recovery’ – this is when ringed birds are found dead", transcriptHighlight: "recovery" },
                    { id: 'b17t3lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t3-p4.mp3', questionText: 'In 1931, the first 40 ___ to show the migration of European birds was printed.', correctAnswers: ['atlas'], transcript: "In 1931, an atlas was published showing where the most common species of European birds migrated to.", transcriptHighlight: "atlas" },
                ]
            }
        ]
    },
    {
        id: 'b17-t3-r2',
        title: 'Test 3: Reading P1',
        section: Section.READING,
        parts: [{
            questions: [
                { id: 'b17t3rq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test3, questionText: 'ate an entirely 1 ___ diet', correctAnswers: ['carnivorous'], passageHighlight: "it was exclusively carnivorous", reason: "The passage explicitly states the thylacine's diet was 'exclusively carnivorous'." },
                { id: 'b17t3rq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test3, questionText: 'probably depended mainly on 2 ___ when hunting', correctAnswers: ['scent'], passageHighlight: "thylacines were likely to have relied more on scent than any other sense.", reason: "The passage states that during long chases, they 'relied more on scent than any other sense'." },
                { id: 'b17t3rq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test3, questionText: "young spent first months of life inside its mother's 3 ___", correctAnswers: ['pouch'], passageHighlight: "Newborns crawled into the pouch on the belly of their mother", reason: "The text describes newborns crawling into the mother's 'pouch' after birth." },
                { id: 'b17t3rq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test3, questionText: 'last evidence in mainland Australia is a 3,100-year-old 4 ___', correctAnswers: ['fossil'], passageHighlight: "a carbon-dated fossil from Murray Cave in Western Australia, which is around 3,100 years old.", reason: "The passage identifies the most recent mainland evidence as a 'carbon-dated fossil'." },
                { id: 'b17t3rq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test3, questionText: 'reduction in 5 ___ and available sources of food were partly responsible for decline in Tasmania', correctAnswers: ['habitat'], passageHighlight: "loss of habitat along with the disappearance of prey species", reason: "The text lists 'loss of habitat' as one of the factors contributing to the thylacine's decline in Tasmania." },
                { id: 'b17t3rq6', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test3, questionText: 'Significant numbers of thylacines were killed by humans from the 1830s onwards.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "The dramatic decline of the thylacine in Tasmania, which began in the 1830s... is generally attributed to the relentless efforts of sheep farmers and bounty hunters", reason: "The passage states the decline began in the 1830s and was attributed to the 'relentless efforts' of farmers and bounty hunters, which implies significant numbers were killed." },
                { id: 'b17t3rq7', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test3, questionText: 'Several thylacines were born in zoos during the late 1800s.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "There was only one successful attempt to breed a thylacine in captivity, at Melbourne Zoo in 1899.", reason: "The passage explicitly states there was 'only one successful attempt', which contradicts the idea of 'several' thylacines being born in zoos." },
                { id: 'b17t3rq8', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test3, questionText: "John Gould's prediction about the thylacine surprised some biologists.", options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage mentions Gould's prediction but does not provide any information on how biologists reacted to it." },
                { id: 'b17t3rq9', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test3, questionText: 'In the early 1900s, many scientists became worried about the possible extinction of the thylacine.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "nor was much concern expressed by scientists at the decline of this species in the decades that followed. A notable exception was T.T. Flynn", reason: "The passage states there was little concern from scientists, with T.T. Flynn being a 'notable exception', which implies that 'many' scientists were not worried." },
                { id: 'b17t3rq10', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test3, questionText: "T. T. Flynn's proposal to rehome captive thylacines on an island proved to be impractical.", options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage mentions Flynn's proposal but provides no information on whether it was ever attempted or what the outcome was." },
                { id: 'b17t3rq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test3, questionText: 'There were still reasonable numbers of thylacines in existence when a piece of legislation protecting the species during their breeding season was passed.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "But it was not until 1929, with the species on the very edge of extinction, that Tasmania’s Animals and Birds Protection Board passed a motion", reason: "The passage states that the legislation was passed when the species was 'on the very edge of extinction', which contradicts the idea that there were 'reasonable numbers' left." },
                { id: 'b17t3rq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test3, questionText: 'From 1930 to 1936, the only known living thylacines were all in captivity.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "The last known wild thylacine to be killed was shot by a farmer... in 1930, leaving just captive specimens... the last known individual died in Hobart Zoo on 7th September, 1936.", reason: "The passage states the last wild one was killed in 1930, leaving 'just captive specimens', and the last of these died in 1936. This supports the statement that only captive ones were known to be alive during this period." },
                { id: 'b17t3rq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test3, questionText: 'Attempts to find living thylacines are now rarely made.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage says there have been 'numerous expeditions and searches' over the years but does not state whether these attempts are still being made rarely or frequently in the present day." },
            ]
        }],
    },
    {
        id: 'b17-t3-r3',
        title: 'Test 3: Reading P2-3',
        section: Section.READING,
        parts: [
            { // Reading Passage 2
                questions: [
                    { id: 'b17t3rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has eight sections, A-H. Which section contains the following information?', passage: ielts17ReadingPassage2Test3, questionText: 'examples of a range of potential environmental advantages of oil palm tree cultivation', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['F'], passageHighlight: "That immensely high yield... is potentially also an ecological benefit... [Palm oil production] actually sequesters more carbon in some ways than other alternatives." },
                    { id: 'b17t3rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has eight sections, A-H. Which section contains the following information?', passage: ielts17ReadingPassage2Test3, questionText: 'description of an organisation which controls the environmental impact of palm oil production', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['G'], passageHighlight: "The industry is now regulated by a group called the Roundtable on Sustainable Palm Oil (RSPO)" },
                    { id: 'b17t3rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has eight sections, A-H. Which section contains the following information?', passage: ielts17ReadingPassage2Test3, questionText: 'examples of the widespread global use of palm oil', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['A'], passageHighlight: "It’s almost certainly in the soap we wash with in the morning, the sandwich we have for lunch, and the biscuits we snack on" },
                    { id: 'b17t3rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has eight sections, A-H. Which section contains the following information?', passage: ielts17ReadingPassage2Test3, questionText: 'reference to a particular species which could benefit the ecosystem of oil palm plantations', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['H'], passageHighlight: "New research at Ellwood’s lab hints at one plant which might make all the difference. The bird’s nest fern" },
                    { id: 'b17t3rq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has eight sections, A-H. Which section contains the following information?', passage: ielts17ReadingPassage2Test3, questionText: 'figures illustrating the rapid expansion of the palm oil industry', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['B'], passageHighlight: "the global land area devoted to growing oil palm trees grew from 6 to 17 million hectares... From a mere two million tonnes... there are now around 60 million tonnes" },
                    { id: 'b17t3rq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has eight sections, A-H. Which section contains the following information?', passage: ielts17ReadingPassage2Test3, questionText: 'an economic justification for not opposing the palm oil industry', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['E'], passageHighlight: "the vital role palm oil plays in lifting many millions of people in the developing world out of poverty." },
                    { id: 'b17t3rq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has eight sections, A-H. Which section contains the following information?', passage: ielts17ReadingPassage2Test3, questionText: 'examples of creatures badly affected by the establishment of oil palm plantations', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['C'], passageHighlight: "most famously the Sumatran orangutan, but also rhinos, elephants, tigers, and numerous other fauna" },
                    { id: 'b17t3rq21', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'Which TWO statements are made about the Roundtable on Sustainable Palm Oil (RSPO)?', passage: ielts17ReadingPassage2Test3, questionText: '', options: ['A Its membership has grown steadily over the course of the last decade.', 'B It demands that certified producers be open and honest about their practices.', 'C It took several years to establish its set of criteria for sustainable palm oil certification.', 'D Its regulations regarding sustainability are stricter than those governing other industries.', 'E It was formed at the request of environmentalists concerned about the loss of virgin forests.'], correctAnswers: ['B It demands that certified producers be open and honest about their practices.', 'C It took several years to establish its set of criteria for sustainable palm oil certification.'], passageHighlight: "Over the past decade or so, an agreement has gradually been reached... The RSPO insists upon... transparency" },
                    { id: 'b17t3rq23', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.', passage: ielts17ReadingPassage2Test3, questionText: 'One advantage of palm oil for manufacturers is that it stays 23 ___ even when not refrigerated.', correctAnswers: ['solid'], passageHighlight: "remaining solid at room temperature" },
                    { id: 'b17t3rq24', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.', passage: ielts17ReadingPassage2Test3, questionText: 'The 24 ___ is the best known of the animals suffering habitat loss as a result of the spread of oil palm plantations.', correctAnswers: ['Sumatran orangutan'], passageHighlight: "most famously the Sumatran orangutan" },
                    { id: 'b17t3rq25', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.', passage: ielts17ReadingPassage2Test3, questionText: 'As one of its criteria for the certification of sustainable palm oil, the RSPO insists that growers check 25 ___ on a routine basis.', correctAnswers: ['carbon stocks'], passageHighlight: "regular assessment of carbon stocks" },
                    { id: 'b17t3rq26', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose NO MORE THAN TWO WORDS from the passage for each answer.', passage: ielts17ReadingPassage2Test3, questionText: "Ellwood and his researchers are looking into whether the bird's nest fern could restore 26 ___ in areas where oil palm trees are grown.", correctAnswers: ['biodiversity'], passageHighlight: "allow these areas to recover their biodiversity" },
                ],
            },
            { // Reading Passage 3
                questions: [
                    { id: 'b17t3rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: "Choose the correct letter, A, B, C or D.", passage: ielts17ReadingPassage3Test3, questionText: "27 What point does Shester make about Barr's book in the first paragraph?", options: ["A It gives a highly original explanation for urban development.", "B Elements of Barr's research papers are incorporated throughout the book.", "C Other books that are available on the subject have taken a different approach.", 'D It covers a range of factors that affected the development of New York.'], correctAnswers: ['D It covers a range of factors that affected the development of New York.'], passageHighlight: "The book combines geology, history, economics, and a lot of data to explain why business clusters developed where they did", reason: "The first paragraph describes the book as combining geology, history, economics, and data, which are a range of factors that influenced New York's development." },
                    { id: 'b17t3rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test3, questionText: '28 How does Shester respond to the information in the book about tenements?', options: ["A She describes the reasons for Barr's interest.", "B She indicates a potential problem with Barr's analysis.", "C She compares Barr's conclusion with that of other writers.", 'D She provides details about the sources Barr used for his research.'], correctAnswers: ["B She indicates a potential problem with Barr's analysis."], passageHighlight: "At first glance, it is not obvious why slum clearance would be limiting, while more expensive foundations would not.", reason: "Shester points out an inconsistency or lack of clarity in Barr's argument ('it is not obvious why...'), which indicates a potential problem with his analysis." },
                    { id: 'b17t3rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test3, questionText: '29 What does Shester say about chapter six of the book?', options: ['A It contains conflicting data.', 'B It focuses too much on possible trends.', 'C It is too specialised for most readers.', 'D It draws on research that is out of date.'], correctAnswers: ['C It is too specialised for most readers.'], passageHighlight: "it is probably more technical than would be preferred by a general audience.", reason: "Shester's comment that the chapter is 'more technical than would be preferred by a general audience' means it is too specialized for most readers." },
                    { id: 'b17t3rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test3, questionText: '30 What does Shester suggest about the chapters focusing on the 1920s building boom?', options: ['A The information should have been organised differently.', 'B More facts are needed about the way construction was financed.', 'C The explanation that is given for the building boom is unlikely.', 'D Some parts will have limited appeal to certain people.'], correctAnswers: ['D Some parts will have limited appeal to certain people.'], passageHighlight: "Chapter eight contains lengthy discussions of urban economic theory that may serve as a distraction to readers primarily interested in New York. However, they would be well-suited for undergraduates", reason: "Shester suggests that parts of the book, like the discussion on urban economic theory, would be more suitable for undergraduates than for a general audience, indicating it has limited appeal for certain people." },
                    { id: 'b17t3rq31', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test3, questionText: '31 What impresses Shester the most about the chapter on land values?', options: ['A the broad time period that is covered', 'B the interesting questions that Barr asks', 'C the nature of the research into the topic', 'D the recommendations Barr makes for the future'], correctAnswers: ['C the nature of the research into the topic'], passageHighlight: "The data work that went into these estimations is particularly impressive.", reason: "Shester explicitly states that the 'data work' that produced the estimations is 'particularly impressive', highlighting the nature of the research." },
                    { id: 'b17t3rq32', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test3, questionText: '32 The description in the first chapter of how New York probably looked from the air in the early 1600s lacks interest.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "giving a fascinating account of how the New York landscape in 1609 might have looked from the sky.", reason: "The reviewer describes the account as 'fascinating', which directly contradicts the statement that it 'lacks interest'." },
                    { id: 'b17t3rq33', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test3, questionText: '33 Chapters two and three prepare the reader well for material yet to come.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "set the stage for the economic analysis that comes later in the book.", reason: "The reviewer states that these chapters 'set the stage' for later analysis, which means they prepare the reader well." },
                    { id: 'b17t3rq34', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test3, questionText: '34 The biggest problem for many nineteenth-century New York immigrant neighbourhoods was a lack of amenities.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage mentions amenities were a factor in location, but not that the lack of them was the 'biggest problem'." },
                    { id: 'b17t3rq35', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test3, questionText: "35 In the nineteenth century, New York's immigrant neighbourhoods tended to concentrate around the harbour.", options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "Most of these enclaves were located on the least valuable land, between the industries located on the waterfront and the wealthy neighborhoods bordering Central Park.", reason: "The statement claims they concentrated *around* the harbour (waterfront). The text states they were located *between* the waterfront industries and Central Park, implying a more dispersed pattern, not a concentration solely around the harbour." },
                    { id: 'b17t3rq36', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-J, below.', passage: ielts17ReadingPassage3Test3, questionText: 'In chapter seven, Barr indicates how the lack of bedrock close to the surface does not explain why skyscrapers are absent from 36 ___ .', options: ['A development plans', 'B deep excavations', 'C great distance', 'D excessive expense', 'E impossible tasks', 'F associated risks', 'G water level', 'H specific areas', 'I total expenditure', 'J construction guidelines'], correctAnswers: ['H specific areas'], passageHighlight: "the reason for skyscrapers not being built between the two urban centers.", reason: "Barr's 'bedrock myth' chapter addresses why skyscrapers weren't built in 'specific areas' (between Downtown and Midtown)." },
                    { id: 'b17t3rq37', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-J, below.', passage: ielts17ReadingPassage3Test3, questionText: 'He points out that although the cost of foundations increases when bedrock is deep below the surface, this cannot be regarded as 37 ___ ,', options: ['A development plans', 'B deep excavations', 'C great distance', 'D excessive expense', 'E impossible tasks', 'F associated risks', 'G water level', 'H specific areas', 'I total expenditure', 'J construction guidelines'], correctAnswers: ['D excessive expense'], passageHighlight: "these costs were neither prohibitively high", reason: "Barr argues that while deeper bedrock increases costs, these costs were not 'prohibitively high,' which means they were not an 'excessive expense' that would stop a project." },
                    { id: 'b17t3rq38', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-J, below.', passage: ielts17ReadingPassage3Test3, questionText: 'especially when compared to 38 ___ .', options: ['A development plans', 'B deep excavations', 'C great distance', 'D excessive expense', 'E impossible tasks', 'F associated risks', 'G water level', 'H specific areas', 'I total expenditure', 'J construction guidelines'], correctAnswers: ['I total expenditure'], passageHighlight: "nor were they large compared to the overall cost of building a skyscraper", reason: "The foundation costs were not large when compared to the 'overall cost' of the project, which is the 'total expenditure'." },
                    { id: 'b17t3rq39', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-J, below.', passage: ielts17ReadingPassage3Test3, questionText: 'He describes not only how 39 ___ are made possible by the use of caissons,', options: ['A development plans', 'B deep excavations', 'C great distance', 'D excessive expense', 'E impossible tasks', 'F associated risks', 'G water level', 'H specific areas', 'I total expenditure', 'J construction guidelines'], correctAnswers: ['B deep excavations'], passageHighlight: "He describes the use of caissons, which enable workers to dig down for considerable distances", reason: "Caissons are described as enabling workers to 'dig down for considerable distances', which are 'deep excavations'." },
                    { id: 'b17t3rq40', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-J, below.', passage: ielts17ReadingPassage3Test3, questionText: 'but he also discusses their 40 ___ .', options: ['A development plans', 'B deep excavations', 'C great distance', 'D excessive expense', 'E impossible tasks', 'F associated risks', 'G water level', 'H specific areas', 'I total expenditure', 'J construction guidelines'], correctAnswers: ['F associated risks'], passageHighlight: "discusses not only how caissons work, but also the dangers involved.", reason: "The text states Barr discusses the 'dangers involved' with caissons, which are the 'associated risks'." },
                ]
            }
        ]
    },
    {
        id: 'b17-t3-w4',
        title: 'Test 3: Writing T1-2',
        section: Section.WRITING,
        parts: [
            {
                questions: [{
                    id: 'b17t3wq1',
                    type: QuestionType.WRITING_TASK,
                    prompt: 'You should spend about 20 minutes on this task.',
                    imageUrl: 'ielts-17/t3-w1-chart.png',
                    task: 'The chart below gives information about how families in one country spent their weekly income in 1968 and in 2018.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.',
                    sampleAnswer: "The chart describes the data about families weekly expenditure prospects in 1968 and in 2018. The most significant spent rate is on food with a 35% ratio in the year 1968. Housing and clothing come next with the same prospect of 10% of the weekly income. Expenditure on leisure, transport, personal goods and household goods are almost same percentage, the former one is slightly more. Lastly, spent rates on fuel and the others are recorded the least with a 6% in the year of 1968.\n\nTurning to 2018, food expenditure of families had dropped dramatically to a percentage between 15 to 20. On the other hand, housing spent had rised significantly with an almost 20% slightly more than food expenditures. The most crucial rise was recorded on leisure spent rates. It had soared abut 10% in 50 years. Transportation expediture comes after and followed by Household goods and the othe categories respetively. Last three had remained the least just as in 1968 which is fuel and power, clothing and footware and personal goods.\n\nOverall, weekly expenditure averages of families had dramatically changed over 50 years. Some spent rates had remained the same whereas some of the alterations are quite noticable.",
                    sampleAnswerBand: 5.5,
                    examinerComment: "This response clearly presents the data from the bar graph. The candidate presents all the data for 1968 first and then the data for 2018. There is an overview in the final sentence, but it should summarise the main changes from the bar chart rather than just saying that expenditure ‘had ... changed’. Information is arranged coherently into four paragraphs, and there is clear overall progression. A range of cohesive devices is used [Turning to 2018 | followed by | whereas] with an awareness of referencing [former one | the othe categories | Last three]. There are some less common examples of vocabulary [dropped dramatically to | rised significantly | soared]. Errors remain [spent rates / expenditure | housing spent / housing costs] but do not impede communication. Similarly, grammatical structures include some complex forms [had dropped ... to] and sentences with multiple clauses; however, there are errors, including inconsistent use of articles and with past tenses. To improve the response, a summary of the main trends from the bar chart is needed in the overview; for example, the candidate could say that there has been a significant decrease in spending on food over the 50-year period, but the cost of leisure, housing and transport has significantly increased."
                }]
            },
            {
                questions: [{
                    id: 'b17t3wq2',
                    type: QuestionType.WRITING_TASK,
                    prompt: 'You should spend about 40 minutes on this task. Write about the following topic:',
                    task: 'Some people believe that professionals, such as doctors and engineers, should be required to work in the country where they did their training. Others believe they should be free to work in another country if they wish.\n\nDiscuss both these views and give your own opinion.\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.',
                    sampleAnswer: "As the number of professionals workking abroad increases, it is often discussed whether they should stay where hey did their trainings or they should be free to move to another country if they desired to. While I believe theat a person should be free to migrate, I agree that it has negative effects on the country of training.\n\nOn the one hand, professionals who decide to work abroad are seeking for a different lifestyle and career opportunities. Therefore, they should be allowed to improve their lives outside the limitations of their country of origin. For example, whilst in Spain residents in a hospital do not have hands-on experience due to safety measures, in other countries such as Argentina, residents actually practice their skills with patients. Besides, cultural exchanges have proven to increase efficiency, since different nationalities mean different believes and the introduction of new methods.\n\nOn the other hand, when professionals leave the country where they trained, countries are damaged socially and economically. In countries where the government provides free education and healthcare, many people think that the population should compensate the country with their skills and abilities. Furthermore, as a study fo South African emigration has pointed out when a professional lease the country it results in the loss of 10 unskilled jobs. Therefore it affect the economy and the community.\n\nTaking everything into account, it can be said that miving out from the country of training should not be taken lightly, given the adverse effects on the population. However, I firmly believe that someone’s professional development should not depend on their country of origin and professionals should be allowed to look for better opportunities overseas.",
                    sampleAnswerBand: 6.5,
                    examinerComment: "This response addresses both parts of the question. Both views are considered and an opinion is given. For a higher rating, fuller coverage on the first point, the requirement to ‘work in the country where they did their training’ could be included. Organisation is logical and there is clear progression thorough the four paragraphs. The range of vocabulary is good with examples of higher-level items [hands-on experience | compensate | better opportunities overseas], but there are a number of errors [theat / that | believes / beliefs | lease / leaves | miving / moving]. Similarly, the range of grammatical structures is reasonable, but the level of error means the Band Score cannot be higher than 6.5."
                }]
            }
        ]
    },
    {
        id: 'b17-t3-s5',
        title: 'Test 3: Speaking P1-3',
        section: Section.SPEAKING,
        parts: [
            {
                questions: [{
                    id: 'b17t3sq1',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 1: Example',
                    question: 'Drinks\n\n- What do you like to drink with your dinner? [Why?]\n- Do you drink a lot of water every day? [Why/Why not?]\n- Do you prefer drinking tea or coffee? [Why?]\n- If people visit you in your home, what do you usually offer them to drink? [Why/Why not?]',
                    sampleAnswer: `**1. What do you like to drink with your dinner?**
"Usually, I just have a glass of water with my dinner. I find it's the most refreshing thing to drink with a meal and it doesn't interfere with the flavours of the food. Occasionally, on a weekend, I might have a glass of wine if I'm having a special meal."

**2. Do you drink a lot of water every day?**
"Yes, I try to. I always keep a water bottle on my desk while I'm working, and I make an effort to drink from it regularly throughout the day. I know it's important for staying hydrated and I find it helps me to concentrate better."

**3. Do you prefer drinking tea or coffee?**
"I'm definitely more of a coffee person, especially in the morning. I really need a cup of coffee to properly wake up and get my day started. I do enjoy a cup of herbal tea in the evening sometimes, as it's very relaxing, but coffee is my go-to drink."

**4. If people visit you in your home, what do you usually offer them to drink?**
"When guests come over, I always offer them a choice. The usual options are tea, coffee, or just a glass of water. If it's a hot day, I might offer some juice or a soft drink as well. It really depends on the visitor and the time of day, but I like to make sure they have a few options."`
                }]
            },
            {
                questions: [{
                    id: 'b17t3sq2',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 2: Cue Card',
                    question: 'Describe a monument (e.g., a statue or sculpture) that you like.\nYou should say:\n- what this monument is\n- where this monument is\n- what it looks like\n- and explain why you like this monument.',
                    sampleAnswer: `A monument that I really like is the Angel of the North. It's a contemporary sculpture located in the northeast of England, near the town of Gateshead.

It's a huge steel sculpture of an angel, standing 20 metres tall, with wings measuring 54 metres across. It's not a traditional, delicate-looking angel; it's very industrial and powerful. The whole structure is made of a reddish-brown steel that has weathered over time, which gives it a very strong, earthy appearance against the green landscape. It stands on a small hill overlooking a major motorway, so millions of people see it every year.

I like this monument for a few reasons. Firstly, its sheer scale is just breathtaking. When you stand near its base, you feel incredibly small. Secondly, I like what it represents. The artist designed it to signify the transition from an industrial age to an information age and to be a symbol of hope for the region. Finally, I just think it's a very bold and impressive piece of public art. It has become an iconic landmark for the area, and it's something I always look forward to seeing when I travel in that part of the country.`
                }]
            },
            {
                questions: [{
                    id: 'b17t3sq3',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 3: Discussion topics',
                    question: 'Public monuments\n- What kinds of monuments do tourists in your country enjoy visiting?\n- Why do you think there are often statues of famous people in public places?\n- Do you agree that old monuments and buildings should always be preserved?\n\nArchitecture\n- Why is architecture such a popular university subject?\n- In what ways has the design of homes changed in recent years?\n- To what extent does the design of buildings affect people’s moods?',
                    sampleAnswer: `**Public monuments**

**1. What kinds of monuments do tourists in your country enjoy visiting?**
"Tourists in my country are often drawn to historical monuments. This includes things like ancient castles, cathedrals, and war memorials. There's a lot of history here, so visitors are often interested in sites that tell a story about the nation's past. Statues of famous historical figures in major cities are also very popular."

**2. Why do you think there are often statues of famous people in public places?**
"I think it's a way for a society to commemorate and honour individuals who have made significant contributions to the country's history or culture – people like political leaders, scientists, or artists. These statues serve as a public reminder of their legacy and achievements, and they can inspire a sense of national pride."

**3. Do you agree that old monuments and buildings should always be preserved?**
"For the most part, yes. They are a physical link to our past and provide a sense of identity and continuity. They are invaluable for education and tourism. However, I don't think 'always' is realistic. If a building is structurally unsafe and beyond repair, or if preserving it would cost an astronomical amount of money that could be better used elsewhere, then sometimes difficult decisions have to be made."

**Architecture**

**4. Why is architecture such a popular university subject?**
"I believe it's popular because it's a unique blend of art and science. It appeals to people who are both creative and technically-minded. There's also something very tangible and lasting about creating buildings that will be used by people for generations. It's a profession where you can leave a visible mark on the world."

**5. In what ways has the design of homes changed in recent years?**
"There have been significant changes. Modern homes are much more focused on open-plan living, with combined kitchen, dining, and living areas. There's also a much greater emphasis on energy efficiency and sustainability, with features like better insulation, solar panels, and smart home technology. Also, the idea of a home office has become a standard feature since so many people now work from home."

**6. To what extent does the design of buildings affect people’s moods?**
"I think it affects our moods to a very large extent. A building with lots of natural light, high ceilings, and a connection to outdoor spaces can make people feel happier, more creative, and more relaxed. In contrast, a dark, cramped, or poorly designed space can make people feel stressed, confined, and even depressed. The environment we are in has a profound psychological impact on us."`
                }]
            }
        ]
    }
];