

import { Lesson, QuestionType, Section, LessonPart } from '../types';

const ielts19ReadingPassage1Test2 = `The Industrial Revolution began in Britain in the mid-1700s and by the 1830s and 1840s had spread to many other parts of the world, including the United States. In Britain, it was a period when a largely rural, agrarian* society was transformed into an industrialised, urban one. Goods that had once been crafted by hand started to be produced in mass quantities by machines in factories, thanks to the invention of steam power and the introduction of new machines and manufacturing techniques in textiles, iron-making and other industries.

The foundations of the Industrial Revolution date back to the early 1700s, when the English inventor Thomas Newcomen designed the first modern steam engine. Called the ‘atmospheric steam engine’, Newcomen’s invention was originally used for power machines that pumped water out of mines. In the 1760s, the Scottish engineer James Watt started to adapt one of Newcomen’s models, and succeeded in making it far more efficient. Watt later worked with the English manufacturer Matthew Boulton to invent a new steam engine driven by both the forward and backward strokes of the piston, while the steam engine it was connected to produced rotary motion. It was a key innovation that would allow steam power to spread across British industries.

The demand for coal, which was a relatively cheap energy source, grew rapidly during the Industrial Revolution, as it was needed to run not only the factories used to produce manufactured goods, but also steam-powered transportation. In the early 1800s, the English engineer Richard Trevithick built a steam-powered locomotive, and by 1830 goods and passengers were being transported between the industrial centres of Manchester and Liverpool. In addition, steam-powered boats and ships were widely used to carry goods along Britain’s canals and across the Atlantic.

Britain had produced textiles like wool, linen and cotton, for hundreds of years, but prior to the Industrial Revolution, the British textile business was a true ‘cottage industry’, with the work performed in small workshops or even homes by individual spinners, weavers and dyers. Starting in the mid-1700s, innovations like the spinning jenny and the power loom made weaving cloth and spinning yarn and thread much easier. With these machines, relatively little labour was required to produce cloth, and the new mechanised textile factories that opened around the country were quickly able to meet customer demand for cloth both at home and abroad.

The British iron industry also underwent major change as it adopted new innovations. Chief among the new techniques was the smelting of iron ore with coke (a material made by heating coal) instead of the traditional charcoal. This method was cheaper and produced metals that were of a higher quality, enabling Britain’s iron and steel production to expand in response to demand created by the Napoleonic Wars (1803–15) and the expansion of the railways from the 1830s.

The latter part of the Industrial Revolution also saw key advances in communication methods, as people increasingly saw the need to communicate efficiently over long distances. In 1837, British inventors William Cooke and Charles Wheatstone patented the first commercial telegraphy system. In the 1830s and 1840s, Samuel Morse and other inventors worked on their own versions in the United States. Cooke and Wheatstone’s system was soon used for railway signalling in the UK. As the speed of the new locomotives increased, it was essential to have a fast and effective means of avoiding collisions.

The impact of the Industrial Revolution on people’s lives was immense. Although many people in Britain had begun moving to the cities from rural areas before the Industrial Revolution, this accelerated dramatically with industrialisation, as the rise of large factories turned smaller towns into major cities in just a few decades. This rapid urbanisation brought significant challenges, as overcrowded cities suffered from pollution and inadequate sanitation.

Although industrialisation improved the standard of living for the middle and upper classes, many poor people continued to struggle. Factory workers had to work long hours in dangerous conditions for extremely low wages. These conditions along with the rapid pace of change fuelled opposition to industrialisation. A group of British workers who became known as ‘Luddites’ were British weavers and textile workers who objected to the increased use of mechanised looms and knitting frames. Many had spent years learning their craft, and they feared that unskilled machine operators were robbing them of their livelihood. A few desperate weavers began breaking into factories and smashing textile machines. They called themselves Luddites after Ned Ludd, a young apprentice who was rumoured to have wrecked a textile machine in 1779.

The first major instances of machine breaking took in 1811 in the city of Nottingham, and the practice soon spread across the country. Machine-breaking Luddites attacked and burned factories, and in some cases they even exchanged gunfire with company guards and soldiers. The workers wanted employers to stop installing new machinery, but the British government responded to the uprisings by making machine-breaking punishable by death. The unrest finally reached its peak in April 1812, when a few Luddites were shot during an attack on a mill near Huddersfield. In the days that followed, other Luddites were arrested, and dozens were hanged or transported to Australia. By 1813, the Luddite resistance had all but vanished.`;
const ielts19ReadingPassage2Test2 = `Athletes and stress

A It isn’t easy being a professional athlete. Not only are the physical demands greater than most people could handle, athletes also face intense psychological pressure during competition. This is something that British tennis player Emma Raducanu wrote about on social media following her withdrawal from the 2021 Wimbledon tournament. Though the young player had been doing well in the tournament, she began having difficulty regulating her breathing and heart rate during a match, which she later attributed to ‘the accumulation of the excitement and the buzz’.

B For athletes, some level of performance stress is almost unavoidable. But there are many different factors that dictate just how people’s minds and bodies respond to stressful events. Typically, stress is the result of an exchange between two factors: demands and resources. An athlete may feel stressed about an event if they feel the demands on them are greater than they can handle. These demands include the high level of physical and mental effort required to succeed, and also the athlete’s concerns about the difficulty of the event, their chance of succeeding, and any potential dangers such as injury. Resources, on the other hand, are a person’s ability to cope with these demands. These include factors such as the competitor’s degree of confidence, how much they believe they can control the situation’s outcome, and whether they’re looking forward to the event or not.

C Each new demand or change in circumstances affects whether a person responds positively or negatively to stress. Typically, the more resources a person feels they have in handling the situation, the more positive their stress response. This positive stress response is called a challenge state. But should the person feel there are too many demands placed on them, the more likely they are to experience a negative stress response – known as a threat state. Research shows that the challenge states lead to good performance, while threat states lead to poorer performance. So, in Emma Raducanu’s case, a much larger audience, higher expectations and facing a more skilful opponent, may all have led her to feel there were greater demands being placed on her at Wimbledon – but she didn’t have the resources to tackle them. This led to her experiencing a threat response.

D Our challenge and threat responses essentially influence how our body responds to stressful situations, as both affect the production of adrenaline and cortisol – also known as stress hormones. During a challenge state, adrenaline increases the amount of blood pumped from the heart and expands the blood vessels, which allows more energy to be delivered to the muscles and brain. This increase of blood and decrease of pressure in the blood vessels has been consistently related to superior sport performance in everything from cricket batting, to golf putting and football penalty taking. But during a threat state, cortisol inhibits the positive effect of adrenaline, resulting in tighter blood vessels, higher blood pressure, slower psychological responses, and a faster heart rate. In short, a threat state makes people more anxious – they make worse decisions and perform more poorly. In tennis players, cortisol has been associated with more unsuccessful serves and greater anxiety.

E That said, anxiety is also a common experience for athletes when they’re under pressure. Anxiety can increase heart rate and perspiration, cause heart palpitations, muscle tremors and shortness of breath, as well as headaches, nausea, stomach pain, weakness and a desire to escape in more extreme cases. Anxiety can also reduce concentration and self-control and cause overthinking. The intensity with which a person experiences anxiety depends on the demands and resources they have. Anxiety may also manifest itself in the form of excitement or nervousness depending on the stress response. Negative stress responses can be damaging to both physical and mental health – and repeated episodes of anxiety coupled with negative responses can increase risk of heart disease and depression.

F But there are many ways athletes can ensure they respond positively under pressure. Positive stress responses can be promoted through the language that they and others – such as coaches or parents – use. Psychologists can also help athletes change how they see their physiological responses – such as helping them see a higher heart rate as excitement, rather than anxiety. Developing psychological skills, such as visualisation, can also help decrease physiological responses to threat. Visualisation may involve the athlete recreating a mental picture of a time when they performed well, or picturing themselves doing well in the future. This can help create a feeling of control over the stressful event. Recreating competitive pressure during training can also help athletes learn how to deal with stress. An example of this might be scoring athletes against their peers to create a sense of competition. This would increase the demands which players experience compared to a normal training session, while still allowing them to practise coping with stress.`;
const ielts19ReadingPassage3Test2 = `An inquiry into the existence of the gifted child

Let us start by looking at a modern ‘genius’, Maryam Mirzakhani, who died at the early age of 40. She was the only female to have been awarded the Fields Medal, often described as the Nobel prize for mathematics. As a child, she was not particularly interested in maths and did rather poorly at it for the first couple of years of high school. It was her older brother who first sparked her interest when he shared a famous maths problem from a magazine that fascinated her – and she was hooked. From that moment, she dedicated her life to taking her mathematical abilities to the heights of original research into mathematics. Another characteristic was her resolve in the face of setbacks. She described her research process as being ‘like being lost in a jungle and trying to use all the knowledge that you can gather to come up with some new tricks, and with some luck you might find a way out’. One of her comments sums it up: ‘Of course, the most rewarding part is the “Aha” moment, the excitement of discovery and enjoyment of understanding something new.’

Most Nobel prize winners were unexceptional in childhood. Einstein was slow to talk as a baby. He failed the general part of the entry test to Zurich Polytechnic. Though they let him in because of high physics and maths scores. He struggled at work initially, but he kept plugging away and eventually rewrote the laws of Newtonian mechanics with his theory of relativity.

There has been a considerable amount of research on high performance over the last century that suggests it goes way beyond tested intelligence. On top of that, research is clear that brains are flexible, new neural pathways can be created, and IQ isn’t fixed. For example, just because you can read stories with hundreds of pages at the age of five doesn’t mean you will still be ahead of your contemporaries in your teens.

While the jury is out on giftedness being innate and other factors potentially making the difference, what is certain is that the behaviours associated with high levels of performance are replicable and most can be taught – even traits such as curiosity.

According to my colleague Prof Deborah Eyre, with whom I’ve collaborated on the book Great Minds and How to Grow Them, the latest neuroscience and psychological research suggests most individuals can reach levels of performance associated in school with the gifted and talented. However, they must be taught the right attitudes and approaches to their learning and develop the attributes of high performers – curiosity, persistence and hard work, for example – an approach Eyre calls ‘high performance learning’. Critically, they need the right support in developing those approaches at home as well as at school.

Prof Anders Ericsson, an eminent education psychologist at Florida State University, US, is the co-author of Peak: Secrets from the New Science of Expertise. After research going back to 1980 into diverse achievements, from music to memory to sport, he doesn’t think unique and innate talents are at the heart of performance. Deliberate practice, that stretches you every step of the way, and around 10,000 hours of it, is what produces the goods. It’s not a magic number – the highest performers move on to doing a whole lot more, of course. Ericsson’s memory research is particularly interesting because random students, trained in memory techniques for the study, went on to outperform others thought to have innately superior memories – those who you might call gifted.

But it is perhaps the work of Benjamin Bloom, another distinguished American educationist working in the 1980s, that gives the most pause for thought. Bloom’s team looked at a group of extraordinarily high achieving people in disciplines as varied as ballet, swimming, piano, tennis, maths, sculpture and neurology. He found a pattern of parents encouraging and supporting their children, often in areas they enjoyed themselves. Bloom’s outstanding people had worked very hard and consistently at something they had become hooked on when at a young age, and their parents all emerged as having strong work ethics themselves.

Eyre says we know how high performers learn. From that she has developed a high performing learning approach. She is working on this with a group of schools, both in Britain and abroad. Some spin-off research, which looked in detail at 24 of the 3,000 children being studied who were succeeding despite difficult circumstances, found something remarkable. Half were getting free school meals because of poverty, more than half were living with a single parent, and four in five were living in disadvantaged areas. Interviews uncovered strong evidence of an adult or adults in the child’s life who valued and supported education, either in the immediate or extended family or in the child’s wider community. Children talked about the need to work hard at school, to listen in class and keep trying.

Let us end with Einstein, the epitome of a genius. He clearly had curiosity, character and determination. He struggled against rejection in early life but was undeterred. Did he think he was a genius or even gifted? He once wrote: ‘It’s not that I’m so smart, it’s just that I stay with problems longer.’ Most people say it is the intellect which makes a great scientist. They are wrong: it is character.`;


export const ielts19Test2Lessons: Lesson[] = [
  {
    id: 'b19-t2-l0',
    title: 'Test 2: Listening P1-2',
    section: Section.LISTENING,
    parts: [
      { // Part 1
        questions: [
            { id: 'b19t2lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the form below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t2-p1.mp3', questionText: 'Coordinator: Gary ___', correctAnswers: ['Mathieson'], transcript: "He’s called a ‘coordinator’ – his name’s Gary Mathieson.", transcriptHighlight: "Mathieson" },
            { id: 'b19t2lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the form below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t2-p1.mp3', questionText: 'Level: ___', correctAnswers: ['beginners'], transcript: "That’s what I thought, too. When I first spoke to Gary on the phone, he said it was a class for beginners.", transcriptHighlight: "beginners" },
            { id: 'b19t2lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the form below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t2-p1.mp3', questionText: 'Place: the ___', correctAnswers: ['college'], transcript: "Well, when I joined the group, they were meeting in Gary’s home, but as the group got bigger, he decided to book a room at the college in town.", transcriptHighlight: "college" },
            { id: 'b19t2lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the form below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t2-p1.mp3', questionText: '___ Street', correctAnswers: ['New'], transcript: "It’s just beyond there at the bottom of New Street near the city roundabout.", transcriptHighlight: "New Street" },
            { id: 'b19t2lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the form below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t2-p1.mp3', questionText: 'Time: Thursday morning at ___', correctAnswers: ['11', 'eleven'], transcript: "We meet on Thursdays. It used to be 10.30 and that suited me well, but now we meet at 11.", transcriptHighlight: "11" },
            { id: 'b19t2lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the form below. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p1.mp3', questionText: "Recommended website: 'The perfect ___'", correctAnswers: ['instrument'], transcript: "Well, you can always buy a second-hand one. There’s a website called ‘The perfect instrument’ that sells all kinds of guitars, violins and so on.", transcriptHighlight: "instrument" },
            { id: 'b19t2lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table below. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p1.mp3', questionText: 'using an app or by ___', correctAnswers: ['ear'], transcript: "Some people have an app they use, but others do it by ear.", transcriptHighlight: "ear" },
            { id: 'b19t2lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table below. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p1.mp3', questionText: 'keeping time while the teacher is ___', correctAnswers: ['clapping'], transcript: "We do at least one song with words and chords. I mean that’s harder than you think. ... So we do at least start just laughing because we’re so bad at keeping time, so Gary starts clapping to help us.", transcriptHighlight: "clapping" },
            { id: 'b19t2lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table below. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p1.mp3', questionText: 'often listening to a ___ of a song', correctAnswers: ['recording'], transcript: "That part of the lesson takes about 15 minutes. He often brings a recording of the song and plays it to us first.", transcriptHighlight: "recording" },
            { id: 'b19t2lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table below. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p1.mp3', questionText: 'playing together, then ___', correctAnswers: ['alone'], transcript: "The only trouble is that he sometimes gets us to play one at a time – you know, alone.", transcriptHighlight: "alone" },
        ],
      },
      { // Part 2
        questions: [
            { id: 'b19t2lq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p2.mp3', questionText: 'What made David leave London and move to Northsea?', options: ['He was eager to develop a hobby.', 'He wanted to work shorter hours.', 'He found his job in website design unsatisfying.'], correctAnswers: ['He was eager to develop a hobby.'], transcript: "I’d been working in London as a website designer, but although that was interesting, I didn’t like city life. I’d been really keen on boats as a teenager, and I thought if I went to live by the sea, I might be able to pursue that interest a bit more in my free time.", transcriptHighlight: "pursue that interest a bit more" },
            { id: 'b19t2lq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p2.mp3', questionText: 'The Lifeboat Institution in Northsea was built with money provided by', options: ['a local organisation.', 'a local resident.', 'the local council.'], correctAnswers: ['a local resident.'], transcript: "The lifeboat institution building here in Northsea’s hard to miss ... It’s one of the largest in the country. It was built 15 years ago with funds provided by a generous member of the public who’d lived here all her life.", transcriptHighlight: "a generous member of the public" },
            { id: 'b19t2lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p2.mp3', questionText: 'In his health assessment, the doctor was concerned about the fact that David', options: ['might be colour blind.', 'was rather short-sighted.', 'had undergone eye surgery.'], correctAnswers: ['might be colour blind.'], transcript: "The doctors were particularly interested in my vision. I used to be short-sighted... They gave me tests for colour blindness and they thought I might have a problem there, but it turned out I was OK.", transcriptHighlight: "tests for colour blindness and they thought I might have a problem" },
            { id: 'b19t2lq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p2.mp3', questionText: 'After arriving at the lifeboat station, they aim to launch the boat within', options: ['five minutes.', 'six to eight minutes.', 'eight and a half minutes.'], correctAnswers: ['six to eight minutes.'], transcript: "When the coastguard gets an alert, all the volunteers are contacted and rush to the lifeboat station. Our target’s to get there in five minutes, then we try to get the boat off the dock and out to sea in another six to eight minutes.", transcriptHighlight: "out to sea in another six to eight minutes" },
            { id: 'b19t2lq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p2.mp3', questionText: "As a 'helmsman', David has the responsibility of deciding", options: ['who will be the members of his crew.', 'what equipment it will be necessary to take.', 'if the lifeboat should be launched.'], correctAnswers: ['if the lifeboat should be launched.'], transcript: "I’ve recently qualified as what’s called a ‘helmsman’, which means I have the ultimate responsibility for the lifeboat. ... it’s ultimately my decision whether it’s safe to launch the boat.", transcriptHighlight: "my decision whether it’s safe to launch the boat" },
            { id: 'b19t2lq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p2.mp3', questionText: 'As well as going out on the lifeboat, David', options: ['gives talks on safety at sea.', 'helps with fundraising.', 'recruits new volunteers.'], correctAnswers: ['gives talks on safety at sea.'], transcript: "As well as going out on the lifeboat, my work involves other things too. A lot of people underestimate how quickly conditions can change at sea, so I speak to youth groups and sailing clubs about the sorts of problems that sailors and swimmers can have if the weather suddenly gets bad.", transcriptHighlight: "I speak to youth groups and sailing clubs" },
            { id: 'b19t2lq17', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'Part 2: Choose TWO letters, A–E.', audioUrl: 'ielts-19/t2-p2.mp3', questionText: 'Which TWO things does David say about the lifeboat volunteer training?', options: ['The residential course developed his leadership skills.', 'The training in use of ropes and knots was quite brief.', 'The casualty care activities were particularly challenging for him.', 'The training exercises have built up his mental strength.', 'The wave tank activities provided practice in survival techniques.'], correctAnswers: ['The casualty care activities were particularly challenging for him.', 'The wave tank activities provided practice in survival techniques.'], transcript: "I was glad I’d done a first aid course before I started, as that’s a big help with the casualty care activities we do... After a year, I did a one-week residential course, led by specialists. They had a wave-tank where they could create extreme weather conditions... so we could get experience at what to do if the boat turned over in a storm at night, for example.", transcriptHighlight: "casualty care activities... wave-tank"},
            { id: 'b19t2lq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose TWO letters, A–E.', maxSelections: 2, audioUrl: 'ielts-19/t2-p2.mp3', questionText: 'Which TWO things does David find most motivating about the work he does?', options: ['working as part of a team', 'experiences when working in winter', 'being thanked by those he has helped', 'the fact that it keeps him fit', 'the chance to develop new equipment'], correctAnswers: ['working as part of a team', 'experiences when working in winter'], transcript: "They’re a great group – we’re like a family really, which helps when you’re drawing yourself out of bed on a cold stormy night. But actually, it’s the colder months that can be the most rewarding time.", transcriptHighlight: "like a family... colder months that can be the most rewarding" },
        ],
      }
    ]
  },
  {
    id: 'b19-t2-l1',
    title: 'Test 2: Listening P3-4',
    section: Section.LISTENING,
    parts: [
      { // Part 3
        questions: [
            { id: 'b19t2lq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p3.mp3', questionText: 'At first, Don thought the topic of recycling footwear might be too', options: ['limited in scope.', 'hard to research.', 'boring for listeners.'], correctAnswers: ['limited in scope.'], transcript: "Well, before I started reading it, I thought recycling footwear, well, although it’s interesting, perhaps there wasn’t enough to talk about it, cos we put shoes in recycling bins, they go to charity shops and that’s about it.", transcriptHighlight: "perhaps there wasn’t enough to talk about it" },
            { id: 'b19t2lq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p3.mp3', questionText: 'When discussing trainers, Bella and Don disagree about', options: ['how popular they are among young people.', 'how suitable they are for school.', 'how quickly they wear out.'], correctAnswers: ['how suitable they are for school.'], transcript: "I know. I think they’re very hard-wearing, but don’t they look a bit casual for school uniform? I don’t think they’re right for that.", transcriptHighlight: "don’t think they’re right for that" },
            { id: 'b19t2lq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p3.mp3', questionText: 'Bella says that she sometimes recycles shoes because', options: ['they no longer fit.', 'she no longer likes them.', 'they are no longer in fashion.'], correctAnswers: ['she no longer likes them.'], transcript: "Yes. Though I tend to wear my old pairs for doing dirty jobs like cleaning my bike. Must admit, I’ve got some perfectly good shoes, that haven’t gone out of fashion and still fit, just because they don’t look great on me any more.", transcriptHighlight: "don’t look great on me any more" },
            { id: 'b19t2lq24', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p3.mp3', questionText: 'What did the article say that confused Don?', options: ['Public consumption of footwear has risen.', 'Less footwear is recycled now than in the past.', 'People dispose of more footwear than they used to.'], correctAnswers: ['Less footwear is recycled now than in the past.'], transcript: "But now it said that the amount of recycled footwear has fallen: it’s 6 percent, compared to previous levels of 11 percent.", transcriptHighlight: "amount of recycled footwear has fallen" },
            { id: 'b19t2lq25', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: What reasons did the recycling manager give for rejecting footwear? \n25 the high-heeled shoes', audioUrl: 'ielts-19/t2-p3.mp3', questionText: '', options: ['A one shoe was missing', 'B the colour of one shoe had faded', 'C one shoe had a hole in it', 'D the shoes were brand new', 'E the shoes were too dirty', 'F the stitching on the shoes was broken'], correctAnswers: ['E the shoes were too dirty'], transcript: "the material was suede and they were beige in colour – it looked like someone had only worn them once, but in a very wet field so the shoes were too stained with mud and grass to re-sell them.", transcriptHighlight: "too stained with mud and grass" },
            { id: 'b19t2lq26', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: What reasons did the recycling manager give for rejecting footwear? \n26 the ankle boots', audioUrl: 'ielts-19/t2-p3.mp3', questionText: '', options: ['A one shoe was missing', 'B the colour of one shoe had faded', 'C one shoe had a hole in it', 'D the shoes were brand new', 'E the shoes were too dirty', 'F the stitching on the shoes was broken'], correctAnswers: ['B the colour of one shoe had faded'], transcript: "One of the shoes was a much lighter shade than the other one – it had obviously been left in the sun.", transcriptHighlight: "a much lighter shade" },
            { id: 'b19t2lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: What reasons did the recycling manager give for rejecting footwear? \n27 the baby shoes', audioUrl: 'ielts-19/t2-p3.mp3', questionText: '', options: ['A one shoe was missing', 'B the colour of one shoe had faded', 'C one shoe had a hole in it', 'D the shoes were brand new', 'E the shoes were too dirty', 'F the stitching on the shoes was broken'], correctAnswers: ['A one shoe was missing'], transcript: "Sure. Then there were the red baby shoes. Oh yes – we’re told to tie shoes together when we put them in a recycling bin, but people often don’t bother.", transcriptHighlight: "people often don’t bother" },
            { id: 'b19t2lq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: What reasons did the recycling manager give for rejecting footwear? \n28 the trainers', audioUrl: 'ielts-19/t2-p3.mp3', questionText: '', options: ['A one shoe was missing', 'B the colour of one shoe had faded', 'C one shoe had a hole in it', 'D the shoes were brand new', 'E the shoes were too dirty', 'F the stitching on the shoes was broken'], correctAnswers: ['C one shoe had a hole in it'], transcript: "Not exactly. One of the soles was so worn under the foot that you could put your finger through it.", transcriptHighlight: "finger through it" },
            { id: 'b19t2lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p3.mp3', questionText: "Why did the project to make 'new' shoes out of old shoes fail?", options: ["People believed the 'new' pairs of shoes were unhygienic.", "There were not enough good parts to use in the old shoes.", "The shoes in the 'new' pairs were not completely alike."], correctAnswers: ["The shoes in the 'new' pairs were not completely alike."], transcript: "Well, people didn’t refuse them for that reason, did they? It was because the pairs of shoes weren’t identical.", transcriptHighlight: "weren’t identical" },
            { id: 'b19t2lq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t2-p3.mp3', questionText: 'Bella and Don agree that they can present their topic', options: ['from a new angle.', 'with relevant images.', 'in a straightforward way.'], correctAnswers: ['from a new angle.'], transcript: "It’s not as simple as you first think, and we can show that by taking a very different approach to it.", transcriptHighlight: "taking a very different approach" },
        ],
      },
      { // Part 4
        questions: [
            { id: 'b19t2lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p4.mp3', questionText: 'also known as water ‘bears’ (due to how they 31 ___) and ‘moss piglets’', correctAnswers: ['move'], transcript: "though the largest species can grow to be 1.2 millimetres in length. They are also sometimes called ‘water bears’ because of the way they move. ‘Moss piglet’ is another name for tardigrades", transcriptHighlight: "move" },
            { id: 'b19t2lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p4.mp3', questionText: 'a 32 ___ round body and four pairs of legs', correctAnswers: ['short'], transcript: "they have a body which is short, and also rounded – a bit like a barrel", transcriptHighlight: "short" },
            { id: 'b19t2lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p4.mp3', questionText: 'claws or 33 ___ for gripping', correctAnswers: ['discs'], transcript: "I should also say that some species don’t have any claws; what they have are discs, and these work by means of suction.", transcriptHighlight: "discs" },
            { id: 'b19t2lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p4.mp3', questionText: 'body filled with a liquid that carries both 34 ___ and blood', correctAnswers: ['oxygen'], transcript: "Instead, oxygen and also blood are transported in a fluid that fills the cavity of the body.", transcriptHighlight: "oxygen" },
            { id: 'b19t2lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p4.mp3', questionText: 'mouth shaped like a 35 ___ with teeth called stylets', correctAnswers: ['tube'], transcript: "the best way I can describe this is that it looks rather strange – a bit squashed even – though many of the websites I looked at described its appearance as cute, which isn’t exactly very scientific. The tardigrade’s mouth is a kind of tube that can open outwards to reveal teeth-like structures known as ‘stylets’.", transcriptHighlight: "tube" },
            { id: 'b19t2lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p4.mp3', questionText: 'very resilient and can exist in very low or high 36 ___', correctAnswers: ['temperatures'], transcript: "they’re also able to withstand temperatures as cold as –200 degrees centigrade, or highs of more than 148 degrees centigrade", transcriptHighlight: "temperatures" },
            { id: 'b19t2lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p4.mp3', questionText: 'A type of 37 ___ ensures their DNA is not damaged.', correctAnswers: ['protein'], transcript: "Within a state of cryptobiosis, tardigrades produce a protein that protects their DNA.", transcriptHighlight: "protein" },
            { id: 'b19t2lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p4.mp3', questionText: 'Research is underway to find out how many days they can stay alive in 38 ___.', correctAnswers: ['space'], transcript: "It has been said that tardigrades could survive long after human beings have been wiped out, even in the event of an asteroid hitting the earth. ... a 120-year-old tun was revived, but this experiment has never been repeated. There are currently several tests taking place in space, to determine how long tardigrades might be able to survive there.", transcriptHighlight: "space" },
            { id: 'b19t2lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p4.mp3', questionText: 'consume liquids, e.g., those found in moss or 39 ___', correctAnswers: ['seaweed'], transcript: "Although they have teeth, they don’t use these for chewing. They suck the juices from moss, or extract fluid from seaweed, but some species prey on other tardigrades", transcriptHighlight: "seaweed" },
            { id: 'b19t2lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t2-p4.mp3', questionText: 'They are not considered to be 40 ___.', correctAnswers: ['endangered'], transcript: "tardigrades have not been evaluated by the International Union for Conservation of Nature and are not on any endangered list.", transcriptHighlight: "not on any endangered list" },
        ],
      }
    ]
  },
  {
    id: 'b19-t2-r2',
    title: 'Test 2: Reading P1',
    section: Section.READING,
    parts: [{
        questions: [
            { id: 'b19t2rq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes. Write ONE WORD ONLY.', passage: ielts19ReadingPassage1Test2, questionText: "In Watt and Boulton's steam engine, the movement of the 1 ___ was linked to a gear system.", correctAnswers: ['piston'], passageHighlight: "a new steam engine driven by both the forward and backward strokes of the piston", reason: "The passage states that James Watt's engine was 'driven by both the forward and backward strokes of the piston' and 'produced rotary motion'. This rotary motion implies a link to a gear system." },
            { id: 'b19t2rq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes. Write ONE WORD ONLY.', passage: ielts19ReadingPassage1Test2, questionText: 'A greater supply of 2 ___ was required to power steam engines.', correctAnswers: ['coal'], passageHighlight: "The demand for coal, which was a relatively cheap energy source, grew rapidly", reason: "The passage explicitly states that 'The demand for coal... grew rapidly during the Industrial Revolution, as it was needed to run' factories and steam-powered transportation." },
            { id: 'b19t2rq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes. Write ONE WORD ONLY.', passage: ielts19ReadingPassage1Test2, questionText: 'Before the Industrial Revolution, spinners and weavers worked at home and in 3 ___.', correctAnswers: ['workshops'], passageHighlight: "the work performed in small workshops or even homes", reason: "The passage describes the pre-industrial textile business as a 'cottage industry', with 'the work performed in small workshops or even homes'." },
            { id: 'b19t2rq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes. Write ONE WORD ONLY.', passage: ielts19ReadingPassage1Test2, questionText: 'Not as much 4 ___ was needed to produce cloth once the spinning jenny and power loom were invented.', correctAnswers: ['labour', 'labor'], passageHighlight: "relatively little labour was required to produce cloth", reason: "The text states that with new machines like the spinning jenny, 'relatively little labour was required to produce cloth'." },
            { id: 'b19t2rq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes. Write ONE WORD ONLY.', passage: ielts19ReadingPassage1Test2, questionText: 'Smelting of iron ore with coke resulted in material that was better 5 ___.', correctAnswers: ['quality'], passageHighlight: "produced metals that were of a higher quality", reason: "The passage mentions that the new smelting method using coke 'produced metals that were of a higher quality'." },
            { id: 'b19t2rq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes. Write ONE WORD ONLY.', passage: ielts19ReadingPassage1Test2, questionText: 'Demand for iron increased with the growth of the 6 ___.', correctAnswers: ['railway', 'railways'], passageHighlight: "the expansion of the railways from the 1830s", reason: "The passage connects the expansion of iron production to 'demand created by ... the expansion of the railways from the 1830s'." },
            { id: 'b19t2rq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes. Write ONE WORD ONLY.', passage: ielts19ReadingPassage1Test2, questionText: 'The new cities were dirty, crowded and lacked sufficient 7 ___.', correctAnswers: ['sanitation'], passageHighlight: "overcrowded cities suffered from pollution and inadequate sanitation", reason: "The passage describes the challenges of rapid urbanization, stating that 'overcrowded cities suffered from pollution and inadequate sanitation'." },
            { id: 'b19t2rq8', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test2, questionText: "Britain's canal network grew rapidly so that more goods could be transported around the country.", options: ['True', 'False', 'Not Given'], correctAnswers: ['Not Given'], reason: "The passage mentions that steam-powered boats used Britain's canals, but it does not provide any information about whether the canal network itself grew rapidly during this period." },
            { id: 'b19t2rq9', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test2, questionText: 'Costs in the iron industry rose when the technique of smelting iron ore with coke was introduced.', options: ['True', 'False', 'Not Given'], correctAnswers: ['False'], passageHighlight: "This method was cheaper", reason: "The passage directly contradicts this statement by saying that the method of smelting with coke 'was cheaper'." },
            { id: 'b19t2rq10', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test2, questionText: "Samuel Morse's communication system was more reliable than that developed by William Cooke and Charles Wheatstone.", options: ['True', 'False', 'Not Given'], correctAnswers: ['Not Given'], reason: "The passage states that Morse worked on his own version of the telegraph but does not compare its reliability to the Cooke and Wheatstone system." },
            { id: 'b19t2rq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test2, questionText: 'The economic benefits of industrialisation were limited to certain sectors of society.', options: ['True', 'False', 'Not Given'], correctAnswers: ['True'], passageHighlight: "Although industrialisation improved the standard of living for the middle and upper classes, many poor people continued to struggle.", reason: "The passage supports this statement by explaining that while industrialisation 'improved the standard of living for the middle and upper classes', the 'poor people continued to struggle', indicating the benefits were not universal." },
            { id: 'b19t2rq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test2, questionText: 'Some skilled weavers believed that the introduction of the new textile machines would lead to job losses.', options: ['True', 'False', 'Not Given'], correctAnswers: ['True'], passageHighlight: "they feared that unskilled machine operators were robbing them of their livelihood", reason: "The passage states that weavers 'feared that unskilled machine operators were robbing them of their livelihood', which is synonymous with leading to job losses." },
            { id: 'b19t2rq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test2, questionText: 'There was some sympathy among local people for the Luddites who were arrested near Huddersfield.', options: ['True', 'False', 'Not Given'], correctAnswers: ['Not Given'], reason: "The passage details the Luddites' actions and the government's harsh response, but it does not mention the opinions or feelings of the general local population towards the arrested Luddites." },
        ],
    }],
  },
  {
    id: 'b19-t2-r3',
    title: 'Test 2: Reading P2-3',
    section: Section.READING,
    parts: [
      { // Reading Passage 2
        questions: [
            { id: 'b19t2rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–F.', passage: ielts19ReadingPassage2Test2, questionText: 'reference to two chemical compounds which impact on performance', options: ['A','B','C','D','E','F'], correctAnswers: ['D'], passageHighlight: "affect the production of adrenaline and cortisol", reason: "Paragraph D explicitly names two stress hormones, 'adrenaline and cortisol', and describes how they affect an athlete's body and performance." },
            { id: 'b19t2rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–F.', passage: ielts19ReadingPassage2Test2, questionText: 'examples of strategies for minimising the effects of stress', options: ['A','B','C','D','E','F'], correctAnswers: ['F'], passageHighlight: "Developing psychological skills, such as visualisation, can also help", reason: "Paragraph F outlines several strategies athletes can use to manage stress, including the use of specific language, psychological skills like 'visualisation', and 'recreating competitive pressure during training'." },
            { id: 'b19t2rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–F.', passage: ielts19ReadingPassage2Test2, questionText: 'how a sportsperson accounted for their own experience of stress', options: ['A','B','C','D','E','F'], correctAnswers: ['A'], passageHighlight: "which she later attributed to ‘the accumulation of the excitement and the buzz’", reason: "Paragraph A introduces tennis player Emma Raducanu and directly quotes how she accounted for her stress, which she 'attributed to ‘the accumulation of the excitement and the buzz’'." },
            { id: 'b19t2rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–F.', passage: ielts19ReadingPassage2Test2, questionText: 'study results indicating links between stress responses and performance', options: ['A','B','C','D','E','F'], correctAnswers: ['C'], passageHighlight: "Research shows that the challenge states lead to good performance, while threat states lead to poorer performance.", reason: "Paragraph C explicitly refers to 'Research shows' to link positive stress responses ('challenge states') to 'good performance' and negative stress responses ('threat states') to 'poorer performance'." },
            { id: 'b19t2rq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–F.', passage: ielts19ReadingPassage2Test2, questionText: 'mention of people who can influence how athletes perceive their stress responses', options: ['A','B','C','D','E','F'], correctAnswers: ['F'], passageHighlight: "Positive stress responses can be promoted through the language that they and others – such as coaches or parents – use.", reason: "Paragraph F mentions that stress responses can be influenced by the language used by the athlete and 'others – such as coaches or parents'." },
            { id: 'b19t2rq19', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Write ONE WORD ONLY.', passage: ielts19ReadingPassage2Test2, questionText: 'Performance stress involves many demands on the athlete, for example, coping with the possible risk of ___.', correctAnswers: ['injury'], passageHighlight: "any potential dangers such as injury", reason: "Paragraph B lists the demands on an athlete, which include 'any potential dangers such as injury'. The sentence asks about a 'possible risk', which directly corresponds to 'potential dangers'." },
            { id: 'b19t2rq20', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Write ONE WORD ONLY.', passage: ielts19ReadingPassage2Test2, questionText: 'Cortisol can cause tennis players to produce fewer good ___.', correctAnswers: ['serves'], passageHighlight: "cortisol has been associated with more unsuccessful serves", reason: "Paragraph D states that in tennis players, 'cortisol has been associated with more unsuccessful serves'. 'Fewer good serves' is a direct paraphrase of 'more unsuccessful serves'." },
            { id: 'b19t2rq21', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Write ONE WORD ONLY.', passage: ielts19ReadingPassage2Test2, questionText: 'Psychologists can help athletes to view their physiological responses as the effect of a positive feeling such as ___.', correctAnswers: ['excitement'], passageHighlight: "helping them see a higher heart rate as excitement, rather than anxiety", reason: "Paragraph F provides an example of how psychologists can help athletes reframe their responses, specifically by 'helping them see a higher heart rate as excitement, rather than anxiety'." },
            { id: 'b19t2rq22', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Write ONE WORD ONLY.', passage: ielts19ReadingPassage2Test2, questionText: '___ is an example of a psychological technique which can reduce an athlete’s stress responses.', correctAnswers: ['Visualisation', 'Visualization'], passageHighlight: "Developing psychological skills, such as visualisation", reason: "Paragraph F identifies 'visualisation' as a specific 'psychological skill' that can help athletes 'decrease physiological responses to threat', which is a way of reducing stress responses." },
            { id: 'b19t2rq23', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'Which TWO facts about Emma Raducanu’s withdrawal from the Wimbledon tournament are mentioned in the text?', passage: ielts19ReadingPassage2Test2, questionText: 'Choose TWO letters, A–E.', options: ["the stage at which she dropped out of the tournament", "symptoms of her performance stress at the tournament", "measures which she had taken to manage her stress levels", "aspects of the Wimbledon tournament which increased her stress levels", "reactions to her social media posts about her experience at Wimbledon"], correctAnswers: ["symptoms of her performance stress at the tournament", "aspects of the Wimbledon tournament which increased her stress levels"], passageHighlight: "began having difficulty regulating her breathing and heart rate during a match... a much larger audience, higher expectations and facing a more skilful opponent", reason: "Paragraph A describes Raducanu's symptoms, noting she had 'difficulty regulating her breathing and heart rate'. Paragraph C suggests aspects of the tournament that increased demands on her, such as 'a much larger audience, higher expectations and facing a more skilful opponent'." },
            { id: 'b19t2rq25', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'Which TWO facts about anxiety are mentioned in Paragraph E of the text?', passage: ielts19ReadingPassage2Test2, questionText: 'Choose TWO letters, A–E.', options: ["the factors which determine how severe it may be", "how long it takes for its effects to become apparent", "which of its symptoms is most frequently encountered", "the types of athletes who are most likely to suffer from it", "the harm that can result if athletes experience it too often"], correctAnswers: ["the factors which determine how severe it may be", "the harm that can result if athletes experience it too often"], passageHighlight: "The intensity with which a person experiences anxiety depends on the demands and resources they have... repeated episodes of anxiety coupled with negative responses can increase risk of heart disease and depression.", reason: "Paragraph E explains that the 'intensity' of anxiety (how severe it is) 'depends on the demands and resources' an athlete has. It also states that 'repeated episodes of anxiety' can lead to harm, such as an 'increase risk of heart disease and depression'." },
        ]
      },
      { // Reading Passage 3
        questions: [
          { id: 'b19t2rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–K, below.', passage: ielts19ReadingPassage3Test2, questionText: 'Maryam Mirzakhani is regarded as 27 ___ in the field of mathematics because she was the only female holder of the prestigious Fields Medal...', correctAnswers: ['H unique'], options: ['A appeal','B determined','C intrigued','D single','E achievement','F devoted','G involved','H unique','I innovative','J satisfaction', 'K intent'], reason: "The passage states that Maryam Mirzakhani 'was the only female to have been awarded the Fields Medal'. The word 'unique' means being the only one of its kind, which directly corresponds to her being the sole female recipient of this prestigious award." },
          { id: 'b19t2rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–K, below.', passage: ielts19ReadingPassage3Test2, questionText: 'However, maths held little 28 ___ for her as a child...', correctAnswers: ['A appeal'], options: ['A appeal','B determined','C intrigued','D single','E achievement','F devoted','G involved','H unique','I innovative','J satisfaction', 'K intent'], reason: "The passage states that as a child, Mirzakhani 'was not particularly interested in maths and did rather poorly at it'. This lack of interest and poor performance indicates that mathematics held little appeal for her at that time." },
          { id: 'b19t2rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–K, below.', passage: ielts19ReadingPassage3Test2, questionText: '... and in fact her performance was below average until she was 29 ___ by a difficult puzzle that one of her siblings showed her.', correctAnswers: ['C intrigued'], options: ['A appeal','B determined','C intrigued','D single','E achievement','F devoted','G involved','H unique','I innovative','J satisfaction', 'K intent'], reason: "The passage explains that her interest was sparked when her brother showed her a maths problem that 'fascinated her – and she was hooked'. The word 'intrigued' means to arouse curiosity or fascination, which perfectly describes her reaction to the puzzle." },
          { id: 'b19t2rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–K, below.', passage: ielts19ReadingPassage3Test2, questionText: 'Later, as a professional mathematician, she had an inquiring mind and proved herself to be 30 ___ when things did not go smoothly.', correctAnswers: ['B determined'], options: ['A appeal','B determined','C intrigued','D single','E achievement','F devoted','G involved','H unique','I innovative','J satisfaction', 'K intent'], reason: "The text highlights Mirzakhani's 'resolve in the face of setbacks'. 'Resolve' and 'determination' are synonyms, especially in the context of overcoming difficulties. This shows she was persistent and did not give up when facing challenges." },
          { id: 'b19t2rq31', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–K, below.', passage: ielts19ReadingPassage3Test2, questionText: 'She said she got the greatest 31 ___ from making ground-breaking discoveries...', correctAnswers: ['J satisfaction'], options: ['A appeal','B determined','C intrigued','D single','E achievement','F devoted','G involved','H unique','I innovative','J satisfaction', 'K intent'], reason: "The passage quotes Mirzakhani describing 'the most rewarding part' as 'the excitement of discovery and enjoyment of understanding something new'. The feeling of getting a reward and enjoyment is synonymous with satisfaction." },
          { id: 'b19t2rq32', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A–K, below.', passage: ielts19ReadingPassage3Test2, questionText: '... and in fact she was responsible for some extremely 32 ___ mathematical studies.', correctAnswers: ['I innovative'], options: ['A appeal','B determined','C intrigued','D single','E achievement','F devoted','G involved','H unique','I innovative','J satisfaction', 'K intent'], reason: "The text describes her work as 'original research into mathematics'. 'Original' in this context means new and not done before, which is the definition of 'innovative'. Therefore, her studies were groundbreaking and innovative." },
          { id: 'b19t2rq33', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer?', passage: ielts19ReadingPassage3Test2, questionText: 'Many people who ended up winning prestigious intellectual prizes only reached an average standard when young.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], reason: "The statement is supported by the passage which explicitly says, 'Most Nobel prize winners were unexceptional in childhood' and gives the example of Einstein who 'failed the general part of the entry test to Zurich Polytechnic'." },
          { id: 'b19t2rq34', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer?', passage: ielts19ReadingPassage3Test2, questionText: 'Einstein’s failures as a young man were due to his lack of confidence.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage mentions Einstein's early struggles, such as being 'slow to talk' and failing an entry test, but it does not provide any reason for these difficulties. There is no mention of his confidence levels, so the statement is 'Not Given'." },
          { id: 'b19t2rq35', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer?', passage: ielts19ReadingPassage3Test2, questionText: 'It is difficult to reach agreement on whether some children are actually born gifted.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], reason: "The passage uses the idiom 'While the jury is out on giftedness being innate', which directly means that a definitive conclusion has not been reached on whether giftedness is an inborn trait. This uncertainty indicates difficulty in reaching an agreement." },
          { id: 'b19t2rq36', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer?', passage: ielts19ReadingPassage3Test2, questionText: 'Einstein was upset by the public’s view of his life’s work.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage presents Einstein's view that 'character' makes a great scientist, contrasting it with the common belief in 'intellect'. However, it does not state his emotional reaction to this public view. There is no mention of him being 'upset', so the statement is 'Not Given'." },
          { id: 'b19t2rq37', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer?', passage: ielts19ReadingPassage3Test2, questionText: 'Einstein put his success down to the speed at which he dealt with scientific questions.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], reason: "The passage directly contradicts this statement by quoting Einstein: 'It’s not that I’m so smart, it’s just that I stay with problems longer.' This emphasizes persistence over speed, making the statement false." },
          { id: 'b19t2rq38', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test2, questionText: 'What does Eyre believe is needed for children to equal ‘gifted’ standards?', options: ['strict discipline from the teaching staff', 'assistance from their peers in the classroom', 'the development of a spirit of inquiry towards their studies', 'the determination to surpass everyone else’s achievements'], correctAnswers: ['the development of a spirit of inquiry towards their studies'], reason: "The passage states that Prof Deborah Eyre's approach involves teaching children 'the right attitudes and approaches to their learning and develop the attributes of high performers – curiosity, persistence and hard work'. Curiosity is the core of a 'spirit of inquiry'." },
          { id: 'b19t2rq39', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test2, questionText: 'What is the result of Ericsson’s research?', options: ['Very gifted students do not need to work on improving memory skills.', 'Being born with a special gift is not the key factor in becoming expert.', 'Including time for physical exercise is crucial to raising performance.', '10,000 hours of relevant and demanding work will create a genius.'], correctAnswers: ['Being born with a special gift is not the key factor in becoming expert.'], reason: "The passage summarises Prof Anders Ericsson's view: 'he doesn’t think unique and innate talents are at the heart of performance.' Instead, he emphasizes 'Deliberate practice'. This directly supports the idea that being born with a gift is not the key factor." },
          { id: 'b19t2rq40', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test2, questionText: 'In the penultimate paragraph, it is stated the key to some deprived children’s success is', options: ['a regular and nourishing diet at home.', 'the loving support of more than one parent.', 'a community which has well-funded facilities for learning.', 'the guidance of someone who recognises the benefits of learning.'], correctAnswers: ['the guidance of someone who recognises the benefits of learning.'], reason: "The passage describes research on children succeeding despite difficult circumstances. It found 'strong evidence of an adult or adults in the child’s life who valued and supported education'. This person provides the guidance that recognizes the benefits of learning." },
        ]
      }
    ]
  },
  {
    id: 'b19-t2-w4',
    title: 'Test 2: Writing T1-2',
    section: Section.WRITING,
    parts: [
       {
        questions: [{
            id: 'b19t2wq1',
            type: QuestionType.WRITING_TASK,
            prompt: 'You should spend about 20 minutes on this task.',
            imageUrl: 'ielts-19/ielts-19-t2-w1-map.png',
            task: 'The plans below show a harbour in 2000 and how it looks today.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.',
            sampleAnswerBand: 6.5,
            sampleAnswer: "The maps give the information about the improvement of the Porth Harbour from 2000 to today. The first impression is that the Harbour today made use of more areas than in the past.\n\nIt can be seen that there are several areas that still stay the same today as in 2000. These include the Carpark and the Showers and Toilets which are located in the north west of the map. However, one more Showers and Toilets are built between the two Carpark today. Besides, the Porth Harbour today also has one more Passenger ferries which right next to the left of the existing one from 2000. Moreover, an area for Cafés and shops is added next to the Lifeboat one. Another significant difference is the relocation of the Marina (private yachts) and the fishing boats areas. Today, the Marina is moved down to the place of the old Fishing boats area to have more space and vice-versa, the Fishing boats area is relocated at the old Marina area. The last noticeable change in this Harbour is the Construction in the South East. The disused old Castle was destroyed and a new Hotel was built there today and another Hotel is also added in the Private beach area.\n\nOverall, even that the harbour still keeps some areas unchanged, there are many reconstructions and improvements for the Porth Harbour today.",
            examinerComment: "Overall, this is a strong response. The candidate has covered the main features of the changes and has included an overview to summarise the changes, in the first and the last paragraph. The main details are accurate, apart from the addition of [another Hotel] in the private beach area.\n\nThe reader can follow the ideas as they are logically organised. This is due to the linking words [However | Besides | Also | Another | Overall] and cohesive features [existing one | vice-versa], but there are some errors.\n\nVocabulary demonstrates some flexibility [first impression | relocated | noticeable change], but there is also some inaccuracy and repetition. The weakest area, though, is the use of grammatical structures. There is a mix of sentence forms, with some complex use [made use of | can be seen that | These include . . . which are] but some errors, such as inaccurate use of the plural [one more Showers | boats areas] (because the candidate has copied the plural form from the question) and incorrect verb form [is moved down | has been moved down]."
        }]
      },
      {
        questions: [{
            id: 'b19t2wq2',
            type: QuestionType.WRITING_TASK,
            prompt: 'You should spend about 40 minutes on this task. Write about the following topic:',
            task: 'The working week should be shorter and workers should have a longer weekend.\n\nDo you agree or disagree?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.',
            sampleAnswerBand: 6.0,
            sampleAnswer: "I personally disagree with the issue whether the working days should be one day less. By no means should we make the weekend three days long. There are two aspects that support my point of view.\n\nFirst of all, now all over the world are facing an unprecedented economic recession caused by COVID-19. Many factories are forced to close and the shops shut down. The economic loss is substantial. Nevertheless, with the advent of vaccine, I perceive that now people can go back to their work. This would certainly be conducive to our economy. If we reduce one day from work, even just from a week, it would cause repercussions on our society in terms of the development of economy.\n\nSecondly, I am used to do my leisure activities in Saturday and Sunday. If there is one day more, I would need to do on that day, and that means I have to rearrange my weekend plans. I think it would be tiring. Most importantly, I come to admit that, to some degree, I am a workaholic. I cannot even image if I am separated from my favourite place – my office. It is the place where I retreat to when I feel anxious and want to get rid of everything. Working, indeed, gives me a sense of achievement and contentment. I, therefore, would oppose to the idea of cutting one working day.\n\nThough some people may argue that they need one day more in the week to reduce their stress from work, it could be harmful to our economic growth in this harsh time. Also, I believe that many people are used to the current working system, which provides two days for break. The sudden change will make people confused. Unless the government enacts a comprehensive policy for this new system, I think the idea does not work, and it would surely brings chaos in our society.",
            examinerComment: "In this good response, the candidate presents their opinion at the start, then gives two main points about why the current working week should not change: economic development and the disruption to our existing pattern of a two-day weekend. In the final paragraph, they consider the other side of the argument and people who might like an additional day off. (However, a counter argument is not necessary for this type of question.)\n\nOverall, ideas are presented in a clear order, and there is some good use of linking words and expressions [First of all | Nevertheless | Most importantly | Unless].\n\nThe response contains some good vocabulary with effective collocation [unprecedented economic recession | conducive to | sense of achievement], and there is a range of structures including conditionals [if], modals [would | may | could] and multi-clause sentences. There are some errors in prepositions and other structures [/ am used to do / I am used to doing], but the impact is not disruptive."
        }]
      }
    ],
  },
  {
    id: 'b19-t2-s5',
    title: 'Test 2: Speaking P1-3',
    section: Section.SPEAKING,
    parts: [
      {
        questions: [{
            id: 'b19t2sq1',
            type: QuestionType.SPEAKING_TASK,
            prompt: 'Part 1: Example',
            question: 'Travelling by plane\n\n- Have you travelled a lot by plane? [To where?/Why not?]\n- Why do you think some people enjoy travelling by plane?\n- Would you like to live near an airport? [Why/Why not?]\n- In the future, do you think you will travel by plane more often? [Why/Why not?]',
            sampleAnswer: `Sure, here are some sample answers for Part 1 on "Travelling by plane":

**1. Have you travelled a lot by plane?**

"Yes, I have. I've been fortunate enough to visit several countries in Europe, like Spain and Italy, for holidays. I also flew to Southeast Asia a couple of years ago, which was an amazing experience. I really enjoy seeing different parts of the world, and flying is the only practical way to do that for long distances."

**2. Why do you think some people enjoy travelling by plane?**

"I think for many, it's the sense of adventure and the excitement of going somewhere new. It's the fastest way to travel long distances, so it opens up the whole world. Also, for some, the experience itself can be quite relaxing – a chance to switch off, watch a movie, and be disconnected for a few hours."

**3. Would you like to live near an airport?**

"Oh, definitely not. While it might be convenient for travelling, I think the constant noise from planes taking off and landing would be unbearable. I much prefer living in a quiet, residential area. The peace and quiet are far more important to me than being a few minutes closer to an airport."

**4. In the future, do you think you will travel by plane more often?**

"I certainly hope so. There are still so many places on my bucket list that I'd love to visit, like Japan and South America. As my career progresses and I hopefully have more disposable income and holiday time, I plan to make international travel a more regular part of my life."`
        }]
      },
      {
        questions: [{
            id: 'b19t2sq2',
            type: QuestionType.SPEAKING_TASK,
            prompt: 'Part 2: Cue Card',
            question: 'Describe a person from your country who has won a prize, award or medal.\nYou should say:\n- who this person is\n- which prize, award or medal they received\n- what they did to win this\n- and explain whether you think it was right that this person received this prize, award or medal.',
            sampleAnswer: `Of course. Here is a sample answer for the Part 2 cue card.

***

"A person from my country who immediately comes to mind is **Sir David Attenborough**. He is a world-renowned broadcaster and natural historian.

The award I'm thinking of isn't a single medal, but rather a lifetime of them, culminating in him receiving the **Champions of the Earth Lifetime Achievement Award** from the United Nations in 2022. This is the UN's highest environmental honour.

He received this award for his decades of tireless work in environmental advocacy. For over 70 years, through his breathtaking documentary series like *Planet Earth* and *Blue Planet*, he has brought the wonders of the natural world into people's homes. More than just showing beautiful pictures, he has been a powerful voice for conservation, highlighting the devastating impact of human activity on our planet, from climate change to plastic pollution. His dedication to research, his powerful storytelling, and his unwavering commitment to protecting biodiversity are what earned him this recognition.

I absolutely think it was right for him to receive this award; in fact, I can't think of anyone more deserving. He has done more to educate and inspire millions of people globally about environmental issues than any other single person. He has a unique ability to connect with audiences of all ages and make them care about the planet. His work has shifted public opinion and influenced policy, making him a true champion for the Earth."`
        }]
      },
       {
        questions: [{
            id: 'b19t2sq3',
            type: QuestionType.SPEAKING_TASK,
            prompt: 'Part 3: Discussion topics',
            question: 'Rewards for children at school\n- What types of school prizes do children in your country receive?\n- What do you think are the advantages of rewarding schoolchildren for good work?\n- Do you agree that it’s more important for children to receive rewards from their parents than from teachers?\n\nRewards for sportspeople\n- Do you think that some sportspeople (e.g., top footballers) are paid too much money?\n- Should everyone on a team get the same prize money when they win?\n- Do you agree with the view that, in sport, taking part is more important than winning?',
            sampleAnswer: `Here are sample answers for the Part 3 discussion.

**Rewards for children at school**

**1. What types of school prizes do children in your country receive?**
"In my country, it ranges from simple things like stickers or certificates for good work in primary school, to more formal awards in secondary school. These can be book tokens, trophies for academic subjects or sports, and sometimes even small scholarships or bursaries for older students who excel."

**2. What do you think are the advantages of rewarding schoolchildren for good work?**
"The main advantage is motivation. Rewards can act as a powerful incentive for students to work harder and strive for excellence. It also provides positive reinforcement, which builds confidence and a sense of achievement. Recognizing effort and success helps to foster a positive learning environment."

**3. Do you agree that it’s more important for children to receive rewards from their parents than from teachers?**
"That's an interesting question. I think both are important, but for different reasons. Teacher rewards validate academic or school-based achievements publicly, which is great for confidence. However, parental rewards are more personal and reinforce family values. If I had to choose, I’d say parental recognition is slightly more crucial because it builds a child's intrinsic sense of self-worth, which is fundamental to their overall development."

---

**Rewards for sportspeople**

**4. Do you think that some sportspeople (e.g., top footballers) are paid too much money?**
"Yes, I do. While I admire their skill and dedication, the salaries of top footballers, for example, seem disproportionate when compared to essential professions like doctors or teachers. The entertainment industry they are part of generates huge revenues, which is how the salaries are justified, but on a societal level, it feels unbalanced."

**5. Should everyone on a team get the same prize money when they win?**
"Ideally, yes. I believe sport is a team effort, and every player contributes to the victory, even those who aren't the star players. Equal prize money would foster team spirit and acknowledge that success is a collective achievement. However, I understand that contracts and bonuses are often tied to individual performance metrics, which complicates things."

**6. Do you agree with the view that, in sport, taking part is more important than winning?**
"I think at an amateur or youth level, absolutely. The focus should be on developing skills, sportsmanship, health, and enjoyment. However, in professional sports, winning is undeniably the primary objective. It’s what drives the competition, the funding, and the careers of the athletes. So, the importance of winning versus participation really depends on the context."`
        }]
      }
    ],
  },
];
