
import { Lesson, QuestionType, Section } from '../types';

const ielts17ReadingPassage1Test4 = `How Madagascar’s bats are helping to save the rainforest

There are few places in the world where relations between agriculture and conservation are more strained. Madagascar’s forests are being converted to agricultural land at a rate of one percent every year. Much of this destruction is fuelled by the cultivation of the country’s main staple crop: rice. And a key reason for this destruction is that insect pests are destroying vast quantities of what is grown by local subsistence farmers, leading them to clear forest to create new paddy fields. The result is devastating habitat and biodiversity loss on the island, but not all species are suffering. In fact, some of the island’s insectivorous bats are currently thriving and this has important implications for farmers and conservationists alike.

Enter University of Cambridge zoologist Ricardo Rocha. He’s passionate about conservation, and bats. More specifically, he’s interested in how bats are responding to human activity and deforestation in particular. Rocha’s new study shows that several species of bats are giving Madagascar’s rice farmers a vital pest control service by feasting on plagues of insects. And this, he believes, can ease the financial pressure on farmers to turn forest into fields.

Bats comprise roughly one-fifth of all mammal species in Madagascar and thirty-six recorded bat species are native to the island, making it one of the most important regions for conservation of this animal group anywhere in the world.

Co-leading an international team of scientists, Rocha found that several species of indigenous bats are taking advantage of habitat modification to hunt insects swarming above the country’s rice fields. They include the Malagasy mouse-eared bat, Major’s long-fingered bat, the Malagasy white-bellied free-tailed bat and Peters’ wrinkle-lipped bat.

‘These winner species are providing a valuable free service to Madagascar as biological pest suppressors,’ says Rocha. ‘We found that six species of bat are preying on rice pests, including the paddy swarming caterpillar and grass webworm. The damage which these insects cause puts the island’s farmers under huge financial pressure and that encourages deforestation.’

The study, now published in the journal Agriculture, Ecosystems and Environment, set out to investigate the feeding activity of insectivorous bats in the farmland bordering the Ranomafana National Park in the southeast of the country.

Rocha and his team used state-of-the-art ultrasonic recorders to record over a thousand bat ‘feeding buzzes’ (echolocation sequences used by bats to target their prey) at 54 sites, in order to identify the favourite feeding spots of the bats. They next used DNA barcoding techniques to analyse droppings collected from bats at the different sites.

The recordings revealed that bat activity over rice fields was much higher than it was in continuous forest – seven times higher over rice fields which were on flat ground, and sixteen times higher over fields on the sides of hills – leaving no doubt that the animals are preferentially foraging in these man-made ecosystems. The researchers suggest that the bats favour these fields because lack of water and nutrient run-off make these crops more susceptible to insect pest infestations. DNA analysis showed that all six species of bat had fed on economically important insect pests. While the findings indicated that rice farming benefits most from the bats, the scientists also found indications that the bats were consuming pests of other crops, including the black twig borer (which infests coffee plants), the sugarcane cicada, the macadamia nut-borer, and the sober tabby (a pest of citrus fruits).

‘The effectiveness of bats as pest controllers has already been proven in the USA and Catalonia,’ said co-author James Kemp, from the University of Lisbon. ‘But our study is the first to show this happening in Madagascar, where the stakes for both farmers and conservationists are so high.’

Local people may have a further reason to be grateful to their bats. While the animal is often associated with spreading disease, Rocha and his team found evidence that Malagasy bats feed not just on crop pests but also on mosquitoes – carriers of malaria, Rift Valley fever virus and elephantiasis – as well as blackflies, which spread river blindness.

Rocha points out that the relationship is complicated. When food is scarce, bats become a crucial source of protein for local people. Even the children will hunt them. And as well as roosting in trees, the bats sometimes roost in buildings, but are not welcomed there because they make them unclean. At the same time, however, they are associated with sacred caves and the ancestors, so they can be viewed as beings between worlds, which makes them very significant in the culture of the people. And one potential problem is that while these bats are benefiting from farming, at the same time deforestation is reducing the places where they can roost, which could have long-term effects on their numbers. Rocha says, ‘With the right help, we hope that farmers can promote this mutually beneficial relationship by installing bat houses.’

Rocha and his colleagues believe that maximising bat populations can help to boost crop yields and promote sustainable livelihoods. The team is now calling for further research to quantify this contribution. ‘I’m very optimistic,’ says Rocha. ‘If we give nature a hand, we can speed up the process of regeneration.’`;

const ielts17ReadingPassage2Test4 = `Does education fuel economic growth?

A. Over the last decade, a huge database about the lives of southwest German villagers between 1600 and 1900 has been compiled by a team led by Professor Sheilagh Ogilvie at Cambridge University’s Faculty of Economics. It includes court records, guild ledgers, parish registers, village censuses, tax lists and – the most recent addition – 9,000 handwritten inventories listing over a million personal possessions belonging to ordinary women and men across three centuries. Ogilvie, who discovered the inventories in the archives of two German communities 30 years ago, believes they may hold the answer to a conundrum that has long puzzled economists: the lack of evidence for a causal link between education and a country’s economic growth.

B. As Ogilvie explains, ‘Education helps us to work more productively, invent better technology, and earn more ... surely it must be critical for economic growth? But, if you look back through history, there’s no evidence that having a high literacy rate made a country industrialise earlier.’ Between 1600 and 1900, England had only mediocre literacy rates by European standards, yet its economy grew fast and it was the first country to industrialise. During this period, Germany and Scandinavia had excellent literacy rates, but their economies grew slowly and they industrialised late. ‘Modern cross-country analyses have also struggled to find evidence that education causes economic growth, even though there is plenty of evidence that growth increases education,’ she adds.

C. In the handwritten inventories that Ogilvie is analysing are the belongings of women and men at marriage, remarriage and death. From badger skins to Bibles, sewing machines to scarlet bodices – the villagers’ entire worldly goods are included. Inventories of agricultural equipment and craft tools reveal economic activities; ownership of books and educationrelated objects like pens and slates suggests how people learned. In addition, the tax lists included in the database record the value of farms, workshops, assets and debts; signatures and people’s estimates of their age indicate literacy and numeracy levels; and court records reveal obstacles (such as the activities of the guilds*) that stifled industry. Previous studies usually had just one way of linking education with economic growth – the presence of schools and printing presses, perhaps, or school enrolment, or the ability to sign names. According to Ogilvie, the database provides multiple indicators for the same individuals, making it possible to analyse links between literacy, numeracy, wealth, and industriousness, for individual women and men over the long term.

D. Ogilvie and her team have been building the vast database of material possessions on top of their full demographic reconstruction of the people who lived in these two German communities. ‘We can follow the same people – and their descendants – across 300 years of educational and economic change,’ she says. Individual lives have unfolded before their eyes. Stories like that of the 24-year-olds Ana Regina and Magdalena Riethmüllerin, who were chastised in 1707 for reading books in church instead of listening to the sermon. ‘This tells us they were continuing to develop their reading skills at least a decade after leaving school,’ explains Ogilvie. The database also reveals the case of Juliana Schweickherdt, a 50-year-old spinster living in the small Black Forest community of Wildberg, who was reprimanded in 1752 by the local weavers’ guild for ‘weaving cloth and combing wool, counter to the guild ordinance’. When Juliana continued taking jobs reserved for male guild members, she was summoned before the guild court and told to pay a fine equivalent to one third of a servant’s annual wage. It was a small act of defiance by today’s standards, but it reflects a time when laws in Germany and elsewhere regulated people’s access to labour markets. The dominance of guilds not only prevented people from using their skills, but also held back even the simplest industrial innovation.

E. The data-gathering phase of the project has been completed and now, according to Ogilvie, it is time ‘to ask the big questions’. One way to look at whether education causes economic growth is to ‘hold wealth constant’. This involves following the lives of different people with the same level of wealth over a period of time. If wealth is constant, it is possible to discover whether education was, for example, linked to the cultivation of new crops, or to the adoption of industrial innovations like sewing machines. The team will also ask what aspect of education helped people engage more with productive and innovative activities. Was it, for instance, literacy, numeracy, book ownership, years of schooling? Was there a threshold level – a tipping point – that needed to be reached to affect economic performance?

F. Ogilvie hopes to start finding answers to these questions over the next few years. One thing is already clear, she says: the relationship between education and economic growth is far from straightforward. ‘German-speaking central Europe is an excellent laboratory for testing theories of economic growth,’ she explains. Between 1600 and 1900, literacy rates and book ownership were high and yet the region remained poor. It was also the case that local guilds and merchant associations were extremely powerful and legislated against anything that undermined their monopolies. In villages throughout the region, guilds blocked labour migration and resisted changes that might reduce their influence. ‘Early findings suggest that the potential benefits of education for the economy can be held back by other barriers, and this has implications for today,’ says Ogilvie. ‘Huge amounts are spent improving education in developing countries, but this spending can fail to deliver economic growth if restrictions block people – especially women and the poor – from using their education in economically productive ways. If economic institutions are poorly set up, for instance, education can’t lead to growth.’`;

const ielts17ReadingPassage3Test4 = `Timur Gareyev – blindfold chess champion

A. Next month, a chess player named Timur Gareyev will take on nearly 50 opponents at once. But that is not the hard part. While his challengers will play the games as normal, Gareyev himself will be blindfolded. Even by world record standards, it sets a high bar for human performance. The 28-year-old already stands out in the rarefied world of blindfold chess. He has a fondness for bright clothes and unusual hairstyles, and he gets his kicks from the adventure sport of BASE jumping. He has already proved himself a strong chess player, too. In a 10-hour chess marathon in 2013, Gareyev played 33 games in his head simultaneously. He won 29 and lost none. The skill has become his brand: he calls himself the Blindfold King.

B. But Gareyev’s prowess has drawn interest from beyond the chess-playing community. In the hope of understanding how he and others like him can perform such mental feats, researchers at the University of California in Los Angeles (UCLA) called him in for tests. They now have their first results. ‘The ability to play a game of chess with your eyes closed is not a far reach for most accomplished players,’ said Jesse Rissman, who runs a memory lab at UCLA. ‘But the thing that’s so remarkable about Timur and a few other individuals is the number of games they can keep active at once. To me it is simply astonishing.’

C. Gareyev learned to play chess in his native Uzbekistan when he was six years old. Tutored by his grandfather, he entered his first tournament aged eight and soon became obsessed with competitions. At 16, he was crowned Asia’s youngest ever chess grandmaster. He moved to the US soon after, and as a student helped his university win its first national chess championship. In 2013, Gareyev was ranked the third best chess player in the US.

D. To the uninitiated, blindfold chess seems to call for superhuman skill. But displays of the feat go back centuries. The first recorded game in Europe was played in 13th-century Florence. In 1947, the Argentinian grandmaster Miguel Najdorf played 45 simultaneous games in his mind, winning 39 in the 24-hour session.

E. Accomplished players can develop the skill of playing blind even without realising it. The nature of the game is to run through possible moves in the mind to see how they play out. From this, regular players develop a memory for the patterns the pieces make, the defences and attacks. ‘You recreate it in your mind,’ said Gareyev. ‘A lot of players are capable of doing what I’m doing.’ The real mental challenge comes from playing multiple games at once in the head. Not only must the positions of each piece on every board be memorised, they must be recalled faithfully when needed, updated with each player’s moves, and then reliably stored again, so the brain can move on to the next board. First moves can be tough to remember because they are fairly uninteresting. But the ends of games are taxing too, as exhaustion sets in. When Gareyev is tired, his recall can get patchy. He sometimes makes moves based on only a fragmented memory of the pieces’ positions.

F. The scientists first had Gareyev perform some standard memory tests. These assessed his ability to hold numbers, pictures and words in mind. One classic test measures how many numbers a person can repeat, both forwards and backwards, soon after hearing them. Most people manage about seven. ‘He was not exceptional on any of these standard tests,’ said Rissman. ‘We didn’t find anything other than playing chess that he seems to be supremely gifted at.’ But next came the brain scans. With Gareyev lying down in the machine, Rissman looked at how well connected the various regions of the chess player’s brain were. Though the results are tentative and as yet unpublished, the scans found much greater than average communication between parts of Gareyev’s brain that make up what is called the frontoparietal control network. Of 63 people scanned alongside the chess player, only one or two scored more highly on the measure. ‘You use this network in almost any complex task. It helps you to allocate attention, keep rules in mind, and work out whether you should be responding or not,’ said Rissman.

G. It was not the only hint of something special in Gareyev’s brain. The scans also suggest that Gareyev’s visual network is more highly connected to other brain parts than usual. Initial results suggest that the areas of his brain that process visual images – such as chess boards – may have stronger links to other brain regions, and so be more powerful than normal. While the analyses are not finalised yet, they may hold the first clues to Gareyev’s extraordinary ability.

H. For the world record attempt, Gareyev hopes to play 47 blindfold games at once in about 16 hours. He will need to win 80% to claim the title. ‘I don’t worry too much about the winning percentage, that’s never been an issue for me,’ he said. ‘The most important part of blindfold chess for me is that I have found the one thing that I can fully dedicate myself to. I miss having an obsession.’`;

export const ielts17Test4Lessons: Lesson[] = [
    {
        id: 'b17-t4-l0',
        title: 'Test 4: Listening P1-2',
        section: Section.LISTENING,
        parts: [
            { // Part 1
                questions: [
                    { id: 'b17t4lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD for each answer.', audioUrl: 'ielts-17/t4-p1.mp3', questionText: 'Cleaning the 1 ___ throughout the apartment', correctAnswers: ['floor'], transcript: "No, I don't have any, but the floor would need cleaning.", transcriptHighlight: "floor" },
                    { id: 'b17t4lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD for each answer.', audioUrl: 'ielts-17/t4-p1.mp3', questionText: 'Cleaning the 2 ___', correctAnswers: ['fridge'], transcript: "but can you do the fridge?", transcriptHighlight: "fridge" },
                    { id: 'b17t4lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD for each answer.', audioUrl: 'ielts-17/t4-p1.mp3', questionText: 'Ironing clothes - 3 ___ only', correctAnswers: ['shirts'], transcript: "It wouldn’t be much, just my shirts for work that week.", transcriptHighlight: "shirts" },
                    { id: 'b17t4lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD for each answer.', audioUrl: 'ielts-17/t4-p1.mp3', questionText: 'Cleaning all the 4 ___ from the inside', correctAnswers: ['windows'], transcript: "if the inside of your windows need cleaning, we could do that.", transcriptHighlight: "windows" },
                    { id: 'b17t4lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD for each answer.', audioUrl: 'ielts-17/t4-p1.mp3', questionText: 'Washing down the 5 ___', correctAnswers: ['balcony'], transcript: "But would you be able to do something about the balcony?", transcriptHighlight: "balcony" },
                    { id: 'b17t4lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD for each answer.', audioUrl: 'ielts-17/t4-p1.mp3', questionText: 'They can organise a plumber or an 6 ___ if necessary.', correctAnswers: ['electrician'], transcript: "And the same thing if you need an electrician.", transcriptHighlight: "electrician" },
                    { id: 'b17t4lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD for each answer.', audioUrl: 'ielts-17/t4-p1.mp3', questionText: 'A special cleaning service is available for customers who are allergic to 7 ___', correctAnswers: ['dust'], transcript: "capturing up to 99% of all the dust in the air. So if you’re troubled by allergies", transcriptHighlight: "dust" },
                    { id: 'b17t4lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD for each answer.', audioUrl: 'ielts-17/t4-p1.mp3', questionText: 'Before being hired, all cleaners have a background check carried out by the 8 ___', correctAnswers: ['police'], transcript: "they have to undergo a security check with the police", transcriptHighlight: "police" },
                    { id: 'b17t4lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD for each answer.', audioUrl: 'ielts-17/t4-p1.mp3', questionText: 'All cleaners are given 9 ___ for two weeks.', correctAnswers: ['training'], transcript: "we give them training for it. That lasts for two weeks", transcriptHighlight: "training" },
                    { id: 'b17t4lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD for each answer.', audioUrl: 'ielts-17/t4-p1.mp3', questionText: 'Customers send a 10 ___ after each visit.', correctAnswers: ['review'], transcript: "we ask all our clients to complete a review of their performance after every visit", transcriptHighlight: "review" },
                ],
            },
            { // Part 2
                questions: [
                    { id: 'b17t4lq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t4-p2.mp3', questionText: 'Many hotel managers are unaware that their staff often leave because of', options: ['A a lack of training.', 'B long hours.', 'C low pay.'], correctAnswers: ['A a lack of training.'], transcript: "but what they don’t realise is that it’s the lack of training in many hotel jobs which is a huge factor.", transcriptHighlight: "lack of training" },
                    { id: 'b17t4lq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t4-p2.mp3', questionText: 'What is the impact of high staff turnover on managers?', options: ['A an increased workload', 'B low morale', 'C an inability to meet targets'], correctAnswers: ['A an increased workload'], transcript: "managers may have to cover some duties while waiting for new staff to arrive.", transcriptHighlight: "cover some duties" },
                    { id: 'b17t4lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t4-p2.mp3', questionText: 'What mistake should managers always avoid?', options: ['A failing to treat staff equally', 'B reorganising shifts without warning', 'C neglecting to have enough staff during busy periods'], correctAnswers: ['A failing to treat staff equally'], transcript: "When organising shifts, for example, make sure you never give certain staff preferential treatment.", transcriptHighlight: "preferential treatment" },
                    { id: 'b17t4lq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t4-p2.mp3', questionText: 'What unexpected benefit did Dunwich Hotel notice after improving staff retention rates?', options: ['A a fall in customer complaints', 'B an increase in loyalty club membership', 'C a rise in spending per customer'], correctAnswers: ['C a rise in spending per customer'], transcript: "they also noticed a significant increase in the amount each customer spent during their stay.", transcriptHighlight: "increase in the amount each customer spent" },
                    { id: 'b17t4lq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which way of reducing staff turnover was used in each of the following hotels?', audioUrl: 'ielts-17/t4-p2.mp3', questionText: '15 The Sun Club', options: ['A improving relationships and teamwork', 'B offering incentives and financial benefits', 'C providing career opportunities'], correctAnswers: ['A improving relationships and teamwork'], transcript: "Junior staff at all levels are regularly invited to meetings where their ideas are welcomed.", transcriptHighlight: "invited to meetings" },
                    { id: 'b17t4lq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which way of reducing staff turnover was used in each of the following hotels?', audioUrl: 'ielts-17/t4-p2.mp3', questionText: '16 The Portland', options: ['A improving relationships and teamwork', 'B offering incentives and financial benefits', 'C providing career opportunities'], correctAnswers: ['C providing career opportunities'], transcript: "Their first step was to introduce a scheme for recognising talent amongst their employees. The hope is that organising training for individuals with management potential will encourage them to stay", transcriptHighlight: "training for individuals with management potential" },
                    { id: 'b17t4lq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which way of reducing staff turnover was used in each of the following hotels?', audioUrl: 'ielts-17/t4-p2.mp3', questionText: '17 Bluewater Hotels', options: ['A improving relationships and teamwork', 'B offering incentives and financial benefits', 'C providing career opportunities'], correctAnswers: ['B offering incentives and financial benefits'], transcript: "As a reward, they’re sent on an all-expenses-paid trip abroad every year.", transcriptHighlight: "all-expenses-paid trip" },
                    { id: 'b17t4lq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which way of reducing staff turnover was used in each of the following hotels?', audioUrl: 'ielts-17/t4-p2.mp3', questionText: '18 Pentlow Hotels', options: ['A improving relationships and teamwork', 'B offering incentives and financial benefits', 'C providing career opportunities'], correctAnswers: ['C providing career opportunities'], transcript: "they introduced a management programme. These staff were given additional responsibilities and the chance to work in various roles", transcriptHighlight: "management programme" },
                    { id: 'b17t4lq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which way of reducing staff turnover was used in each of the following hotels?', audioUrl: 'ielts-17/t4-p2.mp3', questionText: '19 Green Planet', options: ['A improving relationships and teamwork', 'B offering incentives and financial benefits', 'C providing career opportunities'], correctAnswers: ['B offering incentives and financial benefits'], transcript: "To make life easier for staff, many of whom had childcare responsibilities, the hotel began issuing vouchers to help cover the cost of childcare.", transcriptHighlight: "vouchers to help cover the cost of childcare" },
                    { id: 'b17t4lq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which way of reducing staff turnover was used in each of the following hotels?', audioUrl: 'ielts-17/t4-p2.mp3', questionText: '20 The Amesbury', options: ['A improving relationships and teamwork', 'B offering incentives and financial benefits', 'C providing career opportunities'], correctAnswers: ['A improving relationships and teamwork'], transcript: "she has made a huge effort to achieve this by creating a co-operative and supportive environment. For her, the staff are part of a large family", transcriptHighlight: "co-operative and supportive environment" },
                ]
            }
        ]
    },
    {
        id: 'b17-t4-l1',
        title: 'Test 4: Listening P3-4',
        section: Section.LISTENING,
        parts: [
            { // Part 3
                questions: [
                    { id: 'b17t4lq21', maxSelections: 2, type: QuestionType.MULTIPLE_CHOICE, prompt: "Choose TWO letters, A-E.", audioUrl: 'ielts-17/t4-p3.mp3', questionText: "Which TWO points do Thomas and Jeanne make about Thomas's sporting activities at school?", options: ['A He should have felt more positive about them.', 'B The training was too challenging for him.', 'C He could have worked harder at them.', 'D His parents were disappointed in him.', 'E His fellow students admired him.'], correctAnswers: ['C He could have worked harder at them.', 'E His fellow students admired him.'], transcript: "Yeah – that was my goal, and all my classmates assumed I would achieve it; they thought I was brilliant... I think I should have practised more.", transcriptHighlight: "classmates assumed I would achieve it; they thought I was brilliant... I should have practised more" },
                    { id: 'b17t4lq23', maxSelections: 2, type: QuestionType.MULTIPLE_CHOICE, prompt: "Choose TWO letters, A-E.", audioUrl: 'ielts-17/t4-p3.mp3', questionText: 'Which TWO feelings did Thomas experience when he was in Kenya?', options: ['A disbelief', 'B relief', 'C stress', 'D gratitude', 'E homesickness'], correctAnswers: ['A disbelief', 'D gratitude'], transcript: "I just kept thinking how fortunate I was. What a great chance this was! ... But once we started competing, I very quickly realised I wasn’t good enough. I thought ‘this can’t be happening’!", transcriptHighlight: "how fortunate I was... ‘this can’t be happening’" },
                    { id: 'b17t4lq25', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about the development of each of the following items of sporting equipment?", audioUrl: 'ielts-17/t4-p3.mp3', questionText: '25 the table tennis bat', options: ['A It could cause excessive sweating.', 'B The material was being mass produced for another purpose.', 'C People often needed to make their own.', 'D It often had to be replaced.', 'E The material was expensive.', 'F It was unpopular among spectators.', 'G It caused injuries.', 'H No one using it liked it at first.'], correctAnswers: ['B The material was being mass produced for another purpose.'], transcript: "in about the 1920s, a factory was making rolls of the rubber in bulk for something like horse harnesses. ... and someone realised that it’d make a perfect covering for the wooden bats.", transcriptHighlight: "rubber in bulk for something like horse harnesses" },
                    { id: 'b17t4lq26', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about the development of each of the following items of sporting equipment?", audioUrl: 'ielts-17/t4-p3.mp3', questionText: '26 the cricket helmet', options: ['A It could cause excessive sweating.', 'B The material was being mass produced for another purpose.', 'C People often needed to make their own.', 'D It often had to be replaced.', 'E The material was expensive.', 'F It was unpopular among spectators.', 'G It caused injuries.', 'H No one using it liked it at first.'], correctAnswers: ['F It was unpopular among spectators.'], transcript: "when the first cricket helmet came in, in 1978, the Australian batsman who first wore it was booed and jeered by people watching because it was so ugly!", transcriptHighlight: "booed and jeered by people watching" },
                    { id: 'b17t4lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about the development of each of the following items of sporting equipment?", audioUrl: 'ielts-17/t4-p3.mp3', questionText: '27 the cycle helmet', options: ['A It could cause excessive sweating.', 'B The material was being mass produced for another purpose.', 'C People often needed to make their own.', 'D It often had to be replaced.', 'E The material was expensive.', 'F It was unpopular among spectators.', 'G It caused injuries.', 'H No one using it liked it at first.'], correctAnswers: ['A It could cause excessive sweating.'], transcript: "It says serious cyclists ended up with wet hair from all the hard exercise.", transcriptHighlight: "wet hair" },
                    { id: 'b17t4lq28', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about the development of each of the following items of sporting equipment?", audioUrl: 'ielts-17/t4-p3.mp3', questionText: '28 the golf club', options: ['A It could cause excessive sweating.', 'B The material was being mass produced for another purpose.', 'C People often needed to make their own.', 'D It often had to be replaced.', 'E The material was expensive.', 'F It was unpopular among spectators.', 'G It caused injuries.', 'H No one using it liked it at first.'], correctAnswers: ['D It often had to be replaced.'], transcript: "because a club was made entirely of wood, it would easily break and players had to get another.", transcriptHighlight: "easily break" },
                    { id: 'b17t4lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about the development of each of the following items of sporting equipment?", audioUrl: 'ielts-17/t4-p3.mp3', questionText: '29 the hockey stick', options: ['A It could cause excessive sweating.', 'B The material was being mass produced for another purpose.', 'C People often needed to make their own.', 'D It often had to be replaced.', 'E The material was expensive.', 'F It was unpopular among spectators.', 'G It caused injuries.', 'H No one using it liked it at first.'], correctAnswers: ['C People often needed to make their own.'], transcript: "when the game started you had to produce a stick yourself.", transcriptHighlight: "produce a stick yourself" },
                    { id: 'b17t4lq30', type: QuestionType.MULTIPLE_CHOICE, prompt: "What comment do the students make about the development of each of the following items of sporting equipment?", audioUrl: 'ielts-17/t4-p3.mp3', questionText: '30 the football', options: ['A It could cause excessive sweating.', 'B The material was being mass produced for another purpose.', 'C People often needed to make their own.', 'D It often had to be replaced.', 'E The material was expensive.', 'F It was unpopular among spectators.', 'G It caused injuries.', 'H No one using it liked it at first.'], correctAnswers: ['G It caused injuries.'], transcript: "That’s right. You can imagine the damage to players’ necks when the ball was headed.", transcriptHighlight: "damage to players’ necks" },
                ]
            },
            { // Part 4
                questions: [
                    { id: 'b17t4lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t4-p4.mp3', questionText: 'colour described as 31 ___', correctAnswers: ['golden'], transcript: "Maple syrup is a thick, golden, sweet-tasting liquid", transcriptHighlight: "golden" },
                    { id: 'b17t4lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t4-p4.mp3', questionText: 'very 32 ___ compared to refined sugar', correctAnswers: ['healthy'], transcript: "it provides a healthy alternative to refined sugar.", transcriptHighlight: "healthy" },
                    { id: 'b17t4lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t4-p4.mp3', questionText: 'best growing conditions and 33 ___ are in Canada and North America', correctAnswers: ['climate'], transcript: "In these areas, the climate suits the trees perfectly.", transcriptHighlight: "climate" },
                    { id: 'b17t4lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t4-p4.mp3', questionText: 'used hot 34 ___ to heat the sap', correctAnswers: ['rock', 'rocks'], transcript: "they boiled the liquid by placing pieces of rock that had become scorching hot", transcriptHighlight: "rock" },
                    { id: 'b17t4lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t4-p4.mp3', questionText: 'Tree trunks may not have the correct 35 ___ until they have been growing for 40 years.', correctAnswers: ['diameter'], transcript: "they cannot be used to make syrup until the trunks reach a diameter of around 25 centimetres.", transcriptHighlight: "diameter" },
                    { id: 'b17t4lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t4-p4.mp3', questionText: 'A tap is drilled into the trunk and a 36 ___ carries the sap into a bucket.', correctAnswers: ['tube'], transcript: "drilling a small hole into the trunk and inserting a tube into it that ends in a bucket.", transcriptHighlight: "tube" },
                    { id: 'b17t4lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t4-p4.mp3', questionText: 'Large pans of sap called evaporators are heated by means of a 37 ___ .', correctAnswers: ['fire'], transcript: "a fire is built and the pans are then heated until the sap boils.", transcriptHighlight: "fire" },
                    { id: 'b17t4lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t4-p4.mp3', questionText: 'A lot of 38 ___ is produced during the evaporation process.', correctAnswers: ['steam'], transcript: "The evaporation process creates large quantities of steam", transcriptHighlight: "steam" },
                    { id: 'b17t4lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t4-p4.mp3', questionText: "'Sugar sand' is removed because it makes the syrup look 39 ___ and affects the taste.", correctAnswers: ['cloudy'], transcript: "gives the syrup a cloudy appearance", transcriptHighlight: "cloudy" },
                    { id: 'b17t4lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t4-p4.mp3', questionText: 'A huge quantity of sap is needed to make a 40 ___ of maple syrup.', correctAnswers: ['litre', 'liter'], transcript: "It takes 40 litres of sap to produce one litre of maple syrup", transcriptHighlight: "litre" },
                ]
            }
        ]
    },
    {
        id: 'b17-t4-r2',
        title: 'Test 4: Reading P1',
        section: Section.READING,
        parts: [{
            questions: [
                { id: 'b17t4rq1', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in Reading Passage 1?', passage: ielts17ReadingPassage1Test4, questionText: 'Many Madagascan forests are being destroyed by attacks from insects.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "a key reason for this destruction is that insect pests are destroying vast quantities of what is grown by local subsistence farmers, leading them to clear forest", reason: "The passage states that insect pests destroy crops, which in turn leads farmers to clear forests. The insects do not attack the forests directly." },
                { id: 'b17t4rq2', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in Reading Passage 1?', passage: ielts17ReadingPassage1Test4, questionText: 'Loss of habitat has badly affected insectivorous bats in Madagascar.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "not all species are suffering. In fact, some of the island’s insectivorous bats are currently thriving" },
                { id: 'b17t4rq3', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in Reading Passage 1?', passage: ielts17ReadingPassage1Test4, questionText: 'Ricardo Rocha has carried out studies of bats in different parts of the world.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage mentions his new study in Madagascar but not studies in other parts of the world." },
                { id: 'b17t4rq4', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in Reading Passage 1?', passage: ielts17ReadingPassage1Test4, questionText: 'Habitat modification has resulted in indigenous bats in Madagascar becoming useful to farmers.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "several species of indigenous bats are taking advantage of habitat modification to hunt insects swarming above the country’s rice fields... providing a valuable free service to Madagascar as biological pest suppressors" },
                { id: 'b17t4rq5', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in Reading Passage 1?', passage: ielts17ReadingPassage1Test4, questionText: 'The Malagasy mouse-eared bat is more common than other indigenous bat species in Madagascar.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage lists it as one of the species taking advantage of habitat modification but doesn't compare its population to others." },
                { id: 'b17t4rq6', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in Reading Passage 1?', passage: ielts17ReadingPassage1Test4, questionText: 'Bats may feed on paddy swarming caterpillars and grass webworms.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "We found that six species of bat are preying on rice pests, including the paddy swarming caterpillar and grass webworm." },
                { id: 'b17t4rq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test4, questionText: 'DNA analysis of bat 7 ___', correctAnswers: ['droppings'], passageHighlight: "analyse droppings collected from bats" },
                { id: 'b17t4rq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test4, questionText: 'ate pests of rice, 8 ___ , sugarcane, nuts and fruit', correctAnswers: ['coffee'], passageHighlight: "consuming pests of other crops, including the black twig borer (which infests coffee plants)" },
                { id: 'b17t4rq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test4, questionText: 'prevent the spread of disease by eating 9 ___ and blackflies', correctAnswers: ['mosquitoes'], passageHighlight: "feed not just on crop pests but also on mosquitoes" },
                { id: 'b17t4rq10', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test4, questionText: 'they provide food rich in 10 ___', correctAnswers: ['protein'], passageHighlight: "bats become a crucial source of protein for local people." },
                { id: 'b17t4rq11', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test4, questionText: 'the buildings where they roost become 11 ___', correctAnswers: ['unclean'], passageHighlight: "not welcomed there because they make them unclean." },
                { id: 'b17t4rq12', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test4, questionText: 'they play an important role in local 12 ___', correctAnswers: ['culture'], passageHighlight: "makes them very significant in the culture of the people." },
                { id: 'b17t4rq13', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test4, questionText: 'farmers should provide special 13 ___ to support the bat population', correctAnswers: ['houses'], passageHighlight: "promote this mutually beneficial relationship by installing bat houses." },
            ],
        }],
    },
    {
        id: 'b17-t4-r3',
        title: 'Test 4: Reading P2-3',
        section: Section.READING,
        parts: [
            { // Reading Passage 2
                questions: [
                    { id: 'b17t4rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has six sections, A-F. Which section contains the following information?', passage: ielts17ReadingPassage2Test4, questionText: 'an explanation of the need for research to focus on individuals with a fairly consistent income', options: ['A','B','C','D','E','F'], correctAnswers: ['E'], passageHighlight: "One way to look at whether education causes economic growth is to ‘hold wealth constant’." },
                    { id: 'b17t4rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has six sections, A-F. Which section contains the following information?', passage: ielts17ReadingPassage2Test4, questionText: 'examples of the sources the database has been compiled from', options: ['A','B','C','D','E','F'], correctAnswers: ['A'], passageHighlight: "It includes court records, guild ledgers, parish registers, village censuses, tax lists and... 9,000 handwritten inventories" },
                    { id: 'b17t4rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has six sections, A-F. Which section contains the following information?', passage: ielts17ReadingPassage2Test4, questionText: "an account of one individual's refusal to obey an order", options: ['A','B','C','D','E','F'], correctAnswers: ['D'], passageHighlight: "When Juliana continued taking jobs reserved for male guild members, she was summoned before the guild court and told to pay a fine" },
                    { id: 'b17t4rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has six sections, A-F. Which section contains the following information?', passage: ielts17ReadingPassage2Test4, questionText: 'a reference to a region being particularly suited to research into the link between education and economic growth', options: ['A','B','C','D','E','F'], correctAnswers: ['F'], passageHighlight: "‘German-speaking central Europe is an excellent laboratory for testing theories of economic growth,’ she explains." },
                    { id: 'b17t4rq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has six sections, A-F. Which section contains the following information?', passage: ielts17ReadingPassage2Test4, questionText: 'examples of the items included in a list of personal possessions', options: ['A','B','C','D','E','F'], correctAnswers: ['C'], passageHighlight: "From badger skins to Bibles, sewing machines to scarlet bodices – the villagers’ entire worldly goods are included." },
                    { id: 'b17t4rq19', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD from the passage for each answer.', passage: ielts17ReadingPassage2Test4, questionText: 'The database that Ogilvie and her team has compiled sheds light on the lives of a range of individuals, as well as those of their 19 ___ , over a 300-year period.', correctAnswers: ['descendants'], passageHighlight: "‘We can follow the same people – and their descendants – across 300 years" },
                    { id: 'b17t4rq20', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD from the passage for each answer.', passage: ielts17ReadingPassage2Test4, questionText: 'For example, Ana Regina and Magdalena Riethmüllerin were reprimanded for reading while they should have been paying attention to a 20 ___ .', correctAnswers: ['sermon'], passageHighlight: "chastised in 1707 for reading books in church instead of listening to the sermon." },
                    { id: 'b17t4rq21', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD from the passage for each answer.', passage: ielts17ReadingPassage2Test4, questionText: 'There was also Juliana Schweickherdt, who came to the notice of the weavers’ guild in the year 1752 for breaking guild rules. As a punishment, she was later given a 21 ___ .', correctAnswers: ['fine'], passageHighlight: "summoned before the guild court and told to pay a fine" },
                    { id: 'b17t4rq22', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD from the passage for each answer.', passage: ielts17ReadingPassage2Test4, questionText: 'Cases like this illustrate how the guilds could prevent 22 ___ and stop skilled people from working.', correctAnswers: ['innovation'], passageHighlight: "held back even the simplest industrial innovation." },
                    { id: 'b17t4rq23', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'Which TWO of the following statements does the writer make about literacy rates in Section B?', passage: ielts17ReadingPassage2Test4, questionText: '', options: ['A Very little research has been done into the link between high literacy rates and improved earnings.', 'B Literacy rates in Germany between 1600 and 1900 were very good.', 'C There is strong evidence that high literacy rates in the modern world result in economic growth.', 'D England is a good example of how high literacy rates helped a country industrialise.', 'E Economic growth can help to improve literacy rates.'], correctAnswers: ['B Literacy rates in Germany between 1600 and 1900 were very good.', 'E Economic growth can help to improve literacy rates.'], passageHighlight: "Germany and Scandinavia had excellent literacy rates... there is plenty of evidence that growth increases education" },
                    { id: 'b17t4rq25', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'Which TWO of the following statements does the writer make in Section F about guilds in German-speaking Central Europe between 1600 and 1900?', passage: ielts17ReadingPassage2Test4, questionText: '', options: ['A They helped young people to learn a skill.', 'B They were opposed to people moving to an area for work.', 'C They kept better records than guilds in other parts of the world.', 'D They opposed practices that threatened their control over a trade.', 'E They predominantly consisted of wealthy merchants.'], correctAnswers: ['B They were opposed to people moving to an area for work.', 'D They opposed practices that threatened their control over a trade.'], passageHighlight: "legislated against anything that undermined their monopolies... guilds blocked labour migration" },
                ],
            },
            { // Reading Passage 3
                questions: [
                    { id: 'b17t4rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 3 has eight paragraphs, A-H. Which paragraph contains the following information?', passage: ielts17ReadingPassage3Test4, questionText: '27 a reference to earlier examples of blindfold chess', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['D'], passageHighlight: "The first recorded game in Europe was played in 13th-century Florence." },
                    { id: 'b17t4rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 3 has eight paragraphs, A-H. Which paragraph contains the following information?', passage: ielts17ReadingPassage3Test4, questionText: '28 an outline of what blindfold chess involves', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['E'], passageHighlight: "Not only must the positions of each piece on every board be memorised, they must be recalled faithfully when needed" },
                    { id: 'b17t4rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 3 has eight paragraphs, A-H. Which paragraph contains the following information?', passage: ielts17ReadingPassage3Test4, questionText: "29 a claim that Gareyev's skill is limited to chess", options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['F'], passageHighlight: "‘He was not exceptional on any of these standard tests,’ said Rissman. ‘We didn’t find anything other than playing chess that he seems to be supremely gifted at.’" },
                    { id: 'b17t4rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 3 has eight paragraphs, A-H. Which paragraph contains the following information?', passage: ielts17ReadingPassage3Test4, questionText: "30 why Gareyev's skill is of interest to scientists", options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['B'], passageHighlight: "In the hope of understanding how he and others like him can perform such mental feats, researchers at the University of California in Los Angeles (UCLA) called him in for tests." },
                    { id: 'b17t4rq31', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 3 has eight paragraphs, A-H. Which paragraph contains the following information?', passage: ielts17ReadingPassage3Test4, questionText: "31 an outline of Gareyev's priorities", options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['H'], passageHighlight: "‘I don’t worry too much about the winning percentage, that’s never been an issue for me,’ he said. ‘The most important part of blindfold chess for me is that I have found the one thing that I can fully dedicate myself to." },
                    { id: 'b17t4rq32', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 3 has eight paragraphs, A-H. Which paragraph contains the following information?', passage: ielts17ReadingPassage3Test4, questionText: '32 a reason why the last part of a game may be difficult', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['E'], passageHighlight: "But the ends of games are taxing too, as exhaustion sets in." },
                    { id: 'b17t4rq33', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 3?', passage: ielts17ReadingPassage3Test4, questionText: '33 In the forthcoming games, all the participants will be blindfolded.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "While his challengers will play the games as normal, Gareyev himself will be blindfolded." },
                    { id: 'b17t4rq34', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 3?', passage: ielts17ReadingPassage3Test4, questionText: '34 Gareyev has won competitions in BASE jumping.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage says he 'gets his kicks' from BASE jumping, but not that he has won competitions." },
                    { id: 'b17t4rq35', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 3?', passage: ielts17ReadingPassage3Test4, questionText: '35 UCLA is the first university to carry out research into blindfold chess players.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage says researchers at UCLA called him in for tests, but doesn't state it's the first university to do so." },
                    { id: 'b17t4rq36', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 3?', passage: ielts17ReadingPassage3Test4, questionText: '36 Good chess players are likely to be able to play blindfold chess.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "‘The ability to play a game of chess with your eyes closed is not a far reach for most accomplished players,’" },
                    { id: 'b17t4rq37', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage3Test4, questionText: "The researchers started by testing Gareyev's 37 ___ ;", correctAnswers: ['memory'], passageHighlight: "The scientists first had Gareyev perform some standard memory tests." },
                    { id: 'b17t4rq38', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage3Test4, questionText: 'for example, he was required to recall a string of 38 ___ in order and also in reverse order.', correctAnswers: ['numbers'], passageHighlight: "One classic test measures how many numbers a person can repeat" },
                    { id: 'b17t4rq39', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage3Test4, questionText: 'Although his performance was normal, scans showed an unusual amount of 39 ___ within the areas of Gareyev’s brain that are concerned with directing attention.', correctAnswers: ['communication'], passageHighlight: "the scans found much greater than average communication between parts of Gareyev’s brain" },
                    { id: 'b17t4rq40', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage3Test4, questionText: 'In addition, the scans raised the possibility of unusual strength in the parts of his brain that deal with 40 ___ input.', correctAnswers: ['visual'], passageHighlight: "Gareyev’s visual network is more highly connected to other brain parts than usual." },
                ]
            }
        ]
    },
    {
        id: 'b17-t4-w4',
        title: 'Test 4: Writing T1-2',
        section: Section.WRITING,
        parts: [
            {
                questions: [{
                    id: 'b17t4wq1',
                    type: QuestionType.WRITING_TASK,
                    prompt: 'You should spend about 20 minutes on this task.',
                    imageUrl: 'ielts-17/t4-w1-graph.png',
                    task: 'The graph below shows the number of shops that closed and the number of new shops that opened in one country between 2011 and 2018.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.',
                    sampleAnswer: "The line graph shows trends in shop closures and openings of new shops in a particular country between the years 2011 and 2018.\n\nIn 2011 approximately 6,400 shops closed. The number of closures fluctuated over the next four years until 2015, when there was a dramatic fall in closures to roughly 700 shops. The following year the number of shops closing their doors rose sharply, reaching over 5,000. The figures remained steady for the next two years, with just over 5,000 closures in 2018.\n\nThe number of new shops opening decreased dramatically between 2011 (approximately 8,500) and 2012 (just under 4,000) but rebounded by roughly 50% by 2014. In 2015, the number of openings then fell to the 2012 level, but remained stable for the next two years. The last recorded year, 2018, saw a further fall to 3,000 new openings, the lowest point in this seven year period.\n\nOverall, the number of shop closures has remained within the 5,000 to 7,000 range (with the exception of 2015). In contrast, new shop openings have shown a wider range of figures, but generally indicate a downward trend over the same period.",
                    sampleAnswerBand: 7.5,
                    examinerComment: "This is a strong response which provides a clear overview in the final paragraph. Data is presented and key features are highlighted appropriately. Closures are dealt with first, and the details are clearly presented, including the [dramatic fall] key feature. Shop openings are dealt with separately, in similar detail. Key peaks and low points are appropriately flagged.\n\nFor the highest task score, there could be more detail provided during the periods of [fluctuation] between 2011 to 2014 and 2016 to 2018.\n\nIdeas are logically organised, taking each line on the graph in turn, and paragraphing is used appropriately, apart from the single sentence first paragraph. Cohesion is well managed.\n\nThe range of vocabulary is wide, with some skilful use [rebounded by roughly | further fall | exception of]. The grammar includes a variety of complex structures, with numerous long sentences containing a number of clauses. This is a good example of a higher-level response to this Task 1 question."
                }]
            },
            {
                questions: [{
                    id: 'b17t4wq2',
                    type: QuestionType.WRITING_TASK,
                    prompt: 'You should spend about 40 minutes on this task. Write about the following topic:',
                    task: 'Nowadays, a growing number of people with health problems are trying alternative medicines and treatments instead of visiting their usual doctor.\n\nDo you think this is a positive or a negative development?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.',
                    sampleAnswer: "Since ancient times people tried to treat themselves by herbals and another natural products. In these days this type of treatment is named as alternative medicine. Nowadays, more and more people with some diseases decide to use alternative medicines instead of classic medicine. In this essay I will try to discuss pros and cons.\n\nIn my opinion, the disadvantages outweigh the advantages of using traditional medicine. The first reason is that nobody knows how this treatment will affect to a person’s health. There are a lot of cases when using different herbals caused allergic reaction and some people dead. The next reason is that people who do not have any medical education try alternative medicines. They do not know what the result will be and hope that it will be positive but not always is like that.\n\nAlthough there are a lot of disadvantages, advantages might make people not go to usual doctor. The first and the main pro is that using herbals does not cause environmental problems such as air pollution or gas waste. Many pharmaceutical plants use chemicals which have harmful affect on the environment. The other reason is that alternative medicines are usually much cheaper than usual treatment as you do not have to go to pharmacy and buy expensive drugs.\n\nTo sum it up, the alternative treatment will be forever because it has some advantages which many people think that they can outweigh the disadvantages but I do not think so. The conventional medicine which develops rocketly will drive out other types of treatment in the future.",
                    sampleAnswerBand: 6.0,
                    examinerComment: "The response addresses both sides of the question and the candidate states their position in the second paragraph. The disadvantages presented include not knowing if the treatments will work, possible allergic reactions and the dangers of untrained practitioners. The advantages include remedies being kinder to the environment and usually cheaper.\n\nIdeas are arranged coherently with a range of cohesive devices, although organisation is sometimes mechanical due to the high number of linking devices. There is evidence of referencing [chemicals which | it] with some error [that they can outweigh / outweigh].\n\nVocabulary is used adequately and there are some good examples used [allergic reaction | pharmaceutical plants | conventional medicine]; however, some errors remain [dead / die | rocketly / very quickly]. Grammatical structures include some sentences with multiple clauses [which have | as you]. However, there are errors [not always is like that / it is not always] and most sentences are short and simple."
                }]
            }
        ]
    },
    {
        id: 'b17-t4-s5',
        title: 'Test 4: Speaking P1-3',
        section: Section.SPEAKING,
        parts: [
            {
                questions: [{
                    id: 'b17t4sq1',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 1: Example',
                    question: 'Maps\n\n- Do you think it’s better to use a paper map or a map on your phone? [Why?]\n- When was the last time you needed to use a map? [Why/Why not?]\n- If you visit a new city, do you always use a map to find your way around? [Why/Why not?]\n- In general, do you find it easy to read maps? [Why/Why not?]',
                    sampleAnswer: `**1. Do you think it’s better to use a paper map or a map on your phone?**
"For convenience, definitely a map on my phone. It’s always with me, it can pinpoint my exact location, and it gives me real-time directions. However, I think paper maps are better for getting a bigger picture of an area, and they don't run out of battery, which is a big advantage if you're hiking, for example."

**2. When was the last time you needed to use a map?**
"Just last weekend, actually. I was driving to a friend's house in a part of the countryside I'd never been to before. My phone's signal was a bit patchy, so I used the navigation app on my phone to get the general route before I left and then referred to it at a couple of tricky junctions."

**3. If you visit a new city, do you always use a map to find your way around?**
"Yes, absolutely. I'd be completely lost without one. I rely on map apps like Google Maps for almost everything - finding my hotel, navigating the public transport system, and locating restaurants or attractions. It makes exploring a new place so much easier and less stressful."

**4. In general, do you find it easy to read maps?**
"I find digital maps very easy to read because they are interactive and you can zoom in and out. I'm reasonably good with traditional paper maps too, as I learned how to read them when I was younger. I can understand the symbols and grid references, but it definitely takes a bit more concentration than just following a blue dot on a screen."`
                }]
            },
            {
                questions: [{
                    id: 'b17t4sq2',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 2: Cue Card',
                    question: 'Describe an occasion when you had to do something in a hurry.\nYou should say:\n- what you had to do\n- why you had to do this in a hurry\n- how well you did this\n- and explain how you felt about having to do this in a hurry.',
                    sampleAnswer: `I remember a time last year when I had to write a 2,000-word essay in just one evening. It was for my university course, and I had completely misread the deadline.

I had to do it in a hurry because I thought it was due at the end of the week, but when I checked my emails in the afternoon, I realised with horror that it was actually due the next morning at 9 a.m. I had done the research, but I hadn't written a single word. So, I had a huge amount of work to do in a very short space of time.

Considering the circumstances, I think I did it surprisingly well. I just sat down at my desk with a strong coffee and didn't move for about six hours. I had to be incredibly focused and disciplined, typing as fast as I could and forcing myself not to get distracted. I managed to finish it just after midnight and submitted it online with hours to spare. I even got a decent grade for it, which was a huge relief.

To be honest, I felt incredibly stressed and panicked at first. My heart was racing when I realised my mistake. But once I started working, the adrenaline kicked in and I just went into a state of intense concentration. Afterwards, I felt completely exhausted, but also quite proud of myself for managing to pull it off. It definitely taught me a valuable lesson about checking my deadlines more carefully!`
                }]
            },
            {
                questions: [{
                    id: 'b17t4sq3',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 3: Discussion topics',
                    question: 'Arriving late\n- Do you think it’s OK to arrive late when meeting a friend?\n- What should happen to people who arrive late for work?\n- Can you suggest how people can make sure they don’t arrive late?\n\nManaging study time\n- Is it better to study for long periods or in shorter blocks of time?\n- What are the likely effects of students not managing their study time well?\n- How important is it for students to have enough leisure time?',
                    sampleAnswer: `**Arriving late**

**1. Do you think it’s OK to arrive late when meeting a friend?**
"In most cases, I think it's not ideal, but it's generally forgivable between friends. If it's just a few minutes, it's usually not a big deal, as long as you send a message to let them know. However, being consistently or significantly late is disrespectful of your friend's time, so it should be avoided."

**2. What should happen to people who arrive late for work?**
"For work, I think the consequences should be more formal. Occasional lateness due to unforeseen circumstances like a major traffic jam might be excused with a warning. But for persistent lateness, there should be a clear disciplinary procedure, which could include formal warnings and, in serious cases, could even lead to dismissal. It's important for the productivity and fairness of the whole team."

**3. Can you suggest how people can make sure they don’t arrive late?**
"Good planning is key. People should check their route and travel times in advance, and always allow for potential delays. Setting alarms a bit earlier can make a big difference. Also, preparing things like your clothes and bag the night before can save valuable time in the morning and reduce the chances of a last-minute rush."

**Managing study time**

**4. Is it better to study for long periods or in shorter blocks of time?**
"I personally find that studying in shorter, focused blocks is much more effective. For example, using the Pomodoro Technique, where you study for 25 minutes and then take a 5-minute break. I think after an hour or so of continuous study, concentration starts to drop significantly. Shorter blocks help to maintain focus and prevent burnout."

**5. What are the likely effects of students not managing their study time well?**
"Poor time management can lead to a lot of negative effects. The most obvious one is increased stress and anxiety as deadlines approach. It can also result in lower quality work because they have to rush. In the long run, it can lead to poor grades, burnout, and a general feeling of being overwhelmed and demotivated."

**6. How important is it for students to have enough leisure time?**
"It's incredibly important. Leisure time is essential for mental health and well-being. It gives students a chance to de-stress, pursue hobbies, socialise, and simply relax. A good balance between study and leisure prevents burnout and can actually improve academic performance because students return to their studies feeling refreshed and more focused."`
                }]
            }
        ]
    }
];