
import { Lesson, QuestionType, Section } from '../types';

const ielts19ReadingPassage1Test3 = `In early April 2019, Dr Ceri Shipton and his colleagues from Australian National University became the first archaeologists to explore Obi, one of many tropical islands in Indonesia’s Maluku Utara province. The research team’s discoveries suggest that the prehistoric people who lived on Obi were adept on both land and sea, hunting in the dense rainforest, foraging on the seashore, and possibly even voyaging between islands.

The excavations were part of a project to learn more about how people first dispersed from mainland Asia, through the Indonesian archipelago and into the prehistoric continent that once connected Australia and New Guinea. The team’s earlier research suggested that the northernmost islands in the group, known as the Wallacean islands, including Obi, would have offered the easiest migration route. It also seemed likely that these islands were crucial ‘stepping stones’ on humans’ island-hopping voyages through this region millennia ago. But to support this idea, they needed archaeological evidence for humans living in this remote area in the ancient past. So, they travelled to Obi to look for sites that might reveal evidence of early occupation.

Just inland from the village of Kelo on Obi’s northern coast, Shipton and his colleagues found two caves containing prehistoric rock shelters that were suitable for excavation. With the permission and help of the local people of Kelo, they dug a small test excavation in each shelter. There they found numerous artefacts, including fragments of axes, some dating to about 14,000 years ago. The earliest axes at Kelo were made using clam shells, axes made from clam shells from roughly the same time had also previously been found elsewhere in this region, including on the nearby island of Gebe to the northeast. As on Gebe, it is highly likely that Obi’s axes were used in the construction of canoes, thus allowing these early peoples to maintain connections between communities on neighbouring islands.

The oldest cultural layers from the Kelo site provided the team with the earliest record for human occupation on Obi, dating back around 18,000 years. At this time the climate was drier and colder than today, and the island’s dense rainforests would likely have been much less impenetrable than they are now. Sea levels were about 120 metres lower, meaning Obi was a much larger island, encompassing what is today the separate island of Bisa, as well as several other small islands nearby.

Roughly 11,700 years ago, as the most recent ice age ended, the climate became significantly warmer and wetter, no doubt making Obi’s jungle much thicker. According to the researchers, it is no coincidence that around this time the first axes crafted from stone rather than sea shells appear, likely in response to their heavy-duty use for clearing and modification of the increasingly dense rainforest. While stone takes about twice as long to grind into an axe compared to shell, the harder material keeps its sharp edge for longer.

Judging by the bones which the researchers unearthed in the Kelo caves, people living there mainly hunted the Rothschild’s cuscus, a possum-like creature that still lives on Obi today. As the forest grew more dense, people probably used axes to clear patches of forest and make hunting easier.

Shipton’s team’s excavation of the shelters at the Kelo site unearthed a volcanic glass substance called obsidian, which must have been brought over from another island, as there is no known source on Obi. It also revealed particular types of beads, similar to those previously found on islands in southern Wallacea. These finds again support the idea that Obi islanders routinely travelled to other islands.

The excavations suggest people successfully lived in the two Kelo shelters for about 10,000 years. But then, about 8,000 years ago, both were abandoned. Did the residents leave Obi completely, or move elsewhere on the island? Perhaps the jungle had grown so thick that axes were no longer a match for the dense undergrowth. Perhaps people simply moved to the coast and turned to fishing rather than hunting as a means of survival.

Whatever the reason for the departure, there is no evidence for use of the Kelo shelters after this time, until about 1,000 years ago, when they were re-occupied by people who owned pottery as well as items made out of gold and silver. It seems likely, in view of Obi’s location, that this final phase of occupation also saw the Kelo shelters used by people involved in the historic trade in spices between the Maluku islands and the rest of the world.`;

const ielts19ReadingPassage2Test3 = `Wetlands are areas where water covers the soil, or is present either at or near the surface of the soil, for all or part of the year. These are complex ecosystems, rich in unique plant and animal life. But according to the World Wide Fund for Nature (WWFN), half of the world’s wetlands have disappeared since 1990, converted or destroyed for commercial development, drainage schemes and the extraction of minerals and peat*. Many of those that remain have been damaged by agricultural pesticides and fertilisers, industrial pollutants, and construction works.

Throughout history, humans have gathered around wetlands, and their fertile ecosystems have played an important part in human development. Consequently, they are of considerable religious, historical and archaeological value to many communities around the world. ‘Wetlands directly support the livelihoods and well-being of millions of people,’ says Dr Matthew McCartney, principal researcher and hydrologist at the International Water Management Institute (IWMI). ‘In many developing countries, large numbers of people are dependent on wetland agriculture for their livelihoods.’

They also serve a crucial environmental purpose. ‘Wetlands are one of the key tools in mitigating climate change across the planet,’ says Pieter van Eijk, head of Climate Adaptation at Wetlands International (WI), pointing to their use as buffers that protect coastal areas from sea-level rise and extreme weather events such as hurricanes and flooding. Wetland coastal forests provide food and water, as well as shelter from storms, and WI and other agencies are working to restore those forests which have been lost. ‘It can be as simple as planting a few trees per hectare to create shade and substantially change a microclimate,’ he says. ‘Implementing climate change projects isn’t so much about money.’

The world’s wetlands are, unfortunately, rich sources for in-demand commodities, such as palm oil and pulpwood. Peatlands – wetlands with a waterlogged organic soil layer – are particularly targeted. When peatlands are drained for cultivation, they become net carbon emitters instead of active carbon stores, and, according to Marcel Silvius, head of Climate-smart Land-use at WI, this practice causes six per cent of all global carbon emissions. The clearance of peatland for planting also increases the risk of forest fires, which release huge amounts of CO2. ‘We’re seeing huge peatland forests with extremely high biodiversity value being lost for a few decades of oil palm revenues,’ says Silvius.

The damage starts when logging companies arrive to clear the trees. They dig ditches to enter the peat swamps by boat and then float the logs out the same way. These are then used to drain water out of the peatlands to allow for the planting of corn, oil palms or pulpwood trees. Once the water has drained away, bacteria and fungi then break down the carbon in the peat and turn it into CO2 and methane. Meanwhile, the remainder of the solid matter in the peat starts to move downwards, in a process known as subsidence**. Peat comprises 90 per cent water, so this is one of the most alarming consequences of peatland clearances. ‘In the tropics, peat subsides at about four centimetres a year, so within half a century, very large landscapes on Sumatra and Borneo will become flooded as the peat drops below water level,’ says Silvius. ‘It’s a huge catastrophe that’s in preparation. Some provinces will lose 40 per cent of their landmass.’

And while these industries affect wetlands in ways that can easily be documented, Dr Dave Tickner of the WWFN believes that more subtle impacts can be even more devastating. ‘Sediment run-off and fertilisers can be pretty invisible,’ says Tickner. ‘Over-extraction of water is equally invisible. You do get shock stories about rivers running red, or even catching fire, but there’s seldom one big impact that really hurts a wetland.’ Tickner does not blame anyone for deliberate damage, however. ‘I’ve worked on wetland issues for 20 years and have never met anybody who wanted to damage a wetland,’ he says. ‘It isn’t something that people generally set out to do. Quite often, the effects simply come from people trying to make a living.’

Silvius also acknowledges the importance of income generation. ‘It’s not that we just want to restore the biodiversity of wetlands – which we do – but we recognise there’s a need to provide an income for local people.’ This approach is supported by IWMI. ‘The idea is that people in a developing country will only protect wetlands if they value and profit from them,’ says McCartney. ‘For sustainability, it’s essential that local people are involved in wetland planning and decision making and have clear rights to use wetlands.’

The fortunes of wetlands would be improved, Silvius suggests, if more governments recognised their long-term value. ‘Different governments have different attitudes,’ he says, and goes on to explain that some countries place a high priority on restoring wetlands, while others still deny the issue. McCartney is cautiously optimistic, however. ‘Awareness of the importance of wetlands is growing,’ he says. ‘It’s true that wetland degradation still continues at a rapid pace, but my impression is that things are slowly changing.’`;

const ielts19ReadingPassage3Test3 = `Is the era of artificial speech translation upon us?

Noise, Alex Waibel tells me, is one of the major challenges that artificial speech translation has to meet. A device may be able to recognise speech in a laboratory, or a meeting room, but will struggle to cope with the kind of background noise I can hear in my office. Surrounding Professor Waibel as he speaks to me from a Kyoto station in Japan, is a struggling cello. To follow him in English, on a scratchy line that reminds me we are nearly 10,000 kilometres apart – and that distance is still an obstacle to communication even if you’re speaking the same language, as we are. We haven’t reached the future yet. If we had, Waibel would have been able to speak more comfortably in his native German and I would have been able to hear his words in English.

At Karlsruhe Institute of Technology, where he is a professor of computer science, Waibel and his colleagues already give lectures in German that their students can follow in English via an electronic translator. The system generates text that students can read on their laptops or phones, so the process is somewhat similar to subtitling. It helps that lecturers speak clearly, don’t have to compete with background chatter, and say much the same thing each year.

The idea of artificial speech translation has been around for a long time. Douglas Adams’ science fiction novel, The Hitchhiker’s Guide to the Galaxy, published in 1979, featured a life form called the ‘Babel fish’ which, when placed in the ear, enabled a listener to understand any language in the universe. It came to represent one of those devices that technology enthusiasts dream of long before they become practically realisable, like TVs flat enough to hang on walls: objects that we once could only dream of having but that are now commonplace. Now devices that look like prototype Babel fish have started to appear, riding a wave of advances in artificial translation and voice recognition.

At this stage, however, they seem to be regarded as eye-catching novelties rather than steps towards what Waibel calls ‘making a language-transparent society’. They tend to be domestic devices or applications suitable for hotel check-ins, for example, providing a practical alternative to speaking traveller’s English. The efficiency of the translator is less important than the social function. However, ‘Professionals are less inclined to be patient in a conversation,’ founder and CEO of Waverly Labs, Andrew Ochoa observes. To redress this, Waverly is now preparing a new model for professional applications, which entails performance improvements in speech recognition, translation accuracy and the time it takes to deliver the translated speech.

For a conversation, both speakers need to have devices called Pilots (translator earpieces) in their ears. ‘We find that there’s a barrier with sharing one of the earphones with a stranger,’ says Ochoa. That can’t have been totally unexpected. The problem would be solved if earpiece translators became sufficiently prevalent that strangers would be likely to already have their own in their ears. Whether that happens, and how quickly, will probably depend not so much on the earpieces themselves, but on the prevalence of voice-controlled devices and artificial translation in general.

Waibel highlights the significance of certain Asian nations, noting that voice translation has really taken off in countries such as Japan with a range of systems. There is still a long way to go, though. A translation system needs to be simultaneous, like the translator’s voice speaking over the foreign politician being interviewed on the TV, rather than in sections that oblige speakers to pause after every few remarks and wait for the translation to be delivered. It needs to work offline, for situations where internet access isn’t possible, and to address apprehensions about the amount of private speech data accumulating in the cloud, having been sent to servers for processing.

Systems not only need to cope with physical challenges such as noise, they will also need to be socially aware by addressing people in the right way. Some cultural traditions demand solemn respect for academic status, for example, and it is only polite to respect this. Etiquette-sensitive artificial translators could relieve people of the need to know these differing cultural norms. At the same time, they might help to preserve local customs, slowing the spread of habits associated with international English, such as its readiness to get on first-name terms.

Professors and other professionals will not outsource language awareness to software, though. If the technology matures into seamless, ubiquitous artificial speech translation, it will actually add value to language skills. Whether it will help people conduct their family lives or relationships is open to question – though one noteworthy possibility is that it could overcome the language barriers that often arise between generations after migration, leaving children and their grandparents without a shared language.

Whatever uses it is put to, though, it will never be as good as the real thing. Even if voice-morphing technology simulates the speaker’s voice, their lip movements won’t match, and they will look like they are in a dubbed movie. The contrast will underline the value of shared languages, and the value of learning them. Sharing a language can promote a sense of belonging and community, as with the international scientists who use English as a lingua franca, where their predecessors used Latin. Though the practical need for a common language will diminish, the social value of sharing one will persist. And software will never be a substitute for the subtle but vital understanding that comes with knowledge of a language.`;


export const ielts19Test3Lessons: Lesson[] = [
  // Test 3
  {
    id: 'b19-t3-l0',
    title: 'Test 3: Listening P1-2',
    section: Section.LISTENING,
    parts: [
      { // Part 1
        questions: [
            { id: 'b19t3lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t3-p1.mp3', questionText: 'Kite Place – near the 1 ___', correctAnswers: ['harbour', 'harbor'], transcript: "Well, there are plenty of places to buy food in Kite Place – it’s the area by the harbour.", transcriptHighlight: "harbour" },
            { id: 'b19t3lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t3-p1.mp3', questionText: 'cross the 2 ___ and turn right', correctAnswers: ['bridge'], transcript: "it’s at the far end of Kite Place, so you have to go over the bridge and then it’s on the right.", transcriptHighlight: "bridge" },
            { id: 'b19t3lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t3-p1.mp3', questionText: 'best to go before 3 ___ pm, earlier than closing time', correctAnswers: ['3.30', 'three thirty'], transcript: "It doesn’t close until four, but I’d recommend going earlier than that – it does run out of some things. Oh, I don’t want that to happen. So if you get there by 3.30, you should be fine.", transcriptHighlight: "3.30" },
            { id: 'b19t3lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t3-p1.mp3', questionText: "called 4 ‘___’", correctAnswers: ['Rose', 'rose'], transcript: "Well, there’s a really nice organic shop there. Now what’s it called ... it’s the name of a flower, I know, it’s ‘Rose’.", transcriptHighlight: "Rose" },
            { id: 'b19t3lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t3-p1.mp3', questionText: 'look for the large 5 ___ outside', correctAnswers: ['sign'], transcript: "You can’t miss it – there’s also a big sign on the pavement so you can look for that.", transcriptHighlight: "sign" },
            { id: 'b19t3lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t3-p1.mp3', questionText: 'take a 6 ___ minibus, number 289', correctAnswers: ['purple'], transcript: "there’s a minibus that goes to the supermarket if you need it. It’s purple and the number is 289.", transcriptHighlight: "purple" },
            { id: 'b19t3lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p1.mp3', questionText: 'a handful of 7 ___ (type of seaweed)', correctAnswers: ['samphire'], transcript: "Have you ever tried samphire? ... It’s a type of seaweed, I just ask for a handful and you fry it in butter.", transcriptHighlight: "samphire" },
            { id: 'b19t3lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p1.mp3', questionText: 'beans and a 8 ___ for dessert', correctAnswers: ['melon'], transcript: "I’ll see what beans they have in the organic shop and I think I’ll get something for dessert there. How about a mango? I’m not sure – they’re not always ripe. I’d prefer a melon – it’s bigger too.", transcriptHighlight: "melon" },
            { id: 'b19t3lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p1.mp3', questionText: 'spices and 9 ___', correctAnswers: ['coconut'], transcript: "Good idea. The owner also sells a lot of spices that you can put in a curry, and things like coconut.", transcriptHighlight: "coconut" },
            { id: 'b19t3lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p1.mp3', questionText: 'a 10 ___ tart', correctAnswers: ['strawberry'], transcript: "Well – not that, but they have a whole range of tarts and the best are the strawberry ones.", transcriptHighlight: "strawberry" },
        ],
      },
      { // Part 2
        questions: [
            { id: 'b19t3lq11', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: What information is given about each of the following festival workshops? Choose ONE letter, A-H.", audioUrl: 'ielts-19/t3-p2.mp3', questionText: '11 Superheroes', options: ['A involves painting and drawing', 'B will be led by a prize-winning author', 'C is aimed at children with a disability', 'D involves a drama activity', 'E focuses on new relationships', 'F is aimed at a specific age group', 'G explores an unhappy feeling', 'H raises awareness of a particular culture'], correctAnswers: ['C is aimed at children with a disability'], transcript: "This is a special chance for deaf children to share their reading experiences with author Madeleine Gordon, who is herself hearing impaired.", transcriptHighlight: "deaf children... hearing impaired"},
            { id: 'b19t3lq12', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: What information is given about each of the following festival workshops? Choose ONE letter, A-H.", audioUrl: 'ielts-19/t3-p2.mp3', questionText: '12 Just do it', options: ['A involves painting and drawing', 'B will be led by a prize-winning author', 'C is aimed at children with a disability', 'D involves a drama activity', 'E focuses on new relationships', 'F is aimed at a specific age group', 'G explores an unhappy feeling', 'H raises awareness of a particular culture'], correctAnswers: ['D involves a drama activity'], transcript: "‘Just do it’ is a practical workshop led by the well-known illustrator Mark Keane. He’ll take participants on a magical journey to faraway lands with an opportunity for aspiring actors to do some role play.", transcriptHighlight: "do some role play"},
            { id: 'b19t3lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: What information is given about each of the following festival workshops? Choose ONE letter, A-H.", audioUrl: 'ielts-19/t3-p2.mp3', questionText: '13 Count on me', options: ['A involves painting and drawing', 'B will be led by a prize-winning author', 'C is aimed at children with a disability', 'D involves a drama activity', 'E focuses on new relationships', 'F is aimed at a specific age group', 'G explores an unhappy feeling', 'H raises awareness of a particular culture'], correctAnswers: ['F is aimed at a specific age group'], transcript: "‘Count on me’ is an inspiring and entertaining look at the issues of friendship for 13–15-year-olds.", transcriptHighlight: "13–15-year-olds"},
            { id: 'b19t3lq14', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: What information is given about each of the following festival workshops? Choose ONE letter, A-H.", audioUrl: 'ielts-19/t3-p2.mp3', questionText: '14 Speak up', options: ['A involves painting and drawing', 'B will be led by a prize-winning author', 'C is aimed at children with a disability', 'D involves a drama activity', 'E focuses on new relationships', 'F is aimed at a specific age group', 'G explores an unhappy feeling', 'H raises awareness of a particular culture'], correctAnswers: ['G explores an unhappy feeling'], transcript: "‘Speak up’ is part of a series of workshops on the subject of mental health. This is a creative writing workshop encouraging children to describe situations where they’ve experienced loneliness.", transcriptHighlight: "loneliness"},
            { id: 'b19t3lq15', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: What information is given about each of the following festival workshops? Choose ONE letter, A-H.", audioUrl: 'ielts-19/t3-p2.mp3', questionText: '15 Jump for joy', options: ['A involves painting and drawing', 'B will be led by a prize-winning author', 'C is aimed at children with a disability', 'D involves a drama activity', 'E focuses on new relationships', 'F is aimed at a specific age group', 'G explores an unhappy feeling', 'H raises awareness of a particular culture'], correctAnswers: ['B will be led by a prize-winning author'], transcript: "‘Jump for joy’ is many of you will know, is the heart-warming, best-selling story by Nina Karan about a young girl’s trip to visit her relatives in India. Recently it received the Gold medal at the Waterford Awards. Nina will get children to celebrate the word ‘joy’ by writing a poem.", transcriptHighlight: "by Nina Karan"},
            { id: 'b19t3lq16', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: What information is given about each of the following festival workshops? Choose ONE letter, A-H.", audioUrl: 'ielts-19/t3-p2.mp3', questionText: '16 Sticks and stones', options: ['A involves painting and drawing', 'B will be led by a prize-winning author', 'C is aimed at children with a disability', 'D involves a drama activity', 'E focuses on new relationships', 'F is aimed at a specific age group', 'G explores an unhappy feeling', 'H raises awareness of a particular culture'], correctAnswers: ['H raises awareness of a particular culture'], transcript: "‘Sticks and stones’ is the beautifully illustrated picture book for young readers about a community who organise an African-Caribbean festival to help local children learn about their Jamaican roots.", transcriptHighlight: "learn about their Jamaican roots"},
            { id: 'b19t3lq17', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: "Part 2: Choose TWO letters, A–E.", audioUrl: 'ielts-19/t3-p2.mp3', questionText: 'Which TWO reasons does the speaker give for recommending Alive and Kicking?', options: ['It will appeal to both boys and girls.', 'The author is well known.', 'It has colourful illustrations.', 'It is funny.', 'It deals with an important topic.'], correctAnswers: ['It is funny.', 'It deals with an important topic.'], transcript: "It deals with the serious issue of immigration and all the challenges the boy has to face at school and with the language barrier, etc. Usually, books like this are quite sad, but this one actually made me cry with laughter.", transcriptHighlight: "serious issue of immigration... made me cry with laughter"},
            { id: 'b19t3lq19', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: "Part 2: Choose TWO letters, A–E.", audioUrl: 'ielts-19/t3-p2.mp3', questionText: 'Which TWO pieces of advice does the speaker give to parents about reading?', options: ['Encourage children to write down new vocabulary.', 'Allow children to listen to audio books.', 'Get recommendations from librarians.', 'Give children a choice about what they read.', 'Only read aloud to children until they can read independently.'], correctAnswers: ['Allow children to listen to audio books.', 'Get recommendations from librarians.'], transcript: "it’s good to read more advanced books to them as it helps to develop their vocabulary. If you don’t have time for this, then let them listen to audio books. ... Librarians should be able to help you with this.", transcriptHighlight: "listen to audio books... Librarians should be able to help"},
        ],
      }
    ]
  },
  {
    id: 'b19-t3-l1',
    title: 'Test 3: Listening P3-4',
    section: Section.LISTENING,
    parts: [
        { // Part 3
            questions: [
                { id: 'b19t3lq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t3-p3.mp3', questionText: 'How does Clare feel about the students in her Year 12 science class?', options: ['worried that they are not making progress', 'challenged by their poor behaviour in class', 'frustrated at their lack of interest in the subject'], correctAnswers: ['frustrated at their lack of interest in the subject'], transcript: "They don’t seem to think that science has anything to do with their lives. It’s depressing. They listen to what I say, and I gave them a test last week and the results weren’t too bad, but there’s no real engagement.", transcriptHighlight: "no real engagement"},
                { id: 'b19t3lq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t3-p3.mp3', questionText: "How does Jake react to Clare’s suggestion about an experiment based on children’s diet?", options: ['He is concerned that the results might not be meaningful.', 'He feels some of the data might be difficult to obtain.', 'He suspects that the conclusions might be upsetting.'], correctAnswers: ['He feels some of the data might be difficult to obtain.'], transcript: "So your methodology would involve the children recording what they eat. OK. But you’d also need to have access to the children’s medical records and I don’t think people would be happy about that.", transcriptHighlight: "don’t think people would be happy about that"},
                { id: 'b19t3lq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t3-p3.mp3', questionText: 'What problem do they agree may be involved in an experiment involving animals?', options: ['Any results may not apply to humans.', 'It may be complicated to get permission.', 'Students may not be happy about animal experiments.'], correctAnswers: ['Any results may not apply to humans.'], transcript: "But if we found out that, say, a particular diet affects the health of animals, the same thing wouldn’t necessarily be true for people, would it? No, that’s true.", transcriptHighlight: "wouldn’t necessarily be true for people"},
                { id: 'b19t3lq24', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t3-p3.mp3', questionText: 'What question do they decide the experiment should address?', options: ['Are mice capable of controlling their food intake?', 'Does an increase in sugar lead to health problems?', 'How much do supplements of different kinds affect health?'], correctAnswers: ['Are mice capable of controlling their food intake?'], transcript: "In fact, maybe the focus could be on whether mice can control their own diet. So, what happens when they have access to more sugar, that they don’t really need?", transcriptHighlight: "whether mice can control their own diet"},
                { id: 'b19t3lq25', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t3-p3.mp3', questionText: 'Clare might also consider doing another experiment involving', options: ['other types of food supplement.', 'different genetic strains of mice.', 'varying amounts of exercise.'], correctAnswers: ['varying amounts of exercise.'], transcript: "Exactly. Do they eat it or do they decide to leave it? Great. Then on, you could do a follow-up experiment adding another variable. Like, you could give some of the mice the chance to be more active, running on a wheel or something, and the others just sit around and don’t do much.", transcriptHighlight: "chance to be more active"},
                { id: 'b19t3lq26', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Complete the flowchart. Choose ONE letter from the box.', audioUrl: 'ielts-19/t3-p3.mp3', questionText: 'Choose mice which are all the same 26 ___', options: ['A size', 'B escape', 'C age', 'D water', 'E cereal', 'F calculations', 'G changes', 'H colour'], correctAnswers: ['C age'], transcript: "Great. So how many mice would I need? I’d say about 12. And all young ones, not a mixture of old and young.", transcriptHighlight: "all young ones"},
                { id: 'b19t3lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Complete the flowchart. Choose ONE letter from the box.', audioUrl: 'ielts-19/t3-p3.mp3', questionText: 'Divide the mice into two groups, each with a different 27 ___', options: ['A size', 'B escape', 'C age', 'D water', 'E cereal', 'F calculations', 'G changes', 'H colour'], correctAnswers: ['H colour'], transcript: "And how would I tell them apart? I suppose I could put some sort of tag on one group . . . or just mark them in some way? You could use food colouring, that wouldn’t hurt them.", transcriptHighlight: "use food colouring"},
                { id: 'b19t3lq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Complete the flowchart. Choose ONE letter from the box.', audioUrl: 'ielts-19/t3-p3.mp3', questionText: 'Feed group B the same, but also sugar contained in 28 ___', options: ['A size', 'B escape', 'C age', 'D water', 'E cereal', 'F calculations', 'G changes', 'H colour'], correctAnswers: ['E cereal'], transcript: "Would you just give them straight sugar? It might be better to give them something like cereal with it.", transcriptHighlight: "cereal"},
                { id: 'b19t3lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Complete the flowchart. Choose ONE letter from the box.', audioUrl: 'ielts-19/t3-p3.mp3', questionText: 'Place them in a weighing chamber to prevent 29 ___', options: ['A size', 'B escape', 'C age', 'D water', 'E cereal', 'F calculations', 'G changes', 'H colour'], correctAnswers: ['B escape'], transcript: "Exactly. So you’d need to stop the mice from running around. I think you could just use a plastic box with holes in the top.", transcriptHighlight: "stop the mice from running around"},
                { id: 'b19t3lq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Complete the flowchart. Choose ONE letter from the box.', audioUrl: 'ielts-19/t3-p3.mp3', questionText: 'Do all necessary 30 ___', options: ['A size', 'B escape', 'C age', 'D water', 'E cereal', 'F calculations', 'G changes', 'H colour'], correctAnswers: ['F calculations'], transcript: "OK. So once we’ve measured the weight gain of each mouse we can work out the average for each group, as well as the standard deviation.", transcriptHighlight: "work out the average... and the standard deviation"},
            ]
        },
        { // Part 4
            questions: [
                { id: 'b19t3lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p4.mp3', questionText: 'fibres from some 31 ___ during washing', correctAnswers: ['clothing'], transcript: "Threads and microfibres detach from synthetic clothing every time they’re put in a washing machine, and these find their way into the water system.", transcriptHighlight: "clothing" },
                { id: 'b19t3lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p4.mp3', questionText: 'They cause injuries to the 32 ___ of wildlife...', correctAnswers: ['mouths'], transcript: "There is evidence that microplastics harm small creatures in a variety of ways, such as by damaging their mouths, or by impairing their ability to feed", transcriptHighlight: "mouths" },
                { id: 'b19t3lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p4.mp3', questionText: '...e.g., in bottled and tap water, 33 ___ and seafood.', correctAnswers: ['salt'], transcript: "What’s more, salt and many kinds of seafood have also been found to contain microplastics.", transcriptHighlight: "salt" },
                { id: 'b19t3lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p4.mp3', questionText: '...already banned in skin cleaning products and 34 ___ in some countries.', correctAnswers: ['toothpaste'], transcript: "in the UK, there is legislation which prevents manufacturers from adding plastic microbeads to shower gels, facial cleansers and toothpaste.", transcriptHighlight: "toothpaste" },
                { id: 'b19t3lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p4.mp3', questionText: 'Microplastics enter the soil through the air, rain and 35 ___', correctAnswers: ['fertilisers', 'fertilizers'], transcript: "What’s more, many of the fertilisers used by both farmers and gardeners contain microplastics.", transcriptHighlight: "fertilisers" },
                { id: 'b19t3lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p4.mp3', questionText: 'Earthworms are important because they add 36 ___ to the soil.', correctAnswers: ['nutrients'], transcript: "These worms, which live in topsoil, are an essential component of our agricultural system. By feeding on soil, they mix nutrients into it, thereby making it more fertile.", transcriptHighlight: "nutrients" },
                { id: 'b19t3lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p4.mp3', questionText: 'The study aimed to find whether microplastics in earthworms affect the 37 ___ of plants.', correctAnswers: ['growth'], transcript: "The researchers set out to discover whether the introduction of microplastics into the soil – and the subsequent ingestion of these by earthworms – would impact soil quality and ultimately inhibit plant growth.", transcriptHighlight: "growth" },
                { id: 'b19t3lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p4.mp3', questionText: 'The study found that microplastics caused: – 38 ___ loss in earthworms', correctAnswers: ['weight'], transcript: "The result was that the worms lost weight rapidly.", transcriptHighlight: "weight" },
                { id: 'b19t3lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p4.mp3', questionText: '– a rise in the level of 39 ___ in the soil.', correctAnswers: ['acid'], transcript: "The team also discovered that there was an increase in the amount of acid found in the soil", transcriptHighlight: "acid" },
                { id: 'b19t3lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t3-p4.mp3', questionText: '– changes to soil damage both ecosystems and 40 ___', correctAnswers: ['society'], transcript: "That is, when soil becomes impoverished by the presence of microplastics, not only ecosystems but also the whole of society are negatively impacted.", transcriptHighlight: "society" },
            ]
        }
    ]
  },
  {
    id: 'b19-t3-r2',
    title: 'Test 3: Reading P1',
    section: Section.READING,
    parts: [{ 
        questions: [
            { id: 'b19t3rq1', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts19ReadingPassage1Test3, questionText: 'Archaeological research had taken place on the island of Obi before the arrival of Ceri Shipton and his colleagues.', options: ['True', 'False', 'Not Given'], correctAnswers: ['False'], passageHighlight: "became the first archaeologists to explore Obi", reason: "The passage states that Dr. Shipton's team were the 'first archaeologists to explore Obi', directly contradicting the idea that research had taken place there before." },
            { id: 'b19t3rq2', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts19ReadingPassage1Test3, questionText: 'At the Kelo sites, the researchers found the first clam shell axes ever to be discovered in the region.', options: ['True', 'False', 'Not Given'], correctAnswers: ['False'], passageHighlight: "axes made from clam shells from roughly the same time had also previously been found elsewhere in this region", reason: "The passage states that clam shell axes from the same period 'had also previously been found elsewhere in this region', so the ones found at Kelo were not the first." },
            { id: 'b19t3rq3', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts19ReadingPassage1Test3, questionText: 'The size of Obi today is less than it was 18,000 years ago.', options: ['True', 'False', 'Not Given'], correctAnswers: ['True'], passageHighlight: "Sea levels were about 120 metres lower, meaning Obi was a much larger island", reason: "The passage states that 18,000 years ago, 'Sea levels were about 120 metres lower, meaning Obi was a much larger island'. This directly supports the statement that the island is smaller today." },
            { id: 'b19t3rq4', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts19ReadingPassage1Test3, questionText: 'A change in the climate around 11,700 years ago had a greater impact on Obi than on the surrounding islands.', options: ['True', 'False', 'Not Given'], correctAnswers: ['Not Given'], reason: "The passage mentions the climate change on Obi around 11,700 years ago, but it does not compare the severity of its impact with that on surrounding islands." },
            { id: 'b19t3rq5', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts19ReadingPassage1Test3, questionText: 'The researchers believe there is a connection between warmer, wetter weather and a change in the material used to make axes.', options: ['True', 'False', 'Not Given'], correctAnswers: ['True'], passageHighlight: "the climate became significantly warmer and wetter, no doubt making Obi’s jungle much thicker. According to the researchers, it is no coincidence that around this time the first axes crafted from stone rather than sea shells appear", reason: "The passage links the warmer, wetter climate to the appearance of stone axes by stating, 'it is no coincidence that around this time the first axes crafted from stone... appear', implying a direct connection." },
            { id: 'b19t3rq6', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts19ReadingPassage1Test3, questionText: "Shipton’s team were surprised to find evidence of the Obi islanders' hunting practices.", options: ['True', 'False', 'Not Given'], correctAnswers: ['Not Given'], passageHighlight: "Judging by the bones which the researchers unearthed in the Kelo caves, people living there mainly hunted the Rothschild’s cuscus", reason: "The passage states that the researchers found bones and judged that people hunted a certain animal, but it does not mention whether the researchers were surprised by this finding or not." },
            { id: 'b19t3rq7', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts19ReadingPassage1Test3, questionText: 'It is thought that the Kelo shelters were occupied continuously until about 1,000 years ago.', options: ['True', 'False', 'Not Given'], correctAnswers: ['False'], passageHighlight: "about 8,000 years ago, both were abandoned. ... there is no evidence for use of the Kelo shelters after this time, until about 1,000 years ago", reason: "The passage states that the shelters 'were abandoned' about 8,000 years ago and there was 'no evidence for use... until about 1,000 years ago', which contradicts the idea of continuous occupation." },
            { id: 'b19t3rq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test3, questionText: 'Excavations of rock shelters inside 8 ___ near the village of Kelo revealed:', correctAnswers: ['caves'], passageHighlight: "found two caves containing prehistoric rock shelters", reason: "The passage states that the team 'found two caves containing prehistoric rock shelters'." },
            { id: 'b19t3rq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test3, questionText: 'axes made out of 9 ___, dating from around 11,700 years ago', correctAnswers: ['stone'], passageHighlight: "the first axes crafted from stone rather than sea shells appear", reason: "The passage mentions that around the time the climate changed (11,700 years ago), 'the first axes crafted from stone rather than sea shells appear'." },
            { id: 'b19t3rq10', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test3, questionText: '10 ___ of an animal: evidence of what ancient islanders ate', correctAnswers: ['bones'], passageHighlight: "Judging by the bones which the researchers unearthed", reason: "The passage explains that researchers learned about hunting practices by 'Judging by the bones which the researchers unearthed'." },
            { id: 'b19t3rq11', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test3, questionText: '11 ___ which resembled ones found on other islands.', correctAnswers: ['beads'], passageHighlight: "It also revealed particular types of beads", reason: "The passage states that the excavation 'revealed particular types of beads, similar to those previously found on islands'." },
            { id: 'b19t3rq12', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test3, questionText: 'had 12 ___ as well as items made out of metal', correctAnswers: ['pottery'], passageHighlight: "re-occupied by people who owned pottery as well as items made out of gold and silver", reason: "Referring to the re-occupation 1,000 years ago, the passage says the people 'owned pottery as well as items made out of gold and silver'." },
            { id: 'b19t3rq13', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test3, questionText: 'probably took part in the production and sale of 13 ___', correctAnswers: ['spices'], passageHighlight: "the historic trade in spices", reason: "The passage suggests the final occupants were 'involved in the historic trade in spices'." },
        ] 
    }]
  },
  {
    id: 'b19-t3-r3',
    title: 'Test 3: Reading P2-3',
    section: Section.READING,
    parts: [ 
        { // Passage 2
            questions: [
                { id: 'b19t3rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–H.', passage: ielts19ReadingPassage2Test3, questionText: 'reference to the need to ensure that inhabitants of wetland regions continue to benefit from them', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['G'], passageHighlight: "we recognise there’s a need to provide an income for local people." },
                { id: 'b19t3rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–H.', passage: ielts19ReadingPassage2Test3, questionText: 'the proportion of wetlands which have already been lost', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['A'], passageHighlight: "half of the world’s wetlands have disappeared since 1990" },
                { id: 'b19t3rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–H.', passage: ielts19ReadingPassage2Test3, questionText: 'reference to the idea that people are beginning to appreciate the value of wetlands', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['H'], passageHighlight: "Awareness of the importance of wetlands is growing" },
                { id: 'b19t3rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–H.', passage: ielts19ReadingPassage2Test3, questionText: 'mention of the cultural significance of wetlands', options: ['A','B','C','D','E','F','G','H'], correctAnswers: ['B'], passageHighlight: "they are of considerable religious, historical and archaeological value" },
                { id: 'b19t3rq18', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage2Test3, questionText: 'Peatlands which have been drained begin to release ___ instead of storing it.', correctAnswers: ['carbon'], passageHighlight: "they become net carbon emitters instead of active carbon stores" },
                { id: 'b19t3rq19', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage2Test3, questionText: 'Once peatland areas have been cleared, ___ are more likely to occur.', correctAnswers: ['fires'], passageHighlight: "The clearance of peatland for planting also increases the risk of forest fires" },
                { id: 'b19t3rq20', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage2Test3, questionText: 'Clearing peatland forests to make way for oil palm plantations destroys the ___ of the local environment.', correctAnswers: ['biodiversity'], passageHighlight: "huge peatland forests with extremely high biodiversity value being lost" },
                { id: 'b19t3rq21', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage2Test3, questionText: 'Water is drained out of peatlands through the ___ which are created by logging companies.', correctAnswers: ['ditches'], passageHighlight: "They dig ditches to enter the peat swamps" },
                { id: 'b19t3rq22', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage2Test3, questionText: 'Draining peatlands leads to ___: a serious problem which can eventually result in coastal flooding and land loss.', correctAnswers: ['subsidence'], passageHighlight: "the remainder of the solid matter in the peat starts to move downwards, in a process known as subsidence" },
                { id: 'b19t3rq23', type: QuestionType.MULTIPLE_CHOICE, prompt: "Match each statement with the correct expert, A–D.", passage: ielts19ReadingPassage2Test3, questionText: 'Communities living in wetland regions must be included in discussions about the future of these areas.', options: ['A Matthew McCartney', 'B Pieter van Eijk', 'C Marcel Silvius', 'D Dave Tickner'], correctAnswers: ['A Matthew McCartney'], passageHighlight: "it’s essential that local people are involved in wetland planning and decision making" },
                { id: 'b19t3rq24', type: QuestionType.MULTIPLE_CHOICE, prompt: "Match each statement with the correct expert, A–D.", passage: ielts19ReadingPassage2Test3, questionText: 'Official policies towards wetlands vary from one nation to the next.', options: ['A Matthew McCartney', 'B Pieter van Eijk', 'C Marcel Silvius', 'D Dave Tickner'], correctAnswers: ['C Marcel Silvius'], passageHighlight: "Different governments have different attitudes,’ he says, and goes on to explain that some countries place a high priority on restoring wetlands, while others still deny the issue." },
                { id: 'b19t3rq25', type: QuestionType.MULTIPLE_CHOICE, prompt: "Match each statement with the correct expert, A–D.", passage: ielts19ReadingPassage2Test3, questionText: 'People cause harm to wetlands without having any intention to do so.', options: ['A Matthew McCartney', 'B Pieter van Eijk', 'C Marcel Silvius', 'D Dave Tickner'], correctAnswers: ['D Dave Tickner'], passageHighlight: "It isn’t something that people generally set out to do." },
                { id: 'b19t3rq26', type: QuestionType.MULTIPLE_CHOICE, prompt: "Match each statement with the correct expert, A–D.", passage: ielts19ReadingPassage2Test3, questionText: 'Initiatives to reverse environmental damage need not be complex.', options: ['A Matthew McCartney', 'B Pieter van Eijk', 'C Marcel Silvius', 'D Dave Tickner'], correctAnswers: ['B Pieter van Eijk'], passageHighlight: "It can be as simple as planting a few trees per hectare ... Implementing climate change projects isn’t so much about money." },
            ]
        }, 
        { // Passage 3
            questions: [
                { id: 'b19t3rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test3, questionText: 'What does the reader learn about the conversation in the first paragraph?', options: ['The speakers are communicating in different languages.', 'Neither of the speakers is familiar with their environment.', 'The topic of the conversation is difficult for both speakers.', 'Aspects of the conversation are challenging for both speakers.'], correctAnswers: ['Aspects of the conversation are challenging for both speakers.'], passageHighlight: "Noise, Alex Waibel tells me, is one of the major challenges... a struggling cello... on a scratchy line", reason: "The passage explicitly mentions 'challenges' like 'background noise' and a 'scratchy line' which makes the conversation difficult for both the speaker (Waibel) and the listener (the writer)." },
                { id: 'b19t3rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test3, questionText: 'What assists the electronic translator during lectures at Karlsruhe Institute of Technology?', options: ['the repeated content of lectures', 'the students’ reading skills', 'the languages used', 'the lecturers’ technical ability'], correctAnswers: ['the repeated content of lectures'], passageHighlight: "It helps that lecturers speak clearly, don’t have to compete with background chatter, and say much the same thing each year.", reason: "The passage states that it 'helps' the translation system that lecturers 'say much the same thing each year,' which means the content is repeated." },
                { id: 'b19t3rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test3, questionText: 'When referring to The Hitchhiker’s Guide to the Galaxy, the writer suggests that', options: ['the Babel fish was considered undesirable at the time.', 'this book was not seriously intending to predict the future.', 'artificial speech translation was not a surprising development.', 'some speech translation techniques are better than others.'], correctAnswers: ['artificial speech translation was not a surprising development.'], passageHighlight: "The idea of artificial speech translation has been around for a long time.", reason: "The writer introduces the topic by stating 'The idea of artificial speech translation has been around for a long time,' suggesting its eventual development was not a surprise but the realization of a long-held concept." },
                { id: 'b19t3rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test3, questionText: 'What does the writer say about sharing earpieces?', options: ['It is something people will get used to doing.', 'The reluctance to do this is understandable.', 'The equipment will be unnecessary in the future.', 'It is something few people need to worry about.'], correctAnswers: ['The reluctance to do this is understandable.'], passageHighlight: "‘We find that there’s a barrier with sharing one of the earphones with a stranger,’ says Ochoa. That can’t have been totally unexpected.", reason: "After stating that there is a 'barrier' to sharing earpieces, the writer comments, 'That can’t have been totally unexpected,' which implies that this reluctance is understandable or predictable." },
                { id: 'b19t3rq31', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete each sentence with the correct ending, A–F, below.', passage: ielts19ReadingPassage3Test3, questionText: 'Speech translation methods are developing fast in Japan', options: ['A but there are concerns about this.', 'B as systems do not need to conform to standard practices.', 'C but they are far from perfect.', 'D despite the noise issues.', 'E because translation is immediate.', 'F and have an awareness of good manners.'], correctAnswers: ['C but they are far from perfect.'], passageHighlight: "voice translation has really taken off in countries such as Japan with a range of systems. There is still a long way to go, though.", reason: "The passage notes that voice translation has 'taken off' in Japan, but immediately follows with 'There is still a long way to go, though,' indicating that the systems are not yet perfect." },
                { id: 'b19t3rq32', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete each sentence with the correct ending, A–F, below.', passage: ielts19ReadingPassage3Test3, questionText: 'TV interviews that use translation voiceover methods are successful', options: ['A but there are concerns about this.', 'B as systems do not need to conform to standard practices.', 'C but they are far from perfect.', 'D despite the noise issues.', 'E because translation is immediate.', 'F and have an awareness of good manners.'], correctAnswers: ['E because translation is immediate.'], passageHighlight: "A translation system needs to be simultaneous, like the translator’s voice speaking over the foreign politician", reason: "The passage uses the TV interview voiceover as a model for how a translation system should be: 'simultaneous.' This immediacy is what makes it successful." },
                { id: 'b19t3rq33', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete each sentence with the correct ending, A–F, below.', passage: ielts19ReadingPassage3Test3, questionText: 'Future translation systems should address people appropriately', options: ['A but there are concerns about this.', 'B as systems do not need to conform to standard practices.', 'C but they are far from perfect.', 'D despite the noise issues.', 'E because translation is immediate.', 'F and have an awareness of good manners.'], correctAnswers: ['F and have an awareness of good manners.'], passageHighlight: "Etiquette-sensitive artificial translators could relieve people of the need to know these differing cultural norms.", reason: "The passage discusses the need for 'etiquette-sensitive' translators that can handle cultural norms and politeness, which is an awareness of good manners." },
                { id: 'b19t3rq34', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete each sentence with the correct ending, A–F, below.', passage: ielts19ReadingPassage3Test3, questionText: 'Users may be able to maintain their local customs', options: ['A but there are concerns about this.', 'B as systems do not need to conform to standard practices.', 'C but they are far from perfect.', 'D despite the noise issues.', 'E because translation is immediate.', 'F and have an awareness of good manners.'], correctAnswers: ['B as systems do not need to conform to standard practices.'], passageHighlight: "they might help to preserve local customs, slowing the spread of habits associated with international English", reason: "The passage suggests that etiquette-sensitive translators could 'preserve local customs' by adapting to them, rather than forcing the 'habits associated with international English' on the user, thus not conforming to a single standard practice." },
                { id: 'b19t3rq35', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test3, questionText: 'Language translation systems will be seen as very useful throughout the academic and professional worlds.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "Professors and other professionals will not outsource language awareness to software, though.", reason: "The writer explicitly states that professionals 'will not outsource language awareness to software,' which contradicts the idea that the systems will be seen as universally useful, as they won't replace genuine language awareness." },
                { id: 'b19t3rq36', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test3, questionText: 'The overall value of automated translation to family life is yet to be shown.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "Whether it will help people conduct their family lives or relationships is open to question", reason: "The writer states that the usefulness of this technology for family life 'is open to question,' which means its value has not yet been demonstrated or proven." },
                { id: 'b19t3rq37', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test3, questionText: 'Automated translation could make life more difficult for immigrant families.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "one noteworthy possibility is that it could overcome the language barriers that often arise between generations after migration", reason: "The passage directly contradicts this by suggesting a positive outcome: it could 'overcome the language barriers' in immigrant families, not make things more difficult." },
                { id: 'b19t3rq38', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test3, questionText: 'Visual aspects of language translation are being considered by scientists.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage mentions that with automated translation, a speaker's 'lip movements won’t match,' but it does not state whether scientists are currently considering or working on this visual aspect." },
                { id: 'b19t3rq39', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test3, questionText: 'International scientists have found English easier to translate into other languages than Latin.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage compares English and Latin as lingua francas used by scientists at different times but makes no comment on the ease of translating either language." },
                { id: 'b19t3rq40', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test3, questionText: 'As far as language is concerned, there is a difference between people’s social and practical needs.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "Though the practical need for a common language will diminish, the social value of sharing one will persist.", reason: "The writer makes a clear distinction between the 'practical need' for a shared language (which will decrease) and the 'social value' of it (which will persist), highlighting a difference between practical and social aspects." },
            ]
        }
    ]
  },
  {
    id: 'b19-t3-w4',
    title: 'Test 3: Writing T1-2',
    section: Section.WRITING,
    parts: [
      {
        questions: [{
            id: 'b19t3wq1',
            type: QuestionType.WRITING_TASK,
            prompt: 'You should spend about 20 minutes on this task.',
            imageUrl: 'ielts-19/ielts-19-t3-w1-diagram.png',
            task: 'The diagram below shows how a biofuel called ethanol is produced.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.',
            sampleAnswerBand: 6.5,
            sampleAnswer: "The given diagram illustrates the various stages in the process of producing ethanol, a kind of biofuel. Overall, there are 9 main phrases in the ethanol production, starting with growing plants and tress, and finishing with supplying ethanol for transportation and gas mission.\n\nAt the first stage in the process of making ethanol, a large number of trees and plants are grown. Thanks to the source of energy from sunlight and carbon dioxide from humman and transportatin, plants and trees grow up and are haverested when they are mature enough. After being collected by machine, they are put into another machine where slice them into small pieces to form cellulose. This step is call pre-processing.\n\nIn the following stage, cellulose are taken to a factory where “processing” stage occurs. Subsequently, Sugars are extracted from original cellulose before microbes are added to make ethanol. It is then used as a type of fuel for a lot of means of transportation such as cars, trucks, airplanes. Finally, a huge amount of carbon dioxide which is released into the air become energy for process of “photosynthesis” of plants and trees.",
            examinerComment: "This is a strong response. The first short paragraph is an introduction, then the second paragraph contains an overview of the process [starting with growing plants] and [finishing with supplying ethanol]. This is sufficient as an overview, but the candidate should also summarise the main stages. The rest of the response presents and highlights the process. Ideas are logically organised and the response follows the order given in the diagram. There is good use of linking words to describe a process [At the first stage | After being | Subsequently] and other linking devices, including reference and substitution [they | then used]. The candidate uses vocabulary well with some flexibility [extracted | photosynthesis], but there are a handful of errors [phrases / phases | tress / trees | humman / human | transportatin / transportation | tupe / type]. These errors do not get in the way of the meaning. Grammatical range is quite broad and there is a variety of complex structures and sentences with multiple clauses. There are a few errors [where slice them / which slices them]."
        }]
      },
      {
        questions: [{
            id: 'b19t3wq2',
            type: QuestionType.WRITING_TASK,
            prompt: 'You should spend about 40 minutes on this task. Write about the following topic:',
            task: 'It is important for everyone, including young people, to save money for their future.\n\nTo what extent do you agree or disagree with this statement?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.',
            sampleAnswerBand: 7.0,
            sampleAnswer: "Saving money for the future is always a very good idea. First of all money is something that is needed in almost all areas in life. Whether you are young or old you need money to buy everyday things like food, clothing, etc. living etc.\n\nYoung people are usually often full of enthusiasm about life their future. They are looking forward to their first job, to meeting new people or to getting to know as much of the world as they can. Many tend to live in the present rather than in the future so that they don't always plan ahead.\n\nWhen you people get older and settle down they realize that buying a house, starting a family or caring for your health takes up a good considerable amount of money and everybody who began saving money in younger years is glad to have done so. However, saving money is not always possible when you are young. Sometimes unforeseen expenses cannot be avoided, life situations are suddenly changing or there is never even enough money available even for the most necessary things. So So how could you save money for the future in this case? In general, you have to ask yourself what your priorities in life are. What are the things you cherish most? Is it more important for you to plan ahead or do you prefer to just enjoy the moment that you live in?\n\nEverybody has to make own choices and to consider what is really essential for him or herself. In any age taking a moment to f reflect on your life and looking back at the choices you things you have already done is always a good thing to do. If you know yourself well and all about all the things that really make you happy you will be able to make the right decisions in financial issues as well as life other areas in life.\n\nIn what way money plays an important role will be easy to be found out then. Perhaps you need less than you first thought years ago.",
            examinerComment: "This is a strong response to the task. In the first paragraph, the candidate makes their view clear, agreeing with the statement that saving money for the future is a good idea. In the next two paragraphs, they present ideas on how saving money is actually quite challenging: young people can [tend to live in the present], so [don’t always plan ahead], the cost of housing, starting families and health care can be high, and [unforeseen expenses cannot be avoided]. The rest of the response is about how people can decide how much to spend and how much to save. The last line [Perhaps you need less than you first thought years ago] suggests that saving is not the answer for everyone. The ending gives advice to the reader, rather than summarising the main ideas.\n\nIdeas are easy to follow and logically organised. Linking expressions are well integrated [Whether | Sometimes | Perhaps] and generally accurate, and cohesive devices are used well [Many tend to | everybody who] with some errors [own choices / their own choices]. Paragraphing at the start is appropriate, but the last four sentences are set out separately and inappropriately, which affects the score.\n\nThere is some higher-level vocabulary, with effective collocation [full of enthusiasm | tend to live in the present | settle down | unforeseen expenses]. The candidate uses a variety of structures, including comparative forms [rather than | do you prefer], conditionals [if] and a range of multi-clause sentences. Errors remain, with some missing punctuation and incorrect tenses [be f found out / find out] and prepositions [in any age / At any age], but this does not affect the reader’s understanding."
        }]
      }
    ],
  },
  {
    id: 'b19-t3-s5',
    title: 'Test 3: Speaking P1-3',
    section: Section.SPEAKING,
    parts: [
      {
        questions: [{
            id: 'b19t3sq1',
            type: QuestionType.SPEAKING_TASK,
            prompt: 'Part 1: Example',
            question: 'Holidays\n\n- Do you prefer spending holidays with friends or with family? [Why?]\n- What kind of holiday accommodation do you like to stay in? [Why?]\n- What plans do you have for your next holiday?\n- Is your city or region a good place for other people to visit on holiday? [Why/Why not?]',
            sampleAnswer: `Here are sample answers for the "Holidays" topic.

**1. Do you prefer spending holidays with friends or with family? [Why?]**

"That's a tough choice as I enjoy both, but if I had to pick one, I'd probably say with friends. Holidays with family are wonderful for relaxing and catching up, but trips with friends tend to be more adventurous and active. We often explore new cities or go hiking, which I really love. There's a different kind of energy and freedom."

**2. What kind of holiday accommodation do you like to stay in? [Why?]**

"I'm quite flexible, but I generally prefer self-catering apartments or holiday homes. I like having the option to cook my own meals and having a bit more space and privacy than you'd get in a typical hotel room. It often feels more like living like a local, which enhances the travel experience for me."

**3. What plans do you have for your next holiday?**

"I'm hoping to go to Portugal for my next holiday. A few friends and I are planning a trip to Lisbon for a few days to explore the city's history and enjoy the food scene, and then we want to head south to the Algarve region to relax on the beaches. We haven't booked anything yet, but we're in the early stages of planning."

**4. Is your city or region a good place for other people to visit on holiday? [Why/Why not?]**

"Yes, definitely. I live in [Your City/Region], which is quite popular with tourists. It has a beautiful historic centre with lots of museums and galleries. We also have some fantastic parks and a great variety of restaurants and cafes. It's well-connected by public transport, so it's easy for visitors to get around and see everything. It offers a good mix of culture and entertainment."`
        }]
      },
      {
        questions: [{
            id: 'b19t3sq2',
            type: QuestionType.SPEAKING_TASK,
            prompt: 'Part 2: Cue Card',
            question: 'Describe a car journey you made that took longer than expected.\nYou should say:\n- where you were going\n- who you were with\n- how you felt during the journey\n- and explain why this car journey took longer than expected.',
            sampleAnswer: `Of course. Here is a sample answer for the Part 2 cue card.

***

"I can clearly remember a car journey that took much, much longer than planned. A few years ago, I was travelling with **my family** from our home to the coast for a short holiday. We were going to a seaside town called St. Ives, which is in Cornwall, right at the southwestern tip of England. It’s normally about a five-hour drive.

The journey took so long primarily because we made the classic mistake of travelling on the first day of a bank holiday weekend. We set off early, thinking we would beat the traffic, but it seemed everyone else had the same idea. An hour into the trip, we hit a massive traffic jam on the motorway. For what felt like an eternity, we were just crawling along, stop-start, for miles and miles.

During the journey, I felt a whole mix of emotions. Initially, I was quite excited and optimistic, listening to music and chatting. But as the hours ticked by and we barely moved, I started to feel incredibly frustrated and bored. The car felt cramped, and we were all getting a bit irritable with each other. I remember just staring out of the window, watching other cars, feeling completely fed up and wishing we had taken the train instead.

What was supposed to be a five-hour trip ended up taking nearly ten hours. The combination of the sheer volume of holiday traffic and an accident further up the road created the perfect storm for a gridlock. By the time we finally arrived, it was late in the evening, and we were all exhausted. It certainly taught me a lesson about when to travel during peak times!"`
        }]
      },
       {
        questions: [{
            id: 'b19t3sq3',
            type: QuestionType.SPEAKING_TASK,
            prompt: 'Part 3: Discussion topics',
            question: 'Driving a car\n- How interested are young people in your country in learning to drive?\n- What are the differences between driving in the countryside and driving in the city?\n- Do you consider most drivers where you live to be good drivers?\n\nElectric cars\n- How popular are electric cars in your country?\n- In what ways could more people be persuaded to buy electric cars?\n- Do you think all cars will be electric one day?',
            sampleAnswer: `Here are sample answers for the Part 3 discussion.

**Driving a car**

**1. How interested are young people in your country in learning to drive?**
"In my country, learning to drive is still seen as a major rite of passage for young people. It represents freedom and independence. So, yes, most young people are very keen to learn as soon as they turn 17, which is the legal age to start. For those living outside of big cities with good public transport, having a car is almost a necessity for socialising and getting to work."

**2. What are the differences between driving in the countryside and driving in the city?**
"The differences are huge. City driving is characterised by heavy traffic, complex junctions, and a constant need to be aware of pedestrians, cyclists, and buses. It can be very stressful. In contrast, countryside driving usually involves more open roads, higher speeds, and less traffic, but you have different hazards to consider, like sharp bends, narrow lanes, and sometimes animals on the road."

**3. Do you consider most drivers where you live to be good drivers?**
"That's a difficult question. I think 'good' is subjective. Most drivers are competent and follow the rules. However, you do see a lot of impatience on the roads, especially during rush hour—things like tailgating or not using indicators. So, while most are safe, I wouldn't say all of them are particularly considerate drivers."

---

**Electric cars**

**4. How popular are electric cars in your country?**
"They are becoming increasingly popular. You see a lot more of them on the roads now than you did just a few years ago. The government has been offering incentives, and the charging infrastructure is slowly improving. However, the high initial cost is still a major barrier for many people, so they're not yet as common as petrol or diesel cars."

**5. In what ways could more people be persuaded to buy electric cars?**
"I think the main things would be to lower the purchase price, perhaps through more significant government grants, and to rapidly expand the network of public charging points, especially in residential areas and at workplaces. Making charging as easy and convenient as filling up with petrol is key. Also, more education about the long-term cost savings on fuel and maintenance could help."

**6. Do you think all cars will be electric one day?**
"Yes, I believe so. With growing concerns about climate change and the finite nature of fossil fuels, the shift seems inevitable. Many governments have already set deadlines to phase out petrol and diesel cars. As battery technology improves and costs come down, I think electric will become the standard for personal vehicles within the next few decades."`
        }]
      }
    ],
  },
];
