import { Book, Lesson, QuestionType, Section } from '../types';
import { ielts18Test2Lessons } from './book18-2';
import { ielts18Test3Lessons } from './book18-3';
import { ielts18Test4Lessons } from './book18-4';

const ielts18ReadingPassage1 = `In Paris, urban farmers are trying a soil-free approach to agriculture that uses less space and fewer resources. Could it help cities face the threats to our food supplies?

On top of a striking new exhibition hall in southern Paris, the world’s largest urban rooftop farm has started to bear fruit. Strawberries that are small, intensely flavoured and resplendently red sprout abundantly from large plastic tubes. Peer inside and you see the tubes are completely hollow, the roots of dozens of strawberry plants dangling down inside them. From identical vertical tubes nearby burst row upon row of lettuces, near those are aromatic herbs such as basil, sage and peppermint. Opposite, in narrow, horizontal trays packed not with soil but with coconut fibre, grow cherry tomatoes, shiny aubergines and brightly coloured chards.

Pascal Hardy, an engineer and sustainable development consultant, began experimenting with vertical farming and aeroponic growing towers – as the soil-free plastic tubes are known – on his Paris apartment block roof five years ago. The urban rooftop space above the exhibition hall is somewhat bigger: 14,000 square metres and almost exactly the size of a couple of football pitches. Already, the team of young urban farmers who tend it have picked, in one day, 3,000 lettuces and 150 punnets of strawberries. When the farm is in production, 20 staff will harvest up to 1,000 kg of perhaps 35 different varieties of fruit and vegetables, every day. ‘We’re not ever, obviously, going to feed the whole city this way,’ cautions Hardy. ‘In the urban environment you’re working with very significant practical constraints, clearly, on what you can do and where. But if enough unused space can be developed like this, there’s no reason why you shouldn’t eventually target maybe between 5% and 10% of consumption.’

Perhaps most significantly, however, this is a real-life showcase for the work of Hardy’s flourishing urban agriculture consultancy, Agripolis, which is currently fielding enquiries from around the world to design, build and equip a new breed of soil-free inner-city farm. ‘The method’s advantages are many,’ he says. ‘First, I don’t much like the fact that most of the fruit and vegetables we eat have been treated with something like 17 different pesticides, or that the intensive farming techniques that produced them are such huge generators of greenhouse gases. I don’t much like the fact, either, that they’ve travelled an average of 2,000 refrigerated kilometres to my plate, that their quality is so poor, because the varieties are selected for their capacity to withstand such substantial journeys, or that 80% of the price I pay goes to wholesalers and transport companies, not the producers.’

Produce grown using this soil-free method, on the other hand – which relies solely on a small quantity of water, enriched with organic nutrients, pumped around a closed circuit of pipes, towers and trays – is ‘produced up here, and sold locally, just down there. It barely travels at all,’ Hardy says. ‘You can select crop varieties for their flavour, not their resistance to the transport and storage chain, and you can pick them when they’re really at their best, and not before.’ No soil is exhausted, and the water that gently showers the plants’ roots every 12 minutes is recycled, so the method uses 90% less water than a classic intensive farm for the same yield.

Urban farming is not, of course, a new phenomenon. Inner-city agriculture is booming from Shanghai to Detroit and Tokyo to Bangkok. Strawberries are being grown in disused shipping containers, mushrooms in underground carparks. Aeroponic farming, he says, is ‘virtuous’. The equipment weighs little, can be installed on almost any flat surface and is cheap to buy: roughly €100 to €150 per square metre. It is cheap to run, too, consuming a tiny fraction of the electricity used by some techniques.

Produce grown this way typically sells at prices that, while generally higher than those of classic intensive agriculture, are lower than soil-based organic growers. There are limits to what farmers can grow this way, of course, and much of the produce is suited to the summer months. ‘Root vegetables we cannot do, at least not yet,’ he says. ‘Radishes are OK, but carrots, potatoes, that kind of thing – the roots are simply too long. Fruit trees are obviously not an option. And beans tend to take up a lot of space for not much return.’ Nevertheless, urban farming of the kind being practised in Paris is one part of a bigger and fast-changing picture that is bringing food production closer to our lives.`;

const ielts18ReadingPassage2 = `How managing low-quality wood (also known as low-use wood) for bioenergy can encourage sustainable forest management

A. A tree’s ‘value’ depends on several factors including its species, size, form, condition, quality, function, and accessibility, and depends on the management goals for a given forest. The same tree can be valued very differently by each person who looks at it. A large, straight black cherry tree has high value as timber to be cut into logs or made into furniture, but for a landowner more interested in wildlife habitat, the real value of that stem (or trunk) may be the food it provides to animals. Likewise, if the tree suffers from black knot disease, its value for timber decreases, but to a woodworker interested in making bowls, it brings an opportunity for a unique and beautiful piece of art.

B. In the past, Pennsylvania landowners were solely interested in the value of their trees as high-quality timber. The norm was to remove the stems of highest quality and leave behind poorly formed trees that were not as well suited to the site where they grew. This practice, called ‘high-grading’, has left a legacy of ‘low-use wood’ in the forests. Some people even call these ‘junk forests’, and they are abundant in Pennsylvania. These trees have lower economic value for traditional timber markets, compete for growth with higher-value trees, shade out desirable regeneration and decrease the health of a stand* leaving it more vulnerable to poor weather and disease. Management that specifically targets managing low-use wood can help landowners manage these forest health issues, and wood energy markets can help promote this.

C. Wood energy markets can accept less expensive wood material of lower quality than would be suitable for traditional timber markets. Most wood used for energy in Pennsylvania is used to produce heat or electricity through combustion. Many schools and hospitals use wood boiler systems to heat and power their facilities, many homes are primarily heated with wood, and some coal plants incorporate their coal streams to produce electricity. Wood can also be gasified for electrical generation and can even be made into liquid fuels like ethanol and gasoline for lorries and cars. All these products are made primarily from low-use wood. Several tree- and plant-cutting approaches, which could greatly improve the long-term quality of a forest, focus strongly on the use of wood for those markets.

D. One such approach is called a Timber Stand Improvement (TSI) Cut. In a TSI Cut, really poor-quality tree and plant material is cut down to allow more space, light, and other resources to the highest-valued stems that remain. Removing invasive plants might be another primary goal of a TSI Cut. The stems that are left behind might then grow in size and develop more foliage and larger crowns or tops that produce more coverage for wildlife, they have a better chance to regenerate in a less crowded environment. TSI Cuts can be tailored to one farmer’s specific management goals for his or her land.

E. Another approach that might yield a high amount of low-use wood is a Salvage Cut. With the many pests and pathogens visiting forests including hemlock woolly adelgid, Asian longhorned beetle, emerald ash borer, and gypsy moth, to name just a few, it is important to remember that those working in the forests can help ease these issues through cutting procedures. These types of cut reduce the number of sick trees and seek to manage the future spread of a pest problem. They leave vigorous trees that have stayed healthy enough to survive the outbreak.

F. A Shelterwood Cut, which only takes place in a mature forest that has already been thinned several times, involves removing all the mature trees when other seedlings have become established. This then allows the forester to decide which tree species are regenerated. It leaves a young forest where all trees are at a similar point in their growth. It can also be used to develop a two-tier forest so that there are two harvests and the money that comes in is spread out over a decade or more.

G. Thinnings and dense and dead wood removal for fire prevention also center on the production of low-use wood. However, it is important to remember that some retention of what many would classify as low-use wood is very important. The tops of trees that have been cut down should be left on the site so that their nutrients cycle back into the soil. In addition, trees with many cavities are extremely important habitats for insect predators like woodpeckers, bats and small mammals. They help control problem insects and increase the health and resilience of the forest. It is also important to remember that not all small trees are low-use. For example, many species like hawthorn provide food for wildlife. Finally, rare species of trees in a forest should also stay behind as they add to its structural diversity.`;

const ielts18ReadingPassage3 = `Satellites, rocket shards and collision debris are creating major traffic risks in orbit around the planet. Researchers are working to reduce these threats

A. Last year, commercial companies, military and civil departments and amateurs sent more than 400 satellites into orbit, over four times the yearly average in the previous decade. Numbers could rise even more sharply if leading space companies follow through on plans to deploy hundreds to thousands of large constellations of satellites to space in the next few years. All that traffic can lead to disaster. Ten years ago, a US commercial Iridium satellite smashed into an inactive Russian communications satellite called Cosmos-2251, creating thousands of new pieces of space shrapnel that now threaten other satellites in low Earth orbit – the zone stretching up to 2,000 kilometres in altitude. Altogether, there are roughly 20,000 human-made objects in orbit, from working satellites to small rocket pieces. And every collision creates more debris, increasing the chances of further impacts.

B. Concern about space junk goes back to the beginning of the satellite era, but the number of objects in orbit is rising so rapidly that researchers are investigating new ways of attacking the problem. Several teams are trying to improve methods for assessing what is in orbit, so that satellite operators can work more efficiently to move a massive data set that includes the best possible information on where everything is in orbit. Others are developing taxonomies of space debris – working on measuring properties such as the shape and size of an object, so that satellite operators know how much to worry about what’s coming their way. The alternative, many say, is unthinkable. Just a few uncontrolled space crashes could generate enough debris to set off a runaway cascade of fragments, rendering near-Earth space unusable. ‘If we go on like this, we will reach a point of no return,’ says Carolin Frueh, an astrodynamical researcher at Purdue University in West Lafayette, Indiana.

C. Even as our ability to monitor space objects increases, so too does the total number of items in orbit. That means companies, governments and other players in space are collaborating to develop international guidelines on space sustainability. Those include inactivating satellites at the end of their useful life by venting pressurised materials or leftover fuel that might lead to explosions. The intergovernmental groups also advise lowering satellites deep enough into the atmosphere that they will burn up or disintegrate within 25 years. But so far, only about half of all missions have abided by this 25-year goal, says Holger Krag, head of the European Space Agency’s space-debris office in Darmstadt, Germany. Operators of the planned large constellations of satellites say they will be responsible stewards in space. But Krag worries that problems could increase, despite their best intentions. ‘What happens to those that go bankrupt?’ he asks. ‘They are probably not going to spend money to remove their satellites from space.’

D. In theory, given the vastness of space, satellite operators should have plenty of room for all these missions to fly safely without ever nearing another object. So some scientists are tackling the problem of space junk by trying to find out where all the debris is to a high degree of precision. That would alleviate the need for many of the unnecessary manoeuvres that are carried out to avoid potential collisions. ‘If you knew precisely where everything was, you would almost never have a problem,’ says Marlon Sorge, a space-debris specialist at the Aerospace Corporation in El Segundo, California.

E. The field is called space traffic management, because it’s similar to managing traffic on the roads or in the air. Think about a busy day at an airport, says Moriba Jah, an astrodynamicist at the University of Texas at Austin; planes line up in the sky, landing and taking off in a carefully choreographed routine. Air-traffic controllers know the location of the planes down to one metre in accuracy. The same can’t be said for space debris. Not all objects in orbit are known, and even those included in databases are not tracked consistently.

F. An additional problem is that there is no authoritative catalogue that accurately lists the orbits of all known space debris. Jah illustrates this with a web-based database that he has developed. It draws on several sources, such as catalogues maintained by the US and Russian governments, to visualise where objects are in space. When he types in an identifier for a particular space object, the database draws a purple line to designate its orbit. Only this doesn’t quite work for a number of objects, such as a Russian rocket body designated in the database as object 32280. When Jah enters that number, the database draws two purple lines: the US and Russian sources contain two completely different orbits for the same object. Jah says that it is almost impossible to tell which is correct, unless a third source of information made it possible to cross-correlate.

Jah describes himself as a space environmentalist: ‘I want to make a space a place that is safe to operate, that is free and useful for generations to come.’ Until that happens, he argues, the space community will continue devolving into a tragedy in which all spaceflight operators are polluting a common resource.`;

const ielts18Test1Lessons: Lesson[] = [
  // Test 1
  {
    id: 'b18-t1-l0',
    title: 'Test 1: Listening P1-2',
    section: Section.LISTENING,
    parts: [
      { // Part 1
        questions: [
          { id: 'b18t1lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t1-p1.mp3', questionText: 'Postcode: 1 ___', correctAnswers: ['DW30 7YZ'], transcript: "So next your postcode, please. It’s DW30 7YZ.", transcriptHighlight: 'DW30 7YZ' },
          { id: 'b18t1lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t1-p1.mp3', questionText: 'Date of bus journey: 24th ___', correctAnswers: ['April'], transcript: "And that was today. It’s the 24th of April, isn’t it? Isn’t it the 25th? No, actually, you’re right.", transcriptHighlight: "24th of April" },
          { id: 'b18t1lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t1-p1.mp3', questionText: 'Reason for trip: shopping and visit to the ___', correctAnswers: ['dentist'], transcript: "Yes, I did some shopping but the main reason I came here was to go to the dentist.", transcriptHighlight: "dentist" },
          { id: 'b18t1lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t1-p1.mp3', questionText: 'Travelled by bus because cost of ___ too high', correctAnswers: ['parking'], transcript: "I stopped driving in ages ago because parking was so difficult to find and it costs so much.", transcriptHighlight: "parking" },
          { id: 'b18t1lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t1-p1.mp3', questionText: 'Got on bus at ___ Street', correctAnswers: ['Claxby'], transcript: "At the bus stop on Claxby Street. Is that C-L-A-X-B-Y? That’s right.", transcriptHighlight: "Claxby" },
          { id: 'b18t1lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t1-p1.mp3', questionText: 'Complaints about bus service: bus today was ___', correctAnswers: ['late'], transcript: "Well, as I said, it’s very convenient and quick when it’s on time, but this morning it was late. Only about 10 minutes, but still.", transcriptHighlight: "late" },
          { id: 'b18t1lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t1-p1.mp3', questionText: '- frequency of buses in the ___', correctAnswers: ['evening'], transcript: "I mainly use the bus during the day, but any time I’ve been in town in the evening – for dinner or at the cinema – I’ve noticed you have to wait a long time for a bus – there aren’t that many.", transcriptHighlight: "evening" },
          { id: 'b18t1lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t1-p1.mp3', questionText: 'Goes to the ___ by car', correctAnswers: ['supermarket'], transcript: "OK, thanks. So now I’d like to ask you about your car use. Well, I have got a car but I don’t use it that often. Mainly just to go to the supermarket.", transcriptHighlight: "supermarket" },
          { id: 'b18t1lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t1-p1.mp3', questionText: 'Dislikes travelling by bike in the city centre because of the ___', correctAnswers: ['pollution'], transcript: "I’m not keen on cycling there because of all the pollution. But I would like to get a bike – it would be good to use it to get to work.", transcriptHighlight: "pollution" },
          { id: 'b18t1lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t1-p1.mp3', questionText: "Doesn't own a bike because of a lack of ___", correctAnswers: ['storage'], transcript: "So why haven’t you got one now? Well, I live in a flat – on the second floor and it doesn’t have any storage – so we’d have to leave it in the hall outside the flat.", transcriptHighlight: "storage" },
        ],
      },
      { // Part 2
        questions: [
          { id: 'b18t1lq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t1-p2.mp3', questionText: 'Why does the speaker apologise about the seats?', options: ['A They are too small.', 'B There are not enough of them.', 'C Some of them are very close together.'], correctAnswers: ['C Some of them are very close together.'], transcript: "I hope you’re all comfortable – we’ve brought in extra seats so that no one has to stand, but it does mean that the people at the back of the room may be a bit squashed.", transcriptHighlight: "people at the back of the room may be a bit squashed" },
          { id: 'b18t1lq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t1-p2.mp3', questionText: 'What does the speaker say about the age of volunteers?', options: ['A The age of volunteers is less important than other factors.', 'B Young volunteers are less reliable than older ones.', 'C Most volunteers are about 60 years old.'], correctAnswers: ['A The age of volunteers is less important than other factors.'], transcript: "You can be as young as 16 or you can be 60 or over; it all depends on what type of voluntary work you want to do. Other considerations such as reliability are crucial in voluntary work and age isn’t related to these, in our experience.", transcriptHighlight: "age isn’t related to these" },
          { id: 'b18t1lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t1-p2.mp3', questionText: 'What does the speaker say about training?', options: ['A It is continuous.', 'B It is conducted by a manager.', 'C It takes place online.'], correctAnswers: ['A It is continuous.'], transcript: "Another question we get asked relates to training. Well, there’s plenty of that and it’s all face-to-face. What’s more, training doesn’t end when you start working for us – it takes place before, during and after periods of work.", transcriptHighlight: "training doesn’t end when you start working for us" },
          { id: 'b18t1lq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO issues does the speaker ask the audience to consider before they apply to be volunteers?', maxSelections: 2, audioUrl: 'ielts-18/t1-p2.mp3', questionText: 'Choose TWO letters, A-E.', options: ['A their financial situation', 'B their level of commitment', 'C their work experience', 'D their ambition', 'E their availability'], correctAnswers: ['B their level of commitment', 'E their availability'], transcript: "it is critical that you have enough hours in the day for whatever role we agree is suitable for you ... Some of our most loyal volunteers earn very little themselves but still give their full energy to the work they do with us. What we value is dedication.", transcriptHighlight: "enough hours in the day... What we value is dedication" },
          { id: 'b18t1lq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Helpful things volunteers might offer. Choose FIVE answers from the box and write the correct letter, A-G.', audioUrl: 'ielts-18/t1-p2.mp3', questionText: '16 Fundraising', options: ['A experience on stage', 'B original, new ideas', 'C parenting skills', 'D an understanding of food and diet', 'E retail experience', 'F a good memory', 'G a good level of fitness'], correctAnswers: ['B original, new ideas'], transcript: "You may wish to help us raise money. If you have the creativity to come up with an imaginative or novel way of fundraising, we’d be delighted", transcriptHighlight: "creativity to come up with an imaginative or novel way" },
          { id: 'b18t1lq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Helpful things volunteers might offer. Choose FIVE answers from the box and write the correct letter, A-G.', audioUrl: 'ielts-18/t1-p2.mp3', questionText: '17 Litter collection', options: ['A experience on stage', 'B original, new ideas', 'C parenting skills', 'D an understanding of food and diet', 'E retail experience', 'F a good memory', 'G a good level of fitness'], correctAnswers: ['G a good level of fitness'], transcript: "One outdoor activity that we need volunteers for is litter collection and for this it’s useful if you can walk for long periods, sometimes uphill.", transcriptHighlight: "walk for long periods, sometimes uphill" },
          { id: 'b18t1lq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Helpful things volunteers might offer. Choose FIVE answers from the box and write the correct letter, A-G.', audioUrl: 'ielts-18/t1-p2.mp3', questionText: '18 ‘Playmates’', options: ['A experience on stage', 'B original, new ideas', 'C parenting skills', 'D an understanding of food and diet', 'E retail experience', 'F a good memory', 'G a good level of fitness'], correctAnswers: ['D an understanding of food and diet'], transcript: "If you enjoy working with children, we have three vacancies for what are called ‘playmates’. These volunteers help children learn about staying healthy through a range of out-of-school activities. You don’t need to have children yourself, but it’s good if you know something about nutrition", transcriptHighlight: "know something about nutrition" },
          { id: 'b18t1lq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Helpful things volunteers might offer. Choose FIVE answers from the box and write the correct letter, A-G.', audioUrl: 'ielts-18/t1-p2.mp3', questionText: '19 Story club', options: ['A experience on stage', 'B original, new ideas', 'C parenting skills', 'D an understanding of food and diet', 'E retail experience', 'F a good memory', 'G a good level of fitness'], correctAnswers: ['A experience on stage'], transcript: "If that doesn’t appeal to you, maybe you would be interested in helping out at our story club for disabled children, especially if you have done some acting.", transcriptHighlight: "done some acting" },
          { id: 'b18t1lq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Helpful things volunteers might offer. Choose FIVE answers from the box and write the correct letter, A-G.', audioUrl: 'ielts-18/t1-p2.mp3', questionText: '20 First aid', options: ['A experience on stage', 'B original, new ideas', 'C parenting skills', 'D an understanding of food and diet', 'E retail experience', 'F a good memory', 'G a good level of fitness'], correctAnswers: ['F a good memory'], transcript: "Volunteers who join this group can end up teaching others in vulnerable groups who may be at risk of injury. Initially, though, your priority will be to take in a lot of information and not forget any important steps or details.", transcriptHighlight: "not forget any important steps or details" },
        ],
      }
    ]
  },
  {
    id: 'b18-t1-l1',
    title: 'Test 1: Listening P3-4',
    section: Section.LISTENING,
    parts: [
      { // Part 3
        questions: [
          { id: 'b18t1lq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t1-p3.mp3', questionText: 'What problem did Chantal have at the start of the talk?', options: ['A Her view of the speaker was blocked.', 'B She was unable to find an empty seat.', 'C The students next to her were talking.'], correctAnswers: ['A Her view of the speaker was blocked.'], transcript: "it wasn’t that I went early so that I’d get a seat and not have to stand, but then this guy sat right in front of me and he was so tall! It’s hard to see through people’s heads, isn’t it?", transcriptHighlight: "this guy sat right in front of me and he was so tall" },
          { id: 'b18t1lq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t1-p3.mp3', questionText: 'What were Hugo and Chantal surprised to hear about the job market?', options: ['A It has become more competitive than it used to be.', 'B There is more variety in it than they had realised.', 'C Some areas of it are more exciting than others.'], correctAnswers: ['B There is more variety in it than they had realised.'], transcript: "Yeah, but it looks like there’s a whole range of ... areas of work that we hadn’t even thought of – like fashion journalism, for instance.", transcriptHighlight: "whole range of ... areas of work that we hadn’t even thought of" },
          { id: 'b18t1lq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t1-p3.mp3', questionText: 'Hugo and Chantal agree that the speaker’s message was', options: ['A unfair to them at times.', 'B hard for them to follow.', 'C critical of the industry.'], correctAnswers: ['A unfair to them at times.'], transcript: "Perhaps she thinks students are a bit narrow-minded about the industry. It was a bit harsh, though! We know it’s a tough industry.", transcriptHighlight: "It was a bit harsh, though!" },
          { id: 'b18t1lq24', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t1-p3.mp3', questionText: 'What do Hugo and Chantal criticise about their school careers advice?', options: ['A when they received the advice', 'B how much advice was given', 'C who gave the advice'], correctAnswers: ['C who gave the advice'], transcript: "Well, we had numerous talks on careers, which was good, but none of them were very inspiring. They could have asked more people like today’s speaker to talk to us.", transcriptHighlight: "could have asked more people like today’s speaker to talk to us" },
          { id: 'b18t1lq25', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t1-p3.mp3', questionText: 'When discussing their future, Hugo and Chantal disagree on', options: ['A which is the best career in fashion.', 'B when to choose a career in fashion.', 'C why they would like a career in fashion.'], correctAnswers: ['B when to choose a career in fashion.'], transcript: "Well, I promised myself that I’d go through this course and keep an open mind till the end. But I think it’s better to pick an area of the industry now and then aim to get better and better at it.", transcriptHighlight: "better to pick an area of the industry now" },
          { id: 'b18t1lq26', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t1-p3.mp3', questionText: 'How does Hugo feel about being an unpaid assistant?', options: ['A He is realistic about the practice.', 'B He feels the practice is dishonest.', 'C He thinks others want to change the practice.'], correctAnswers: ['A He is realistic about the practice.'], transcript: "One thing’s for certain, though. That we’ll be unpaid assistants in the industry for quite a long time. I’m prepared for that, aren’t you? Actually, I’m not going to accept that view. Really? But she knows it’s the case – and everyone else says the same.", transcriptHighlight: "I’m prepared for that" },
          { id: 'b18t1lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO mistakes did the speaker admit she made in her first job?', maxSelections: 2, audioUrl: 'ielts-18/t1-p3.mp3', questionText: 'Choose TWO letters, A-E.', options: ['A being dishonest to her employer', 'B paying too much attention to how she looked', 'C expecting to become well known', 'D trying to earn a lot of money', 'E openly disliking her client'], correctAnswers: ['B paying too much attention to how she looked', 'E openly disliking her client'], transcript: "I must have felt amazing – though she said all she was looking for back then was experience, not financial reward. Mmm. And then he was so mean, telling her she was more interested in her own appearance than that! ... She obviously regretted losing the job. Well, she said she should have hidden her negative feelings about him, but she didn’t.", transcriptHighlight: "more interested in her own appearance... should have hidden her negative feelings" },
          { id: 'b18t1lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO pieces of retail information do Hugo and Chantal agree would be useful?', maxSelections: 2, audioUrl: 'ielts-18/t1-p3.mp3', questionText: 'Choose TWO letters, A-E.', options: ['A the reasons people return fashion items', 'B how much time people have to shop for clothes', 'C fashion designs people want but can’t find', 'D the best time of year for fashion buying', 'E the most popular fashion sizes'], correctAnswers: ['A the reasons people return fashion items', 'C fashion designs people want but can’t find'], transcript: "I think that’s an issue for manufacturers, not designers. However, it would be useful to know if there’s a gap in the market – you know, an item that no one’s stocking but that consumers are looking for. ... Yeah. Imagine you worked in an expensive shop and you found out the garments sold there were being returned because they ... fell apart in the wash!", transcriptHighlight: "gap in the market... garments sold there were being returned" },
        ],
      },
      { // Part 4
        questions: [
          { id: 'b18t1lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t1-p4.mp3', questionText: 'damage to 31 ___ in the park', correctAnswers: ['fences'], transcript: "Firstly, there was more competition for food, which meant that some elephants were suffering from hunger. As there was a limit on the amount of food in the national park, some elephants began looking further afield. If elephants were routinely knocking down fences around the park, which then had to be repaired at a significant cost.", transcriptHighlight: "fences" },
          { id: 'b18t1lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t1-p4.mp3', questionText: 'a suitable group of elephants from the same 32 ___ was selected', correctAnswers: ['family'], transcript: "Elephants were moved in groups of between eight and twenty, all belonging to one family.", transcriptHighlight: "family" },
          { id: 'b18t1lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t1-p4.mp3', questionText: 'vets and park staff made use of 33 ___ to help guide the elephants into an open plain', correctAnswers: ['helicopters'], transcript: "A team of vets and park rangers flew over the park in helicopters and targeted a group, which were rounded up and directed to a designated open plain.", transcriptHighlight: "helicopters" },
          { id: 'b18t1lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t1-p4.mp3', questionText: 'this process had to be completed quickly to reduce 34 ___', correctAnswers: ['stress'], transcript: "This also had to be done as quickly as possible so as to minimise the stress caused.", transcriptHighlight: "stress" },
          { id: 'b18t1lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t1-p4.mp3', questionText: 'elephants had to be turned on their 35 ___ to avoid damage to their lungs', correctAnswers: ['sides'], transcript: "To avoid the risk of suffocation, the team had to make sure none of the elephants were lying on their chests, because their lungs could be crushed in this position. So all the elephants had to be placed on their sides.", transcriptHighlight: "sides" },
          { id: 'b18t1lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t1-p4.mp3', questionText: "elephants' 36 ___ had to be monitored constantly", correctAnswers: ['breathing'], transcript: "if there were fewer than six breaths per minute, the elephant would need urgent medical attention.", transcriptHighlight: "breaths" },
          { id: 'b18t1lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t1-p4.mp3', questionText: 'data including the size of their tusks and 37 ___ was taken', correctAnswers: ['feet'], transcript: "Measurements were taken of each elephant’s tusks – elephants with large tusks would be at greater risk from poachers – and also of their feet.", transcriptHighlight: "feet" },
          { id: 'b18t1lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t1-p4.mp3', questionText: '38 ___ opportunities', correctAnswers: ['employment'], transcript: "The elephants translocated to Nkhotakota settled in very well and the project has generally been accepted to have been a huge success – and not just for the elephants. Employment prospects have improved enormously,", transcriptHighlight: "Employment" },
          { id: 'b18t1lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t1-p4.mp3', questionText: 'a reduction in the number of poachers and 39 ___', correctAnswers: ['weapons'], transcript: "In fact, many of them volunteered to give up their weapons, as they were no longer of any use to them.", transcriptHighlight: "weapons" },
          { id: 'b18t1lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t1-p4.mp3', questionText: 'an increase in 40 ___ as a contributor to GDP', correctAnswers: ['tourism'], transcript: "All this has been a big draw for tourism, which contributes five times more than the illegal wildlife trade to GDP", transcriptHighlight: "tourism" },
        ],
      }
    ]
  },
  {
    id: 'b18-t1-r2',
    title: 'Test 1: Reading P1',
    section: Section.READING,
    parts: [{
      questions: [
        { id: 'b18t1rq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER.', passage: ielts18ReadingPassage1, questionText: 'Vertical tubes are used to grow strawberries, ___ and herbs.', correctAnswers: ['lettuces'], passageHighlight: "From identical vertical tubes nearby burst row upon row of lettuces, near those are aromatic herbs", reason: "The passage lists what grows in vertical tubes: strawberries, lettuces, and herbs." },
        { id: 'b18t1rq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER.', passage: ielts18ReadingPassage1, questionText: 'There will eventually be a daily harvest of as much as ___ in weight of fruit and vegetables.', correctAnswers: ['1,000 kg', '1000 kg'], passageHighlight: "20 staff will harvest up to 1,000 kg of perhaps 35 different varieties of fruit and vegetables, every day", reason: "The passage explicitly states the daily harvest amount." },
        { id: 'b18t1rq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Choose NO MORE THAN TWO WORDS AND/OR A NUMBER.', passage: ielts18ReadingPassage1, questionText: "It may be possible that the farm's produce will account for as much as 10% of the city's ___ overall.", correctAnswers: ['consumption'], passageHighlight: "there’s no reason why you shouldn’t eventually target maybe between 5% and 10% of consumption", reason: "The text mentions the farm could target supplying 5-10% of the city's consumption." },
        { id: 'b18t1rq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1, questionText: 'Intensive farming: Growth - wide range of 4 ___ used', correctAnswers: ['pesticides'], passageHighlight: "most of the fruit and vegetables we eat have been treated with something like 17 different pesticides", reason: "The passage mentions that conventionally grown produce is treated with many pesticides." },
        { id: 'b18t1rq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1, questionText: 'Intensive farming: Selection - varieties of fruit and vegetables chosen that can survive long 5 ___', correctAnswers: ['journeys'], passageHighlight: "the varieties are selected for their capacity to withstand such substantial journeys", reason: "The passage states that varieties are selected based on their ability to withstand long journeys." },
        { id: 'b18t1rq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1, questionText: 'Intensive farming: Sale - 6 ___ receive very little of overall income', correctAnswers: ['producers'], passageHighlight: "80% of the price I pay goes to wholesalers and transport companies, not the producers", reason: "The passage states that producers do not get a large share of the income." },
        { id: 'b18t1rq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1, questionText: 'Aeroponic urban farming: Selection - produce chosen because of its 7 ___', correctAnswers: ['flavour', 'flavor'], passageHighlight: "You can select crop varieties for their flavour", reason: "In contrast to intensive farming, aeroponic farming allows selection based on flavour." },
        { id: 'b18t1rq8', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1, questionText: 'Urban farming can take place above or below ground.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "Strawberries are being grown in disused shipping containers, mushrooms in underground carparks", reason: "The passage gives examples of urban farming in shipping containers (above ground) and underground carparks (below ground)." },
        { id: 'b18t1rq9', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1, questionText: 'Some of the equipment used in aeroponic farming can be made by hand.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage describes the equipment as 'cheap to buy' but does not mention whether it can be made by hand." },
        { id: 'b18t1rq10', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1, questionText: 'Urban farming relies more on electricity than some other types of farming.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "consuming a tiny fraction of the electricity used by some techniques", reason: "The passage directly contradicts this, stating that it consumes a 'tiny fraction of the electricity' used by other methods." },
        { id: 'b18t1rq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1, questionText: 'Fruit and vegetables grown on an aeroponic urban farm are cheaper than traditionally grown organic produce.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "prices that... are lower than soil-based organic growers", reason: "The passage states that prices are 'lower than soil-based organic growers'." },
        { id: 'b18t1rq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1, questionText: 'Most produce can be grown on an aeroponic urban farm at any time of the year.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "much of the produce is suited to the summer months", reason: "The passage contradicts this, stating that 'much of the produce is suited to the summer months'." },
        { id: 'b18t1rq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1, questionText: 'Beans take longer to grow on an urban farm than other vegetables.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage says beans 'take up a lot of space for not much return' but does not compare their growing time to other vegetables." },
      ]
    }]
  },
  {
    id: 'b18-t1-r3',
    title: 'Test 1: Reading P2-3',
    section: Section.READING,
    parts: [
      { // Reading Passage 2
        questions: [
          { id: 'b18t1rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A-G.', passage: ielts18ReadingPassage2, questionText: '14 bad outcomes for a forest when people focus only on its financial reward', options: ['A','B','C','D','E','F','G'], correctAnswers: ['B'], passageHighlight: "This practice, called ‘high-grading’, has left a legacy of ‘low-use wood’ in the forests... decrease the health of a stand" },
          { id: 'b18t1rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A-G.', passage: ielts18ReadingPassage2, questionText: '15 reference to the aspects of any tree that help to contribute to its worth', options: ['A','B','C','D','E','F','G'], correctAnswers: ['A'], passageHighlight: "A tree’s ‘value’ depends on several factors including its species, size, form, condition, quality, function, and accessibility" },
          { id: 'b18t1rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A-G.', passage: ielts18ReadingPassage2, questionText: '16 mention of the potential use of wood to help run vehicles', options: ['A','B','C','D','E','F','G'], correctAnswers: ['C'], passageHighlight: "made into liquid fuels like ethanol and gasoline for lorries and cars" },
          { id: 'b18t1rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A-G.', passage: ielts18ReadingPassage2, questionText: '17 examples of insects that attack trees', options: ['A','B','C','D','E','F','G'], correctAnswers: ['E'], passageHighlight: "hemlock woolly adelgid, Asian longhorned beetle, emerald ash borer, and gypsy moth" },
          { id: 'b18t1rq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A-G.', passage: ielts18ReadingPassage2, questionText: '18 an alternative name for trees that produce low-use wood', options: ['A','B','C','D','E','F','G'], correctAnswers: ['B'], passageHighlight: "Some people even call these ‘junk forests’" },
          { id: 'b18t1rq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each purpose with the correct timber cut, A, B or C.', passage: ielts18ReadingPassage2, questionText: '19 to remove trees that are diseased', options: ['A a TSI Cut', 'B a Salvage Cut', 'C a Shelterwood Cut'], correctAnswers: ['B a Salvage Cut'], passageHighlight: "reduce the number of sick trees and seek to manage the future spread of a pest problem" },
          { id: 'b18t1rq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each purpose with the correct timber cut, A, B or C.', passage: ielts18ReadingPassage2, questionText: '20 to generate income across a number of years', options: ['A a TSI Cut', 'B a Salvage Cut', 'C a Shelterwood Cut'], correctAnswers: ['C a Shelterwood Cut'], passageHighlight: "develop a two-tier forest so that there are two harvests and the money that comes in is spread out over a decade or more" },
          { id: 'b18t1rq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each purpose with the correct timber cut, A, B or C.', passage: ielts18ReadingPassage2, questionText: '21 to create a forest whose trees are close in age', options: ['A a TSI Cut', 'B a Salvage Cut', 'C a Shelterwood Cut'], correctAnswers: ['C a Shelterwood Cut'], passageHighlight: "It leaves a young forest where all trees are at a similar point in their growth." },
          { id: 'b18t1rq22', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage2, questionText: '22 Some dead wood is removed to avoid the possibility of ___.', correctAnswers: ['fire'], passageHighlight: "Thinnings and dense and dead wood removal for fire prevention" },
          { id: 'b18t1rq23', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage2, questionText: '23 The ___ from the tops of cut trees can help improve soil quality.', correctAnswers: ['nutrients'], passageHighlight: "The tops of trees that have been cut down should be left on the site so that their nutrients cycle back into the soil." },
          { id: 'b18t1rq24', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage2, questionText: '24 Some damaged trees should be left, as their ___ provide habitats for a range of creatures.', correctAnswers: ['cavities'], passageHighlight: "trees with many cavities are extremely important habitats for insect predators" },
          { id: 'b18t1rq25', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage2, questionText: '25 Some trees that are small, such as ___, are a source of food for animals and insects.', correctAnswers: ['hawthorn'], passageHighlight: "many species like hawthorn provide food for wildlife" },
          { id: 'b18t1rq26', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage2, questionText: '26 Any trees that are ___ should be left to grow, as they add to the variety of species in the forest.', correctAnswers: ['rare'], passageHighlight: "rare species of trees in a forest should also stay behind" },
        ]
      },
      { // Reading Passage 3
        questions: [
          { id: 'b18t1rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which section contains the following information? Write the correct letter, A-F.', passage: ielts18ReadingPassage3, questionText: '27 a reference to the cooperation that takes place to try and minimise risk', options: ['A','B','C','D','E','F'], correctAnswers: ['C'], passageHighlight: "companies, governments and other players in space are collaborating to develop international guidelines" },
          { id: 'b18t1rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which section contains the following information? Write the correct letter, A-F.', passage: ielts18ReadingPassage3, questionText: "28 an explanation of a person's aims", options: ['A','B','C','D','E','F'], correctAnswers: ['F'], passageHighlight: "Jah describes himself as a space environmentalist: ‘I want to make a space a place that is safe to operate...’" },
          { id: 'b18t1rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which section contains the following information? Write the correct letter, A-F.', passage: ielts18ReadingPassage3, questionText: '29 a description of a major collision that occurred in space', options: ['A','B','C','D','E','F'], correctAnswers: ['A'], passageHighlight: "a US commercial Iridium satellite smashed into an inactive Russian communications satellite" },
          { id: 'b18t1rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which section contains the following information? Write the correct letter, A-F.', passage: ielts18ReadingPassage3, questionText: '30 a comparison between tracking objects in space and the efficiency of a transportation system', options: ['A','B','C','D','E','F'], correctAnswers: ['E'], passageHighlight: "similar to managing traffic on the roads or in the air. Think about a busy day at an airport" },
          { id: 'b18t1rq31', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which section contains the following information? Write the correct letter, A-F.', passage: ielts18ReadingPassage3, questionText: '31 a reference to efforts to classify space junk', options: ['A','B','C','D','E','F'], correctAnswers: ['B'], passageHighlight: "developing taxonomies of space debris – working on measuring properties such as the shape and size of an object" },
          { id: 'b18t1rq32', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3, questionText: 'The committee gives advice on how the 32 ___ of space can be achieved.', correctAnswers: ['sustainability'], passageHighlight: "collaborating to develop international guidelines on space sustainability" },
          { id: 'b18t1rq33', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3, questionText: 'The committee advises that when satellites are no longer active, any unused 33 ___ or pressurised material that could cause', correctAnswers: ['fuel'], passageHighlight: "venting pressurised materials or leftover fuel that might lead to explosions" },
          { id: 'b18t1rq34', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3, questionText: '34 ___ should be removed.', correctAnswers: ['explosions'], passageHighlight: "venting pressurised materials or leftover fuel that might lead to explosions" },
          { id: 'b18t1rq35', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3, questionText: 'Holger Krag points out that the operators that become 35 ___ are unlikely to prioritise removing their satellites from space.', correctAnswers: ['bankrupt'], passageHighlight: "What happens to those that go bankrupt?" },
          { id: 'b18t1rq36', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct person, A, B, C or D.', passage: ielts18ReadingPassage3, questionText: '36 Knowing the exact location of space junk would help prevent any possible danger.', options: ['A Carolin Frueh', 'B Holger Krag', 'C Marlon Sorge', 'D Moriba Jah'], correctAnswers: ['C Marlon Sorge'], passageHighlight: "If you knew precisely where everything was, you would almost never have a problem" },
          { id: 'b18t1rq37', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct person, A, B, C or D.', passage: ielts18ReadingPassage3, questionText: '37 Space should be available to everyone and should be preserved for the future.', options: ['A Carolin Frueh', 'B Holger Krag', 'C Marlon Sorge', 'D Moriba Jah'], correctAnswers: ['D Moriba Jah'], passageHighlight: "I want to make a space a place that is safe to operate, that is free and useful for generations to come." },
          { id: 'b18t1rq38', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct person, A, B, C or D.', passage: ielts18ReadingPassage3, questionText: '38 A recommendation regarding satellites is widely ignored.', options: ['A Carolin Frueh', 'B Holger Krag', 'C Marlon Sorge', 'D Moriba Jah'], correctAnswers: ['B Holger Krag'], passageHighlight: "so far, only about half of all missions have abided by this 25-year goal, says Holger Krag" },
          { id: 'b18t1rq39', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct person, A, B, C or D.', passage: ielts18ReadingPassage3, questionText: '39 There is conflicting information about where some satellites are in space.', options: ['A Carolin Frueh', 'B Holger Krag', 'C Marlon Sorge', 'D Moriba Jah'], correctAnswers: ['D Moriba Jah'], passageHighlight: "the US and Russian sources contain two completely different orbits for the same object" },
          { id: 'b18t1rq40', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct person, A, B, C or D.', passage: ielts18ReadingPassage3, questionText: '40 There is a risk we will not be able to undo the damage that occurs in space.', options: ['A Carolin Frueh', 'B Holger Krag', 'C Marlon Sorge', 'D Moriba Jah'], correctAnswers: ['A Carolin Frueh'], passageHighlight: "If we go on like this, we will reach a point of no return" },
        ]
      }
    ]
  },
  {
    id: 'b18-t1-w4',
    title: 'Test 1: Writing T1-2',
    section: Section.WRITING,
    parts: [
      {
        questions: [{
          id: 'b18t1wq1',
          type: QuestionType.WRITING_TASK,
          prompt: 'You should spend about 20 minutes on this task.',
          imageUrl: 'ielts-18/ielts-18-t1-w1-graph.png',
          task: "The graph below gives information about the percentage of the population in four Asian countries living in cities from 1970 to 2020, with predictions for 2030 and 2040.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\nWrite at least 150 words.",
          sampleAnswer: "The line graph illustrates the proportion of urban citizens in the Philippines, Malaysia, Thailand and Indonesia between 1970 and 2020, with the expected population in 2030 and 2040.\n\nOverall, it can be easily seen that all four countries has a dramatic rise in population, starting at the lowest point in 1970 and being projected to reach the peak in 2040. Malaysia and Indonesia saw a slightly rise in population, respectively from 30 to about 45 and around 12 to over 20 percent from 1970 to 1990. After that, both countries has climbed rapidly until now before being predicted to continue increasing for the next 20 years.\n\nAfter almost remaining in the 70s, Philippines percentage increased dramatically to reach about 47 percent on 1990 and dropped to 40% in 2010. Then, this country faced slightly rise in 2020. Meanwhile, Thailand reached approximate 30% in 1990 and saw not much changes until 2020. Both two countries are projected to increase in population in 2030 and 2040.",
          sampleAnswerBand: 6.0,
          examinerComment: "This response covers the requirements of the task. There is an overview in the second paragraph and key features are presented for each country, with main trends identified. Ideas are grouped together with a clear overall progression: countries with a similar trend are presented in the same paragraph, first Malaysia and Indonesia, then Thailand and the Philippines. There is some effective use of linkers [Overall | After that | Meanwhile] and other cohesive devices [respectively | this country], but a few errors remain [Both two].\n\nVocabulary includes a range, with some less common examples [proportion | expected population | dramatic rise | projected to reach the peak]. There are some errors [slightly / slight | almost remaining | approximate / approximately], which do not impede communication. The mix of grammatical structures is good, with some complex sentence forms [being predicted to continue increasing for the next 20 years]. Some errors remain, but they rarely reduce communication. To improve the Band Score for this response, there could be more detail on the similarity of the trends on the graph, more detail on data from 1990 onwards and fewer errors in spelling and grammar. However, this is a good response that does address the requirements of the task."
        }]
      },
      {
        questions: [{
          id: 'b18t1wq2',
          type: QuestionType.WRITING_TASK,
          prompt: "You should spend about 40 minutes on this task. Write about the following topic:",
          task: "The most important aim of science should be to improve people's lives.\n\nTo what extent do you agree or disagree with this statement?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.",
          sampleAnswer: "This model has been prepared by an examiner as an example of a very good answer. Scientific developments are occurring at a great rate but some of them do not seem to be of help to people. In fact, sometimes scientific innovations are regretted by those who invented them. This essay will argue that science should never harm people but scientists should aim to further their understanding as much as to improve people’s lives.\n\nOn one hand, there is a strong argument that the public good should be the top priority for scientists. They are the ones who have the potential to make discoveries and invent things that can change the world. Electricity, modern medicine, telecommunications and the internet are just some of the scientific innovations that have changed lives for the better.\n\nOn the other hand, sometimes scientists do research just in the hope of adding to their knowledge. While they should make absolutely sure that their experiments do no harm, they may not know until they have finished how their findings will be used and whether they will improve people’s lives. The scientist Nobel invented dynamite to help with mining, not knowing that it would one day be used in weapons, and the scientist who discovered the life-saving drug penicillin did so quite by chance.\n\nOverall, it seems that science should improve the lives of people and that ought to be one of its aims. However, knowledge and discovery are aims in themselves and are just as important for scientists. Sometimes scientists do not know how their scientific breakthroughs will be used until their work is done.",
        }]
      }
    ],
  },
  {
    id: 'b18-t1-s5',
    title: 'Test 1: Speaking P1-3',
    section: Section.SPEAKING,
    parts: [
      {
        questions: [{
          id: 'b18t1sq1',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 1: Example',
          question: 'Paying bills\n\n- What kinds of bills do you have to pay?\n- How do you usually pay your bills – in cash or by another method? [Why?]\n- Have you ever forgotten to pay a bill? [Why/Why not?]\n- Is there anything you could do to make your bills cheaper? [Why/Why not?]',
          sampleAnswer: `**1. What kinds of bills do you have to pay?**\n\n"Well, the usual ones really. I have to pay for rent, electricity, gas, and water, which are the main household bills. On top of that, there are bills for my mobile phone and internet connection. They all add up quite a bit each month."\n\n**2. How do you usually pay your bills – in cash or by another method?**\n\n"I almost always pay by another method, usually through direct debit from my bank account. I find it much more convenient because it's automatic, so I don't have to worry about remembering due dates. It's just simpler and more efficient than handling cash."\n\n**3. Have you ever forgotten to pay a bill?**\n\n"Yes, unfortunately, it has happened once or twice. A few months ago, I forgot to pay my credit card bill. It wasn't a regular bill, so I didn't have a direct debit set up. I just got busy with work and it completely slipped my mind until I got a reminder email. It was a bit embarrassing, but I paid it straight away."\n\n**4. Is there anything you could do to make your bills cheaper?**\n\n"Definitely. I could probably make my electricity bill cheaper by being more conscious of turning off lights and unplugging appliances when I'm not using them. I could also shop around for a better deal on my internet and phone plans. It just takes a bit of time and effort to research the options, but it would likely save me some money in the long run."`
        }]
      },
      {
        questions: [{
          id: 'b18t1sq2',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 2: Cue Card',
          question: 'Describe some food or drink that you learned to prepare.\nYou should say:\n- what food or drink you learned to prepare\n- when and where you learned to prepare this\n- how you learned to prepare this\n- and explain how you felt about learning to prepare this food or drink.',
          sampleAnswer: `I'd like to talk about learning to make a proper Italian carbonara. It's a pasta dish that seems simple, but getting it right is actually quite tricky.\n\nI learned how to make this a couple of years ago, right in my own kitchen. I'd always loved eating carbonara in restaurants, but my attempts at home were always disappointing – they usually ended up like scrambled eggs with pasta. So, I decided to properly learn during a quiet weekend.\n\nI learned by watching several videos from Italian chefs on YouTube. I realised the key mistakes I was making. The authentic recipe doesn't use cream; it's all about using the heat of the freshly cooked pasta to cook the egg and cheese mixture, creating a creamy sauce. I followed the steps very carefully: frying the pancetta, mixing the egg yolks with pecorino cheese and black pepper, and then combining it all off the heat.\n\nI felt a real sense of achievement when I finally got it right. The sauce was rich and creamy, not scrambled, and it tasted amazing. It was so satisfying to master a technique and be able to recreate a restaurant-quality dish at home. It made me feel much more confident in the kitchen and encouraged me to try learning other classic recipes.`
        }]
      },
      {
        questions: [{
          id: 'b18t1sq3',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 3: Discussion topics',
          question: "Young people and cooking\n- What kinds of things can children learn to cook?\n- Do you think it is important for children to learn to cook?\n- Do you think young people should learn to cook at home or at school?\n\nWorking as a chef\n- How enjoyable do you think it would be to work as a professional chef?\n- What skills does a person need to be a great chef?\n- How much influence do celebrity/TV chefs have on what ordinary people cook?",
          sampleAnswer: `**Young people and cooking**\n\n**1. What kinds of things can children learn to cook?**\n"Children can start with very simple things like making sandwiches or decorating cakes. As they get a bit older, they can learn to make scrambled eggs, simple pasta dishes, or bake cookies. The key is to start with safe, manageable tasks that build their confidence before moving on to more complex recipes that involve using the oven or sharp knives."\n\n**2. Do you think it is important for children to learn to cook?**\n"Absolutely. I think it's a fundamental life skill. Learning to cook teaches them about nutrition and how to eat healthily. It also gives them a sense of independence and responsibility. Plus, it can be a really fun and creative activity that they can share with their family."\n\n**3. Do you think young people should learn to cook at home or at school?**\n"I believe it should be a combination of both. Learning at home from parents or family members can be a wonderful bonding experience and teaches them family recipes. However, learning in school ensures that all children, regardless of their home situation, get a basic culinary education. School can provide a structured curriculum covering food hygiene and nutrition, which is very important."\n\n**Working as a chef**\n\n**4. How enjoyable do you think it would be to work as a professional chef?**\n"I think it would be a mix of being incredibly rewarding and extremely stressful. On one hand, there must be a huge amount of satisfaction in creating beautiful food that makes people happy. But on the other hand, the hours are very long, the environment is high-pressure, and it's physically demanding work. It's definitely not as glamorous as it looks on TV."\n\n**5. What skills does a person need to be a great chef?**\n"Beyond excellent cooking technique, a great chef needs to be creative to develop new dishes. They also need to be very organised and work well under pressure to manage a busy kitchen service. Strong leadership skills are essential for managing the kitchen team, and they must have a great palate and a deep understanding of flavour combinations."\n\n**6. How much influence do celebrity/TV chefs have on what ordinary people cook?**\n"They have a massive influence. When a popular TV chef features a particular ingredient or recipe, supermarkets often sell out of those items the next day. They make cooking seem more accessible and exciting, and they introduce people to new cuisines and techniques that they might not have tried otherwise. They've definitely encouraged a lot more people to cook at home."`
        }]
      }
    ]
  }
];

export const book18: Book = {
  id: 18,
  title: 'IELTS 18 Academic',
  description: 'Authentic Practice Tests from Cambridge. The perfect way to practise – EXACTLY like the real exam.',
  lessons: [
    ...ielts18Test1Lessons,
    ...ielts18Test2Lessons,
    ...ielts18Test3Lessons,
    ...ielts18Test4Lessons,
  ],
};
