
import { Lesson, QuestionType, Section } from '../types';

const ielts18ReadingPassage1Test4 = `Rooftops covered with grass, vegetable gardens and lush foliage are now a common sight in many cities around the world. More and more private companies and city authorities are investing in green roofs, drawn to their wide-ranging benefits. Among the benefits are saving on energy costs, mitigating the risk of floods, making habitats for urban wildlife, tackling air pollution and even growing food. These increasingly radical urban designs can help cities adapt to the monumental problems they face, such as access to resources and a lack of green space due to development. But the involvement of city authorities, businesses and other institutions is crucial to ensuring their success – as is research investigating different options to suit the variety of rooftop spaces found in cities. The UK is relatively new to developing green roofs, and local governments and institutions are playing a major role in spreading the practice. London is home to much of the UK’s green roof market, mainly due to forward-thinking policies such as the London Plan, which has paved the way to more than doubling the area of green roofs in the capital.

Ongoing research is showcasing how green roofs in cities can integrate with ‘living walls’: environmentally friendly walls which are partially or completely covered with greenery, including a growing medium, such as soil or water. Research also indicates that green roofs can be integrated with drainage systems on the ground, such as street trees, so that the water is managed better and the built environment in general is made more sustainable. There is also evidence to demonstrate the social value of green roofs. Doctors are increasingly prescribing time spent gardening outdoors for patients dealing with anxiety and depression. And research has found that access to even the most basic green spaces can provide a better quality of life for dementia sufferers and help people avoid obesity.

In North America, green roofs have become mainstream, with a wide array of expansive, accessible and food-producing roofs installed in buildings. Again, city leaders and authorities have helped push the movement forward – only recently, San Francisco, USA, created a policy requiring new buildings to have green roofs. Toronto, Canada, has policies dating from the 1990s, encouraging the development of urban farms on rooftops. These countries also benefit from having newer buildings than in many parts of the world, which makes it easier to install green roofs. Being able to keep enough water at roof height and distribute it across the rooftop is crucial to maintaining the plants on any green roof – especially on ‘edible roofs’ where fruit and vegetables are cultivated. And it’s much easier to do this in newer buildings with roofs that can typically hold greater weight, than to retro-fit old ones. Having a stronger roof also makes it easier to grow a greater variety of plants, since the soil can be deeper.

For green roofs to become the norm for new developments, there needs to be support from public authorities and private investors. Those responsible for maintaining buildings may have to acquire new skills, such as landscaping, and in some cases, volunteers may be needed to help out. Other considerations include installing drainage paths, meeting health and safety requirements and perhaps allowing access to the public, as well as planning restrictions and disruption from regular activities in and around the buildings during installation. To convince investors and developers that installing green roofs is worthwhile, economic arguments are still the most important. The term ‘natural capital’ has been developed to explain the economic value of nature; for example, measuring the money saved by installing natural solutions to protect against flood damage, adapt to climate change or help people lead healthier and happier lives.

As the expertise about green roofs grows, official standards have been developed to ensure that they are designed, constructed and maintained properly, and function well. Improvements in the science and technology underpinning green roof development have also led to new variations in the concept. For example, ‘blue roofs’ enable buildings to hold water over longer periods of time, rather than draining it away quickly – crucial in times of heavier rainfall. There are also combinations of green roofs with solar panels, and ‘brown roofs’ which are wilder in nature and maximise biodiversity. If the trend continues, it could create new jobs and a more vibrant and sustainable local food economy – alongside many other benefits. There are still barriers to overcome, but the evidence so far indicates that green roofs have the potential to transform cities and help them function well into the future. The success stories need to be studied and replicated elsewhere, to make green, blue, brown and food-producing roofs the norm in cities around the world.`;

const ielts18ReadingPassage2Test4 = `Over the past century, a powerful idea has taken root in the educational landscape. The concept of intelligence as something innate is not fixed, and that, with the right training, we can be the authors of our own cognitive capabilities. Psychologist Alfred Binet, the developer of the first intelligence tests, was one of many 19th-century scientists who held that earlier tests measured innate ability. Then, in the early 20th century, progressive thinkers revolted against the notion that inherent ability is destiny. Instead, educators such as John Dewey argued that every child’s intelligence could be developed, given the right environment.

‘Growth mindset theory’ is a relatively new – and extremely popular – version of this idea. In many schools today you will see hallways covered in motivational posters and hear speeches on the mindset of great sporting heroes who simply believed their way to the top. A major focus of the growth mindset in schools is coaxing students away from seeing failure as an indication of their ability, and towards seeing it as a chance to improve that ability. As educationalist Jeff Howard noted several decades ago: ‘Smart is not something that you just are, smart is something that you can get.’

The idea of the growth mindset is based on the work of psychologist Carol Dweck in California in the 1990s. In one key experiment, Dweck divided a group of 10- to 12-year-olds into two groups. All were told that they had achieved a high score on a test but the first group were praised for their intelligence in achieving this, while the others were praised for their effort. The second group were subsequently far more likely to put effort into future tasks. Meanwhile, the former group had inferred that success or failure is due to innate ability, and this ‘fixed mindset’ had led them to fear of failure and lack of effort. Praising ability actually made the students perform worse, while praising effort emphasised that change was possible.

One of the greatest impediments to successfully implementing a growth mindset, however, is the education system itself: in many parts of the world, the school climate is obsessed with performance in the form of constant testing, analysing and ranking of students – a key characteristic of the fixed mindset. Nor is it unusual for schools to create a certain cognitive dissonance, when they applaud the benefits of a growth mindset but then hand out fixed target grades in lesson based on performance.

Aside from the implementation problem, the original growth mindset research has also received harsh criticism. The statistician Andrew Gelman claims that ‘their research designs have enough degrees of freedom that they could get their data to support just about any theory’.

Professor of Psychology Timothy Bates, who has been trying to replicate Dweck’s work, is finding that the results are repeatedly null. He notes that: ‘People with a growth mindset don’t get better grades, either before or after our intervention study.’

Much of this criticism is not lost on Dweck, and she deserves great credit for responding to it and adapting her work accordingly. In fact, she argues that her work has been misunderstood and misapplied in a range of ways. She has also expressed concerns that her theories are being misappropriated in schools by being conflated with the self-esteem movement: ‘For me the growth mindset is a tool for learning and improvement. It’s not just a vehicle for making children feel good.’

But there is another factor at work here. The failure to translate the growth mindset into the classroom might reflect a misunderstanding of the nature of teaching and learning itself. Growth mindset supporters David Yeager and Gregory Walton claim that interventions should be delivered in a subtle way to maximise their effectiveness. They say that if adolescents perceive a teacher’s intervention as conveying that they are in need of help, this could undo its intended effects.

A lot of what drives students is their innate beliefs and how they perceive themselves. There is a strong correlation between self-perception and achievement, but there is evidence to suggest that the actual effect of achievement on self-perception is stronger than the other way round. To stand up in a classroom and successfully deliver a good speech is a genuine achievement, and that is likely to be more powerfully motivating than vague notions of ‘motivation’ itself.

Recent evidence would suggest that growth mindset interventions are not the elixir of student learning that its proponents claim it to be. The growth mindset appears to be a viable construct in the lab, which, when administered in the classroom via targeted interventions, doesn’t seem to work. It is hard to dispute that having faith in the capacity to change is a good attribute for students. Paradoxically, however, that aspiration is not well served by direct interventions that try to instil it.

Motivational posters and talks are often a waste of time, and might well give students a deluded notion of what success actually means. Teaching concrete skills such as how to write an effective introduction to an essay then praising students’ effort in getting there is probably a far better way of improving confidence than telling them how unique they are, or indeed how capable they are of changing their own brains. Perhaps growth mindset works best as a philosophy and not an intervention.`;

const ielts18ReadingPassage3Test4 = `by Mott T Greene

This is a book about the life and scientific work of Alfred Wegener, whose reputation today rests with his theory of continental displacements, better known as ‘continental drift’. Wegener proposed this theory in 1912 and developed it extensively for nearly 20 years. His book on the subject, The Origin of Continents and Oceans, went through four editions and was the focus of an international controversy in his lifetime and for some years after his death.

Wegener’s basic idea was that many mysteries about the Earth’s history could be solved if one supposed that the continents moved laterally, rather than supposing that they remained fixed in place. Wegener showed how they worked, being in evidence from a large number of sciences including geology, geophysics, paleontology, and climatology. Wegener’s idea – that the continents move – is at the heart of the theory that guides Earth sciences today, namely plate tectonics. Plate tectonics is in many respects quite different from Wegener’s proposal, in the same way that modern evolutionary theory is very different from the ideas Charles Darwin proposed in the 1850s about biological evolution. Yet plate tectonics is a descendant of Alfred Wegener’s theory of continental drift, in quite the same way that modern evolutionary theory is a descendant of Darwin’s theory of natural selection.

When I started writing about Wegener’s life and work, one of the most intriguing things about him for me was that, although he came up with a theory of continental drift, he was not a geologist. He trained as an astronomer and pursued a career in atmospheric physics. When he proposed the theory of continental displacements in 1912, he was a lecturer in physics and astronomy at the University of Marburg, in southern Germany. However, he was not an ‘unknown’. In 1906 he had set a world record (with his brother Kurt) for time aloft in a hot-air balloon: 52 hours. Between 1906 and 1908 he had taken part in a highly publicized and extremely dangerous expedition to the coast of northeast Greenland. He had also made a name for himself among meteorologists and atmospheric physicists in Germany as the author of a textbook, Thermodynamics of the Atmosphere (1911), and of a number of interesting scientific papers.

As important as Wegener’s work on continental drift has turned out to be, it was largely a sideline to his interest in atmospheric physics, geophysics, and paleoclimatology, and thus I have been at great pains to put Wegener’s work on continental drift in the larger context of his scientific life, and in the even larger context of atmospheric sciences in his lifetime. This is a ‘continental drift book’ only to the extent that Wegener was interested in that topic and later became famous in it. My treatment of his other scientific work is no less detailed, though I certainly have devoted more attention to the reception of his ideas on continental displacement, as they were much more controversial than his other work.

Readers interested in the specific detail of Wegener’s career will see that he often stopped pursuing a given line of investigation (sometimes for years on end), only to pick it up later. I have tried to provide guideposts to his rapidly shifting interests by characterizing different phases of his life as careers in different sciences, which is reflected in the titles of the chapters. Thus, the Index should be a sufficient guide for those interested in a particular aspect of Wegener’s life but perhaps not all of it. My own feeling however is that the parts do not make as much sense on their own as do all of his activities taken together. It is in this respect I urge readers to try to experience Wegener’s life as he lived it, with all the interruptions, changes of mind, and renewed efforts this entailed.

Wegener left behind a few published works but, as was standard practice, these reported the results of his work – not the journey he took to reach that point. Only a few hundred of the many thousands of letters he wrote and received in his lifetime have survived and he didn’t keep notebooks or diaries that recorded his life and activities. He was not active (with a few exceptions) in scientific societies, and did not seek to find influence or advance his ideas through professional contacts and politics, spending most of his time at home in his study reading and writing, or in the field collecting observations.

Some famous scientists, such as Newton, Darwin, and Einstein, left mountains of written material behind, hundreds of notebooks and letters numbering in the tens of thousands. Others, like Michael Faraday, left extensive journals of their thoughts and speculations, parallel to their scientific notebooks. The more such material a scientist leaves behind, the better chance a biographer has of forming an accurate picture of how the scientist’s ideas took shape and evolved.

I am firmly of the opinion that most of us, Wegener included, are not in any real sense the authors of our own lives. We plan, think, and act, often with apparent freedom, but most of the time our lives ‘happen to us’, and we only retrospectively turn this happenstance into a coherent narrative of fulfilled Wegener planned and intended, is a story both of the life and scientific work that Alfred Wegener planned and intended and of the life and scientific work that actually ‘happened to him’. These are, as I think you will soon see, not always the same thing.`;

export const ielts18Test4Lessons: Lesson[] = [
  // Test 4
  {
    id: 'b18-t4-l0',
    title: 'Test 4: Listening P1-2',
    section: Section.LISTENING,
    parts: [
      { // Part 1
        questions: [
          { id: 'b18t4lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t4-p1.mp3', questionText: 'Role: 1 ___', correctAnswers: ['receptionist'], transcript: "So this is a position for a receptionist – I believe you’ve done that sort of work before?", transcriptHighlight: "position for a receptionist" },
          { id: 'b18t4lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t4-p1.mp3', questionText: 'Location: Fordham 2 ___ Centre', correctAnswers: ['Medical'], transcript: "Well, this job’s in Fordsham, so not too far away for you, and it’s at the medical centre there.", transcriptHighlight: "medical centre" },
          { id: 'b18t4lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t4-p1.mp3', questionText: '3 ___ Road, Fordham', correctAnswers: ['Chastons'], transcript: "Chastons Road – that’s C-H-A-S-T-O-N-S.", transcriptHighlight: "Chastons Road" },
          { id: 'b18t4lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t4-p1.mp3', questionText: 'making 4 ___ and reorganising them', correctAnswers: ['appointments'], transcript: "you’d also be involved in making appointments, whether face to face or on the phone.", transcriptHighlight: "making appointments" },
          { id: 'b18t4lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t4-p1.mp3', questionText: 'maintaining the internal 5 ___', correctAnswers: ['database'], transcript: "And another of your duties would be keeping the centre’s database up-to-date.", transcriptHighlight: "keeping the centre’s database" },
          { id: 'b18t4lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t4-p1.mp3', questionText: '6 ___ (essential)', correctAnswers: ['experience'], transcript: "Now when the details came in, I immediately thought of you because one thing they do require is someone with experience", transcriptHighlight: "require is someone with experience" },
          { id: 'b18t4lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t4-p1.mp3', questionText: 'a calm and 7 ___ manner', correctAnswers: ['confident'], transcript: "they want someone who can cope with that and stay calm, and at the same time be confident when interacting with the public.", transcriptHighlight: "be confident" },
          { id: 'b18t4lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t4-p1.mp3', questionText: 'a 8 ___ job – further opportunities may be available', correctAnswers: ['temporary'], transcript: "I should tell you that this isn’t a permanent job. It’s temporary", transcriptHighlight: "It’s temporary" },
          { id: 'b18t4lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t4-p1.mp3', questionText: 'hours: 7.45 a.m. to 9 ___ p.m. Monday to Friday', correctAnswers: ['1.15'], transcript: "What time would I finish? One fifteen.", transcriptHighlight: "One fifteen" },
          { id: 'b18t4lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t4-p1.mp3', questionText: '10 ___ is available onsite', correctAnswers: ['parking'], transcript: "one thing ... is there parking available for staff at the centre? Yes, there is", transcriptHighlight: "parking available for staff" },
        ],
      },
      { // Part 2
        questions: [
          { id: 'b18t4lq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t4-p2.mp3', questionText: '11 The museum building was originally', options: ['A a factory.', 'B a private home.', 'C a hall of residence.'], correctAnswers: ['B a private home.'], transcript: "So, where we’re standing at the moment is the entrance to a large building that was constructed in 1880 as the home of a local businessman, Alfred Palmer", transcriptHighlight: "home of a local businessman" },
          { id: 'b18t4lq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t4-p2.mp3', questionText: '12 The university uses part of the museum building as', options: ['A teaching rooms.', 'B a research library.', 'C administration offices.'], correctAnswers: ['A teaching rooms.'], transcript: "The museum’s owned by the university... You may see some students going into the building for lessons, but it’s not open to museum visitors", transcriptHighlight: "students going into the building for lessons" },
          { id: 'b18t4lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t4-p2.mp3', questionText: '13 What does the guide say about the entrance fee?', options: ['A Visitors decide whether or not they wish to pay.', 'B Only children and students receive a discount.', 'C The museum charges extra for special exhibitions.'], correctAnswers: ['A Visitors decide whether or not they wish to pay.'], transcript: "We do have a donation box just over there so feel free to give whatever amount you consider appropriate.", transcriptHighlight: "feel free to give whatever amount you consider appropriate" },
          { id: 'b18t4lq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t4-p2.mp3', questionText: '14 What are visitors advised to leave in the cloakroom?', options: ['A cameras', 'B coats', 'C bags'], correctAnswers: ['C bags'], transcript: "We do have a cloakroom, so feel free to leave your coats and bags somewhere. Unlike other museums, photography is allowed here, so you might like to keep your cameras with you.", transcriptHighlight: "leave your coats and bags" },
          { id: 'b18t4lq15', type: QuestionType.MULTIPLE_CHOICE, prompt: "What information does the speaker give about each of the following areas of the museum?", audioUrl: 'ielts-18/t4-p2.mp3', questionText: '15 Four Seasons', options: ['A Parents must supervise their children.', 'B There are new things to see.', 'C It is closed today.', 'D This is only for school groups.', 'E There is a quiz for visitors.', 'F It features something created by students.', 'G An expert is here today.', 'H There is a one-way system.'], correctAnswers: ['F It features something created by students.'], transcript: "It was designed especially for the museum by a group of young people from a film studies course", transcriptHighlight: "designed especially for the museum by a group of young people" },
          { id: 'b18t4lq16', type: QuestionType.MULTIPLE_CHOICE, prompt: "What information does the speaker give about each of the following areas of the museum?", audioUrl: 'ielts-18/t4-p2.mp3', questionText: '16 Farmhouse Kitchen', options: ['A Parents must supervise their children.', 'B There are new things to see.', 'C It is closed today.', 'D This is only for school groups.', 'E There is a quiz for visitors.', 'F It features something created by students.', 'G An expert is here today.', 'H There is a one-way system.'], correctAnswers: ['G An expert is here today.'], transcript: "This morning, a specialist cheesemaker will be giving demonstrations of how it’s produced.", transcriptHighlight: "a specialist cheesemaker will be giving demonstrations" },
          { id: 'b18t4lq17', type: QuestionType.MULTIPLE_CHOICE, prompt: "What information does the speaker give about each of the following areas of the museum?", audioUrl: 'ielts-18/t4-p2.mp3', questionText: '17 A Year on the Farm', options: ['A Parents must supervise their children.', 'B There are new things to see.', 'C It is closed today.', 'D This is only for school groups.', 'E There is a quiz for visitors.', 'F It features something created by students.', 'G An expert is here today.', 'H There is a one-way system.'], correctAnswers: ['E There is a quiz for visitors.'], transcript: "If you’re feeling competitive, you can take our memory test in which you answer questions about things you’ve seen in the museum.", transcriptHighlight: "you can take our memory test" },
          { id: 'b18t4lq18', type: QuestionType.MULTIPLE_CHOICE, prompt: "What information does the speaker give about each of the following areas of the museum?", audioUrl: 'ielts-18/t4-p2.mp3', questionText: '18 Wagon Walk', options: ['A Parents must supervise their children.', 'B There are new things to see.', 'C It is closed today.', 'D This is only for school groups.', 'E There is a quiz for visitors.', 'F It features something created by students.', 'G An expert is here today.', 'H There is a one-way system.'], correctAnswers: ['A Parents must supervise their children.'], transcript: "The carts are old and fragile, so we ask you to keep your children close to you and ensure they don’t climb on the carts.", transcriptHighlight: "keep your children close to you" },
          { id: 'b18t4lq19', type: QuestionType.MULTIPLE_CHOICE, prompt: "What information does the speaker give about each of the following areas of the museum?", audioUrl: 'ielts-18/t4-p2.mp3', questionText: '19 Bees are Magic', options: ['A Parents must supervise their children.', 'B There are new things to see.', 'C It is closed today.', 'D This is only for school groups.', 'E There is a quiz for visitors.', 'F It features something created by students.', 'G An expert is here today.', 'H There is a one-way system.'], correctAnswers: ['C It is closed today.'], transcript: "We’re redeveloping this area so you can’t visit that at the moment.", transcriptHighlight: "you can’t visit that at the moment" },
          { id: 'b18t4lq20', type: QuestionType.MULTIPLE_CHOICE, prompt: "What information does the speaker give about each of the following areas of the museum?", audioUrl: 'ielts-18/t4-p2.mp3', questionText: '20 The Pond', options: ['A Parents must supervise their children.', 'B There are new things to see.', 'C It is closed today.', 'D This is only for school groups.', 'E There is a quiz for visitors.', 'F It features something created by students.', 'G An expert is here today.', 'H There is a one-way system.'], correctAnswers: ['B There are new things to see.'], transcript: "There are baby ducks that are only a few days old, as well as tiny frogs.", transcriptHighlight: "baby ducks that are only a few days old" },
        ]
      }
    ]
  },
  {
    id: 'b18-t4-l1',
    title: 'Test 4: Listening P3-4',
    section: Section.LISTENING,
    parts: [
      { // Part 3
        questions: [
          { id: 'b18t4lq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO educational skills were shown in the video of children doing origami?', maxSelections: 2, audioUrl: 'ielts-18/t4-p3.mp3', questionText: 'Choose TWO letters, A-E.', options: ['A solving problems', 'B following instructions', 'C working cooperatively', 'D learning through play', 'E developing hand-eye coordination'], correctAnswers: ['B following instructions', 'D learning through play'], transcript: "On the video you could see them really listening... One thing that really stood out for me was that the children were all having fun while being taught something new.", transcriptHighlight: "really listening... having fun while being taught something new" },
          { id: 'b18t4lq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which comment do the students make about each of the following children in the video?', audioUrl: 'ielts-18/t4-p3.mp3', questionText: '23 Sid', options: ['A demonstrated independence', 'B asked for teacher support', 'C developed a competitive attitude', 'D seemed to find the activity calming', 'E seemed pleased with the results', 'F seemed confused', 'G seemed to find the activity easy'], correctAnswers: ['D seemed to find the activity calming'], transcript: "he was being quite disruptive... it helped him to settle down and start concentrating.", transcriptHighlight: "it helped him to settle down" },
          { id: 'b18t4lq24', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which comment do the students make about each of the following children in the video?', audioUrl: 'ielts-18/t4-p3.mp3', questionText: '24 Jack', options: ['A demonstrated independence', 'B asked for teacher support', 'C developed a competitive attitude', 'D seemed to find the activity calming', 'E seemed pleased with the results', 'F seemed confused', 'G seemed to find the activity easy'], correctAnswers: ['A demonstrated independence'], transcript: "I noticed he seemed to want to work things out for himself... him trying out different things rather than asking the teacher for help.", transcriptHighlight: "work things out for himself" },
          { id: 'b18t4lq25', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which comment do the students make about each of the following children in the video?', audioUrl: 'ielts-18/t4-p3.mp3', questionText: '25 Naomi', options: ['A demonstrated independence', 'B asked for teacher support', 'C developed a competitive attitude', 'D seemed to find the activity calming', 'E seemed pleased with the results', 'F seemed confused', 'G seemed to find the activity easy'], correctAnswers: ['C developed a competitive attitude'], transcript: "she decided she wanted her mouse to be the best and that motivated her to try harder.", transcriptHighlight: "wanted her mouse to be the best" },
          { id: 'b18t4lq26', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which comment do the students make about each of the following children in the video?', audioUrl: 'ielts-18/t4-p3.mp3', questionText: '26 Anya', options: ['A demonstrated independence', 'B asked for teacher support', 'C developed a competitive attitude', 'D seemed to find the activity calming', 'E seemed pleased with the results', 'F seemed confused', 'G seemed to find the activity easy'], correctAnswers: ['G seemed to find the activity easy'], transcript: "Anya was such a star. She listened so carefully and then produced the perfect bird with very little effort.", transcriptHighlight: "produced the perfect bird with very little effort" },
          { id: 'b18t4lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which comment do the students make about each of the following children in the video?', audioUrl: 'ielts-18/t4-p3.mp3', questionText: '27 Zara', options: ['A demonstrated independence', 'B asked for teacher support', 'C developed a competitive attitude', 'D seemed to find the activity calming', 'E seemed pleased with the results', 'F seemed confused', 'G seemed to find the activity easy'], correctAnswers: ['F seemed confused'], transcript: "She seemed unsure about what she was supposed to do, but in the end hers didn’t turn out too badly.", transcriptHighlight: "seemed unsure about what she was supposed to do" },
          { id: 'b18t4lq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t4-p3.mp3', questionText: 'Before starting an origami activity in class, the students think it is important for the teacher to', options: ['A make models that demonstrate the different stages.', 'B check children understand the terminology involved.', 'C tell children not to worry if they find the activity difficult.'], correctAnswers: ['A make models that demonstrate the different stages.'], transcript: "it would be taken me ages to prepare examples showing each of the steps involved in making the bird. But that was a really good idea. The children could see what they were aiming for", transcriptHighlight: "prepare examples showing each of the steps" },
          { id: 'b18t4lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t4-p3.mp3', questionText: 'The students agree that some teachers might be unwilling to use origami in class because', options: ['A they may not think that crafts are important.', 'B they may not have the necessary skills.', 'C they may worry that it will take up too much time.'], correctAnswers: ['B they may not have the necessary skills.'], transcript: "I bet it’s because so many teachers are clumsy like me. That’s true – too much effort required if you’re not good with your hands.", transcriptHighlight: "not good with your hands" },
          { id: 'b18t4lq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t4-p3.mp3', questionText: 'Why do the students decide to use origami in their maths teaching practice?', options: ['A to correct a particular misunderstanding', 'B to set a challenge', 'C to introduce a new concept'], correctAnswers: ['C to introduce a new concept'], transcript: "I can see using origami is a really engaging way of reinforcing children’s knowledge of geometric shapes, like they were doing in the video, but I think it would also work really well for presenting fractions, which is coming up soon.", transcriptHighlight: "presenting fractions" },
        ]
      },
      { // Part 4
        questions: [
          { id: 'b18t4lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t4-p4.mp3', questionText: 'We know more about its overall 31 ___ than about its author.', correctAnswers: ['plot'], transcript: "So, some of us on this course have a pretty general idea of the plot, but we know much less about its author.", transcriptHighlight: "general idea of the plot" },
          { id: 'b18t4lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t4-p4.mp3', questionText: 'He spoke publicly about social issues, such as 32 ___ and education.', correctAnswers: ['poverty'], transcript: "he also gave many speeches about issues like the level of poverty in his society.", transcriptHighlight: "level of poverty" },
          { id: 'b18t4lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t4-p4.mp3', questionText: 'Victor Hugo had to live elsewhere in 33 ___ .', correctAnswers: ['Europe'], transcript: "So, Victor Hugo was forced to reside in other parts of Europe.", transcriptHighlight: "reside in other parts of Europe" },
          { id: 'b18t4lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t4-p4.mp3', questionText: 'He used his income from the sale of some 34 ___ he had written to buy a house on Guernsey.', correctAnswers: ['poetry'], transcript: "This was a property that he bought using the money he’d made in France from the publication of a collection of his poetry.", transcriptHighlight: "collection of his poetry" },
          { id: 'b18t4lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t4-p4.mp3', questionText: 'The ground floor contains portraits, 35 ___ and tapestries that he valued.', correctAnswers: ['drawings'], transcript: "portraits of its members still hang in rooms on the ground floor, along with drawings that he did during his travels that he felt were important to him.", transcriptHighlight: "along with drawings" },
          { id: 'b18t4lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t4-p4.mp3', questionText: 'He bought cheap 36 ___ made of wood and turned this into beautiful wall carvings.', correctAnswers: ['furniture'], transcript: "The walls are covered in dark wood panelling that Hugo himself created himself using wooden furniture that he bought in the market.", transcriptHighlight: "using wooden furniture" },
          { id: 'b18t4lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t4-p4.mp3', questionText: 'The first floor consists of furnished areas with wallpaper and 37 ___ that have a Chinese design.', correctAnswers: ['lamps'], transcript: "and the lamps – which he would have made himself by copying original versions.", transcriptHighlight: "and the lamps" },
          { id: 'b18t4lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t4-p4.mp3', questionText: 'He wrote in a room at the top of the house that had a view of the 38 ___ .', correctAnswers: ['harbour', 'harbor'], transcript: "at the very top of the house, there’s a room called the Lookout – called that because it looks out over the harbour", transcriptHighlight: "looks out over the harbour" },
          { id: 'b18t4lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t4-p4.mp3', questionText: 'he entertained other writers as well as poor 39 ___ in his house.', correctAnswers: ['children'], transcript: "but he also invited a large group of local children from the deprived areas of the island to dinner once a week.", transcriptHighlight: "large group of local children" },
          { id: 'b18t4lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t4-p4.mp3', questionText: "Victor Hugo's 40 ___ gave ownership of the house to the city of Paris in 1927.", correctAnswers: ['relatives'], transcript: "In 1927, the house was owned by his relatives, and they decided to donate it to the city of Paris.", transcriptHighlight: "owned by his relatives" },
        ]
      }
    ]
  },
  {
    id: 'b18-t4-r2',
    title: 'Test 4: Reading P1',
    section: Section.READING,
    parts: [{
      questions: [
        { id: 'b18t4rq1', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A-E.', passage: ielts18ReadingPassage1Test4, questionText: '1 mention of several challenges to be overcome before a green roof can be installed', options: ['A','B','C','D','E'], correctAnswers: ['D'], passageHighlight: "Other considerations include installing drainage paths, meeting health and safety requirements and perhaps allowing access to the public, as well as planning restrictions and disruption" },
        { id: 'b18t4rq2', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A-E.', passage: ielts18ReadingPassage1Test4, questionText: '2 a reference to a city where green roofs have been promoted for many years', options: ['A','B','C','D','E'], correctAnswers: ['C'], passageHighlight: "Toronto, Canada, has policies dating from the 1990s, encouraging the development of urban farms on rooftops." },
        { id: 'b18t4rq3', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A-E.', passage: ielts18ReadingPassage1Test4, questionText: '3 a belief that existing green roofs should be used as a model for new ones', options: ['A','B','C','D','E'], correctAnswers: ['E'], passageHighlight: "The success stories need to be studied and replicated elsewhere" },
        { id: 'b18t4rq4', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A-E.', passage: ielts18ReadingPassage1Test4, questionText: '4 examples of how green roofs can work in combination with other green urban initiatives', options: ['A','B','C','D','E'], correctAnswers: ['B'], passageHighlight: "green roofs in cities can integrate with ‘living walls’... green roofs can be integrated with drainage systems on the ground, such as street trees" },
        { id: 'b18t4rq5', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A-E.', passage: ielts18ReadingPassage1Test4, questionText: '5 the need to make a persuasive argument for the financial benefits of green roofs', options: ['A','B','C','D','E'], correctAnswers: ['D'], passageHighlight: "To convince investors and developers that installing green roofs is worthwhile, economic arguments are still the most important." },
        { id: 'b18t4rq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1Test4, questionText: 'lessening the likelihood that floods will occur, reducing how much money is spent on 6 ___', correctAnswers: ['energy'], passageHighlight: "Among the benefits are saving on energy costs, mitigating the risk of floods" },
        { id: 'b18t4rq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1Test4, questionText: 'and creating environments that are suitable for wildlife. In many cases, they can also be used for producing 7 ___ .', correctAnswers: ['food'], passageHighlight: "making habitats for urban wildlife... and even growing food." },
        { id: 'b18t4rq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1Test4, questionText: 'There are also social benefits of green roofs. For example, the medical profession recommends 8 ___ as an activity to help people cope with mental health issues.', correctAnswers: ['gardening'], passageHighlight: "Doctors are increasingly prescribing time spent gardening outdoors for patients dealing with anxiety and depression." },
        { id: 'b18t4rq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage1Test4, questionText: 'Studies have also shown that the availability of green spaces can prevent physical problems such as 9 ___ .', correctAnswers: ['obesity'], passageHighlight: "help people avoid obesity." },
        { id: 'b18t4rq10', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO advantages of using newer buildings for green roofs are mentioned in Paragraph C of the passage?', maxSelections: 2, passage: ielts18ReadingPassage1Test4, questionText: 'Choose TWO letters, A-E.', options: ['A a longer growing season for edible produce', 'B more economical use of water', 'C greater water-storage capacity', 'D ability to cultivate more plant types', 'E a large surface area for growing plants'], correctAnswers: ['C greater water-storage capacity', 'D ability to cultivate more plant types'], passageHighlight: "newer buildings with roofs that can typically hold greater weight... Having a stronger roof also makes it easier to grow a greater variety of plants" },
        { id: 'b18t4rq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO aims of new variations on the concept of green roofs are mentioned in Paragraph E of the passage?', maxSelections: 2, passage: ielts18ReadingPassage1Test4, questionText: 'Choose TWO letters, A-E.', options: ['A to provide habitats for a wide range of species', 'B to grow plants successfully even in the wettest climates', 'C to regulate the temperature of the immediate environment', 'D to generate power from a sustainable source', 'E to collect water to supply other buildings'], correctAnswers: ['A to provide habitats for a wide range of species', 'D to generate power from a sustainable source'], passageHighlight: "combinations of green roofs with solar panels, and ‘brown roofs’ which are wilder in nature and maximise biodiversity." },
      ]
    }],
  },
  {
    id: 'b18-t4-r3',
    title: 'Test 4: Reading P2-3',
    section: Section.READING,
    parts: [
      { // Reading Passage 2
        questions: [
          { id: 'b18t4rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test4, questionText: '14 What can we learn from the first paragraph?', options: ['A where the notion of innate intelligence first began', 'B when ideas about the nature of intelligence began to shift', 'C how scientists have responded to changing views of intelligence', 'D why thinkers turned away from the idea of intelligence being fixed'], correctAnswers: ['B when ideas about the nature of intelligence began to shift'], passageHighlight: "Then, in the early 20th century, progressive thinkers revolted against the notion that inherent ability is destiny." },
          { id: 'b18t4rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test4, questionText: '15 The second paragraph describes how schools encourage students to', options: ['A identify their personal ambitions.', 'B help each other to realise their goals.', 'C have confidence in their potential to succeed.', 'D concentrate on where their particular strengths lie.'], correctAnswers: ['C have confidence in their potential to succeed.'], passageHighlight: "A major focus of the growth mindset in schools is coaxing students away from seeing failure as an indication of their ability, and towards seeing it as a chance to improve that ability." },
          { id: 'b18t4rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test4, questionText: '16 In the third paragraph, the writer suggests that students with a fixed mindset', options: ['A tend to be less competitive.', 'B generally have a low sense of self-esteem.', 'C will only work hard if they are given constant encouragement.', 'D are afraid to push themselves beyond what they see as their limitations.'], correctAnswers: ['D are afraid to push themselves beyond what they see as their limitations.'], passageHighlight: "this ‘fixed mindset’ had led them to fear of failure and lack of effort." },
          { id: 'b18t4rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.', passage: ielts18ReadingPassage2Test4, questionText: '17 The methodology behind the growth mindset studies was not strict enough.', options: ['A Alfred Binet', 'B Carol Dweck', 'C Andrew Gelman', 'D Timothy Bates', 'E David Yeager and Gregory Walton'], correctAnswers: ['C Andrew Gelman'], passageHighlight: "The statistician Andrew Gelman claims that ‘their research designs have enough degrees of freedom that they could get their data to support just about any theory’." },
          { id: 'b18t4rq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.', passage: ielts18ReadingPassage2Test4, questionText: '18 The idea of the growth mindset has been incorrectly interpreted.', options: ['A Alfred Binet', 'B Carol Dweck', 'C Andrew Gelman', 'D Timothy Bates', 'E David Yeager and Gregory Walton'], correctAnswers: ['B Carol Dweck'], passageHighlight: "she argues that her work has been misunderstood and misapplied in a range of ways." },
          { id: 'b18t4rq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.', passage: ielts18ReadingPassage2Test4, questionText: '19 Intellectual ability is an unchangeable feature of each individual.', options: ['A Alfred Binet', 'B Carol Dweck', 'C Andrew Gelman', 'D Timothy Bates', 'E David Yeager and Gregory Walton'], correctAnswers: ['A Alfred Binet'], passageHighlight: "Alfred Binet, the developer of the first intelligence tests, was one of many 19th-century scientists who held that earlier tests measured innate ability." },
          { id: 'b18t4rq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.', passage: ielts18ReadingPassage2Test4, questionText: '20 The growth mindset should not be promoted without students being aware of it.', options: ['A Alfred Binet', 'B Carol Dweck', 'C Andrew Gelman', 'D Timothy Bates', 'E David Yeager and Gregory Walton'], correctAnswers: ['E David Yeager and Gregory Walton'], passageHighlight: "Growth mindset supporters David Yeager and Gregory Walton claim that interventions should be delivered in a subtle way to maximise their effectiveness." },
          { id: 'b18t4rq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.', passage: ielts18ReadingPassage2Test4, questionText: '21 The growth mindset is not only about boosting students’ morale.', options: ['A Alfred Binet', 'B Carol Dweck', 'C Andrew Gelman', 'D Timothy Bates', 'E David Yeager and Gregory Walton'], correctAnswers: ['B Carol Dweck'], passageHighlight: "It’s not just a vehicle for making children feel good." },
          { id: 'b18t4rq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.', passage: ielts18ReadingPassage2Test4, questionText: '22 Research shows that the growth mindset has no effect on academic achievement.', options: ['A Alfred Binet', 'B Carol Dweck', 'C Andrew Gelman', 'D Timothy Bates', 'E David Yeager and Gregory Walton'], correctAnswers: ['D Timothy Bates'], passageHighlight: "People with a growth mindset don’t get better grades" },
          { id: 'b18t4rq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 2?', passage: ielts18ReadingPassage2Test4, questionText: '23 Dweck has handled criticisms of her work in an admirable way.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "she deserves great credit for responding to it and adapting her work accordingly" },
          { id: 'b18t4rq24', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 2?', passage: ielts18ReadingPassage2Test4, questionText: '24 Students’ self-perception is a more effective driver of self-confidence than actual achievement.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "the actual effect of achievement on self-perception is stronger than the other way round" },
          { id: 'b18t4rq25', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 2?', passage: ielts18ReadingPassage2Test4, questionText: '25 Recent evidence about growth mindset interventions has attracted unfair coverage in the media.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'] },
          { id: 'b18t4rq26', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 2?', passage: ielts18ReadingPassage2Test4, questionText: '26 Deliberate attempts to encourage students to strive for high achievement may have a negative effect.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "that aspiration is not well served by direct interventions that try to instil it" },
        ]
      },
      { // Reading Passage 3
        questions: [
          { id: 'b18t4rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts18ReadingPassage3Test4, questionText: "27 Wegener's ideas about continental drift were widely disputed while he was alive.", options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "His book on the subject, The Origin of Continents and Oceans, went through four editions and was the focus of an international controversy in his lifetime" },
          { id: 'b18t4rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts18ReadingPassage3Test4, questionText: '28 The theory of plate tectonics was less complex than Wegener’s theory of continental drift.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'] },
          { id: 'b18t4rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts18ReadingPassage3Test4, questionText: '29 Wegener relied on a limited range of scientific fields to support his theory of continental drift.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "being in evidence from a large number of sciences including geology, geophysics, paleontology, and climatology." },
          { id: 'b18t4rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts18ReadingPassage3Test4, questionText: '30 The similarities between Wegener’s theory of continental drift and modern-day plate tectonics are enormous.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "Plate tectonics is in many respects quite different from Wegener’s proposal" },
          {
            id: 'b18t4rq31',
            type: QuestionType.MULTIPLE_CHOICE,
            prompt: 'Complete the summary. Choose the correct letter, A-J.',
            passage: ielts18ReadingPassage3Test4,
            questionText: 'One of the remarkable things about Wegener from a 31 ___ is that although he proposed a theory of continental drift, he was not a geologist.',
            options: ["A modest fame", "B vast range", "C record-breaking achievement", "D research methods", "E select group", "F professional interests", "G scientific debate", "H hazardous exploration", "I biographer's perspective", "J narrow investigation"],
            correctAnswers: ["I biographer's perspective"],
            passageHighlight: "When I started writing about Wegener’s life and work, one of the most intriguing things about him for me was that, although he came up with a theory of continental drift, he was not a geologist."
          },
          {
            id: 'b18t4rq32',
            type: QuestionType.MULTIPLE_CHOICE,
            prompt: 'Complete the summary. Choose the correct letter, A-J.',
            passage: ielts18ReadingPassage3Test4,
            questionText: 'His 32 ___ were limited to atmospheric physics.',
            options: ["A modest fame", "B vast range", "C record-breaking achievement", "D research methods", "E select group", "F professional interests", "G scientific debate", "H hazardous exploration", "I biographer's perspective", "J narrow investigation"],
            correctAnswers: ["F professional interests"],
            passageHighlight: "He trained as an astronomer and pursued a career in atmospheric physics."
          },
          {
            id: 'b18t4rq33',
            type: QuestionType.MULTIPLE_CHOICE,
            prompt: 'Complete the summary. Choose the correct letter, A-J.',
            passage: ielts18ReadingPassage3Test4,
            questionText: 'However, at the time he proposed his theory of continental drift in 1912, he had already a person of 33 ___ .',
            options: ["A modest fame", "B vast range", "C record-breaking achievement", "D research methods", "E select group", "F professional interests", "G scientific debate", "H hazardous exploration", "I biographer's perspective", "J narrow investigation"],
            correctAnswers: ["A modest fame"],
            passageHighlight: "he was not an ‘unknown’... he had set a world record... he had taken part in a highly publicized and extremely dangerous expedition... made a name for himself"
          },
          {
            id: 'b18t4rq34',
            type: QuestionType.MULTIPLE_CHOICE,
            prompt: 'Complete the summary. Choose the correct letter, A-J.',
            passage: ielts18ReadingPassage3Test4,
            questionText: 'Six years previously, there had been his 34 ___ of 52 hours in a hot-air balloon,',
            options: ["A modest fame", "B vast range", "C record-breaking achievement", "D research methods", "E select group", "F professional interests", "G scientific debate", "H hazardous exploration", "I biographer's perspective", "J narrow investigation"],
            correctAnswers: ["C record-breaking achievement"],
            passageHighlight: "In 1906 he had set a world record (with his brother Kurt) for time aloft in a hot-air balloon: 52 hours."
          },
          {
            id: 'b18t4rq35',
            type: QuestionType.MULTIPLE_CHOICE,
            prompt: 'Complete the summary. Choose the correct letter, A-J.',
            passage: ielts18ReadingPassage3Test4,
            questionText: 'followed by his well-publicised but 35 ___ of Greenland’s coast.',
            options: ["A modest fame", "B vast range", "C record-breaking achievement", "D research methods", "E select group", "F professional interests", "G scientific debate", "H hazardous exploration", "I biographer's perspective", "J narrow investigation"],
            correctAnswers: ["H hazardous exploration"],
            passageHighlight: "he had taken part in a highly publicized and extremely dangerous expedition to the coast of northeast Greenland."
          },
          {
            id: 'b18t4rq36',
            type: QuestionType.MULTIPLE_CHOICE,
            prompt: 'Complete the summary. Choose the correct letter, A-J.',
            passage: ielts18ReadingPassage3Test4,
            questionText: 'With the publication of his textbook on thermodynamics, he had also come to the attention of a 36 ___ of German scientists.',
            options: ["A modest fame", "B vast range", "C record-breaking achievement", "D research methods", "E select group", "F professional interests", "G scientific debate", "H hazardous exploration", "I biographer's perspective", "J narrow investigation"],
            correctAnswers: ["E select group"],
            passageHighlight: "He had also made a name for himself among meteorologists and atmospheric physicists in Germany"
          },
          { id: 'b18t4rq37', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage3Test4, questionText: '37 What is Mott T Greene doing in the fifth paragraph?', options: ['A describing what motivated him to write the book', 'B explaining why it is desirable to read the whole book', 'C suggesting why Wegener pursued so many different careers', 'D indicating what aspects of Wegener’s life interested him most'], correctAnswers: ['B explaining why it is desirable to read the whole book'], passageHighlight: "My own feeling however is that the parts do not make as much sense on their own as do all of his activities taken together. It is in this respect I urge readers to try to experience Wegener’s life as he lived it" },
          { id: 'b18t4rq38', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage3Test4, questionText: '38 What is said about Wegener in the sixth paragraph?', options: ['A He was not a particularly ambitious person.', 'B He kept a record of all his scientific observations.', 'C He did not adopt many of the scientific practices of the time.', 'D He enjoyed discussing new discoveries with other scientists.'], correctAnswers: ['A He was not a particularly ambitious person.'], passageHighlight: "did not seek to find influence or advance his ideas through professional contacts and politics" },
          { id: 'b18t4rq39', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage3Test4, questionText: '39 What does Greene say about other famous scientists?', options: ["A Their published works had a greater impact than Wegener's did.", "B They had fewer doubts about their scientific ideas than Wegener did.", 'C They are easier subjects to write about than Wegener.', 'D Their scientific ideas were more controversial than Wegener’s.'], correctAnswers: ['D Their scientific ideas were more controversial than Wegener’s.'] },
          { id: 'b18t4rq40', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage3Test4, questionText: '40 What is Greene’s main point in the final paragraph?', options: ['A It is not enough in life to have good intentions.', 'B People need to plan carefully if they want to succeed.', 'C People have little control over many aspects of their lives.', 'D It is important that people ensure they have the freedom to act.'], correctAnswers: ['C People have little control over many aspects of their lives.'], passageHighlight: "most of the time our lives ‘happen to us’, and we only retrospectively turn this happenstance into a coherent narrative" },
        ]
      }
    ]
  },
  {
    id: 'b18-t4-w4',
    title: 'Test 4: Writing T1-2',
    section: Section.WRITING,
    parts: [
      {
        questions: [{
          id: 'b18t4wq1',
          type: QuestionType.WRITING_TASK,
          prompt: 'You should spend about 20 minutes on this task.',
          imageUrl: 'ielts-18/ielts-18-t4-w1-graph.png',
          task: "The graph below shows the average monthly change in the prices of three metals during 2014.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\nWrite at least 150 words.",
          sampleAnswer: "This model has been prepared by an examiner as an example of a very good answer. From the line graph, we can see the average monthly rise or fall in how much copper, nickel and zinc cost throughout 2014.\n\nOverall, nickel started with the highest percentage change of the three but ended with the lowest. Zinc started with the smallest change and ended with the highest, and copper prices fluctuated. Prices for all three metals dipped in June.\n\nIn January the price of nickel was up six per cent, but this dropped to negative three percent in June, ending the year with a one percent increase in both November and December. Copper began the year with an increase of two percent and by May, the price was dropping (by slightly less than one per cent). It rose again, increasing by a percentage point in July, August and September. Zinc saw its most dramatic increase in February, with three per cent and the price fell in June (a one percent decrease). The change was negative until October/November when it began to rise.",
          examinerComment: "This response reports the main data for each of the three metals. There is an introduction in the first paragraph and an overview in the second, followed by the presentation of the main trends of all three categories in the third. Some details are missing (copper after September and no percentage changes for any metal from July to September). The candidate identifies the ‘dip’ for all three in June, but to score more highly, they could also have mentioned that overall, percentage changes fell at the beginning of the year, remained static from July to September and rose after October to the end of the year. Information is arranged coherently; each metal is taken in turn for data reporting. There is good use of cohesive devices [Overall | but | with | when], but there could be more. Vocabulary is adequate with some attempts to use less common items [fluctuated | dramatic increase] and attempts to use synonyms [ended with the lowest | dipped | dropped]. There is a lack of complex structures, as most sentences are simple or compound. However, there is some variety in structures, including comparatives [highest | smallest | most dramatic] and continuous tenses [was dropping]. To improve the response, the candidate could extend the overview to reflect some common trends and should include some of the missing details."
        }]
      },
      {
        questions: [{
          id: 'b18t4wq2',
          type: QuestionType.WRITING_TASK,
          prompt: "You should spend about 40 minutes on this task. Write about the following topic:",
          task: "In many countries, people are now living longer than ever before. Some people say an ageing population creates problems for governments. Other people think there are benefits if society has more elderly people.\n\nTo what extent do the advantages of having an ageing population outweigh the disadvantages?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.",
          sampleAnswer: "This model has been prepared by an examiner as an example of a very good answer. The population in most parts of the world is ageing: people are living longer and there are fewer younger people in many places as birth rates fall. This phenomenon has pros and cons, but this essay will contend that, on balance, the advantages of having an older population outweigh the negatives.\n\nThe first issue that occurs to many people when considering the ageing population is the expense. If people live longer, they may have more than 30 years of retirement and may need to be supported financially by the government or their families. If they experience age-related illness, this impacts the health system and takes up resources needed by other people in society. What’s more, when older people are financially independent, it might be hard for younger people if they have to compete to get a foot in the door of the housing market or gain employment.\n\nThat being said, older people have a lot to contribute in terms of wisdom, experience and skills. Many people are active and productive for longer than their counterparts were 50 years ago and are an asset to the economy and society well into their old age. They are able to work for longer and after retirement they contribute in many ways too, such as by doing charitable work, spending money as consumers and supporting their families. Grandparents often care for their young grandchildren, making it easier for both parents to work.\n\nWhile it is true that an ageing population poses challenges for governments, it is clear that these are outweighed by the significant benefits that elderly people bring to society.",
        }]
      }
    ]
  },
  {
    id: 'b18-t4-s5',
    title: 'Test 4: Speaking P1-3',
    section: Section.SPEAKING,
    parts: [
      {
        questions: [{
          id: 'b18t4sq1',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 1: Example',
          question: 'Sleep\n\n- How many hours do you usually sleep at night?\n- Do you sometimes sleep during the day? [Why/Why not?]\n- What do you do if you can’t get to sleep at night? [Why?]\n- Do you ever remember the dreams you’ve had while you were asleep?',
          sampleAnswer: `**1. How many hours do you usually sleep at night?**\n"I usually get around seven to eight hours of sleep a night. I try to be quite consistent with my sleeping schedule, even on weekends, as I find it helps me feel more rested and energetic during the day."\n\n**2. Do you sometimes sleep during the day?**\n"Not usually, no. I find that if I take a nap during the day, it makes it much harder for me to fall asleep at night. However, on a rare occasion, if I've had a very poor night's sleep, I might take a short 20-minute power nap in the afternoon to recharge."\n\n**3. What do you do if you can’t get to sleep at night?**\n"If I'm struggling to fall asleep, I try not to just lie there and get frustrated. I'll get up and do something relaxing for a little while, like reading a book in a dimly lit room or listening to some calm music. Usually, that helps my mind to switch off, and then I can go back to bed and fall asleep."\n\n**4. Do you ever remember the dreams you’ve had while you were asleep?**\n"Yes, sometimes I do, quite vividly. It's often just for a few moments after I wake up, and then the details start to fade away. They're usually quite random and don't make much sense, but it's always interesting to try and piece together what my brain was up to while I was sleeping."`
        }]
      },
      {
        questions: [{
          id: 'b18t4sq2',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 2: Cue Card',
          question: 'Describe a time when you met someone who you became good friends with.\nYou should say:\n- who you met\n- where and when you met this person\n- what you thought about this person when you first met\n- and explain why you think you became good friends with this person.',
          sampleAnswer: `I'd like to talk about meeting one of my best friends, Alex. I met him about five years ago when I started a new job. We were both new starters in the same department, and we met on our first day during the company induction.\n\nInitially, I just thought he seemed like a friendly and approachable person. He had a really good sense of humour, and during the slightly boring parts of the training, he would make quiet, funny comments that made me laugh. I remember thinking that he would probably be a good person to work with.\n\nWe became good friends because we spent a lot of time together in those first few weeks, learning the ropes of the new job. We quickly discovered we had a lot in common. We both love hiking and are big fans of the same kind of music. We started going for lunch together, and that soon turned into hanging out after work and on weekends. I think the reason our friendship developed so strongly is because we have a very similar outlook on life and we can talk about anything. He's very easy-going and supportive, and we just clicked right away.`
        }]
      },
      {
        questions: [{
          id: 'b18t4sq3',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 3: Discussion topics',
          question: 'Friends at school\n- How important is it for children to have lots of friends at school?\n- Do you think it is wrong for parents to influence which friends their children have?\n- Why do you think children often choose to influence which friends they get as they get older?\n\nMaking new friends\n- If a person is moving to a new town, what is a good way to make new friends?\n- Can you think of any disadvantages of making new friends online?\n- Would you say that it is harder for people to make new friends as they get older?',
          sampleAnswer: `**Friends at school**\n\n**1. How important is it for children to have lots of friends at school?**\n"I think it's very important. Having friends at school is crucial for a child's social and emotional development. It teaches them vital skills like cooperation, sharing, and resolving conflicts. A good circle of friends provides a support system and makes the school experience much more enjoyable and less intimidating."\n\n**2. Do you think it is wrong for parents to influence which friends their children have?**\n"That's a tricky one. I don't think it's 'wrong' for parents to be concerned and offer guidance, especially if they see their child getting involved with a friend who is a bad influence. However, I think parents shouldn't be overly controlling. Children need to learn to make their own judgments about people, and trying to forbid a friendship can often backfire."\n\n**3. Why do you think children often choose different friends as they get older?**\n"As children mature, their personalities and interests develop and change. A friend they had a lot in common with in primary school might have very different interests by the time they are teenagers. They start to form their own identity and naturally gravitate towards peers who share their new hobbies, values, or academic interests. It's a natural part of growing up."\n\n**Making new friends**\n\n**4. If a person is moving to a new town, what is a good way to make new friends?**\n"Joining clubs or groups based on hobbies is a great way. Whether it's a sports team, a book club, or a volunteering group, it's an easy way to meet like-minded people with shared interests. Taking a class, perhaps at a local community college, can also be effective. It provides a structured environment to interact with new people regularly."\n\n**5. Can you think of any disadvantages of making new friends online?**\n"Yes, there are a few. The main one is safety; you can never be 100% sure who you are talking to. There's also the risk of miscommunication, as you miss out on tone of voice and body language. And sometimes, an online friendship doesn't translate well into the real world because the chemistry just isn't the same in person."\n\n**6. Would you say that it is harder for people to make new friends as they get older?**\n"Generally, yes, I would say it is. When you're young, you're constantly in environments like school and university that are designed for social interaction. As adults, people's lives become busier with work and family commitments, so there are fewer opportunities to meet new people. People also tend to become more settled in their existing social circles and may be less open to forming new, deep connections."`
        }]
      }
    ]
  }
];
