

import { Lesson, QuestionType, Section } from '../types';

const ielts19ReadingPassage1Test4 = `According to conservationists, populations of around two thirds of butterfly species have declined in Britain over the past 40 years. If this trend continues, it might have unpredictable knock-on effects for other species in the ecosystem. Butterfly eggs develop into caterpillars and these insects, which are the second stage in a new butterfly’s lifecycle, consume vast quantities of plant material, and in turn act as prey for birds as well as bats and other small mammals. Only by arming themselves with an understanding of why butterfly numbers are down can conservationists hope to halt or reverse the decline.

Butterflies prefer outdoor conditions to be ‘just right’, which means neither too hot nor too cold. Under the conditions of climate change, the temperature at any given time in summer is generally getting warmer, leaving butterflies with the challenge of how to deal with this. One of the main ways in which species are ensuring conditions suit them is by changing the time of year at which they are active and reproduce. Scientists refer to the timing of such lifecycle events as ‘phenology’, so when an animal or plant starts to do something earlier in the year than it usually does, it is said to be ‘advancing its phenology’.

These advances have been observed already in a wide range of butterflies – indeed, most species are advancing their phenology to some extent. In Britain, as the average spring temperature has increased by roughly 0.5 °C over the past 20 years, species have advanced by between three days and a week on average, to keep in line with cooler temperatures. Is this a sign that butterflies are well equipped to cope with climate change, and can readily adjust to new temperatures? Or are these populations under stress, being dragged along unwillingly by unnaturally fast changes? The answer is still unknown, but a new study is seeking to answer these questions.

First, the researchers pulled together data from millions of records that had been submitted by butterfly enthusiasts – people who spend their free time observing the activities of different species. This provided information on 130 species of butterflies in Great Britain every year for a 20-year period. They then estimated the abundance and distribution of each species across the country, along with how far north in the country they had moved. The data also, crucially, allowed researchers to estimate subtle changes in what time of the year each species was changing into an adult butterfly.

Analysing the trends in each variable, the researchers discovered that species with more flexible lifecycles were more likely to be able to benefit from an earlier emergence driven by climate change. Some species are able to go from caterpillar to butterfly twice or more per year, so that the individual butterflies you see flying in the spring are the grandchildren or great-grandchildren of the individuals seen a year previously. Among these species, researchers observed that those which have been advancing their phenology the most over the 20-year study period also had the most positive trends in abundance, distribution and northwards extent. For these species, there is an advantage to emerging earlier. Indeed, worryingly, it was found that the species in this group that specialise in very specific habitat types, often related to the caterpillar’s preferred diet, actually tended to be most at harm from advancing phenology. The beautiful High Brown Fritillary, often described as Britain’s most endangered butterfly, is in this group. It is found only in coppiced woodland and limestone pavement habitats. It is also a single-generation butterfly that has advanced its phenology. This suggests that climate change, while undoubtedly not the sole cause, may have played a part in the downfall of this species.

All is not lost, however. Many of Britain’s single-generation species show the capacity, in continental Europe, to add a second generation in years that are sufficiently warm. Therefore, as the climate continues to warm, species like the Silver-studded Blue might be able to switch to multiple generations in the UK as well, and so begin to extract benefits from the additional warmth, potentially leading to population increases.

More immediately, conservationists can arm themselves with all this new knowledge to spot the warning signs of species that may be at risk. The White Admiral of southern England, a much sought-after butterfly, experienced a significant increase in numbers from the 1920s but has shown a considerable decline in the past 20 years. This may be because the caterpillar exists solely on a diet of a plant called honeysuckle. But it is also likely to be due to climate change.`;

const ielts19ReadingPassage2Test4 = `Bacteria from the ocean floor can beat superbugs and cancer. But habitats are at risk from the hunger for marine minerals

A When Professor Mat Upton found that a microbe from a deep-sea sponge was killing pathogenic bugs in his laboratory, he realised it could be a breakthrough in the fight against antibiotic-resistant superbugs, which are responsible for thousands of deaths a year in the UK alone. Further tests confirmed that an antibiotic from the sponge bacteria, found living more than 700 metres under the sea at the Rockall trough in the north-east Atlantic, was previously unknown to science. It’s a life-saving medicine. But Upton, a medical microbiologist at the University of Plymouth. He and other scientists who view the deep ocean and its wealth of unique and undocumented species as a prospecting ground for new medicines, fear such potential will be lost in the rush to exploit the deep sea’s equally rich metal and mineral resources.

B ‘We’re looking at the bioactive potential of marine resources, to see if there are any more medicines or drugs down there before we destroy it for ever,’ says Upton, a medical microbiologist at the University of Plymouth. He is among many scientists trying a halt to deep-sea mining, asking for time to weigh up the pros and cons. ‘In sustainability terms, this could be a better way of exploiting the economic potential of the deep sea,’ he argues. Oceanographers using remotely operated vehicles have spotted many new species. Among them have been sea cucumbers with tails allowing them to sail along the ocean floor, and a rare ‘Dumbo’ octopus, found 3,000 metres under the Pacific Ocean, off the coast of California. Any one of these could offer lifesaving potential. Upton estimates it could take up to a decade for a newly discovered antibiotic to become a medicine – but the race towards commercial mining in the ocean abyss has already begun.

C The deep sea contains more nickel, cobalt and rare earth metals than all land reserves combined, according to the US Geological Survey. Mining corporations argue that deep-sea exploration could help diversify the supply of metals and point to the fact that demand for resources such as copper, aluminium, cobalt for electric car batteries and other metals to power technology and smartphones, is soaring. They say that deep-sea mining could yield far superior ore to land mining with less waste. Different methods of extraction exist, but most involve employing some form of converted machinery previously used in terrestrial mining to excavate materials from the sea floor, at depths of up to 6,000 metres, then drawing a seawater slurry, containing rock and other solid particles, from the sea floor to ships on the surface. The slurry is then ‘de-watered’ and transferred to another vessel for shipping. Extracted seawater is pumped back down and discharged close to the sea floor.

D But environmental and legal groups have urged caution, arguing there are potentially massive and unknown ramifications for the environment and for nearby communities, and that the global regulatory framework is not yet drafted. ‘Despite arising in the last half century, the “new global gold rush” of deep-sea mining shares many features with past resource scrambles – including a general disregard for environmental and social impacts, and the marginalisation of indigenous peoples and their rights,’ a paper, written by Julie Hunter and Julian Aguon, from Blue Ocean Law, and Pradeep Singh, from the Centre for Marine Environmental Sciences, Bremen, argues. The authors say that knowledge of the deep seabed remains extremely limited, and that the surface of the Moon, Mars and even Venus have all been mapped and studied in much greater detail, leading marine scientists to commonly remark that, with respect to the deep sea, ‘We don’t yet know what we need to know*.*’

E Scientific research – including a recent paper in Marine Policy journal – has suggested the deep seabed and hydrothermal vents, which are created when seawater meets volcanic magma, have crucial impacts upon biodiversity and the global climate. The mineral-rich vents and their surrounds are also home to many well-known animals including crustaceans, tubeworms, clams, slugs, anemones and fish. ‘It is becoming increasingly clear that deep-sea mining poses a grave threat to these vital seabed functions,’ the paper says. ‘Extraction methods would produce large sediment plumes and involve the discharge of waste back into the ocean, significantly disturbing seabed environments,’ the paper continues. ‘On deep sea vents, scientists are clear,’ says Dr Jon Copley of the National Oceanography Centre, Southampton: ‘we don’t want mining on them.’

F The oceans occupy around 70% of the planet and are relatively unexplored, says Mike Johnston, chief executive of Nautilus, a Canadian underwater exploration company: ‘It makes sense to explore this untapped potential in an environmentally sustainable way, instead of continually looking at the fast depleting land resources of the planet to meet society’s rising needs.’ Those leading the global rush to place giant mining machines thousands of metres below the sea surface say the environmental impacts will be far lower than on land. But critics say exotic and little-known ecosystems in the deep oceans could be destroyed and must be protected. ‘Mining will be the greatest assault on deep-sea ecosystems ever inflicted by humans,’ according to hydrothermal vent expert Verena Tunnicliffe, at the University of Victoria in Canada. She argues that active vents must be off-limits for mining to protect the new knowledge and biotechnology spin-offs they can deliver, and that strict controls must be in place elsewhere.`;

const ielts19ReadingPassage3Test4 = `The Unselfish Gene

A psychologist gives his view on how humans became self-centred

There has long been a general assumption that human beings are essentially selfish. We’re apparently ruthless, with strong impulses to compete against each other for resources and to accumulate power and possessions. If we are kind to one another, it’s usually because we have ulterior motives. If we are good, it’s only because we have managed to control and transcend our innate selfishness and brutality.

This bleak view of human nature is closely associated with the science writer Richard Dawkins, whose 1976 book The Selfish Gene became popular because it fitted so well with – and helped to justify – the competitive and individualistic ethos that was so prevalent in late 20th-century societies. Like many others, Dawkins justifies his views with reference to the field of evolutionary psychology. Evolutionary psychology theorises that present-day human traits developed in prehistoric times, during what is termed the ‘environment of evolutionary adaptedness’.

Prehistory is usually seen as a period of intense competition, when life was such a brutal battle that only those with traits such as selfishness, aggression and ruthlessness survived. And because survival depended on access to resources – such as rivers, forests and animals – there was bound to be conflict between rival groups, which led to the development of traits such as racism and warfare. This seems logical. But, in fact, the assumption on which this all rests – that prehistoric life was a desperate struggle for survival – is false.

It’s important to remember that in the prehistoric era, the world was very sparsely populated. According to some estimates, around 15,000 years ago, the population of Europe was only 29,000, and the population of the whole world was less than half a million. At that time there were hunter-gatherers: people who lived by hunting wild animals and collecting wild plants. With such small population densities, it seems unlikely that prehistoric hunter-gatherers had to compete against each other for resources or had any need to develop ruthlessness and competitiveness, or to go to war.

There is significant evidence to back this notion from contemporary hunter-gatherer groups, who live in the same way as prehistoric humans did. As the anthropologist Bruce Knauft has remarked, hunter-gatherers are characterised by ‘extreme political and sexual egalitarianism’. Knauft has observed that individuals in such groups don’t accumulate property or possessions and have an ethical obligation to share everything. They also have methods of preserving egalitarianism by ensuring that disparities of status don’t arise.

The !Kung people of southern Africa, for example, swap arrows before going hunting and when an animal is killed, the acclaim does not go to the person who fired the arrow, but to the person the arrow belongs to. And if a person becomes too domineering, the other members of the group ostracise them, exiling the offender from society. Typically in such groups, men do not dictate what women do. Women in hunter-gatherer groups worldwide often benefit from a high level of autonomy, being able to select their own marriage partners, decide what work they do and work whenever they choose to. And if a marriage breaks down, they have custody rights over their children.

Many anthropologists believe that societies such as the !Kung were normal until a few thousand years ago, when population growth led to the development of agriculture and a settled lifestyle. In view of the above, there seems little reason to assume that traits such as racism, warfare and male domination should have been selected by evolution – as they would have been of little benefit in the prehistoric era. Individuals who behaved selfishly and ruthlessly would be less likely to survive, since they would have been ostracised from their groups.

It makes more sense, then, to see traits such as cooperation, egalitarianism, altruism and peacefulness as innate characteristics of human beings. These were the traits that were prevalent in human life for tens of thousands of years. So presumably these traits are still strong in us now.

But if prehistoric life wasn’t really as brutal as has often been assumed, why do modern humans behave so selfishly and ruthlessly? Perhaps these negative traits should be seen as a later development, the result of environmental and psychological factors. Research has shown repeatedly that when the natural habitats of primates such as apes and gorillas are disrupted, they tend to become more violent and hierarchical.

So, it could well be that the same thing has happened to us. I believe that the end of the hunter-gatherer lifestyle and the advent of farming was connected to a psychological change that occurred in some groups of people. There was a new sense of individuality and separateness, which led to a new selfishness, and ultimately to hierarchical societies, patriarchy and warfare. At any rate, these negative traits appear to have developed so recently that it doesn’t seem feasible to explain them in adaptive or evolutionary terms.`;

export const ielts19Test4Lessons: Lesson[] = [
    // Test 4
    {
        id: 'b19-t4-l0',
        title: 'Test 4: Listening P1-2',
        section: Section.LISTENING,
        parts: [
            { // Part 1
                questions: [
                    { id: 'b19t4lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t4-p1.mp3', questionText: 'Name of supervisor: 1 ___', correctAnswers: ['Kaeden'], transcript: "Hello Charlotte. I'm Kaeden, one of the supervisors. ... It's Kaeden. It's K-A-E-D-E-N.", transcriptHighlight: 'Kaeden' },
                    { id: 'b19t4lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t4-p1.mp3', questionText: 'Where to leave coat and bag: use 2 ___ in staffroom', correctAnswers: ['locker', 'lockers'], transcript: "Put your coat and rucksack in one of the lockers there.", transcriptHighlight: 'lockers' },
                    { id: 'b19t4lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t4-p1.mp3', questionText: 'See Tiffany in HR: to give 3 ___ number', correctAnswers: ['passport'], transcript: "I was told to bring my passport with me. HR need to take a note of the number in it.", transcriptHighlight: 'passport' },
                    { id: 'b19t4lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t4-p1.mp3', questionText: 'to collect 4 ___', correctAnswers: ['uniform'], transcript: "OK. Tiffany will give you a uniform. They have lots in different sizes, so you just tell her what you need.", transcriptHighlight: 'uniform' },
                    { id: 'b19t4lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t4-p1.mp3', questionText: 'Location of HR office: on 5 ___ floor', correctAnswers: ['third', '3rd'], transcript: "The staffroom’s on the first floor, and HR are a couple of floors above that, on the third floor.", transcriptHighlight: 'third floor' },
                    { id: 'b19t4lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the notes. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-19/t4-p1.mp3', questionText: 'Supervisor’s mobile number: 6 ___', correctAnswers: ['0412665903'], transcript: "I'll just give you my phone number... It's oh-four-one-two double-six-five nine-oh-three.", transcriptHighlight: 'oh-four-one-two double-six-five nine-oh-three' },
                    { id: 'b19t4lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p1.mp3', questionText: 'Change price labels | Use 7 ___ labels', correctAnswers: ['yellow'], transcript: "For today, you'll put a new price label on the packaging. Yes, but that shouldn't happen - we check the stock every day. When something needs a new price label, put a yellow one on the package, next to the original price.", transcriptHighlight: 'yellow' },
                    { id: 'b19t4lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p1.mp3', questionText: 'Re-stock with 8 ___ boxes if needed', correctAnswers: ['plastic'], transcript: "You'll see lots of flat cardboard boxes at one end of the counter. Beneath those is where we keep the plastic boxes - we run out of those really quickly, so you should bring more from the storeroom.", transcriptHighlight: 'plastic boxes' },
                    { id: 'b19t4lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p1.mp3', questionText: 'Collect 9 ___ for the fish from the cold-room', correctAnswers: ['ice'], transcript: "The fish is laid on ice, but when that starts to melt, you'll need to get more from the cold-room.", transcriptHighlight: 'ice' },
                    { id: 'b19t4lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Part 1: Complete the table. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p1.mp3', questionText: 'Must wear special 10 ___', correctAnswers: ['gloves'], transcript: "You won't be serving customers directly, so no. But make sure you put on thermal gloves when you take anything out of the cold-room.", transcriptHighlight: 'gloves' },
                ],
            },
            { // Part 2
                questions: [
                    { id: 'b19t4lq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose TWO letters, A–E.', maxSelections: 2, audioUrl: 'ielts-19/t4-p2.mp3', questionText: 'Which TWO problems with some training programmes for new runners does Liz mention?', options: ['A There is a risk of serious injury.', 'B They are unsuitable for certain age groups.', 'C They are unsuitable for people with health issues.', 'D It is difficult to stay motivated.', 'E There is a lack of individual support.'], correctAnswers: ['C They are unsuitable for people with health issues.', 'E There is a lack of individual support.'], transcript: "However, they don’t work for everyone – especially if you suffer from something like a heart condition or asthma, because they’re aimed at people with average fitness and running ability. Another thing is that everyone is different – and if you have any specific questions related to your needs, there’s no one to provide any answers.", transcriptHighlight: 'suffer from something like a heart condition or asthma... no one to provide any answers' },
                    { id: 'b19t4lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 2: Choose TWO letters, A–E.', maxSelections: 2, audioUrl: 'ielts-19/t4-p2.mp3', questionText: 'Which TWO tips does Liz recommend for new runners?', options: ['A doing two runs a week', 'B running in the evening', 'C going on runs with a friend', 'D running very slowly', 'E listening to music during runs'], correctAnswers: ['A doing two runs a week', 'D running very slowly'], transcript: "I have a couple of simple tips I always give to new runners. I expect you’ve been told to run very slowly until your fitness increases. ... She was worried about being left behind and being the slowest runner. But she says she was made to feel so welcome she soon forgot all about that. She was advised to train regularly – twice a week is enough to begin with.", transcriptHighlight: 'run very slowly... twice a week' },
                    { id: 'b19t4lq15', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: What reason prevented each of the following members... from joining until recently?", audioUrl: 'ielts-19/t4-p2.mp3', questionText: '15 Ceri', options: ['A a lack of confidence', 'B a dislike of running', 'C a lack of time'], correctAnswers: ['A a lack of confidence'], transcript: "Ceri, for example, joined the club two years ago at the age of 40. She’d always enjoyed running at school but wasn’t sure if she’d be able to do it. She was worried about being left behind and being the slowest runner.", transcriptHighlight: 'wasn’t sure if she’d be able to do it' },
                    { id: 'b19t4lq16', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: What reason prevented each of the following members... from joining until recently?", audioUrl: 'ielts-19/t4-p2.mp3', questionText: '16 James', options: ['A a lack of confidence', 'B a dislike of running', 'C a lack of time'], correctAnswers: ['B a dislike of running'], transcript: "James had always hated the idea of running but a friend encouraged him to come along for a taster session and he hasn’t looked back.", transcriptHighlight: 'hated the idea of running' },
                    { id: 'b19t4lq17', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: What reason prevented each of the following members... from joining until recently?", audioUrl: 'ielts-19/t4-p2.mp3', questionText: '17 Leo', options: ['A a lack of confidence', 'B a dislike of running', 'C a lack of time'], correctAnswers: ['C a lack of time'], transcript: "Leo was worried about having to commit himself to training sessions every week and wasn’t sure he’d be able to fit training into his busy schedule.", transcriptHighlight: 'fit training into his busy schedule' },
                    { id: 'b19t4lq18', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: What reason prevented each of the following members... from joining until recently?", audioUrl: 'ielts-19/t4-p2.mp3', questionText: '18 Mark', options: ['A a lack of confidence', 'B a dislike of running', 'C a lack of time'], correctAnswers: ['A a lack of confidence'], transcript: "Mark is quite typical of our new members. He’s never considered himself to be a sporty person and it was only when he retired that he decided to take up the challenge of trying to run 5 kilometres. It took him months to find the courage to contact us but felt reassured immediately as there were other people his age who were only just taking up running for the first time.", transcriptHighlight: 'find the courage' },
                    { id: 'b19t4lq19', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: Choose the correct letter, A, B or C.", audioUrl: 'ielts-19/t4-p2.mp3', questionText: "What does Liz say about running her first marathon?", options: ['It had always been her ambition.', 'Her husband persuaded her to do it.', 'She nearly gave up before the end.'], correctAnswers: ['She nearly gave up before the end.'], transcript: "I felt like giving up halfway through – it was only the support of the spectators that kept me going.", transcriptHighlight: 'felt like giving up' },
                    { id: 'b19t4lq20', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 2: Choose the correct letter, A, B or C.", audioUrl: 'ielts-19/t4-p2.mp3', questionText: "Liz says new runners should sign up for a race", options: ['every six months.', 'within a few weeks of taking up running.', 'after completing several practice runs.'], correctAnswers: ['within a few weeks of taking up running.'], transcript: "But after you’ve been running for a few weeks, it’s worth putting your name down for a 5K", transcriptHighlight: 'after you’ve been running for a few weeks' },
                ]
            }
        ]
    },
    {
        id: 'b19-t4-l1',
        title: 'Test 4: Listening P3-4',
        section: Section.LISTENING,
        parts: [
            { // Part 3
                questions: [
                    { id: 'b19t4lq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t4-p3.mp3', questionText: "Kieran thinks the packing advice given by Jane’s grandfather is", options: ['common sense.', 'hard to follow.', 'over-protective.'], correctAnswers: ['common sense.'], transcript: "Well, I hope they don’t get spoilt. It’s OK – my grandfather works in a bookshop and he told me how to pack them. Oh, that’s helpful. He says you have to support the spine otherwise the paper can come away from the cover. Yeah – that’s obvious.", transcriptHighlight: 'Yeah – that’s obvious' },
                    { id: 'b19t4lq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t4-p3.mp3', questionText: 'How does Jane feel about the books her grandfather has given her?', options: ['They are not worth keeping.', 'They should go to a collector.', 'They have sentimental value for her.'], correctAnswers: ['They have sentimental value for her.'], transcript: "You know some of the books my grandfather’s given me are like that already. Oh. I should dump them really if they’re going to deteriorate further, but I’d feel bad. They’ll always remind me of him.", transcriptHighlight: 'They’ll always remind me of him' },
                    { id: 'b19t4lq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t4-p3.mp3', questionText: 'Jane and Kieran agree that hardback books should be', options: ['put on display.', 'given as gifts to visitors.', 'more attractively designed.'], correctAnswers: ['put on display.'], transcript: "That’s such a pity. When I visit someone – if they have, say, a colourful book on a table, it’s the first thing I’m drawn to. I agree – and book covers can be a work of art in themselves.", transcriptHighlight: 'I agree' },
                    { id: 'b19t4lq24', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t4-p3.mp3', questionText: 'While talking about taking a book from a shelf, Jane', options: ['describes the mistakes other people make doing it.', 'reflects on a significant childhood experience.', 'explains why some books are easier to remove than others.'], correctAnswers: ['reflects on a significant childhood experience.'], transcript: "He watched me pull a heavy book off the shelf when I was small, and it fell on the floor and broke apart. Oh dear! I can still remember it!", transcriptHighlight: 'I can still remember it!' },
                    { id: 'b19t4lq25', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-19/t4-p3.mp3', questionText: 'What do Jane and Kieran suggest about new books?', options: ['Their parents liked buying them as presents.', 'They would like to buy more of them.', 'Not everyone can afford them.'], correctAnswers: ['Not everyone can afford them.'], transcript: "My parents used to laugh at me when I was a kid because I loved putting books up to my nose. Almost as much as reading them! New books aren’t cheap, though, are they? I guess we’re lucky we can buy them.", transcriptHighlight: 'New books aren’t cheap, though, are they?' },
                    { id: 'b19t4lq26', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 3: Where does Jane's grandfather keep each of the following types of books?", audioUrl: 'ielts-19/t4-p3.mp3', questionText: '26 rare books', options: ['A near the entrance', 'B in the attic', 'C at the back of the shop', 'D on a high shelf', 'E near the stairs', 'F in a specially designed space', 'G within the café'], correctAnswers: ['D on a high shelf'], transcript: "I guess he treasures things like first editions and other rare books. Yeah – you might think he’d keep those in the attic or somewhere. So they’d be hidden? Yeah. But he likes people to know that he has them. So, he puts them out in the shop but makes sure you need a ladder to get them.", transcriptHighlight: 'need a ladder to get them' },
                    { id: 'b19t4lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 3: Where does Jane's grandfather keep each of the following types of books?", audioUrl: 'ielts-19/t4-p3.mp3', questionText: "27 children's books", options: ['A near the entrance', 'B in the attic', 'C at the back of the shop', 'D on a high shelf', 'E near the stairs', 'F in a specially designed space', 'G within the café'], correctAnswers: ['F in a specially designed space'], transcript: "Not exactly – he’s got a dedicated area on the ground floor with cushions so that parents can enter with their toddlers, go there and spend some time reading to them.", transcriptHighlight: 'dedicated area on the ground floor' },
                    { id: 'b19t4lq28', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 3: Where does Jane's grandfather keep each of the following types of books?", audioUrl: 'ielts-19/t4-p3.mp3', questionText: '28 unwanted books', options: ['A near the entrance', 'B in the attic', 'C at the back of the shop', 'D on a high shelf', 'E near the stairs', 'F in a specially designed space', 'G within the café'], correctAnswers: ['A near the entrance'], transcript: "he hardly ever throws anything away – he just leaves unwanted books by the front door for customers to take.", transcriptHighlight: 'by the front door' },
                    { id: 'b19t4lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 3: Where does Jane's grandfather keep each of the following types of books?", audioUrl: 'ielts-19/t4-p3.mp3', questionText: '29 requested books', options: ['A near the entrance', 'B in the attic', 'C at the back of the shop', 'D on a high shelf', 'E near the stairs', 'F in a specially designed space', 'G within the café'], correctAnswers: ['C at the back of the shop'], transcript: "Yeah – and books people or institutions have requested, they all go at the far end.", transcriptHighlight: 'at the far end' },
                    { id: 'b19t4lq30', type: QuestionType.MULTIPLE_CHOICE, prompt: "Part 3: Where does Jane's grandfather keep each of the following types of books?", audioUrl: 'ielts-19/t4-p3.mp3', questionText: '30 coursebooks', options: ['A near the entrance', 'B in the attic', 'C at the back of the shop', 'D on a high shelf', 'E near the stairs', 'F in a specially designed space', 'G within the café'], correctAnswers: ['G within the café'], transcript: "They’re actually part of the coffee shop, on low shelves all around it.", transcriptHighlight: 'part of the coffee shop' },
                ]
            },
            { // Part 4
                questions: [
                    { id: 'b19t4lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p4.mp3', questionText: 'not include invasive species because of possible 31 ___ with native species', correctAnswers: ['competition'], transcript: "Invasive species are a significant contributor to the current global biodiversity crisis and are often in competition with native species and may threaten their long-term survival.", transcriptHighlight: 'competition' },
                    { id: 'b19t4lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p4.mp3', questionText: 'provide sustainable sources of 32 ___ for local people', correctAnswers: ['food'], transcript: "These could include selecting trees that can contribute to wildlife conservation, improve the availability of food for the local community and maintain the stability of soil systems.", transcriptHighlight: 'food' },
                    { id: 'b19t4lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p4.mp3', questionText: 'use tree seeds with a high genetic diversity to increase resistance to 33 ___ and climate change', correctAnswers: ['disease'], transcript: "Using seeds with low genetic diversity generally lowers the resilience of restored forests, which can make them vulnerable to disease and unable to adapt to climate change.", transcriptHighlight: 'disease' },
                    { id: 'b19t4lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p4.mp3', questionText: 'plant trees on previously forested land which is in a bad condition, not select land which is being used for 34 ___', correctAnswers: ['agriculture'], transcript: "Reforesting areas which are currently exploited for agriculture should be avoided as this often leads to other areas being deforested.", transcriptHighlight: 'agriculture' },
                    { id: 'b19t4lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p4.mp3', questionText: 'Base planning decisions on information from accurate 35 ___', correctAnswers: ['maps'], transcript: "Having detailed and up-to-date maps identifying high-priority areas for reforestation is essential.", transcriptHighlight: 'maps' },
                    { id: 'b19t4lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p4.mp3', questionText: 'Drones are useful for identifying areas in Brazil which are endangered by keeping 36 ___ and illegal logging.', correctAnswers: ['cattle'], transcript: "In Brazil, it’s being used to identify and quantify how parts of the Amazon are being devastated by human activities such as rearing cattle and illegal logging.", transcriptHighlight: 'cattle' },
                    { id: 'b19t4lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p4.mp3', questionText: 'increasing the 37 ___ of recovery by attracting animals and birds', correctAnswers: ['speed'], transcript: "These species are known to tropical forest ecosystems as they accelerate the speed of the recovery process by attracting animals and birds", transcriptHighlight: 'speed' },
                    { id: 'b19t4lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p4.mp3', questionText: 'e.g., 38 ___ were soon attracted to the area.', correctAnswers: ['monkeys'], transcript: "At the site, after only three rainy seasons, monkeys started visiting to eat the fig fruits, naturally dispersing seeds", transcriptHighlight: 'monkeys' },
                    { id: 'b19t4lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p4.mp3', questionText: 'Destruction of mangrove forests in Madagascar made it difficult for people to make a living from 39 ___.', correctAnswers: ['fishing'], transcript: "Destruction of the mangrove forests had a terrible impact on plant and animal life, and also badly affected the fishing industry", transcriptHighlight: 'fishing' },
                    { id: 'b19t4lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-19/t4-p4.mp3', questionText: 'protects against the higher risk of 40 ___', correctAnswers: ['flooding'], transcript: "The mangroves also act as a defence against the increased threat of flooding caused by climate change.", transcriptHighlight: 'flooding' },
                ]
            }
        ]
    },
    {
        id: 'b19-t4-r2',
        title: 'Test 4: Reading P1',
        section: Section.READING,
        parts: [{
            questions: [
                { id: 'b19t4rq1', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test4, questionText: 'Forty years ago, there were fewer butterflies in Britain than at present.', options: ['True', 'False', 'Not Given'], correctAnswers: ['False'], passageHighlight: "populations of around two thirds of butterfly species have declined in Britain over the past 40 years.", reason: "The passage states that two-thirds of species have declined, which means there were more butterflies 40 years ago, not fewer. This directly contradicts the statement." },
                { id: 'b19t4rq2', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test4, questionText: 'Caterpillars are eaten by a number of different predators.', options: ['True', 'False', 'Not Given'], correctAnswers: ['True'], passageHighlight: "and in turn act as prey for birds as well as bats and other small mammals.", reason: "The passage explicitly states that caterpillars 'act as prey' for various animals like birds and bats, which means they are eaten by different predators." },
                { id: 'b19t4rq3', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test4, questionText: "'Phenology' is a term used to describe a creature's ability to alter the location of a lifecycle event.", options: ['True', 'False', 'Not Given'], correctAnswers: ['False'], passageHighlight: "Scientists refer to the timing of such lifecycle events as ‘phenology’", reason: "The passage defines 'phenology' as being related to the 'timing' of lifecycle events, not the 'location'. This contradicts the statement." },
                { id: 'b19t4rq4', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test4, questionText: 'Some species of butterfly have a reduced lifespan due to spring temperature increases.', options: ['True', 'False', 'Not Given'], correctAnswers: ['Not Given'], passageHighlight: "Some species are able to go from caterpillar to butterfly twice or more per year", reason: "The passage mentions that some species can complete their lifecycle more quickly and have more generations per year due to warmer temperatures. However, it provides no information about the lifespan of an individual butterfly. Therefore, the statement is not given." },
                { id: 'b19t4rq5', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test4, questionText: 'There is a clear reason for the adaptations that butterflies are making to climate change.', options: ['True', 'False', 'Not Given'], correctAnswers: ['False'], passageHighlight: "Or are these populations under stress... The answer is still unknown", reason: "The passage explicitly poses the question of whether the butterflies' adaptation is a good sign or a sign of stress, and then states, 'The answer is still unknown.' This shows there is not a clear reason." },
                { id: 'b19t4rq6', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts19ReadingPassage1Test4, questionText: 'The data used in the study was taken from the work of amateur butterfly watchers.', options: ['True', 'False', 'Not Given'], correctAnswers: ['True'], passageHighlight: "data from millions of records that had been submitted by butterfly enthusiasts", reason: "'Butterfly enthusiasts' who spend their free time observing butterflies are amateur watchers. The statement is a correct paraphrase." },
                { id: 'b19t4rq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test4, questionText: 'The Small Blue | lives in large 7 ___', correctAnswers: ['colonies'], passageHighlight: "the dainty Small Blue, whose colonies are up to a hundred strong", reason: "The passage explicitly mentions 'the dainty Small Blue, whose colonies are up to a hundred strong'." },
                { id: 'b19t4rq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test4, questionText: 'first appears at the start of 8 ___', correctAnswers: ['spring'], passageHighlight: "the individual butterflies you see flying in the spring are the grandchildren or great-grandchildren of the individuals seen a year previously.", reason: "The passage talks about species with multiple lifecycles per year, with individuals 'flying in the spring'." },
                { id: 'b19t4rq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test4, questionText: 'The High Brown Fritillary | is considered to be more 9 ___ than other species', correctAnswers: ['endangered'], passageHighlight: "The beautiful High Brown Fritillary, often described as Britain’s most endangered butterfly", reason: "The passage directly refers to this butterfly as 'Britain’s most endangered butterfly'." },
                { id: 'b19t4rq10', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test4, questionText: 'its caterpillars occupy a limited range of 10 ___', correctAnswers: ['habitat', 'habitats'], passageHighlight: "It is found only in coppiced woodland and limestone pavement habitats.", reason: "The passage specifies that this butterfly is found 'only in' certain types of habitats, indicating a limited range." },
                { id: 'b19t4rq11', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test4, questionText: 'The Silver-studded Blue | is already able to reproduce twice a year in warm areas of 11 ___', correctAnswers: ['Europe'], passageHighlight: "Many of Britain’s single-generation species show the capacity, in continental Europe, to add a second generation", reason: "The passage explicitly mentions 'continental Europe' as a place where single-generation species can have a second generation in warm years." },
                { id: 'b19t4rq12', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test4, questionText: 'The White Admiral | is found in 12 ___ areas of England', correctAnswers: ['southern'], passageHighlight: "The White Admiral of southern England", reason: "The text directly states 'The White Admiral of southern England'." },
                { id: 'b19t4rq13', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage.', passage: ielts19ReadingPassage1Test4, questionText: 'both climate change and the 13 ___ of the caterpillar are possible reasons for decline', correctAnswers: ['diet'], passageHighlight: "This may be because the caterpillar exists solely on a diet of a plant called honeysuckle.", reason: "The passage identifies the caterpillar's specific 'diet' as a possible reason for the White Admiral's decline." },
            ],
        }],
    },
    {
        id: 'b19-t4-r3',
        title: 'Test 4: Reading P2-3',
        section: Section.READING,
        parts: [
            { // Reading Passage 2
                questions: [
                    { id: 'b19t4rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–F.', passage: ielts19ReadingPassage2Test4, questionText: 'a reference to the rapidly increasing need for one raw material in the transport industry', options: ['A','B','C','D','E','F'], correctAnswers: ['C'], passageHighlight: "cobalt for electric car batteries... is soaring", reason: "Paragraph C mentions the soaring 'demand for resources such as... cobalt for electric car batteries', which is a raw material for the transport industry." },
                    { id: 'b19t4rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–F.', passage: ielts19ReadingPassage2Test4, questionText: 'a rough estimate of the area of the Earth covered by the oceans', options: ['A','B','C','D','E','F'], correctAnswers: ['F'], passageHighlight: "The oceans occupy around 70% of the planet", reason: "Paragraph F begins by stating that 'The oceans occupy around 70% of the planet', which is a rough estimate of the area." },
                    { id: 'b19t4rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–F.', passage: ielts19ReadingPassage2Test4, questionText: 'how a particular underwater habitat, where minerals and organisms co-exist, is formed', options: ['A','B','C','D','E','F'], correctAnswers: ['E'], passageHighlight: "hydrothermal vents, which are created when seawater meets volcanic magma", reason: "Paragraph E explains how 'hydrothermal vents' are formed and notes that these 'mineral-rich vents' are also home to many animals." },
                    { id: 'b19t4rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which paragraph contains the following information? Write the correct letter, A–F.', passage: ielts19ReadingPassage2Test4, questionText: 'reference to the fact that the countries of the world have yet to agree on rules for the exploration of the seabed', options: ['A','B','C','D','E','F'], correctAnswers: ['D'], passageHighlight: "the global regulatory framework is not yet drafted", reason: "Paragraph D states that 'the global regulatory framework is not yet drafted', meaning rules have not been agreed upon." },
                    { id: 'b19t4rq18', type: QuestionType.MULTIPLE_CHOICE, prompt: "Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.", passage: ielts19ReadingPassage2Test4, questionText: 'A move away from the exploration of heavily mined reserves on land is a good idea.', options: ['A Professor Mat Upton', 'B Julie Hunter, Julian Aguon and Pradeep Singh', 'C Dr Jon Copley', 'D Mike Johnston', 'E Verena Tunnicliffe'], correctAnswers: ['D Mike Johnston'], passageHighlight: "It makes sense to explore this untapped potential... instead of continually looking at the fast depleting land resources" },
                    { id: 'b19t4rq19', type: QuestionType.MULTIPLE_CHOICE, prompt: "Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.", passage: ielts19ReadingPassage2Test4, questionText: 'The negative effects of undersea exploration on local areas and their inhabitants are being ignored.', options: ['A Professor Mat Upton', 'B Julie Hunter, Julian Aguon and Pradeep Singh', 'C Dr Jon Copley', 'D Mike Johnston', 'E Verena Tunnicliffe'], correctAnswers: ['B Julie Hunter, Julian Aguon and Pradeep Singh'], passageHighlight: "a general disregard for environmental and social impacts, and the marginalisation of indigenous peoples" },
                    { id: 'b19t4rq20', type: QuestionType.MULTIPLE_CHOICE, prompt: "Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.", passage: ielts19ReadingPassage2Test4, questionText: 'There are more worthwhile things to extract from the sea than minerals.', options: ['A Professor Mat Upton', 'B Julie Hunter, Julian Aguon and Pradeep Singh', 'C Dr Jon Copley', 'D Mike Johnston', 'E Verena Tunnicliffe'], correctAnswers: ['A Professor Mat Upton'], passageHighlight: "to see if there are any more medicines or drugs down there before we destroy it for ever" },
                    { id: 'b19t4rq21', type: QuestionType.MULTIPLE_CHOICE, prompt: "Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.", passage: ielts19ReadingPassage2Test4, questionText: 'No other form of human exploration will have such a destructive impact on marine life as deep-sea mining.', options: ['A Professor Mat Upton', 'B Julie Hunter, Julian Aguon and Pradeep Singh', 'C Dr Jon Copley', 'D Mike Johnston', 'E Verena Tunnicliffe'], correctAnswers: ['E Verena Tunnicliffe'], passageHighlight: "Mining will be the greatest assault on deep-sea ecosystems ever inflicted by humans" },
                    { id: 'b19t4rq22', type: QuestionType.MULTIPLE_CHOICE, prompt: "Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.", passage: ielts19ReadingPassage2Test4, questionText: 'More is known about outer space than about what lies beneath the oceans.', options: ['A Professor Mat Upton', 'B Julie Hunter, Julian Aguon and Pradeep Singh', 'C Dr Jon Copley', 'D Mike Johnston', 'E Verena Tunnicliffe'], correctAnswers: ['B Julie Hunter, Julian Aguon and Pradeep Singh'], passageHighlight: "the surface of the Moon, Mars and even Venus have all been mapped and studied in much greater detail" },
                    { id: 'b19t4rq23', type: QuestionType.MULTIPLE_CHOICE, prompt: "Look at the following statements and the list of people below. Match each statement with the correct person or people, A-E.", passage: ielts19ReadingPassage2Test4, questionText: 'There is one marine life habitat where experts agree mining should not take place.', options: ['A Professor Mat Upton', 'B Julie Hunter, Julian Aguon and Pradeep Singh', 'C Dr Jon Copley', 'D Mike Johnston', 'E Verena Tunnicliffe'], correctAnswers: ['C Dr Jon Copley'], passageHighlight: "On deep sea vents, scientists are clear... we don’t want mining on them" },
                    { id: 'b19t4rq24', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage2Test4, questionText: '...can be removed without producing much 24 ___.', correctAnswers: ['waste'], passageHighlight: "deep-sea mining could yield far superior ore to land mining with less waste" },
                    { id: 'b19t4rq25', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage2Test4, questionText: 'The extraction is often done by adapting the 25 ___ that has already been used to work on land.', correctAnswers: ['machinery'], passageHighlight: "most involve employing some form of converted machinery previously used in terrestrial mining" },
                    { id: 'b19t4rq26', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage2Test4, questionText: '...concerned groups strongly believe that 26 ___ is necessary due to the possible number of unidentified consequences.', correctAnswers: ['caution'], passageHighlight: "environmental and legal groups have urged caution" },
                ]
            },
            { // Reading Passage 3
                questions: [
                    { id: 'b19t4rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test4, questionText: 'What is the writer doing in the first paragraph?', options: ['setting out two opposing views about human nature', 'justifying his opinion about our tendency to be greedy', 'describing a commonly held belief about people’s behaviour', 'explaining why he thinks that humans act in a selfish manner'], correctAnswers: ['describing a commonly held belief about people’s behaviour'], reason: "The paragraph introduces the 'general assumption that human beings are essentially selfish' and elaborates on this single, commonly held belief." },
                    { id: 'b19t4rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test4, questionText: "What point is made about Richard Dawkins' book The Selfish Gene?", options: ['Its appeal lay in the radical nature of its ideas.', 'Its success was due to the scientific support it offered.', 'It presented a view that was in line with the attitudes of its time.', 'It took an innovative approach to the analysis of human psychology.'], correctAnswers: ['It presented a view that was in line with the attitudes of its time.'], reason: "The passage states the book 'became popular because it fitted so well with... the competitive and individualistic ethos that was so prevalent in late 20th-century societies.'" },
                    { id: 'b19t4rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test4, questionText: 'What does the writer suggest about the prehistoric era in the fourth paragraph?', options: ['Societies were more complex than many people believe.', 'Supplies of natural resources were probably relatively plentiful.', 'Most estimates about population sizes are likely to be inaccurate.', 'Humans moved across continents more than was previously thought.'], correctAnswers: ['Supplies of natural resources were probably relatively plentiful.'], reason: "The writer argues that with very small populations, it's 'unlikely that prehistoric hunter-gatherers had to compete against each other for resources,' implying resources were sufficient." },
                    { id: 'b19t4rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts19ReadingPassage3Test4, questionText: 'The writer refers to Bruce Knauft’s work as support for the idea that', options: ['selfishness is a relatively recent development in human societies.', 'only people in isolated communities can live in an unselfish manner.', 'very few lifestyles have survived unchanged since prehistoric times.', 'hunter-gatherer cultures worldwide are declining in number.'], correctAnswers: ['selfishness is a relatively recent development in human societies.'], reason: "Knauft's work shows hunter-gatherers are egalitarian and share everything. The writer uses this to argue these were the original human traits, making selfishness a more recent development." },
                    { id: 'b19t4rq31', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage3Test4, questionText: 'Bruce Knauft’s research shows that contemporary hunter-gatherer societies tend to exhibit a high level of 31 ___ in all areas of life.', correctAnswers: ['egalitarianism'], passageHighlight: "hunter-gatherers are characterised by ‘extreme political and sexual egalitarianism’" },
                    { id: 'b19t4rq32', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage3Test4, questionText: 'These societies also employ strategies to prevent differences in 32 ___ occurring.', correctAnswers: ['status'], passageHighlight: "ensuring that disparities of status don’t arise" },
                    { id: 'b19t4rq33', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage3Test4, questionText: 'for example, the !Kung follow a custom whereby the credit for one person’s success at 33 ___ is given to another member of the group.', correctAnswers: ['hunting'], passageHighlight: "swap arrows before going hunting and when an animal is killed, the acclaim does not go to the person who fired the arrow" },
                    { id: 'b19t4rq34', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage3Test4, questionText: 'Individuals who behave in a 34 ___ manner are punished by being excluded from the group', correctAnswers: ['domineering'], passageHighlight: "if a person becomes too domineering, the other members of the group ostracise them" },
                    { id: 'b19t4rq35', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts19ReadingPassage3Test4, questionText: 'and women have a considerable amount of 35 ___ in choices regarding work and marriage.', correctAnswers: ['autonomy'], passageHighlight: "Women in hunter-gatherer groups worldwide often benefit from a high level of autonomy" },
                    { id: 'b19t4rq36', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test4, questionText: 'Some anthropologists are mistaken about the point when the number of societies such as the !Kung began to decline.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage states what 'Many anthropologists believe' about when these societies changed, but it doesn't mention any disagreement or mistaken views among them." },
                    { id: 'b19t4rq37', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test4, questionText: 'Humans who developed warlike traits in prehistory would have had an advantage over those who did not.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], reason: "The writer argues that traits like warfare 'would have been of little benefit in the prehistoric era,' which contradicts the idea that they provided an advantage." },
                    { id: 'b19t4rq38', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test4, questionText: 'Being peaceful and cooperative is a natural way for people to behave.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], reason: "The writer explicitly states that it 'makes more sense... to see traits such as cooperation, egalitarianism, altruism and peacefulness as innate characteristics of human beings.'" },
                    { id: 'b19t4rq39', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test4, questionText: 'Negative traits are more apparent in some modern cultures than in others.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage discusses the emergence of negative traits in modern humans but does not make a comparison between different modern cultures." },
                    { id: 'b19t4rq40', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the views of the writer in Reading Passage 3?', passage: ielts19ReadingPassage3Test4, questionText: 'Animal research has failed to reveal a link between changes in the environment and the emergence of aggressive tendencies.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], reason: "The passage contradicts this by stating, 'Research has shown repeatedly that when the natural habitats of primates... are disrupted, they tend to become more violent.' This means the research has succeeded, not failed." },
                ]
            }
        ]
    },
    {
        id: 'b19-t4-w4',
        title: 'Test 4: Writing T1-2',
        section: Section.WRITING,
        parts: [
            {
                questions: [{
                    id: 'b19t4wq1',
                    type: QuestionType.WRITING_TASK,
                    prompt: 'You should spend about 20 minutes on this task.',
                    imageUrl: 'ielts-19/ielts-19-t4-w1-charts.png',
                    task: 'The charts below give information on the location and types of dance classes young people in a town in Australia are currently attending.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.',
                    sampleAnswer: "The table and chart provide information about the location and different types of dance class undertaken by young people in Australia.\n\nThe chart says In Private Studios 48% young people are taking dance classes.\n\nAnd in community halls and other 18% folks are taking dance classes And other location. After school classes 24% people are taking classes and other last one location college based studios these are 10% percent people Taking classes. The table reveal in Ballet type dance 600 students under age of 11 learning. And 300 age of 11–16 are learning. And 420 students age of 11–16 learning and last type of Dance Modern these are 515 students are learning who are under age of 11 and 300 other students who are age of 11–16.\n\nTo conclusion in Private Studio the numbers of people much higher than other locations. And type of ballet dance classes number of student Much higher in under age of 11 than other type of dance classes.",
                    sampleAnswerBand: 5.0,
                    examinerComment: "This candidate has worked hard to report all data contained in the graphs. The key areas are covered, but the overall effect is rather mechanical, as each point is presented in a linear sequence.\n\nThe ideas are set out in the correct order, following the order of the graphs in the question, but linking between and within the sentences is not strong. The format is quite repetitive [taking classes | learning] because of the lack of linking devices.\n\nSimilarly, vocabulary is limited and a wider range would be needed for a higher score. Grammatical range is also minimal. There is a noticeable level of error, but the reader is still able to understand the message.\n\nTo improve the score, this candidate should use a wider range of linking devices and take a less mechanical approach. A stronger and wider range of vocabulary and grammar would also be beneficial."
                }]
            },
            {
                questions: [{
                    id: 'b19t4wq2',
                    type: QuestionType.WRITING_TASK,
                    prompt: 'You should spend about 40 minutes on this task. Write about the following topic:',
                    task: 'In many countries nowadays, consumers can go to a supermarket and buy food produced all over the world.\n\nDo you think this is a positive or negative development?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.',
                    sampleAnswer: "Today there are a lot of different shops where we can buy all kind of stuff produced all over the world. Is it right to buy food produced in other countries? Is this idea useful for people nowadays?\n\nI suppose this to be a good idea. When supermarkets and even small shops provide people food from abroad then there are much more possibilities for us to choose something. When shops have only food and things produced in our country, it is really hard to make a good choise. Sometimes people want to try something new and interesting maybe even something extraordinary which they never buy before. In this cases food which is produced in other countries will help them to be satisfied with their demands. When supermarkets have a good suply of different food produced anywhere than people can find delicious things depending on their tastes. For example, people who like French products can buy some kinds of french cheese or wine not only in France.\n\nFood from other countries is useful too because some people are vegetarians and they need vegetables and fruits during the whole year.\n\nThe only disadvantage of food which is produced in other countries is the way how it has been delivered. in some cases products can be not so fresh especialy in summer, when it is very hot outside.\n\nTo sum it up, I can surely say that buying products from other countries is a good thing to become more closer to other cultures. You can certainly cook something unrusual at home and it will taste like in very good expensive restaurant somewhere abroad.",
                    sampleAnswerBand: 6.0,
                    examinerComment: "This is a good response to the task. The candidate clearly agrees with the idea that people should be able to buy international food in supermarkets. The main reason given is that people want to try something [new and interesting] and different. Examples are given of French products and seasonal produce for vegetarians. One disadvantage is given, related to the impact of hot weather on transportation. The conclusion includes bringing cultures together through food and sums up the points made in the full answer. A more relevant conclusion would help the candidate achieve a higher score, as well as further extending the ideas.\n\nGenerally, the candidate organises the ideas well, and we can follow them clearly. Some good linking devices are used [where | maybe even | which | who], but some errors remain [this cases / these cases | than / then]. The response is set out across five paragraphs, but three of them have only two sentences. these are short paragraphs and could be extended to illustrate the central topic in more detail.\n\nAgain, vocabulary is generally appropriate for the question, with some strong examples [extraordinary | depending on their tastes], but there is a lack of precision [stuff] and frequent minor spelling errors [choise | suply | especialy | culturies | unusial]. However, we can still understand what is meant.\n\nThere are attempts at a wider range of structures and a number of multi-clause sentences. however, the level of error [which they never buy before / which they have never bought before | the way how it has been delivered / the way it has been delivered] detracts from the score.\n\nOverall, a more comprehensive conclusion, longer paragraphs, a wider range of vocabulary and fewer grammatical slips would improve the response and achieve a higher score."
                }]
            }
        ],
    },
    {
        id: 'b19-t4-s5',
        title: 'Test 4: Speaking P1-3',
        section: Section.SPEAKING,
        parts: [
            {
                questions: [{
                    id: 'b19t4sq1',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 1: Example',
                    question: 'Cafés\n\n- Do you have a favourite café? [Why/Why not?]\n- Do you often go to cafés by yourself? [Why/Why not?]\n- What do you think helps to make a café very popular? [Why?]\n- Why do some people prefer cafés that are part of large chains, rather than small, local cafés?',
                    sampleAnswer: `**1. Do you have a favourite café? [Why/Why not?]**\n\n"Yes, I do. There's a small, independent café near my house called 'The Corner Perk'. I love it because it's very cozy, the staff are incredibly friendly, and they make the best flat white in town. It has a really relaxed atmosphere, which is perfect for reading or catching up with friends."\n\n**2. Do you often go to cafés by yourself? [Why/Why not?]**\n\n"Quite often, actually. I find it's a great way to have a change of scenery if I need to get some work done on my laptop. It's nice to be around the gentle buzz of other people without having to interact. Sometimes I just go to sit with a coffee and a good book for an hour to unwind."\n\n**3. What do you think helps to make a café very popular? [Why?]**\n\n"I think it's a combination of three things: the quality of the coffee, a comfortable and inviting atmosphere, and friendly service. If the coffee is excellent, people will come back. But if the place is also comfortable and the staff make you feel welcome, that's what turns a good café into a great and popular one."\n\n**4. Why do some people prefer cafés that are part of large chains, rather than small, local cafés?**\n\n"I think it's mainly about consistency and convenience. With a large chain, you know exactly what you're going to get, no matter which branch you go into. The menu is familiar, and the quality is usually very consistent. They also often have drive-thrus or mobile ordering apps, which can be very convenient for people in a hurry."`
                }]
            },
            {
                questions: [{
                    id: 'b19t4sq2',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 2: Cue Card',
                    question: 'Describe a place you visited that has beautiful views.\nYou should say:\n- where this place is\n- when you visited this place\n- what you saw from this place\n- and explain why you think these views are so beautiful.',
                    sampleAnswer: `I'd love to talk about a place with breathtaking views. It was the top of Arthur's Seat, which is an ancient, extinct volcano right in the middle of Edinburgh, the capital city of Scotland.\n\nI visited this place a couple of years ago in the autumn, around October. I was on a short trip to the city with a friend, and we decided to climb it on a crisp, clear afternoon.\n\nFrom the summit, the view was absolutely panoramic. You could see the entire city spread out below you like a map. I could see the historic Edinburgh Castle perched on its rock, the winding medieval streets of the Old Town, and the elegant Georgian architecture of the New Town. Beyond the city, you could see the blue expanse of the sea, the Firth of Forth, with its famous bridges in the distance. The landscape was a stunning mix of urban and natural beauty.\n\nI think the views were so beautiful because of the unique contrast and the sheer scale of it all. To be standing on this rugged, wild-looking hill and looking down on a bustling, historic city was incredible. The mix of colours – the grey stone of the buildings, the green of the hills, and the blue of the sea – was just spectacular. It felt like you were seeing centuries of history and nature all in one go.`
                }]
            },
            {
                questions: [{
                    id: 'b19t4sq3',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 3: Discussion topics',
                    question: 'The beauty industry\n- Do you agree that most beauty products are a waste of money?\n- How does the beauty industry advertise its products so successfully?\n- What do you think of the view that beauty and culture should not be advertised to children?\n\nBeauty and culture\n- Why do many people equate youth with beauty?\n- Do you think that somebody’s ideas about beauty could affect a person’s success in life?\n- Why might society’s ideas about beauty change over time?',
                    sampleAnswer: `**The beauty industry**\n\n**1. Do you agree that most beauty products are a waste of money?**\n\n"To some extent, yes. I think many products make exaggerated claims that they can't deliver on, and people can end up spending a lot of money on things they don't really need. However, some basic products, like sunscreen or a good moisturiser, are genuinely beneficial for skin health. So, I wouldn't say all of them are a waste, but consumers need to be discerning."\n\n**2. How does the beauty industry advertise its products so successfully?**\n\n"They are masters of marketing. They successfully link their products to aspirations of youth, confidence, and success. They use celebrity endorsements, sophisticated packaging, and powerful social media campaigns with influencers. They often create a 'problem'—like wrinkles or blemishes—and then present their product as the 'solution', which is a very effective advertising tactic."\n\n**3. What do you think of the view that beauty products should not be advertised to children?**\n\n"I completely agree with that view. Children are very impressionable, and advertising beauty products to them can create insecurities and unhealthy obsessions with appearance at a very young age. It's important to let children be children without placing adult pressures about looks on them."\n\n**Beauty and culture**\n\n**4. Why do many people equate youth with beauty?**\n\n"I believe it's deeply rooted in both biology and culture. Biologically, youth is associated with health and fertility, which are attractive traits. Culturally, the media and advertising industries constantly bombard us with images of young, flawless models, which reinforces the idea that youth is the ideal standard of beauty. This creates a cycle where society values youth, and the media reflects and amplifies that value."\n\n**5. Do you think that somebody’s ideas about beauty could affect a person’s success in life?**\n\n"Unfortunately, I think it can. There's a phenomenon known as 'beauty bias' or 'lookism', where people who are considered conventionally attractive often receive preferential treatment in areas like hiring and promotions. While it's not fair, first impressions matter, and societal beauty standards can unconsciously influence people's judgements about a person's competence or character."\n\n**6. Why might society’s ideas about beauty change over time?**\n\n"Ideas about beauty are constantly evolving because they are social constructs. They change with cultural shifts, global influences, and media trends. For example, what was considered beautiful in the Victorian era is very different from today's standards. Increased global interconnectedness means we are exposed to diverse ideas of beauty from different cultures, which also helps to broaden and change our collective perceptions over time."`
                }]
            }
        ],
    },
];