import { Lesson, QuestionType, Section } from '../types';

const ielts17ReadingPassage1Test1 = `The development of the London underground railway

In the first half of the 1800s, London’s population grew at an astonishing rate, and the central area became increasingly congested. In addition, the expansion of the overground railway network resulted in more and more passengers arriving in the capital. However, in 1846, a Royal Commission decided that the railways should not be allowed to enter the City, the capital’s historic and business centre. The result was that the overground railway stations formed a ring around the City. The area within consisted of poorly built, overcrowded slums and the streets were full of horse-drawn traffic. Crossing the City became a nightmare. It could take an hour and a half to travel 8 km by horse-drawn carriage or bus. Numerous schemes were proposed to resolve these problems, but few succeeded.

Amongst the most vocal advocates for a solution to London’s traffic problems was Charles Pearson, who worked as a solicitor for the City of London. He saw both social and economic advantages in building an underground railway that would link the overground railway stations together and clear London slums at the same time. His idea was to relocate the poor workers who lived in the inner-city slums to newly constructed suburbs, and to provide cheap rail travel for them to get to work. Pearson’s ideas gained support amongst some businessmen and in 1851 he submitted a plan to Parliament. It was rejected, but coincided with a proposal from another group for an underground connecting line, which Parliament passed.

The two groups merged and established the Metropolitan Railway Company in August 1854. The company’s plan was to construct an underground railway line from the Great Western Railway’s (GWR) station at Paddington to the edge of the City at Farringdon Street – a distance of almost 5 km. The organisation had difficulty in raising the funding for such a radical and expensive scheme, not least because of the critical articles printed by the press. Objectors argued that the tunnels would collapse under the weight of traffic overhead, buildings would be shaken and passengers would be poisoned by the emissions from the train engines. However, Pearson and his partners persisted.

The GWR, aware that the new line would finally enable them to run trains into the heart of the City, invested almost £250,000 in the scheme. Eventually, over a five-year period, £1m was raised. The chosen route ran beneath existing main roads to minimise the expense of demolishing buildings. Originally scheduled to be completed in 21 months, the construction of the underground line took three years. It was built just below street level using a technique known as ‘cut and cover’. A trench about ten metres wide and six metres deep was dug, and the sides temporarily held up with timber beams. Brick walls were then constructed, and finally a brick arch was added to create a tunnel. A two-metre-deep layer of soil was laid on top of the tunnel and the road above rebuilt.

The Metropolitan line, which opened on 10 January 1863, was the world’s first underground railway. On its first day, almost 40,000 passengers were carried between Paddington and Farringdon, the journey taking about 18 minutes. By the end of the Metropolitan’s first year of operation, 9.5 million journeys had been made.

Even as the Metropolitan began operation, the first extensions to the line were being authorised; these were built over the next five years, reaching Moorgate in the east of London and Hammersmith in the west. The original plan was to pull the trains with steam locomotives, using firebricks in the boilers to provide steam, but these engines were never introduced. Instead, the line used specially designed locomotives that were fitted with water tanks in which steam could be condensed. However, smoke and fumes remained a problem, even though ventilation shafts were added to the tunnels.

Despite the extension of the underground railway, by the 1880s, congestion on London’s streets had become worse. The problem was partly that the existing underground lines formed a circuit around the centre of London and extended to the suburbs, but did not cross the capital’s centre. The ‘cut and cover’ method of construction was not an option in this part of the capital. The only alternative was to tunnel deep underground.

Although the technology to create these tunnels existed, steam locomotives could not be used in such a confined space. It wasn’t until the development of a reliable electric motor, and a means of transferring power from the generator to a moving train, that the world’s first deep-level electric railway, the City & South London, became possible. The line opened in 1890, and ran from the City to Stockwell, south of the River Thames. The trains were made up of three carriages and driven by electric engines. The carriages were narrow and had tiny windows just below the roof because it was thought that passengers would not want to look out at the tunnel walls. The line was not without its problems, mainly caused by an unreliable power supply. Although the City & South London Railway was a great technical achievement, it did not make a profit. Then, in 1900, the Central London Railway, known as the ‘Tuppenny Tube’, began operation using new electric locomotives. It was very popular and soon afterwards new railways and extensions were added to the growing tube network. By 1907, the heart of today’s Underground system was in place.`;

const ielts17ReadingPassage2Test1 = `Stadiums: past, present and future

A. Stadiums are among the oldest forms of urban architecture: vast stadiums where the public could watch sporting events were at the centre of western city life as far back as the ancient Greek and Roman Empires, well before the construction of the great medieval cathedrals and the grand 19th- and 20th-century railway stations which dominated urban skylines in later eras. Today, however, stadiums are regarded with growing scepticism. Construction costs can soar above £1 billion, and stadiums finished for major events such as the Olympic Games or the FIFA World Cup have notably fallen into disuse and disrepair. But this need not be the case. History shows that stadiums can drive urban development and adapt to the culture of every age. Even today, architects and planners are finding new ways to adapt the mono-functional sports arenas which became emblematic of modernisation during the 20th century.

B. The amphitheatre of Arles in southwest France, with a capacity of 25,000 spectators, is perhaps the best example of just how versatile stadiums can be. Built by the Romans in 90 AD, it became a fortress with four towers after the fifth century, and was then transformed into a village containing more than 200 houses. With the growing interest in conservation during the 19th century, it was converted back into an arena for the staging of bullfights, thereby returning the structure to its original use as a venue for public spectacles. Another example is the imposing arena of Verona in northern Italy, with space for 30,000 spectators, which was built 60 years before the Arles amphitheatre and 40 years before Rome’s famous Colosseum. It has endured the centuries and is currently considered one of the world’s prime sites for opera, thanks to its outstanding acoustics.

C. The area in the centre of the Italian town of Lucca, known as the Piazza dell’ Anfiteatro, is yet another impressive example of an amphitheatre becoming absorbed into the fabric of the city. The site evolved in a similar way to Arles and was progressively filled with buildings from the Middle Ages until the 19th century, variously used as houses, a salt depot and a prison. But rather than reverting to an arena, it became a market square, designed by Romanticist architect Lorenzo Nottolini. Today, the ruins of the amphitheatre remain embedded in the various shops and residences surrounding the public square.

D. There are many similarities between modern stadiums and the ancient amphitheatres intended for games. But some of the flexibility was lost at the beginning of the 20th century, as stadiums were developed using new products such as steel and reinforced concrete, and made use of bright lights for night-time matches. Many such stadiums are situated in suburban areas, designed for sporting use only and surrounded by parking lots. These factors mean that they may not be as accessible to the general public, require more energy to run and contribute to urban heat.

E. But many of today’s most innovative architects see scope for the stadium to help improve the city. Among the current strategies, two seem to be having particular success: the stadium as an urban hub, and as a power plant. There’s a growing trend for stadiums to be equipped with public spaces and services that serve a function beyond sport, such as hotels, retail outlets, conference centres, restaurants and bars, children’s playgrounds and green space. Creating mixed-use developments such as this reinforces compactness and multi-functionality, making more efficient use of land and helping to regenerate urban spaces. This opens the space up to families and a wider cross-section of society, instead of catering only to sportspeople and supporters. There have been many examples of this in the UK: the mixed-use facilities at Wembley and Old Trafford have become a blueprint for many other stadiums in the world.

F. The phenomenon of stadiums as power stations has arisen from the idea that energy problems can be overcome by integrating interconnected buildings by means of a smart grid, which is an electricity supply network that uses digital communications technology to detect and react to local changes in usage, without significant energy losses. Stadiums are ideal for these purposes, because their canopies have a large surface area for fitting photovoltaic panels and rise high enough (more than 40 metres) to make use of micro wind turbines. Freiburg Mage Solar Stadium in Germany is the first of a new wave of stadiums as power plants, which also includes the Amsterdam Arena and the Kaohsiung Stadium. The latter, inaugurated in 2009, has 8,844 photovoltaic panels producing up to 1.14 GWh of electricity annually. This reduces the annual output of carbon dioxide by 660 tons and supplies up to 80 percent of the surrounding area when the stadium is not in use. This is proof that a stadium can serve its city, and have a decidedly positive impact in terms of reduction of CO2 emissions.

G. Sporting arenas have always been central to the life and culture of cities. In every era, the stadium has acquired new value and uses: from military fortress to residential village, public space to theatre and most recently a field for experimentation in advanced engineering. The stadium of today now brings together multiple functions, thus helping cities to create a sustainable future.`;

const ielts17ReadingPassage3Test1 = `To catch a king

Anna Keay reviews Charles Spencer’s book about the hunt for King Charles II during the English Civil War of the seventeenth century

Charles Spencer’s latest book, To Catch a King, tells us the story of the hunt for King Charles II in the six weeks after his resounding defeat at the Battle of Worcester in September 1651. And what a story it is. After his father was executed by the Parliamentarians in 1649, the young Charles II sacrificed one of the very principles his father had died for and did a deal with the Scots, thereby accepting Presbyterianism as the national religion in return for being crowned King of Scots. His arrival in Edinburgh prompted the English Parliamentary army to invade Scotland in a pre-emptive strike. This was followed by a Scottish invasion of England. The two sides finally faced one another at Worcester in the west of England in 1651. After being comprehensively defeated on the meadows outside the city by the Parliamentarian army, the 21-year-old king found himself the subject of a national manhunt, with a huge sum offered for his capture. Over the following six weeks he managed, through a series of heart-poundingly close escapes, to evade the Parliamentarians before seeking refuge in France. For the next nine years, the penniless and defeated Charles wandered around Europe with only a small group of loyal supporters.

Years later, after his restoration as king, the 50-year-old Charles II requested a meeting with the writer and diarist Samuel Pepys. His intention when asking Pepys to commit his story to paper was to ensure that this most extraordinary episode was never forgotten. Over two three-hour sittings, the king related to him in great detail his personal recollections of the six weeks he had spent as a fugitive. As the king and secretary settled down (a scene that is surely a gift for a future scriptwriter), Charles commenced his story: ‘After the battle was so absolutely lost as to be beyond hope of recovery, I began to think of the best way of saving myself.’

One of the joys of Spencer’s book, a result not least of its use of Charles II’s own narrative as well as those of his supporters, is just how close the reader gets to the action. The day-byday retelling of the fugitives’ doings provides delicious details: the cutting of the king’s long hair with agricultural shears, the use of walnut leaves to dye his pale skin, and the day Charles spent lying on a branch of the great oak tree in Boscobel Wood as the Parliamentary soldiers scoured the forest floor below. Spencer draws out both the humour – such as the preposterous refusal of Charles’s friend Henry Wilmot to adopt disguise on the grounds that it was beneath his dignity – and the emotional tension when the secret of the king’s presence was cautiously revealed to his supporters.

Charles’s adventures after losing the Battle of Worcester hide the uncomfortable truth that whilst almost everyone in England had been appalled by the execution of his father, they had not welcomed the arrival of his son with the Scots army, but had instead firmly bolted their doors. This was partly because he rode at the head of what looked like a foreign invasion force and partly because, after almost a decade of civil war, people were desperate to avoid it beginning again. This makes it all the more interesting that Charles II himself loved the story so much ever after. As well as retelling it to anyone who would listen, causing eye-rolling among courtiers, he set in train a series of initiatives to memorialise it. There was to be a new order of chivalry, the Knights of the Royal Oak. A series of enormous oil paintings depicting the episode were produced, including a two-metre-wide canvas of Boscobel Wood and a set of six similarly enormous paintings of the king on the run. In 1660, Charles II commissioned the artist John Michael Wright to paint a flying squadron of cherubs carrying an oak tree to the heavens on the ceiling of his bedchamber. It is hard to imagine many other kings marking the lowest point in their life so enthusiastically, or indeed pulling off such an escape in the first place.

Charles Spencer is the perfect person to pass the story on to a new generation. His pacey, readable prose steers deftly clear of modern idioms and elegantly brings to life the details of the great tale. He has even-handed sympathy for both the fugitive king and the fierce republican regime that hunted him, and he succeeds in his desire to explore far more of the background of the story than previous books on the subject have done. Indeed, the opening third of the book is about how Charles II found himself at Worcester in the first place, which for some will be reason alone to read To Catch a King.

The tantalising question left, in the end, is that of what it all meant. Would Charles II have been a different king had these six weeks never happened? The days and nights spent in hiding must have affected him in some way. Did the need to assume disguises, to survive on wit and charm alone, to use trickery and subterfuge to escape from tight corners help form him? This is the one area where the book doesn’t quite hit the mark. Instead its depiction of Charles II in his final years as an ineffective, pleasure-loving monarch doesn’t do justice to the man (neither is it accurate), or to the complexity of his character. But this one niggle aside, To Catch a King is an excellent read, and those who come to it knowing little of the famous tale will find they have a treat in store.`;

export const ielts17Test1Lessons: Lesson[] = [
    {
        id: 'b17-t1-l0',
        title: 'Test 1: Listening P1-2',
        section: Section.LISTENING,
        parts: [
            { // Part 1
                questions: [
                    { id: 'b17t1lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t1-p1.mp3', questionText: 'making sure the beach does not have 1 ___ on it', correctAnswers: ['litter'], transcript: "One of the regular ones is trying to keep the beach free of litter.", transcriptHighlight: "litter" },
                    { id: 'b17t1lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t1-p1.mp3', questionText: 'no 2 ___', correctAnswers: ['dogs'], transcript: "I’m afraid not, as they’re banned from the beach itself.", transcriptHighlight: "banned from the beach" },
                    { id: 'b17t1lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t1-p1.mp3', questionText: 'next task is taking action to attract 3 ___ to the place', correctAnswers: ['insects'], transcript: "next we’re going to work on encouraging insects", transcriptHighlight: "insects" },
                    { id: 'b17t1lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t1-p1.mp3', questionText: 'identifying types of 4 ___', correctAnswers: ['butterflies'], transcript: "we’re also running a project to identify the different species of butterflies that visit the reserve.", transcriptHighlight: "butterflies" },
                    { id: 'b17t1lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t1-p1.mp3', questionText: 'building a new 5 ___', correctAnswers: ['wall'], transcript: "Another job we’re doing at the reserve is replacing the wall on the southern side", transcriptHighlight: "wall" },
                    { id: 'b17t1lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t1-p1.mp3', questionText: 'walk across the sands and reach the 6 ___', correctAnswers: ['island'], transcript: "walk to the island without getting wet.", transcriptHighlight: "island" },
                    { id: 'b17t1lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t1-p1.mp3', questionText: 'wear appropriate 7 ___', correctAnswers: ['boots'], transcript: "make sure your boots are waterproof.", transcriptHighlight: "boots" },
                    { id: 'b17t1lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t1-p1.mp3', questionText: 'suitable for 8 ___ to participate in', correctAnswers: ['beginners'], transcript: "Is it OK for beginners to take part? Definitely.", transcriptHighlight: "beginners" },
                    { id: 'b17t1lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t1-p1.mp3', questionText: 'making 9 ___ out of wood', correctAnswers: ['spoons'], transcript: "You’ll be starting with wooden spoons", transcriptHighlight: "spoons" },
                    { id: 'b17t1lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t1-p1.mp3', questionText: 'cost of session (no camping): 10 £___', correctAnswers: ['35'], transcript: "There’s a charge of £35, including lunch", transcriptHighlight: "35" },
                ],
            },
            { // Part 2
                questions: [
                    { id: 'b17t1lq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 11-14: Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t1-p2.mp3', questionText: 'What is the maximum number of people who can stand on each side of the boat?', options: ['9', '15', '18'], correctAnswers: ['9'], transcript: "if there are more than nine people on either side of the boat, we’ll move some of you over", transcriptHighlight: "nine people" },
                    { id: 'b17t1lq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 11-14: Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t1-p2.mp3', questionText: 'What colour are the tour boats?', options: ['dark red', 'jet black', 'light green'], correctAnswers: ['light green'], transcript: "a light-green exterior", transcriptHighlight: "light-green" },
                    { id: 'b17t1lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 11-14: Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t1-p2.mp3', questionText: "Which lunchbox is suitable for someone who doesn’t eat meat or fish?", options: ['Lunchbox 1', 'Lunchbox 2', 'Lunchbox 3'], correctAnswers: ['Lunchbox 2'], transcript: "Lunchbox 1 contains ham and tomato sandwiches. Lunchbox 2 contains a cheddar cheese roll and Lunchbox 3 is salad-based and also contains eggs and tuna.", transcriptHighlight: "Lunchbox 2 contains a cheddar cheese roll" },
                    { id: 'b17t1lq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 11-14: Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t1-p2.mp3', questionText: 'What should people do with their litter?', options: ['take it home', 'hand it to a member of staff', 'put it in the bins provided on the boat'], correctAnswers: ['hand it to a member of staff'], transcript: "Jess, myself or Ray, our other guide, will collect it from you after lunch", transcriptHighlight: "collect it from you" },
                    { id: 'b17t1lq15', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'Questions 15 and 16: Choose TWO letters, A-E.', audioUrl: 'ielts-17/t1-p2.mp3', questionText: 'Which TWO features of the lighthouse does Lou mention?', options: ['why it was built', 'who built it', 'how long it took to build', 'who staffed it', 'what it was built with'], correctAnswers: ['why it was built', 'who staffed it'], transcript: "it was built in 1838 to protect sailors... These workers were mainly prison convicts until the middle of that century when ordinary families willing to live in such circumstances took over.", transcriptHighlight: "protect sailors... prison convicts" },
                    { id: 'b17t1lq17', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'Questions 17 and 18: Choose TWO letters, A-E.', audioUrl: 'ielts-17/t1-p2.mp3', questionText: 'Which TWO types of creature might come close to the boat?', options: ['sea eagles', 'fur seals', 'dolphins', 'whales', 'penguins'], correctAnswers: ['fur seals', 'dolphins'], transcript: "the rocky area inhabited by fur seals... Dolphins, on the other hand, can sometimes approach on their own or in groups", transcriptHighlight: "fur seals... Dolphins" },
                    { id: 'b17t1lq19', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'Questions 19 and 20: Choose TWO letters, A-E.', audioUrl: 'ielts-17/t1-p2.mp3', questionText: 'Which TWO points does Lou make about the caves?', options: ['Only large tourist boats can visit them.', 'The entrances to them are often blocked.', 'It is too dangerous for individuals to go near them.', 'Someone will explain what is inside them.', 'They cannot be reached on foot.'], correctAnswers: ['Someone will explain what is inside them.', 'They cannot be reached on foot.'], transcript: "They can only be approached by sea... What we’ll do is to go through a narrow channel... and from there we’ll be able to see the openings to the caves, and at that point we’ll talk to you about what lies beyond.", transcriptHighlight: "only be approached by sea... talk to you about what lies beyond" },
                ]
            }
        ]
    },
    {
        id: 'b17-t1-l1',
        title: 'Test 1: Listening P3-4',
        section: Section.LISTENING,
        parts: [
            { // Part 3
                questions: [
                    { id: 'b17t1lq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 21-26: Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t1-p3.mp3', questionText: 'What problem did both Diana and Tim have when arranging their work experience?', options: ['making initial contact with suitable farms', 'organising transport to and from the farm', 'finding a placement for the required length of time'], correctAnswers: ['making initial contact with suitable farms'], transcript: "arranging the work experience was hard. One problem was it was miles away... But finding the right sort of farm to apply to wasn’t easy. No, they don’t seem to have websites, do they.", transcriptHighlight: "finding the right sort of farm to apply to wasn’t easy" },
                    { id: 'b17t1lq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 21-26: Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t1-p3.mp3', questionText: 'Tim was pleased to be able to help', options: ['a lamb that had a broken leg.', 'a sheep that was having difficulty giving birth.', 'a newly born lamb that was having trouble feeding.'], correctAnswers: ['a sheep that was having difficulty giving birth.'], transcript: "I was up most of one night helping a sheep deliver a lamb... it was a great feeling to see the lamb stagger to its feet", transcriptHighlight: "helping a sheep deliver a lamb" },
                    { id: 'b17t1lq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 21-26: Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t1-p3.mp3', questionText: 'Diana says the sheep on her farm', options: ['were of various different varieties.', 'were mainly reared for their meat.', 'had better quality wool than sheep on the hills.'], correctAnswers: ['were mainly reared for their meat.'], transcript: "So were they bred for their meat? Mostly, yes.", transcriptHighlight: "Mostly, yes" },
                    { id: 'b17t1lq24', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 21-26: Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t1-p3.mp3', questionText: 'What did the students learn about adding supplements to chicken feed?', options: ['These should only be given if specially needed.', 'It is worth paying extra for the most effective ones.', 'The amount given at one time should be limited.'], correctAnswers: ['These should only be given if specially needed.'], transcript: "he didn’t give them as a matter of routine, just at times when the chickens seemed to particularly require them.", transcriptHighlight: "didn’t give them as a matter of routine" },
                    {
                        id: 'b17t1lq25',
                        type: QuestionType.MULTIPLE_CHOICE,
                        prompt: 'Questions 21-26: Choose the correct letter, A, B or C.',
                        audioUrl: 'ielts-17/t1-p3.mp3',
                        questionText: 'What happened when Diana was working with dairy cows?',
                        options: ['She identified some cows incorrectly.', 'She accidentally threw some milk away.', 'She made a mistake when storing milk.'],
                        correctAnswers: ['She made a mistake when storing milk.'],
                        transcript: "I got mixed up, and I poured some milk from the wrong cow in with the milk for humans, so the whole lot had to be thrown away.",
                        transcriptHighlight: "poured some milk from the wrong cow in with the milk for humans"
                    },
                    { id: 'b17t1lq26', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 21-26: Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t1-p3.mp3', questionText: 'What did both farmers mention about vets and farming?', options: ['Vets are failing to cope with some aspects of animal health.', 'There needs to be a fundamental change in the training of vets.', 'Some jobs could be done by the farmer rather than by a vet.'], correctAnswers: ['Some jobs could be done by the farmer rather than by a vet.'], transcript: "he said that actually some of the stuff the vets do, like minor operations, he’d be quite capable of doing himself. Yeah. My farmer said the same.", transcriptHighlight: "quite capable of doing himself" },
                    { id: 'b17t1lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 27-30: Choose FOUR answers from the box and write the correct letter, A-F.', audioUrl: 'ielts-17/t1-p3.mp3', questionText: '27 Medical terminology', options: ['A Tim found this easier than expected.', 'B Tim thought this was not very clearly organised.', 'C Diana may do some further study on this.', 'D They both found the reading required for this was difficult.', 'E Tim was shocked at something he learned on this module.', 'F They were both surprised how little is known about some aspects of this.'], correctAnswers: ['A Tim found this easier than expected.'], transcript: "I’d thought it’d be hard, but actually I found it all quite straightforward.", transcriptHighlight: "found it all quite straightforward" },
                    { id: 'b17t1lq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 27-30: Choose FOUR answers from the box and write the correct letter, A-F.', audioUrl: 'ielts-17/t1-p3.mp3', questionText: '28 Diet and nutrition', options: ['A Tim found this easier than expected.', 'B Tim thought this was not very clearly organised.', 'C Diana may do some further study on this.', 'D They both found the reading required for this was difficult.', 'E Tim was shocked at something he learned on this module.', 'F They were both surprised how little is known about some aspects of this.'], correctAnswers: ['E Tim was shocked at something he learned on this module.'], transcript: "Do you remember what they told us about pet food and the fact that there’s such limited checking into whether or not it’s contaminated?... I thought that was terrible.", transcriptHighlight: "I thought that was terrible" },
                    { id: 'b17t1lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 27-30: Choose FOUR answers from the box and write the correct letter, A-F.', audioUrl: 'ielts-17/t1-p3.mp3', questionText: '29 Animal disease', options: ['A Tim found this easier than expected.', 'B Tim thought this was not very clearly organised.', 'C Diana may do some further study on this.', 'D They both found the reading required for this was difficult.', 'E Tim was shocked at something he learned on this module.', 'F They were both surprised how little is known about some aspects of this.'], correctAnswers: ['F They were both surprised how little is known about some aspects of this.'], transcript: "scientists don’t know much about the diseases that affect them... I thought they’d know a lot about ways of controlling and eradicating those diseases, but that’s not the case at all.", transcriptHighlight: "that’s not the case at all" },
                    { id: 'b17t1lq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Questions 27-30: Choose FOUR answers from the box and write the correct letter, A-F.', audioUrl: 'ielts-17/t1-p3.mp3', questionText: '30 Wildlife medication', options: ['A Tim found this easier than expected.', 'B Tim thought this was not very clearly organised.', 'C Diana may do some further study on this.', 'D They both found the reading required for this was difficult.', 'E Tim was shocked at something he learned on this module.', 'F They were both surprised how little is known about some aspects of this.'], correctAnswers: ['C Diana may do some further study on this.'], transcript: "Yeah, I thought I might write my dissertation on something connected with that.", transcriptHighlight: "write my dissertation" },
                ]
            },
            { // Part 4
                questions: [
                    { id: 'b17t1lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t1-p4.mp3', questionText: 'Mazes are a type of 31 ___ .', correctAnswers: ['puzzle'], transcript: "A maze is quite different as it is a kind of puzzle", transcriptHighlight: "puzzle" },
                    { id: 'b17t1lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t1-p4.mp3', questionText: '- 32 ___ is needed to navigate through a maze', correctAnswers: ['logic'], transcript: "using logic to work out the pattern", transcriptHighlight: "logic" },
                    { id: 'b17t1lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t1-p4.mp3', questionText: "- the word 'maze' is derived from a word meaning a feeling of 33 ___ .", correctAnswers: ['confusion'], transcript: "The word ‘maze’ is believed to come from a Scandinavian word for a state of confusion.", transcriptHighlight: "confusion" },
                    { id: 'b17t1lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t1-p4.mp3', questionText: '- they have frequently been used in 34 ___ and prayer', correctAnswers: ['meditation'], transcript: "have been used as a meditation and prayer tool", transcriptHighlight: "meditation" },
                    { id: 'b17t1lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t1-p4.mp3', questionText: 'Ancient carvings on 35 ___ have been found across many cultures', correctAnswers: ['stone'], transcript: "The earliest examples of the labyrinth spiral pattern have been found carved into stone", transcriptHighlight: "stone" },
                    { id: 'b17t1lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t1-p4.mp3', questionText: 'Ancient Greeks used the symbol on 36 ___ .', correctAnswers: ['coins'], transcript: "the labyrinth spiral was used on coins", transcriptHighlight: "coins" },
                    { id: 'b17t1lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t1-p4.mp3', questionText: 'The largest surviving example of a turf labyrinth once had a big 37 ___ at its centre', correctAnswers: ['tree'], transcript: "the largest one at Saffron Walden, England, which used to have a large tree in the middle of it.", transcriptHighlight: "tree" },
                    { id: 'b17t1lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t1-p4.mp3', questionText: "walking a maze can reduce a person's 38 ___ rate", correctAnswers: ['breathing'], transcript: "which include slower breathing and a restored sense of balance and perspective.", transcriptHighlight: "slower breathing" },
                    { id: 'b17t1lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t1-p4.mp3', questionText: "patients who can't walk can use 'finger labyrinths' made from 39 ___ .", correctAnswers: ['paper'], transcript: "patients who can’t walk can have a paper ‘finger labyrinth’ brought to their bed.", transcriptHighlight: "paper" },
                    { id: 'b17t1lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t1-p4.mp3', questionText: "research has shown that Alzheimer's sufferers experience less 40 ___ .", correctAnswers: ['anxiety'], transcript: "relief from anxiety’ for Alzheimer’s patients.", transcriptHighlight: "anxiety" },
                ]
            }
        ]
    },
    {
        id: 'b17-t1-r2',
        title: 'Test 1: Reading P1',
        section: Section.READING,
        parts: [{
            questions: [
                { id: 'b17t1rq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test1, questionText: 'The 1 ___ of London increased rapidly between 1800 and 1850', correctAnswers: ['population'], passageHighlight: "London’s population grew at an astonishing rate" },
                { id: 'b17t1rq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test1, questionText: 'Building the railway would make it possible to move people to better housing in the 2 ___ .', correctAnswers: ['suburbs'], passageHighlight: "relocate the poor workers who lived in the inner-city slums to newly constructed suburbs" },
                { id: 'b17t1rq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test1, questionText: "A number of 3 ___ agreed with Pearson's idea", correctAnswers: ['businessmen'], passageHighlight: "Pearson’s ideas gained support amongst some businessmen" },
                { id: 'b17t1rq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test1, questionText: 'The company initially had problems getting the 4 ___ needed for the project', correctAnswers: ['funding'], passageHighlight: "The organisation had difficulty in raising the funding" },
                { id: 'b17t1rq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test1, questionText: 'Negative articles about the project appeared in the 5 ___ .', correctAnswers: ['press'], passageHighlight: "critical articles printed by the press" },
                { id: 'b17t1rq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test1, questionText: 'With the completion of the brick arch, the tunnel was covered with 6 ___ .', correctAnswers: ['soil'], passageHighlight: "A two-metre-deep layer of soil was laid on top of the tunnel" },
                { id: 'b17t1rq7', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1? Choose TRUE, FALSE or NOT GIVEN.', passage: ielts17ReadingPassage1Test1, questionText: 'Other countries had built underground railways before the Metropolitan line opened.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "The Metropolitan line, which opened on 10 January 1863, was the world’s first underground railway." },
                { id: 'b17t1rq8', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1? Choose TRUE, FALSE or NOT GIVEN.', passage: ielts17ReadingPassage1Test1, questionText: 'More people than predicted travelled on the Metropolitan line on the first day.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage states that 'almost 40,000 passengers were carried' but doesn't mention any predictions." },
                { id: 'b17t1rq9', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1? Choose TRUE, FALSE or NOT GIVEN.', passage: ielts17ReadingPassage1Test1, questionText: 'The use of ventilation shafts failed to prevent pollution in the tunnels.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "smoke and fumes remained a problem, even though ventilation shafts were added to the tunnels." },
                { id: 'b17t1rq10', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1? Choose TRUE, FALSE or NOT GIVEN.', passage: ielts17ReadingPassage1Test1, questionText: "A different approach from the 'cut and cover' technique was required in London's central area.", options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "The ‘cut and cover’ method of construction was not an option in this part of the capital. The only alternative was to tunnel deep underground." },
                { id: 'b17t1rq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1? Choose TRUE, FALSE or NOT GIVEN.', passage: ielts17ReadingPassage1Test1, questionText: 'The windows on City & South London trains were at eye level.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "The carriages were narrow and had tiny windows just below the roof" },
                { id: 'b17t1rq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1? Choose TRUE, FALSE or NOT GIVEN.', passage: ielts17ReadingPassage1Test1, questionText: 'The City & South London Railway was a financial success.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "it did not make a profit." },
                { id: 'b17t1rq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1? Choose TRUE, FALSE or NOT GIVEN.', passage: ielts17ReadingPassage1Test1, questionText: "Trains on the 'Tuppenny Tube' nearly always ran on time.", options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage mentions it was 'very popular' but gives no information about its punctuality." },
            ],
        }],
    },
    {
        id: 'b17-t1-r3',
        title: 'Test 1: Reading P2-3',
        section: Section.READING,
        parts: [
            { // Reading Passage 2
                questions: [
                    { id: 'b17t1rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has seven sections, A-G. Which section contains the following information?', passage: ielts17ReadingPassage2Test1, questionText: 'a mention of negative attitudes towards stadium building projects', options: ['A','B','C','D','E','F','G'], correctAnswers: ['A'], passageHighlight: "Today, however, stadiums are regarded with growing scepticism. Construction costs can soar above £1 billion, and stadiums finished for major events such as the Olympic Games or the FIFA World Cup have notably fallen into disuse and disrepair." },
                    { id: 'b17t1rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has seven sections, A-G. Which section contains the following information?', passage: ielts17ReadingPassage2Test1, questionText: 'figures demonstrating the environmental benefits of a certain stadium', options: ['A','B','C','D','E','F','G'], correctAnswers: ['F'], passageHighlight: "This reduces the annual output of carbon dioxide by 660 tons and supplies up to 80 percent of the surrounding area when the stadium is not in use." },
                    { id: 'b17t1rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has seven sections, A-G. Which section contains the following information?', passage: ielts17ReadingPassage2Test1, questionText: 'examples of the wide range of facilities available at some new stadiums', options: ['A','B','C','D','E','F','G'], correctAnswers: ['E'], passageHighlight: "such as hotels, retail outlets, conference centres, restaurants and bars, children’s playgrounds and green space." },
                    { id: 'b17t1rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has seven sections, A-G. Which section contains the following information?', passage: ielts17ReadingPassage2Test1, questionText: 'reference to the disadvantages of the stadiums built during a certain era', options: ['A','B','C','D','E','F','G'], correctAnswers: ['D'], passageHighlight: "Many such stadiums are situated in suburban areas, designed for sporting use only and surrounded by parking lots. These factors mean that they may not be as accessible to the general public, require more energy to run and contribute to urban heat." },
                    { id: 'b17t1rq18', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage2Test1, questionText: 'The amphitheatre of Arles, for example, was converted first into a 18 ___', correctAnswers: ['fortress'], passageHighlight: "it became a fortress with four towers" },
                    { id: 'b17t1rq19', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage2Test1, questionText: '... and finally into an arena where spectators could watch 19 ___ .', correctAnswers: ['bullfights'], passageHighlight: "converted back into an arena for the staging of bullfights" },
                    { id: 'b17t1rq20', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage2Test1, questionText: 'Meanwhile, the arena in Verona... is famous today as a venue where 20 ___ is performed.', correctAnswers: ['opera'], passageHighlight: "currently considered one of the world’s prime sites for opera" },
                    { id: 'b17t1rq21', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage2Test1, questionText: 'The site of Lucca’s amphitheatre has also been used for many purposes over the centuries, including the storage of 21 ___ .', correctAnswers: ['salt'], passageHighlight: "variously used as houses, a salt depot and a prison." },
                    { id: 'b17t1rq22', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage2Test1, questionText: 'It is now a market square with 22 ___ and homes incorporated into the remains of the Roman amphitheatre.', correctAnswers: ['shops'], passageHighlight: "the ruins of the amphitheatre remain embedded in the various shops and residences" },
                    { id: 'b17t1rq23', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'When comparing twentieth-century stadiums to ancient amphitheatres in Section D, which TWO negative features does the writer mention?', passage: ielts17ReadingPassage2Test1, questionText: '', options: ['They are less imaginatively designed.', 'They are less spacious.', 'They are in less convenient locations.', 'They are less versatile.', 'They are made of less durable materials.'], correctAnswers: ['They are in less convenient locations.', 'They are less versatile.'], passageHighlight: "some of the flexibility was lost at the beginning of the 20th century... Many such stadiums are situated in suburban areas, designed for sporting use only" },
                    { id: 'b17t1rq25', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: 'Which TWO advantages of modern stadium design does the writer mention?', passage: ielts17ReadingPassage2Test1, questionText: '', options: ['offering improved amenities for the enjoyment of sports events', 'bringing community life back into the city environment', 'facilitating research into solar and wind energy solutions', 'enabling local residents to reduce their consumption of electricity', 'providing a suitable site for the installation of renewable power generators'], correctAnswers: ['bringing community life back into the city environment', 'providing a suitable site for the installation of renewable power generators'], passageHighlight: "There’s a growing trend for stadiums to be equipped with public spaces and services that serve a function beyond sport... making more efficient use of land and helping to regenerate urban spaces... Stadiums are ideal for these purposes, because their canopies have a large surface area for fitting photovoltaic panels and rise high enough (more than 40 metres) to make use of micro wind turbines." },
                ],
            },
            { // Reading Passage 3
                questions: [
                    { id: 'b17t1rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-J, below.', passage: ielts17ReadingPassage3Test1, questionText: 'Charles II then formed a 27 ___ with the Scots', options: ['A military innovation', 'B large reward', 'C widespread conspiracy', 'D relative safety', 'E new government', 'F decisive victory', 'G political debate', 'H strategic alliance', 'I popular solution', 'J religious conviction'], correctAnswers: ['H strategic alliance'], passageHighlight: "did a deal with the Scots, thereby accepting Presbyterianism as the national religion in return for being crowned King of Scots." },
                    { id: 'b17t1rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-J, below.', passage: ielts17ReadingPassage3Test1, questionText: 'he abandoned an important 28 ___ that was held by his father', options: ['A military innovation', 'B large reward', 'C widespread conspiracy', 'D relative safety', 'E new government', 'F decisive victory', 'G political debate', 'H strategic alliance', 'I popular solution', 'J religious conviction'], correctAnswers: ['J religious conviction'], passageHighlight: "sacrificed one of the very principles his father had died for and did a deal with the Scots, thereby accepting Presbyterianism as the national religion" },
                    { id: 'b17t1rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-J, below.', passage: ielts17ReadingPassage3Test1, questionText: 'The battle led to a 29 ___ for the Parliamentarians', options: ['A military innovation', 'B large reward', 'C widespread conspiracy', 'D relative safety', 'E new government', 'F decisive victory', 'G political debate', 'H strategic alliance', 'I popular solution', 'J religious conviction'], correctAnswers: ['F decisive victory'], passageHighlight: "his resounding defeat at the Battle of Worcester... After being comprehensively defeated on the meadows outside the city by the Parliamentarian army" },
                    { id: 'b17t1rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-J, below.', passage: ielts17ReadingPassage3Test1, questionText: 'A 30 ___ was offered for Charles’s capture', options: ['A military innovation', 'B large reward', 'C widespread conspiracy', 'D relative safety', 'E new government', 'F decisive victory', 'G political debate', 'H strategic alliance', 'I popular solution', 'J religious conviction'], correctAnswers: ['B large reward'], passageHighlight: "with a huge sum offered for his capture." },
                    { id: 'b17t1rq31', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-J, below.', passage: ielts17ReadingPassage3Test1, questionText: 'he eventually managed to reach the 31 ___ of continental Europe.', options: ['A military innovation', 'B large reward', 'C widespread conspiracy', 'D relative safety', 'E new government', 'F decisive victory', 'G political debate', 'H strategic alliance', 'I popular solution', 'J religious conviction'], correctAnswers: ['D relative safety'], passageHighlight: "to evade the Parliamentarians before seeking refuge in France." },
                    { id: 'b17t1rq32', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test1, questionText: 'Charles chose Pepys for the task because he considered him to be trustworthy.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage doesn't explain why Charles chose Pepys." },
                    { id: 'b17t1rq33', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test1, questionText: "Charles's personal recollection of the escape lacked sufficient detail.", options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "the king related to him in great detail his personal recollections of the six weeks he had spent as a fugitive." },
                    { id: 'b17t1rq34', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test1, questionText: 'Charles indicated to Pepys that he had planned his escape before the battle.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "‘After the battle was so absolutely lost as to be beyond hope of recovery, I began to think of the best way of saving myself.’" },
                    { id: 'b17t1rq35', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test1, questionText: "The inclusion of Charles's account is a positive aspect of the book.", options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "One of the joys of Spencer’s book, a result not least of its use of Charles II’s own narrative as well as those of his supporters, is just how close the reader gets to the action." },
                    { id: 'b17t1rq36', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test1, questionText: "What is the reviewer's main purpose in the first paragraph?", options: ['to describe what happened during the Battle of Worcester', "to give an account of the circumstances leading to Charles II's escape", "to provide details of the Parliamentarians' political views", "to compare Charles II's beliefs with those of his father"], correctAnswers: ["to give an account of the circumstances leading to Charles II's escape"], passageHighlight: "tells us the story of the hunt for King Charles II in the six weeks after his resounding defeat at the Battle of Worcester in September 1651." },
                    { id: 'b17t1rq37', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test1, questionText: "Why does the reviewer include examples of the fugitives' behaviour in the third paragraph?", options: ["to explain how close Charles II came to losing his life", "to suggest that Charles II's supporters were badly prepared", 'to illustrate how the events of the six weeks are brought to life', 'to argue that certain aspects are not as well known as they should be'], correctAnswers: ['to illustrate how the events of the six weeks are brought to life'], passageHighlight: "is just how close the reader gets to the action. The day-byday retelling of the fugitives’ doings provides delicious details" },
                    { id: 'b17t1rq38', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test1, questionText: "What point does the reviewer make about Charles II in the fourth paragraph?", options: ['He chose to celebrate what was essentially a defeat.', 'He misunderstood the motives of his opponents.', "He aimed to restore people's faith in the monarchy.", 'He was driven by a desire to be popular.'], correctAnswers: ['He chose to celebrate what was essentially a defeat.'], passageHighlight: "It is hard to imagine many other kings marking the lowest point in their life so enthusiastically, or indeed pulling off such an escape in the first place." },
                    { id: 'b17t1rq39', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test1, questionText: 'What does the reviewer say about Charles Spencer in the fifth paragraph?', options: ['His decision to write the book comes as a surprise.', 'He takes an unbiased approach to the subject matter.', 'His descriptions of events would be better if they included more detail.', 'He chooses language that is suitable for a twenty-first-century audience.'], correctAnswers: ['He takes an unbiased approach to the subject matter.'], passageHighlight: "He has even-handed sympathy for both the fugitive king and the fierce republican regime that hunted him" },
                    { id: 'b17t1rq40', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test1, questionText: "When the reviewer says the book 'doesn't quite hit the mark', she is making the point that", options: ['it overlooks the impact of events on ordinary people.', 'it lacks an analysis of prevalent views on monarchy.', 'it omits any references to the deceit practised by Charles II during his time in hiding.', "it fails to address whether Charles II's experiences had a lasting influence on him."], correctAnswers: ["it fails to address whether Charles II's experiences had a lasting influence on him."], passageHighlight: "Would Charles II have been a different king had these six weeks never happened? The days and nights spent in hiding must have affected him in some way... This is the one area where the book doesn’t quite hit the mark." },
                ]
            }
        ]
    },
    {
        id: 'b17-t1-w4',
        title: 'Test 1: Writing T1-2',
        section: Section.WRITING,
        parts: [
            {
                questions: [{
                    id: 'b17t1wq1',
                    type: QuestionType.WRITING_TASK,
                    prompt: 'You should spend about 20 minutes on this task.',
                    imageUrl: 'ielts-17/t1-w1-map.png',
                    task: 'The maps below show an industrial area in the town of Norbiton, and planned future development of the site.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.',
                    sampleAnswer: "The two maps illustrates the norbiton area in the present days, as well as, the planned development. Overall, the norbiton industrial area is located at the east side of the town, with a river on the north, separating the farmland from the industrial area, which is located in the center of the map, represented by a few factory biuldings and roads, followed by the main road at the extreme south of the map.\n\nthe planned development shows a substantially growth and modifications of the overall infrastructure of the area between the farmland and the main road. firstly, the planned development of the norbiton area replaces what once were factories for housings. Moreover, the roads have been developed to acomodate all the new biuldings that have been planned for the area, which are, a school and a playground to the east side of the roundabout located in the center of the map, as well as shops and a medical center around the round about. secondly, a bridge is planned for the north of the map to cross the river and provide acess to the housing that will be located in farmland.",
                    sampleAnswerBand: 6.0,
                    examinerComment: "This response covers the key changes to be made to the industrial area, although more detail could be provided, for example, housing to the west of the roundabout. There is an overview in the second paragraph and the response could be improved by adding a summary of the main changes. Ideas are arranged coherently, with some effective use of cohesive devices [what once were], sequencing adverbs [Firstly / Secondly] and referencing [which / that]. There is some less common vocabulary but spelling is often inaccurate [acomodate / accommodate | biuldings / buildings] and word formation is incorrect [substantially growth / substantial growth]. To achieve a higher score, the candidate would need to reduce the number of errors in vocabulary and sentence structure."
                }]
            },
            {
                questions: [{
                    id: 'b17t1wq2',
                    type: QuestionType.WRITING_TASK,
                    prompt: 'You should spend about 40 minutes on this task. Write about the following topic:',
                    task: 'It is important for people to take risks, both in their professional lives and their personal lives.\n\nDo you think the advantages of taking risks outweigh the disadvantages?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.',
                    sampleAnswer: "It is said that taking risks brings a lot of benefits. However, it also gives us some drawbacks. First of all, it is obvious that taking risks will cause a great loss if people do it and fail. In personal life, this loss might not be so harmful. However, it will be really harmfull in professional life, because people take a responsibility not only for themselves but also others such as colleages, customers and their families. It will even damage the society from the economic point.\n\nOn the other hand, we can receive huge benefits by taking risks. firstly, we can learn how to prepare for one goal through this process. In order to achieve the aim, people will make all the efforts to think about it and try to find more efficient way if they do this in the professional circumstances, they will recognise the responsibility and importance of cooperation. Also, it will be completely meaningful even though people can't achieve the goal after taking risks. They will learn the reason why they have failed and how to change it. The failure will enable them to improve their skills and to achieve their object next time.\n\nAs I mentioned, it is true that taking risks give us both advantages and disadvantages. However, it can be argued that the benefits outweighed the drawbacks in that we can obtain advantages not only from the result but also from the process of taking risks.",
                    sampleAnswerBand: 6.5,
                    examinerComment: "This response discusses the advantages and the disadvantages of taking risks. It puts much greater emphasis on risks in ‘professional life’. As this response is below 250 words (it is only 242), more could be added to include risks in ‘personal life’ along with some specific examples of risks that people commonly take. There is a clear progression through the response and ideas are logically organised; disadvantages are presented first and advantages second. Cohesive devices can be quite mechanical with examples at the start of most sentences [First of all | However | On the other hand | Firstly] but referencing is generally appropriate [it | this loss | They | The failure]. The first paragraph is very short and paragraphing is not entirely logical. Vocabulary is effective with some less common items [damage the society | receive huge benefits | enable | obtain advantages ... from the process]. Occasional errors remain [object / objective | point / perspective). Sentence structure is good, with frequent error-free sentences. There is a variety of complex structures, including conditionals [if], but a few errors remain. To improve this response, the word count of 250 should be reached and concrete example(s) of risk could be provided."
                }]
            }
        ]
    },
    {
        id: 'b17-t1-s5',
        title: 'Test 1: Speaking P1-3',
        section: Section.SPEAKING,
        parts: [
            {
                questions: [{
                    id: 'b17t1sq1',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 1: Example',
                    question: 'History\n\n- What did you study in history lessons when you were at school?\n- Did you enjoy studying history at school? [Why/Why not?]\n- How often do you watch TV programmes about history now? [Why/Why not?]\n- What period in history would you like to learn more about? [Why?]',
                    sampleAnswer: `**1. What did you study in history lessons when you were at school?**
"At school, we covered a broad range of topics. I remember studying ancient civilizations like the Romans and Egyptians, then moving on to key periods in my own country's history, and also covering major world events like the two World Wars. It was quite varied."

**2. Did you enjoy studying history at school?**
"Yes, for the most part, I did. I found it fascinating to learn about how past events have shaped the world we live in today. It was like putting together the pieces of a giant puzzle. Some topics were more engaging than others, of course, but overall I found it to be a very interesting subject."

**3. How often do you watch TV programmes about history now?**
"Quite often, actually. I'm a big fan of historical documentaries. I probably watch one or two a week if I can. I find it a very accessible and entertaining way to learn about different periods and figures that I might not have studied at school."

**4. What period in history would you like to learn more about?**
"I'd love to learn more about the Renaissance period in Europe. It seems like such an incredible time of innovation in art, science, and philosophy. I've seen some of the art from that era, but I'd be interested to understand more about the social and political changes that were happening at the same time."`
                }]
            },
            {
                questions: [{
                    id: 'b17t1sq2',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 2: Cue Card',
                    question: 'Describe the neighbourhood you lived in when you were a child.\nYou should say:\n- where in your town/city the neighbourhood was\n- what kind of people lived there\n- what it was like to live in this neighbourhood\n- and explain whether you would like to live in this neighbourhood in the future.',
                    sampleAnswer: `When I was a child, I lived in a suburban neighbourhood on the outskirts of my city. It was a relatively new development at the time, with lots of young families.

The people who lived there were mostly young couples with children around my age, so it was a very family-oriented community. There was a real mix of professions - teachers, office workers, people in trades. Generally, everyone was very friendly and knew each other at least by sight.

Living there was great as a kid. It felt very safe, and there were always lots of other children to play with outside. We had a small park with a playground just at the end of our street, which was the main meeting point. I have very fond memories of long summer evenings spent playing football or riding our bikes around the quiet streets. It was a very peaceful and friendly place to grow up.

As for whether I'd like to live there in the future, it's a nice thought, but probably not. While I loved it as a child, as an adult I prefer being closer to the city centre with more amenities and better public transport. It was perfect for a family, but my priorities are different now. However, I'll always look back on my time there with a lot of happiness.`
                }]
            },
            {
                questions: [{
                    id: 'b17t1sq3',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 3: Discussion topics',
                    question: 'Neighbours\n- What sort of things can neighbours do to help each other?\n- How well do people generally know their neighbours in your country?\n- How important do you think it is to have good neighbours?\n\nFacilities in cities\n- Which facilities are most important to people living in cities?\n- How does shopping in small local shops differ from shopping in large city centre shops?\n- Do you think that children should always go to the school nearest to where they live?',
                    sampleAnswer: `**Neighbours**

**1. What sort of things can neighbours do to help each other?**
"Neighbours can help each other in many small but significant ways. Things like taking in parcels when someone is out, keeping an eye on the house when they're on holiday, or lending a tool or an ingredient for cooking. In some communities, neighbours might help each other with childcare or offer support to elderly residents by doing their shopping."

**2. How well do people generally know their neighbours in your country?**
"I think it varies a lot. In smaller towns and villages, it's quite common for people to know their neighbours well and have strong community ties. However, in big cities, it's often more anonymous. People might exchange a polite 'hello', but many don't know their neighbours' names. Life is just so busy and transient in cities."

**3. How important do you think it is to have good neighbours?**
"I think it's extremely important. Good neighbours contribute to a sense of security and community. Knowing you have people nearby you can trust and rely on in an emergency is very reassuring. It also just makes daily life more pleasant when you have friendly, respectful people living next to you."

**Facilities in cities**

**4. Which facilities are most important to people living in cities?**
"I would say reliable public transport is probably the most important, as it affects everyone's ability to get to work and move around. After that, access to good healthcare facilities, quality schools for families, and green spaces like parks are crucial for a good quality of life. Of course, a variety of shops and entertainment options are also very important."

**5. How does shopping in small local shops differ from shopping in large city centre shops?**
"The experience is quite different. Small local shops often offer more personal service; the owner might know you by name and can provide expert advice. They tend to sell unique or locally sourced products. In contrast, large city-centre shops offer a much wider variety of brands and more competitive prices, but the experience is usually less personal and more anonymous."

**6. Do you think that children should always go to the school nearest to where they live?**
"In an ideal world, yes, because it fosters a sense of community and makes logistics like the school run much easier for parents. It allows children to be friends with others in their immediate neighbourhood. However, I don't think it should be a strict rule. If the nearest school is underperforming or isn't a good fit for a particular child, parents should have the freedom to choose a better option, even if it's further away."`
                }]
            }
        ]
    }
];