
import { Lesson, QuestionType, Section } from '../types';

const ielts17ReadingPassage1Test2 = `The Dead Sea Scrolls

In late 1946 or early 1947, three Bedouin teenagers were tending their goats and sheep near the ancient settlement of Qumran, located on the northwest shore of the Dead Sea in what is now known as the West Bank. One of these young shepherds tossed a rock into an opening on the side of a cliff and was surprised to hear a shattering sound. He and his companions later entered the cave and stumbled across a collection of large clay jars, seven of which contained scrolls with writing on them. The teenagers took the seven scrolls to a nearby town where they were sold for a small sum to a local antiquities dealer. Word of the find spread, and Bedouins and archaeologists eventually unearthed tens of thousands of additional scroll fragments from 10 nearby caves; together they make up between 800 and 900 manuscripts. It soon became clear that this was one of the greatest archaeological discoveries ever made.

The origin of the Dead Sea Scrolls, which were written around 2,000 years ago between 150 BCE and 70 CE, is still the subject of scholarly debate even today. According to the prevailing theory, they are the work of a population that inhabited the area until Roman troops destroyed the settlement around 70 CE. The area was known as Judea at that time, and the people are thought to have belonged to a group called the Essenes, a devout Jewish sect.

The majority of the texts on the Dead Sea Scrolls are in Hebrew, with some fragments written in an ancient version of its alphabet thought to have fallen out of use in the fifth century BCE. But there are other languages as well. Some scrolls are in Aramaic, the language spoken by many inhabitants of the region from the sixth century BCE to the siege of Jerusalem in 70 CE. In addition, several texts feature translations of the Hebrew Bible into Greek.

The Dead Sea Scrolls include fragments from every book of the Old Testament of the Bible except for the Book of Esther. The only entire book of the Hebrew Bible preserved among the manuscripts from Qumran is Isaiah; this copy, dated to the first century BCE, is considered the earliest biblical manuscript still in existence. Along with biblical texts, the scrolls include documents about sectarian regulations and religious writings that do not appear in the Old Testament.

The writing on the Dead Sea Scrolls is mostly in black or occasionally red ink, and the scrolls themselves are nearly all made of either parchment (animal skin) or an early form of paper called ‘papyrus’. The only exception is the scroll numbered 3Q15, which was created out of a combination of copper and tin. Known as the Copper Scroll, this curious document features letters chiselled onto metal – perhaps, as some have theorized, to better withstand the passage of time. One of the most intriguing manuscripts from Qumran, this is a sort of ancient treasure map that lists dozens of gold and silver caches. Using an unconventional vocabulary and odd spelling, it describes 64 underground hiding places that supposedly contain riches buried for safekeeping. None of these hoards have been recovered, possibly because the Romans pillaged Judea during the first century CE. According to various hypotheses, the treasure belonged to local people, or was rescued from the Second Temple before its destruction or never existed to begin with.

Some of the Dead Sea Scrolls have been on interesting journeys. In 1948, a Syrian Orthodox archbishop known as Mar Samuel acquired four of the original seven scrolls from a Jerusalem shoemaker and part-time antiquity dealer, paying less than $100 for them. He then travelled to the United States and unsuccessfully offered them to a number of universities, including Yale. Finally, in 1954, he placed an advertisement in the business newspaper The Wall Street Journal – under the category ‘Miscellaneous Items for Sale’ – that read: ‘Biblical Manuscripts dating back to at least 200 B.C. are for sale. This would be an ideal gift to an educational or religious institution by an individual or group.’ Fortunately, Israeli archaeologist and statesman Yigael Yadin negotiated their purchase and brought the scrolls back to Jerusalem, where they remain to this day.

In 2017, researchers from the University of Haifa restored and deciphered one of the last untranslated scrolls. The university’s Eshbal Ratson and Jonathan Ben-Dov spent one year reassembling the 60 fragments that make up the scroll. Deciphered from a band of coded text on parchment, the find provides insight into the community of people who wrote it and the 364-day calendar they would have used. The scroll names celebrations that indicate shifts in seasons and details two yearly religious events known from another Dead Sea Scroll. Only one more known scroll remains untranslated.`;

const ielts17ReadingPassage2Test2 = `A second attempt at domesticating the tomato

A. It took at least 3,000 years for humans to learn how to domesticate the wild tomato and cultivate it for food. Now two separate teams in Brazil and China have done it all over again in less than three years. And they have done it better in some ways, as the re-domesticated tomatoes are more nutritious than the ones we eat at present. This approach relies on the revolutionary CRISPR genome editing technique, in which changes are deliberately made to the DNA of a living cell, allowing genetic material to be added, removed or altered. The technique could not only improve existing crops, but could also be used to turn thousands of wild plants into useful and appealing foods. In fact, a third team in the US has already begun to do this with a relative of the tomato called the groundcherry. This fast-track domestication could help make the world’s food supply healthier and far more resistant to diseases, such as the rust fungus devastating wheat crops. ‘This could transform what we eat,’ says Jorg Kudla at the University of Munster in Germany, a member of the Brazilian team. ‘There are 50,000 edible plants in the world, but 90 percent of our energy comes from just 15 crops.’ ‘We can now mimic the known domestication course of major crops like rice, maize, sorghum or others,’ says Caixia Gao of the Chinese Academy of Sciences in Beijing. ‘Then we might try to domesticate plants that have never been domesticated.’

B. Wild tomatoes, which are native to the Andes region in South America, produce pea-sized fruits. Over many generations, peoples such as the Aztecs and Incas transformed the plant by selecting and breeding plants with mutations* in their genetic structure, which resulted in desirable traits such as larger fruit. But every time a single plant with a mutation is taken from a larger population for breeding, much genetic diversity is lost. And sometimes the desirable mutations come with less desirable traits. For instance, the tomato strains grown for supermarkets have lost much of their flavour. By comparing the genomes of modern plants to those of their wild relatives, biologists have been working out what genetic changes occurred as plants were domesticated. The teams in Brazil and China have now used this knowledge to reintroduce these changes from scratch while maintaining or even enhancing the desirable traits of wild strains.

C. Kudla’s team made six changes altogether. For instance, they tripled the size of fruit by editing a gene called FRUIT WEIGHT, and increased the number of tomatoes per truss by editing another called MULTIFLORA. While the historical domestication of tomatoes reduced levels of the red pigment lycopene – thought to have potential health benefits – the team in Brazil managed to boost it instead. The wild tomato has twice as much lycopene as cultivated ones; the newly domesticated one has five times as much. ‘They are quite tasty,’ says Kudla. ‘A little bit strong. And very aromatic.’ The team in China re-domesticated several strains of wild tomatoes with desirable traits lost in domesticated tomatoes. In this way they managed to create a strain resistant to a common disease called bacterial spot race, which can devastate yields. They also created another strain that is more salt tolerant – and has higher levels of vitamin C.

D. Meanwhile, Joyce Van Eck at the Boyce Thompson Institute in New York state decided to use the same approach to domesticate the groundcherry or goldenberry (Physalis pruinosa) for the first time. This fruit looks similar to the closely related Cape gooseberry (Physalis peruviana). Groundcherries are already sold to a limited extent in the US but they are hard to produce because the plant has a sprawling growth habit and the small fruits fall off the branches when ripe. Van Eck’s team has edited the plants to increase fruit size, make their growth more compact and to stop fruits dropping. ‘There’s potential for this to be a commercial crop,’ says Van Eck. But she adds that taking the work further would be expensive because of the need to pay for a licence for the CRISPR technology and get regulatory approval.

E. This approach could boost the use of many obscure plants, says Jonathan Jones of the Sainsbury Lab in the UK. But it will be hard for new foods to grow so popular with farmers and consumers that they become new staple crops, he thinks. The three teams already have their eye on other plants that could be ‘catapulted into the mainstream’, including foxtail, oat-grass and cowpea. By choosing wild plants that are drought or heat tolerant, says Gao, we could create crops that will thrive even as the planet warms. But Kudla didn’t want to reveal which species were in his team’s sights, because CRISPR has made the process so easy. ‘Any one with the right skills could go to their lab and do this.’`;

const ielts17ReadingPassage3Test2 = `Insight or evolution?

Two scientists consider the origins of discoveries and other innovative behavior

Scientific discovery is popularly believed to result from the sheer genius of such intellectual stars as naturalist Charles Darwin and theoretical physicist Albert Einstein. Our view of such unique contributions to science often disregards the person’s prior experience and the efforts of their lesser-known predecessors. Conventional wisdom also places great weight on insight in promoting breakthrough scientific achievements, as if ideas spontaneously pop into someone’s head – fully formed and functional.

There may be some limited truth to this view. However, we believe that it largely misrepresents the real nature of scientific discovery, as well as that of creativity and innovation in many other realms of human endeavor.

Setting aside such greats as Darwin and Einstein – whose monumental contributions are duly celebrated – we suggest that innovation is more a process of trial and error, where two steps forward may sometimes come with one step back, as well as one or more steps to the right or left. This evolutionary view of human innovation undermines the notion of creative genius and recognizes the cumulative nature of scientific progress.

Consider one unheralded scientist: John Nicholson, a mathematical physicist working in the 1910s who postulated the existence of ‘proto-elements’ in outer space. By combining different numbers of weights of these proto-elements’ atoms, Nicholson could recover the weights of all the elements in the then-known periodic table. These successes are all the more noteworthy given the fact that Nicholson was wrong about the presence of proto-elements: they do not actually exist. Yet, amid his often fanciful theories and wild speculations, Nicholson also proposed a novel theory about the structure of atoms. Niels Bohr, the Nobel prize-winning father of modern atomic theory, jumped off from this interesting idea to conceive his now-famous model of the atom.

What are we to make of this story? One might simply conclude that science is a collective and cumulative enterprise. That may be true, but there may be a deeper insight to be gleaned. We propose that science is constantly evolving, much as species of animals do. In biological systems, organisms may display new characteristics that result from random genetic mutations. In the same way, random, arbitrary or accidental mutations of ideas may help pave the way for advances in science. If mutations prove beneficial, then the animal or the scientific theory will continue to thrive and perhaps reproduce.

Support for this evolutionary view of behavioral innovation comes from many domains. Consider one example of an influential innovation in US horseracing. The so-called ‘acey-deucy’ stirrup placement, in which the rider’s foot in his left stirrup is placed as much as 25 centimeters lower than the right, is believed to confer important speed advantages when turning on oval tracks. It was developed by a relatively unknown jockey named Jackie Westrope. Had Westrope conducted methodical investigations or examined extensive film records in a shrewd plan to outrun his rivals? Had he foreseen the speed advantage that would be conferred by riding acey-deucy? No. He suffered a leg injury, which left him unable to fully bend his left knee. His modification just happened to coincide with enhanced left-hand turning performance. This led to the rapid and widespread adoption of riding acey-deucy by many riders, a racing style which continues in today’s thoroughbred racing.

Plenty of other stories show that fresh advances can arise from error, misadventure, and also pure serendipity – a happy accident. For example, in the early 1970s, two employees of the company 3M each had a problem: Spencer Silver had a product – a glue which was only slightly sticky – and no use for it, while his colleague Art Fry was trying to figure out how to affix temporary bookmarks in his hymn book without damaging its pages. The solution to both these problems was the invention of the brilliantly simple yet phenomenally successful Post-It note. Such examples give lie to the claim that ingenious, designing minds are responsible for human creativity and invention. Far more banal and mechanical forces may be at work; forces that are fundamentally connected to the laws of science.

The notions of insight, creativity and genius are often invoked, but they remain vague and of doubtful scientific utility, especially when one considers the diverse and enduring contributions of individuals such as Plato, Leonardo da Vinci, Shakespeare, Beethoven, Galileo, Newton, Kepler, Curie, Pasteur and Edison. These notions merely label rather than explain the evolution of human innovations. We need another approach, and there is a promising candidate.

The Law of Effect was advanced by psychologist Edward Thorndike in 1898, some 40 years after Charles Darwin published his groundbreaking work on biological evolution, On the Origin of Species. This simple law holds that organisms tend to repeat successful behaviors and to refrain from performing unsuccessful ones. Just like Darwin’s Law of Natural Selection, the Law of Effect involves an entirely mechanical process of variation and selection, without any end objective in sight.

Of course, the origin of human innovation demands much further study. In particular, the provenance of the raw material on which the Law of Effect operates is not as clearly known as that of the genetic mutations on which the Law of Natural Selection operates. The generation of novel ideas and behaviors may not be entirely random, but constrained by prior successes and failures – of the current individual (such as Bohr) or of predecessors (such as Nicholson).

The time seems right for abandoning the naive notions of intelligent design and genius, and for scientifically exploring the true origins of creative behavior.`;

export const ielts17Test2Lessons: Lesson[] = [
    {
        id: 'b17-t2-l0',
        title: 'Test 2: Listening P1-2',
        section: Section.LISTENING,
        parts: [
            { // Part 1
                questions: [
                    { id: 'b17t2lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t2-p1.mp3', questionText: 'Help with 1 ___ books (times to be arranged)', correctAnswers: ['collecting'], transcript: "one thing you could do is get involved in collecting them", transcriptHighlight: "collecting" },
                    { id: 'b17t2lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t2-p1.mp3', questionText: 'Help needed to keep 2 ___ of books up to date', correctAnswers: ['records'], transcript: "Another thing is the records that we keep of the books we’re given", transcriptHighlight: "records" },
                    { id: 'b17t2lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t2-p1.mp3', questionText: 'Library is in the 3 ___ Room in the village hall', correctAnswers: ['West'], transcript: "we simply have the use of a room in the village hall, the West Room.", transcriptHighlight: "West" },
                    { id: 'b17t2lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t2-p1.mp3', questionText: 'Help by providing 4 ___ .', correctAnswers: ['transport'], transcript: "I could help with transport, if that’s of any use.", transcriptHighlight: "transport" },
                    { id: 'b17t2lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t2-p1.mp3', questionText: 'Help with hobbies such as 5 ___ .', correctAnswers: ['art'], transcript: "particularly if there are any art groups. Excellent.", transcriptHighlight: "art" },
                    { id: 'b17t2lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t2-p1.mp3', questionText: 'Taking Mrs Carroll to 6 ___ .', correctAnswers: ['hospital'], transcript: "She needs a lift to the hospital next week", transcriptHighlight: "hospital" },
                    { id: 'b17t2lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t2-p1.mp3', questionText: "Work in the 7 ___ at Mr Selsbury's house", correctAnswers: ['garden'], transcript: "if you could do some weeding in his garden, that would be wonderful.", transcriptHighlight: "garden" },
                    { id: 'b17t2lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t2-p1.mp3', questionText: 'Event: 8 ___', correctAnswers: ['quiz'], transcript: "we’re holding a quiz", transcriptHighlight: "quiz" },
                    { id: 'b17t2lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t2-p1.mp3', questionText: 'Help needed: checking 9 ___', correctAnswers: ['tickets'], transcript: "Well, we sell tickets in advance, and having an extra person to check them at the door... would be good", transcriptHighlight: "tickets" },
                    { id: 'b17t2lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write ONE WORD ONLY for each answer.', audioUrl: 'ielts-17/t2-p1.mp3', questionText: 'Help needed: designing the 10 ___', correctAnswers: ['poster'], transcript: "The one thing we haven’t got yet is a poster.", transcriptHighlight: "poster" },
                ]
            },
            { // Part 2
                questions: [
                    { id: 'b17t2lq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t2-p2.mp3', questionText: 'Many past owners made changes to', options: ['A the gardens.', 'B the house.', 'C the farm.'], correctAnswers: ['B the house.'], transcript: "Almost all of them have left their mark, generally by adding new rooms, like the ballroom and conservatory, or by demolishing others.", transcriptHighlight: "adding new rooms... demolishing others" },
                    { id: 'b17t2lq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t2-p2.mp3', questionText: 'Sir Edward Downes built Oniton Hall because he wanted', options: ['A a place for discussing politics.', 'B a place to display his wealth.', 'C a place for artists and writers.'], correctAnswers: ['C a place for artists and writers.'], transcript: "hosted meetings of creative and literary people, like painters and poets.", transcriptHighlight: "painters and poets" },
                    { id: 'b17t2lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t2-p2.mp3', questionText: 'Visitors can learn about the work of servants in the past from', options: ['A audio guides.', 'B photographs.', 'C people in costume.'], correctAnswers: ['C people in costume.'], transcript: "you’ll see volunteers dressed up as nineteenth-century servants, going about their work.", transcriptHighlight: "volunteers dressed up as nineteenth-century servants" },
                    { id: 'b17t2lq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t2-p2.mp3', questionText: 'What is new for children at Oniton Hall?', options: ['A clothes for dressing up', 'B mini tractors', 'C the adventure playground'], correctAnswers: ['B mini tractors'], transcript: "Our latest addition is child-sized tractors, that you can drive around the grounds.", transcriptHighlight: "child-sized tractors" },
                    { id: 'b17t2lq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which activity is offered at each of the following locations on the farm?', audioUrl: 'ielts-17/t2-p2.mp3', questionText: '15 dairy', options: ['A shopping', 'B watching cows being milked', 'C seeing old farming equipment', 'D eating and drinking', 'E starting a trip', 'F seeing rare breeds of animals', 'G helping to look after animals', 'H using farming tools'], correctAnswers: ['D eating and drinking'], transcript: "Until recently, the dairy was where milk from the cows was turned into cheese. It’s now the place to go for lunch, or afternoon tea, or just a cup of coffee and a slice of homemade cake.", transcriptHighlight: "place to go for lunch" },
                    { id: 'b17t2lq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which activity is offered at each of the following locations on the farm?', audioUrl: 'ielts-17/t2-p2.mp3', questionText: '16 large barn', options: ['A shopping', 'B watching cows being milked', 'C seeing old farming equipment', 'D eating and drinking', 'E starting a trip', 'F seeing rare breeds of animals', 'G helping to look after animals', 'H using farming tools'], correctAnswers: ['C seeing old farming equipment'], transcript: "in here is our collection of agricultural tools. These were used in the past to plough the earth, sow seeds, make gates, and much more.", transcriptHighlight: "collection of agricultural tools" },
                    { id: 'b17t2lq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which activity is offered at each of the following locations on the farm?', audioUrl: 'ielts-17/t2-p2.mp3', questionText: '17 small barn', options: ['A shopping', 'B watching cows being milked', 'C seeing old farming equipment', 'D eating and drinking', 'E starting a trip', 'F seeing rare breeds of animals', 'G helping to look after animals', 'H using farming tools'], correctAnswers: ['G helping to look after animals'], transcript: "you can groom the donkeys and horses, to keep their coats clean.", transcriptHighlight: "groom the donkeys and horses" },
                    { id: 'b17t2lq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which activity is offered at each of the following locations on the farm?', audioUrl: 'ielts-17/t2-p2.mp3', questionText: '18 stables', options: ['A shopping', 'B watching cows being milked', 'C seeing old farming equipment', 'D eating and drinking', 'E starting a trip', 'F seeing rare breeds of animals', 'G helping to look after animals', 'H using farming tools'], correctAnswers: ['A shopping'], transcript: "The horses no longer live in the stables, which instead is the place to go to buy gifts, books, our own jams and pickles, and clothes and blankets", transcriptHighlight: "place to go to buy gifts" },
                    { id: 'b17t2lq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which activity is offered at each of the following locations on the farm?', audioUrl: 'ielts-17/t2-p2.mp3', questionText: '19 shed', options: ['A shopping', 'B watching cows being milked', 'C seeing old farming equipment', 'D eating and drinking', 'E starting a trip', 'F seeing rare breeds of animals', 'G helping to look after animals', 'H using farming tools'], correctAnswers: ['E starting a trip'], transcript: "Outside the shed, which is the only brick building, you can climb into a horse-drawn carriage for a lovely, relaxing tour of the park and farm.", transcriptHighlight: "climb into a horse-drawn carriage for a lovely, relaxing tour" },
                    { id: 'b17t2lq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which activity is offered at each of the following locations on the farm?', audioUrl: 'ielts-17/t2-p2.mp3', questionText: '20 parkland', options: ['A shopping', 'B watching cows being milked', 'C seeing old farming equipment', 'D eating and drinking', 'E starting a trip', 'F seeing rare breeds of animals', 'G helping to look after animals', 'H using farming tools'], correctAnswers: ['F seeing rare breeds of animals'], transcript: "You’ll see types of cattle and sheep that are hardly ever found on farms these days. We’re helping to preserve them", transcriptHighlight: "cattle and sheep that are hardly ever found" },
                ]
            }
        ]
    },
    {
        id: 'b17-t2-l1',
        title: 'Test 2: Listening P3-4',
        section: Section.LISTENING,
        parts: [
            { // Part 3
                questions: [
                    { id: 'b17t2lq21', type: QuestionType.MULTIPLE_CHOICE, maxSelections: 2, prompt: "Choose TWO letters, A-E.", audioUrl: 'ielts-17/t2-p3.mp3', questionText: 'Which TWO things do the students agree they need to include in their reviews of Romeo and Juliet?', options: ['A analysis of the text', 'B a summary of the plot', 'C a description of the theatre', 'D a personal reaction', 'E a reference to particular scenes'], correctAnswers: ['D a personal reaction', 'E a reference to particular scenes'], transcript: "And part of that means talking about the emotional impact the performance had on us. I think that’s important. Yes. And we should definitely mention how well the director handled important bits of the play", transcriptHighlight: "emotional impact the performance had on us... mention how well the director handled important bits of the play" },
                    { id: 'b17t2lq23', type: QuestionType.MULTIPLE_CHOICE, prompt: "Choose FIVE answers from the box and write the correct letter, A-G.", audioUrl: 'ielts-17/t2-p3.mp3', questionText: '23 the set', options: ['A They both expected this to be more traditional.', 'B They both thought this was original.', 'C They agree this created the right atmosphere.', 'D They agree this was a major strength.', 'E They were both disappointed by this.', 'F They disagree about why this was an issue.', 'G They disagree about how this could be improved.'], correctAnswers: ['D They agree this was a major strength.'], transcript: "I think it was visually really stunning. I’d say that was probably the most memorable thing about this production. You’re right. The set design was really amazing", transcriptHighlight: "visually really stunning" },
                    { id: 'b17t2lq24', type: QuestionType.MULTIPLE_CHOICE, prompt: "Choose FIVE answers from the box and write the correct letter, A-G.", audioUrl: 'ielts-17/t2-p3.mp3', questionText: '24 the lighting', options: ['A They both expected this to be more traditional.', 'B They both thought this was original.', 'C They agree this created the right atmosphere.', 'D They agree this was a major strength.', 'E They were both disappointed by this.', 'F They disagree about why this was an issue.', 'G They disagree about how this could be improved.'], correctAnswers: ['C They agree this created the right atmosphere.'], transcript: "Some of the scenes were so dimly lit it was quite hard to see. I didn’t dislike it. It helped to change the mood of the quieter scenes. That’s a good point.", transcriptHighlight: "change the mood of the quieter scenes" },
                    { id: 'b17t2lq25', type: QuestionType.MULTIPLE_CHOICE, prompt: "Choose FIVE answers from the box and write the correct letter, A-G.", audioUrl: 'ielts-17/t2-p3.mp3', questionText: '25 the costume design', options: ['A They both expected this to be more traditional.', 'B They both thought this was original.', 'C They agree this created the right atmosphere.', 'D They agree this was a major strength.', 'E They were both disappointed by this.', 'F They disagree about why this was an issue.', 'G They disagree about how this could be improved.'], correctAnswers: ['A They both expected this to be more traditional.'], transcript: "I was a bit surprised by the contemporary dress, I must say. Yeah – I think it worked well, but I had assumed it would be more conventional.", transcriptHighlight: "assumed it would be more conventional" },
                    { id: 'b17t2lq26', type: QuestionType.MULTIPLE_CHOICE, prompt: "Choose FIVE answers from the box and write the correct letter, A-G.", audioUrl: 'ielts-17/t2-p3.mp3', questionText: '26 the music', options: ['A They both expected this to be more traditional.', 'B They both thought this was original.', 'C They agree this created the right atmosphere.', 'D They agree this was a major strength.', 'E They were both disappointed by this.', 'F They disagree about why this was an issue.', 'G They disagree about how this could be improved.'], correctAnswers: ['E They were both disappointed by this.'], transcript: "I thought they were wasted because the music didn’t have much impact in Acts 2 and 3. Yes – that was a shame.", transcriptHighlight: "that was a shame" },
                    { id: 'b17t2lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: "Choose FIVE answers from the box and write the correct letter, A-G.", audioUrl: 'ielts-17/t2-p3.mp3', questionText: "27 the actors' delivery", options: ['A They both expected this to be more traditional.', 'B They both thought this was original.', 'C They agree this created the right atmosphere.', 'D They agree this was a major strength.', 'E They were both disappointed by this.', 'F They disagree about why this was an issue.', 'G They disagree about how this could be improved.'], correctAnswers: ['F They disagree about why this was an issue.'], transcript: "They were speaking too fast. It was a problem I agree, but I thought it was because they weren’t speaking loudly enough", transcriptHighlight: "too fast... not speaking loudly enough" },
                    { id: 'b17t2lq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t2-p3.mp3', questionText: 'The students think the story of Romeo and Juliet is still relevant for young people today because', options: ['A it illustrates how easily conflict can start.', 'B it deals with problems that families experience.', 'C it teaches them about relationships.'], correctAnswers: ['B it deals with problems that families experience.'], transcript: "There are always disagreements and tension between teenagers and their parents. Yes, that’s something all young people can relate to", transcriptHighlight: "disagreements and tension between teenagers and their parents" },
                    { id: 'b17t2lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t2-p3.mp3', questionText: 'The students found watching Romeo and Juliet in another language', options: ['A frustrating.', 'B demanding.', 'C moving.'], correctAnswers: ['C moving.'], transcript: "The ending was pretty powerful. Yes. That somehow intensified the emotion for me.", transcriptHighlight: "intensified the emotion" },
                    { id: 'b17t2lq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B or C.', audioUrl: 'ielts-17/t2-p3.mp3', questionText: "Why do the students think Shakespeare's plays have such international appeal?", options: ['A The stories are exciting.', 'B There are recognisable characters.', 'C They can be interpreted in many ways.'], correctAnswers: ['C They can be interpreted in many ways.'], transcript: "Yeah, and they can also be understood on different levels. The characters have such depth. Right – which allows directors to experiment and find new angles.", transcriptHighlight: "allows directors to experiment and find new angles" },
                ]
            },
            { // Part 4
                questions: [
                    { id: 'b17t2lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t2-p4.mp3', questionText: 'has approximately 31 ___ speakers', correctAnswers: ['321,000', '321000'], transcript: "which is spoken by around 321,000 people", transcriptHighlight: "321,000" },
                    { id: 'b17t2lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t2-p4.mp3', questionText: 'has a 32 ___ that is still growing', correctAnswers: ['vocabulary'], transcript: "the vocabulary of Icelandic is continually increasing", transcriptHighlight: "vocabulary" },
                    { id: 'b17t2lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t2-p4.mp3', questionText: '...such as web browser and 33 ___ .', correctAnswers: ['podcast'], transcript: "Then there’s an Icelandic word for podcast", transcriptHighlight: "podcast" },
                    { id: 'b17t2lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t2-p4.mp3', questionText: '...digital technology, such as 34 ___ .', correctAnswers: ['smartphones'], transcript: "Think about smartphones.", transcriptHighlight: "smartphones" },
                    { id: 'b17t2lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t2-p4.mp3', questionText: 'are becoming 35 ___ very quickly', correctAnswers: ['bilingual'], transcript: "it promotes their bilingual skills", transcriptHighlight: "bilingual" },
                    { id: 'b17t2lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t2-p4.mp3', questionText: '...while they are in the 36 ___ at school', correctAnswers: ['playground'], transcript: "teachers have found that playground conversations in Icelandic secondary schools can be conducted entirely in English", transcriptHighlight: "playground" },
                    { id: 'b17t2lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t2-p4.mp3', questionText: '...identify the content of a 37 ___ in English than Icelandic', correctAnswers: ['picture'], transcript: "their classes find it easier to say what is in a picture using English, rather than Icelandic.", transcriptHighlight: "picture" },
                    { id: 'b17t2lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t2-p4.mp3', questionText: '...of how complicated its 38 ___ is', correctAnswers: ['grammar'], transcript: "The other drawback of Icelandic is the grammar, which is significantly more complex than in most languages.", transcriptHighlight: "grammar" },
                    { id: 'b17t2lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t2-p4.mp3', questionText: '...young Icelanders may lose their 39 ___ as Icelanders', correctAnswers: ['identity'], transcript: "will young Icelanders lose their sense of their own identity?", transcriptHighlight: "identity" },
                    { id: 'b17t2lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.', audioUrl: 'ielts-17/t2-p4.mp3', questionText: '...children not being 40 ___ in either Icelandic or English', correctAnswers: ['fluent'], transcript: "If children are learning two languages through different routes, neither of which they are fully fluent in", transcriptHighlight: "fluent" },
                ]
            }
        ]
    },
    {
        id: 'b17-t2-r2',
        title: 'Test 2: Reading P1',
        section: Section.READING,
        parts: [{
            questions: [
                { id: 'b17t2rq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test2, questionText: 'heard a noise of breaking when one teenager threw a 1 ___ .', correctAnswers: ['rock'], passageHighlight: "One of these young shepherds tossed a rock into an opening" },
                { id: 'b17t2rq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test2, questionText: 'teenagers went into the 2 ___ and found a number of containers', correctAnswers: ['cave'], passageHighlight: "He and his companions later entered the cave" },
                { id: 'b17t2rq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test2, questionText: 'made of 3 ___ .', correctAnswers: ['clay'], passageHighlight: "stumbled across a collection of large clay jars" },
                { id: 'b17t2rq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test2, questionText: 'thought to have been written by group of people known as the 4 ___ .', correctAnswers: ['Essenes'], passageHighlight: "the people are thought to have belonged to a group called the Essenes" },
                { id: 'b17t2rq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage1Test2, questionText: 'written mainly in the 5 ___ language', correctAnswers: ['Hebrew'], passageHighlight: "The majority of the texts on the Dead Sea Scrolls are in Hebrew" },
                { id: 'b17t2rq6', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test2, questionText: 'The Bedouin teenagers who found the scrolls were disappointed by how little money they received for them.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage says they were sold 'for a small sum' but doesn't mention the teenagers' feelings about this." },
                { id: 'b17t2rq7', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test2, questionText: 'There is agreement among academics about the origin of the Dead Sea Scrolls.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "is still the subject of scholarly debate even today." },
                { id: 'b17t2rq8', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test2, questionText: 'Most of the books of the Bible written on the scrolls are incomplete.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "The Dead Sea Scrolls include fragments from every book... The only entire book... is Isaiah" },
                { id: 'b17t2rq9', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test2, questionText: 'The information on the Copper Scroll is written in an unusual way.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "Using an unconventional vocabulary and odd spelling" },
                { id: 'b17t2rq10', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test2, questionText: 'Mar Samuel was given some of the scrolls as a gift.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "paying less than $100 for them." },
                { id: 'b17t2rq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test2, questionText: 'In the early 1950s, a number of educational establishments in the US were keen to buy scrolls from Mar Samuel.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "unsuccessfully offered them to a number of universities, including Yale." },
                { id: 'b17t2rq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test2, questionText: 'The scroll that was pieced together in 2017 contains information about annual occasions in the Qumran area 2,000 years ago.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "The scroll names celebrations that indicate shifts in seasons and details two yearly religious events" },
                { id: 'b17t2rq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information given in Reading Passage 1?', passage: ielts17ReadingPassage1Test2, questionText: 'Academics at the University of Haifa are currently researching how to decipher the final scroll.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage says 'Only one more known scroll remains untranslated' but doesn't state who is currently working on it." },
            ]
        }],
    },
    {
        id: 'b17-t2-r3',
        title: 'Test 2: Reading P2-3',
        section: Section.READING,
        parts: [
            { // Reading Passage 2
                questions: [
                    { id: 'b17t2rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has five sections, A-E. Which section contains the following information?', passage: ielts17ReadingPassage2Test2, questionText: 'a reference to a type of tomato that can resist a dangerous infection', options: ['A','B','C','D','E'], correctAnswers: ['C'], passageHighlight: "managed to create a strain resistant to a common disease called bacterial spot race" },
                    { id: 'b17t2rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has five sections, A-E. Which section contains the following information?', passage: ielts17ReadingPassage2Test2, questionText: 'an explanation of how problems can arise from focusing only on a certain type of tomato plant', options: ['A','B','C','D','E'], correctAnswers: ['B'], passageHighlight: "But every time a single plant with a mutation is taken from a larger population for breeding, much genetic diversity is lost. And sometimes the desirable mutations come with less desirable traits." },
                    { id: 'b17t2rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has five sections, A-E. Which section contains the following information?', passage: ielts17ReadingPassage2Test2, questionText: 'a number of examples of plants that are not cultivated at present but could be useful as food sources', options: ['A','B','C','D','E'], correctAnswers: ['E'], passageHighlight: "including foxtail, oat-grass and cowpea." },
                    { id: 'b17t2rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has five sections, A-E. Which section contains the following information?', passage: ielts17ReadingPassage2Test2, questionText: 'a comparison between the early domestication of the tomato and more recent research', options: ['A','B','C','D','E'], correctAnswers: ['A'], passageHighlight: "It took at least 3,000 years for humans to learn how to domesticate the wild tomato... Now two separate teams... have done it all over again in less than three years." },
                    { id: 'b17t2rq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Reading Passage 2 has five sections, A-E. Which section contains the following information?', passage: ielts17ReadingPassage2Test2, questionText: 'a personal reaction to the flavour of a tomato that has been genetically edited', options: ['A','B','C','D','E'], correctAnswers: ['C'], passageHighlight: "‘They are quite tasty,’ says Kudla. ‘A little bit strong. And very aromatic.’" },
                    { id: 'b17t2rq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct researcher, A-D.', passage: ielts17ReadingPassage2Test2, questionText: '19 Domestication of certain plants could allow them to adapt to future environmental challenges.', options: ['A Jorg Kudla', 'B Caixia Gao', 'C Joyce Van Eck', 'D Jonathan Jones'], correctAnswers: ['B Caixia Gao'], passageHighlight: "By choosing wild plants that are drought or heat tolerant, says Gao, we could create crops that will thrive even as the planet warms." },
                    { id: 'b17t2rq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct researcher, A-D.', passage: ielts17ReadingPassage2Test2, questionText: '20 The idea of growing and eating unusual plants may not be accepted on a large scale.', options: ['A Jorg Kudla', 'B Caixia Gao', 'C Joyce Van Eck', 'D Jonathan Jones'], correctAnswers: ['D Jonathan Jones'], passageHighlight: "But it will be hard for new foods to grow so popular with farmers and consumers that they become new staple crops, he thinks." },
                    { id: 'b17t2rq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct researcher, A-D.', passage: ielts17ReadingPassage2Test2, questionText: '21 It is not advisable for the future direction of certain research to be made public.', options: ['A Jorg Kudla', 'B Caixia Gao', 'C Joyce Van Eck', 'D Jonathan Jones'], correctAnswers: ['A Jorg Kudla'], passageHighlight: "But Kudla didn’t want to reveal which species were in his team’s sights, because CRISPR has made the process so easy." },
                    { id: 'b17t2rq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct researcher, A-D.', passage: ielts17ReadingPassage2Test2, questionText: '22 Present efforts to domesticate one wild fruit are limited by the costs involved.', options: ['A Jorg Kudla', 'B Caixia Gao', 'C Joyce Van Eck', 'D Jonathan Jones'], correctAnswers: ['C Joyce Van Eck'], passageHighlight: "But she adds that taking the work further would be expensive because of the need to pay for a licence for the CRISPR technology and get regulatory approval." },
                    { id: 'b17t2rq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Match each statement with the correct researcher, A-D.', passage: ielts17ReadingPassage2Test2, questionText: '23 Humans only make use of a small proportion of the plant food available on Earth.', options: ['A Jorg Kudla', 'B Caixia Gao', 'C Joyce Van Eck', 'D Jonathan Jones'], correctAnswers: ['A Jorg Kudla'], passageHighlight: "‘There are 50,000 edible plants in the world, but 90 percent of our energy comes from just 15 crops.’" },
                    { id: 'b17t2rq24', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage2Test2, questionText: 'An undesirable trait such as loss of 24 ___ may be caused by a mutation in a tomato gene.', correctAnswers: ['flavour', 'flavor'], passageHighlight: "the tomato strains grown for supermarkets have lost much of their flavour." },
                    { id: 'b17t2rq25', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage2Test2, questionText: 'By modifying one gene in a tomato plant, researchers made the tomato three times its original 25 ___ .', correctAnswers: ['size'], passageHighlight: "they tripled the size of fruit by editing a gene called FRUIT WEIGHT" },
                    { id: 'b17t2rq26', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the sentences below. Choose ONE WORD ONLY from the passage for each answer.', passage: ielts17ReadingPassage2Test2, questionText: 'A type of tomato which was not badly affected by 26 ___ , and was rich in vitamin C, was produced by a team of researchers in China.', correctAnswers: ['salt'], passageHighlight: "another strain that is more salt tolerant – and has higher levels of vitamin C." },
                ],
            },
            { // Reading Passage 3
                questions: [
                    { id: 'b17t2rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test2, questionText: '27 The purpose of the first paragraph is to', options: ['A defend particular ideas.', 'B compare certain beliefs.', 'C disprove a widely held view.', 'D outline a common assumption.'], correctAnswers: ['D outline a common assumption.'], passageHighlight: "Scientific discovery is popularly believed to result from the sheer genius... Conventional wisdom also places great weight on insight...", reason: "The paragraph introduces what is 'popularly believed' and 'conventional wisdom', which are common assumptions, before the authors present their alternative view." },
                    { id: 'b17t2rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test2, questionText: '28 What are the writers doing in the second paragraph?', options: ['A criticising an opinion', 'B justifying a standpoint', 'C explaining an approach', 'D supporting an argument'], correctAnswers: ['A criticising an opinion'], passageHighlight: "However, we believe that it largely misrepresents the real nature of scientific discovery", reason: "The paragraph starts with 'However' and states that the popular view 'largely misrepresents' the truth, which is a direct criticism of the opinion outlined in the first paragraph." },
                    { id: 'b17t2rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test2, questionText: '29 In the third paragraph, what do the writers suggest about Darwin and Einstein?', options: ['A They represent an exception to a general rule.', 'B Their way of working has been misunderstood.', 'C They are an ideal which others should aspire to.', 'D Their achievements deserve greater recognition.'], correctAnswers: ['A They represent an exception to a general rule.'], passageHighlight: "Setting aside such greats as Darwin and Einstein... we suggest that innovation is more a process of trial and error", reason: "The text explicitly 'sets aside' Darwin and Einstein before presenting what the authors believe is the general rule for innovation (trial and error), implying they are exceptions." },
                    { id: 'b17t2rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test2, questionText: '30 John Nicholson is an example of a person whose idea', options: ['A established his reputation as an influential scientist.', 'B was only fully understood at a later point in history.', "C laid the foundations for someone else's breakthrough.", 'D initially met with scepticism from the scientific community.'], correctAnswers: ["C laid the foundations for someone else's breakthrough."], passageHighlight: "Niels Bohr, the Nobel prize-winning father of modern atomic theory, jumped off from this interesting idea to conceive his now-famous model of the atom.", reason: "The passage shows that Bohr used Nicholson's 'interesting idea' as a starting point ('jumped off from') for his own famous model, meaning Nicholson's work was the foundation." },
                    { id: 'b17t2rq31', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts17ReadingPassage3Test2, questionText: "31 What is the key point of interest about the 'acey-deucy' stirrup placement?", options: ['A the simple reason why it was invented', 'B the enthusiasm with which it was adopted', 'C the research that went into its development', 'D the cleverness of the person who first used it'], correctAnswers: ['A the simple reason why it was invented'], passageHighlight: "He suffered a leg injury, which left him unable to fully bend his left knee. His modification just happened to coincide with enhanced left-hand turning performance.", reason: "The passage explains the invention wasn't from methodical investigation but from a simple, accidental reason: a leg injury." },
                    { id: 'b17t2rq32', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test2, questionText: '32 Acknowledging people such as Plato or da Vinci as geniuses will help us understand the process by which great minds create new ideas.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "These notions merely label rather than explain the evolution of human innovations. We need another approach", reason: "The author states that calling people geniuses is just a 'label' and doesn't 'explain' the process of innovation, implying it's not a helpful approach to understanding it." },
                    { id: 'b17t2rq33', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test2, questionText: '33 The Law of Effect was discovered at a time when psychologists were seeking a scientific reason why creativity occurs.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage gives the date for the Law of Effect (1898) but does not state what other psychologists were doing or seeking at that specific time." },
                    { id: 'b17t2rq34', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test2, questionText: '34 The Law of Effect states that no planning is involved in the behaviour of organisms.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "an entirely mechanical process of variation and selection, without any end objective in sight.", reason: "The passage describes the process as 'entirely mechanical' and 'without any end objective in sight', which means no planning is involved." },
                    { id: 'b17t2rq35', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test2, questionText: '35 The Law of Effect sets out clear explanations about the sources of new ideas and behaviours.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "the provenance of the raw material on which the Law of Effect operates is not as clearly known", reason: "The passage explicitly states that the source ('provenance of the raw material') for the Law of Effect is 'not as clearly known', contradicting the idea that it provides clear explanations." },
                    { id: 'b17t2rq36', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer in Reading Passage 3?', passage: ielts17ReadingPassage3Test2, questionText: '36 Many scientists are now turning away from the notion of intelligent design and genius.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The final paragraph is a call to action from the writers ('The time seems right for abandoning...'), not a statement of fact that this is already happening among many scientists." },
                    { id: 'b17t2rq37', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of words, A-G, below.', passage: ielts17ReadingPassage3Test2, questionText: 'The traditional view of scientific discovery is that breakthroughs happen when a single great mind has sudden 37 ___ .', options: ['A invention', 'B goals', 'C compromise', 'D mistakes', 'E luck', 'F inspiration', 'G experiments'], correctAnswers: ['F inspiration'], passageHighlight: "as if ideas spontaneously pop into someone’s head – fully formed and functional.", reason: "The idea of something 'spontaneously popping into someone's head' is a classic description of sudden inspiration." },
                    { id: 'b17t2rq38', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of words, A-G, below.', passage: ielts17ReadingPassage3Test2, questionText: 'In some cases, this process involves 38 ___ , such as Nicholson’s theory about proto-elements.', options: ['A invention', 'B goals', 'C compromise', 'D mistakes', 'E luck', 'F inspiration', 'G experiments'], correctAnswers: ['D mistakes'], passageHighlight: "Nicholson was wrong about the presence of proto-elements: they do not actually exist.", reason: "Nicholson's theory was based on a mistake (proto-elements don't exist), but it still led to a breakthrough." },
                    { id: 'b17t2rq39', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of words, A-G, below.', passage: ielts17ReadingPassage3Test2, questionText: 'There is also often an element of 39 ___ , for example, the coincidence of ideas that led to the invention of the Post-It note.', options: ['A invention', 'B goals', 'C compromise', 'D mistakes', 'E luck', 'F inspiration', 'G experiments'], correctAnswers: ['E luck'], passageHighlight: "pure serendipity – a happy accident.", reason: "The invention of the Post-It note is given as an example of 'pure serendipity - a happy accident', which is an element of luck." },
                    { id: 'b17t2rq40', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of words, A-G, below.', passage: ielts17ReadingPassage3Test2, questionText: 'With both the Law of Natural Selection and the Law of Effect, there may be no clear 40 ___ involved, but merely a process of variation and selection.', options: ['A invention', 'B goals', 'C compromise', 'D mistakes', 'E luck', 'F inspiration', 'G experiments'], correctAnswers: ['B goals'], passageHighlight: "without any end objective in sight.", reason: "'End objective' is a synonym for a clear goal. The passage states the process works without one." },
                ]
            }
        ]
    },
    {
        id: 'b17-t2-w4',
        title: 'Test 2: Writing T1-2',
        section: Section.WRITING,
        parts: [
            {
                questions: [{
                    id: 'b17t2wq1',
                    type: QuestionType.WRITING_TASK,
                    prompt: 'You should spend about 20 minutes on this task.',
                    imageUrl: 'ielts-17/t2-w1-charts.png',
                    task: "The table and charts below give information on the police budget for 2017 and 2018 in one area of Britain. The table shows where the money came from and the charts show how it was distributed.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant. Write at least 150 words.",
                    sampleAnswer: "The table illustrates the data on the police budget in which the money came from and the two pie charts describe the distribution of the amount of money in the two of year 2017 and 2018 in an area of Britain. Overall, there was an upward trend in all three different sources while the money spent on salaries was always the majority of contribution.\n\nLooking into more details, the highest amount of money on the police budget belonged to ‘National Government’, 175.5 million pounds in 2017 and it kept rising to 177.8 million pounds. Thus, was followed by ‘Local Taxes’, at 91.2 million pounds in 2017, after one year, it increase significantly to 102.3 million pounds.\n\nIn term of the how the money was spent, the majority of police budget goes to salaries which was for officers and staff, dropping slightly from 75% in 2017 to 69% in 2018. Meanwhile, the proportion of ‘Buildings and transport’ remained constantly, at 17% each year. An opposite pattern can be seen in the category of technology, its figure rose sharply from 8% in 2017 to 14% in 2018, which was always the lowest rate during the given period.",
                    sampleAnswerBand: 7.5,
                    examinerComment: "This is a strong response. The candidate provides a clear overview at the end of the first paragraph which highlights the consistently increasing trend from the table and identifies the largest category from the pie charts. Full details are given for the first two sources of the budget but, to achieve a higher rating, key features in the table could be more fully extended.\n\nInformation is presented in the order of the table first and then the charts, in a logical manner. The test taker demonstrates a good range of cohesive devices [while | which was] and uses three paragraphs appropriately to organise and sequence the required data.\n\nThere is a wide range of vocabulary [figure rose sharply | during the given period] with accurate spelling, although there are occasional errors in word choice. The range of grammatical structures is wide, including modal [can] and continuous forms [kept rising] - although there are occasional errors e.g. using present tenses [goes on] to describe data from 2017 and 2018.\n\nTo improve this response, the key features presented from the table could be more fully extended. The candidate could also reduce the few errors in sentence structure."
                }]
            },
            {
                questions: [{
                    id: 'b17t2wq2',
                    type: QuestionType.WRITING_TASK,
                    prompt: 'You should spend about 40 minutes on this task. Write about the following topic:',
                    task: 'Some children spend hours every day on their smartphones.\n\nWhy is this the case? Do you think this is a positive or a negative development?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.',
                    sampleAnswer: "Mobile phones, nowadays, contains essential features with entertainment also. There has been a large growth seen in usage hours of smartphones among youngsters. There are several reasons behind this situation and I find this development more beneficial than negative. Both the reasons and my view is elaborated further.\n\nThe first reason for overusage of smart devices by youngsters is the social benefit they provide. The smart phone connected with internet opens up the large possibilities, from creating new friends to communicating with them over social media. for instance, a child in my neighbourhood chats for hours with his school friends over Facebook (a social media) and also spend time over online video sharing phone application. Moreover, the mobile gaming, specially multiplayer games, is another major reason for the situation. Children plays different kind of games over mobile for the entertainment purpose and they involve themselves in games in such a manner, that they forget about the timing and other work to do.\n\nHowever, I believe that smartphones have also increased the knowledge of pupils. It has developed some important social skills, such as communication skill, team work and many more, by allowing them to work and play in groups, without the restriction of distance. In addition, children can learn through internet by watchin online videos and reading articles, which ultimately helps them in their studies as well as language skills. for example, whenever my niece require to know about something, he searches it over the internet and learns from it. Moreover, multiplayer online gaming improves their multitasking ability and it also gives them a competitive environment\n\nOverall, I agree that overusage of smartphones on regular basis is harmful for them, but if given proper guidance, mobile phones can help them in learning some life-long skills.",
                    sampleAnswerBand: 6.5,
                    examinerComment: "This response addresses both parts of the question. A range of ideas is expressed and the candidate gives their position in the opening paragraph and then provides evidence and relevant examples.\n\nIdeas are logically organised and there is clear progression throughout the four paragraphs. A range of cohesive devices are used [The first reason | For instance | Moreover] with referencing used appropriately [they | themselves | their studies | it].\n\nThe range of vocabulary is good with examples of higher-level items [social skills | restriction of distance | ultimately] and there are few errors [overusage / overuse | niece ... he / niece ... she | watchin / watching | require to know / needs to know]. Similarly, the range of grammatical structures is reasonable, but the level of error means the Band Score cannot be higher than 6.5."
                }]
            }
        ]
    },
    {
        id: 'b17-t2-s5',
        title: 'Test 2: Speaking P1-3',
        section: Section.SPEAKING,
        parts: [
            {
                questions: [{
                    id: 'b17t2sq1',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 1: Example',
                    question: 'Reading\n\n- Did you have a favourite book when you were a child? [Why/Why not?]\n- How much reading do you do for your work/studies? [Why/Why not?]\n- What kinds of books do you read for pleasure? [Why/Why not?]\n- Do you prefer to read a newspaper or a magazine online, or to buy a copy? [Why?]',
                    sampleAnswer: `**1. Did you have a favourite book when you were a child?**
"Yes, definitely. My favourite book was 'The Hobbit' by J.R.R. Tolkien. I loved the sense of adventure and the detailed fantasy world he created. It really sparked my imagination, and I must have read it at least five or six times."

**2. How much reading do you do for your work/studies?**
"For my studies, I do a substantial amount of reading. I have to get through several academic articles and textbook chapters every week. It's not always the most exciting material, but it's essential for understanding my subject in depth."

**3. What kinds of books do you read for pleasure?**
"For pleasure, I enjoy a mix of things. I'm a big fan of contemporary fiction and also historical novels. Occasionally, I'll pick up a non-fiction book if the topic interests me, like a biography or something about popular science. I like to vary what I read to keep it interesting."

**4. Do you prefer to read a newspaper or a magazine online, or to buy a copy?**
"I almost always read news and magazines online now. It's just so much more convenient and up-to-date. I can access a huge range of sources from my phone or laptop, and it's better for the environment than buying a physical copy every day. I do miss the feeling of holding a newspaper sometimes, though."`
                }]
            },
            {
                questions: [{
                    id: 'b17t2sq2',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 2: Cue Card',
                    question: 'Describe a big city you would like to visit.\nYou should say:\n- which big city you would like to visit\n- how you would travel there\n- what you would do there\n- and explain why you would like to visit this big city.',
                    sampleAnswer: `A big city I would absolutely love to visit is Tokyo, in Japan. It's a place that has fascinated me for a long time.

To get there, I would have to travel by plane, as it's a very long-haul flight from my country. It would be a journey of over 12 hours, but I think it would be completely worth it.

Once I was there, I would want to experience the huge contrast between the traditional and the ultra-modern. I'd visit ancient temples like the Senso-ji Temple and explore the serene gardens of the Imperial Palace. Then, I'd dive into the modern side of the city by visiting places like Shibuya Crossing, which is famously the busiest intersection in the world, and exploring the vibrant, neon-lit streets of Shinjuku. Of course, I'd also have to indulge in the incredible food scene, from high-end sushi restaurants to small, local ramen shops.

The main reason I want to visit Tokyo is its unique culture. It seems like a city that is simultaneously futuristic and deeply rooted in tradition. The politeness of the people, the efficiency of the public transport, and the incredible attention to detail in everything from food presentation to architecture are all things I find incredibly appealing. I feel it would be a completely different world to explore.`
                }]
            },
            {
                questions: [{
                    id: 'b17t2sq3',
                    type: QuestionType.SPEAKING_TASK,
                    prompt: 'Part 3: Discussion topics',
                    question: 'Visiting cities on holiday\n- What are the most interesting things to do while visiting cities on holiday?\n- Why can it be expensive to visit cities on holiday?\n- Do you think it is better to visit cities alone or in a group with friends?\n\nThe growth of cities\n- Why have cities increased in size in recent years?\n- What are the challenges created by ever-growing cities?\n- In what ways do you think cities of the future will be different to cities today?',
                    sampleAnswer: `**Visiting cities on holiday**

**1. What are the most interesting things to do while visiting cities on holiday?**
"I think the most interesting things involve soaking up the local culture. This includes visiting historical sites and museums to understand the city's past, but also just wandering through different neighbourhoods to see how people live. Trying the local cuisine is also essential, as it's a huge part of any culture. I also enjoy finding a good viewpoint to see the city's skyline."

**2. Why can it be expensive to visit cities on holiday?**
"Cities are often expensive because everything is concentrated there – accommodation, transport, and attractions. High demand for central hotels drives up prices. Entrance fees for museums and famous landmarks can also add up quickly. Plus, eating out for every meal in popular tourist areas can be very costly compared to smaller towns."

**3. Do you think it is better to visit cities alone or in a group with friends?**
"Both have their advantages. Travelling alone gives you complete freedom and flexibility to do what you want, when you want. It can be a very reflective experience. However, visiting with friends is great for sharing experiences and creating memories together. It can also feel safer and more sociable, especially in the evenings."

**The growth of cities**

**4. Why have cities increased in size in recent years?**
"The primary reason is economic opportunity. Cities are hubs for jobs, education, and innovation, which attracts people from rural areas and other countries seeking better prospects. This migration, combined with natural population growth within cities, has led to rapid urban expansion."

**5. What are the challenges created by ever-growing cities?**
"There are many challenges. Infrastructure often struggles to keep up, leading to traffic congestion and strained public services like healthcare and schools. There's also the issue of affordable housing, which becomes increasingly scarce. Environmental problems like pollution and waste management are also major challenges for large, dense populations."

**6. In what ways do you think cities of the future will be different to cities today?**
"I think future cities will be 'smarter' and more sustainable. We'll likely see more integration of technology in managing traffic, energy, and public services. I also expect a greater focus on green spaces, pedestrian-friendly areas, and more efficient, environmentally-friendly public transport systems. There might also be a shift towards more mixed-use neighbourhoods where people can live, work, and socialise without long commutes."`
                }]
            }
        ]
    }
];
