import { Lesson, QuestionType, Section } from '../types';

const ielts18ReadingPassage1Test2 = `For centuries, historians and archaeologists have puzzled over the many mysteries of Stonehenge, a prehistoric monument that took an estimated 1,500 years to erect. Located on Salisbury Plain in southern England, it is comprised of roughly 100 massive upright stones placed in a circular layout.

Archaeologists believe England’s most iconic prehistoric ruin was built in several stages, with the earliest constructed 5,000 or more years ago. First, Neolithic* Britons used primitive tools, which may have been fashioned out of deer antlers, to dig a massive circular ditch and bank, or henge. Deep pits dating back to that era and located within the circle may have once held a ring of timber posts, according to some scholars.

Several hundred years later, it is thought, Stonehenge’s builders hoisted an estimated 80 bluestones, 43 of which remain today, into standing positions and placed them in either a horseshoe or circular formation. These stones have been traced all the way to the Preseli Hills in Wales, some 300 kilometres from Stonehenge. How, then, did prehistoric builders without sophisticated tools or engineering haul these boulders, which weigh up to four tons, over such a great distance?

According to one long-standing theory among archaeologists, Stonehenge’s builders fashioned sledges and rollers out of tree trunks to lug the bluestones from the Preseli Hills. They then transferred the boulders onto rafts and floated them first along the Welsh coast and then up the River Avon toward Salisbury Plain; alternatively, they may have towed each stone with a fleet of vessels. More recent archaeological hypotheses have them transporting the bluestones with supersized wicker baskets on a combination of ball bearings and long grooved planks, hauled by oxen.

As early as the 1970s, geologists have been adding their voices to the debate over how Stonehenge came into being. Challenging the classic image of industrious builders pushing, carting, rolling or hauling giant stones from faraway Wales, some scientists have suggested that it was glaciers, not humans, that carried the bluestones to Salisbury Plain. Most archaeologists have remained sceptical about this theory, however, wondering how the forces of nature could have delivered the exact number of stones needed to complete the circle.

The third phase of construction took place around 2000 BCE. At this point, sandstone slabs – known as ‘sarsens’ – were arranged into an outer crescent or ring; some were assembled into the iconic three-pieced structures called trilithons that stand tall in the centre of Stonehenge. Some 50 of these stones are now visible on the site, which may once have contained many more. Radiocarbon dating has revealed that work continued at Stonehenge until roughly 1600 BCE, with the bluestones in particular being repositioned multiple times.

But who were the builders of Stonehenge? In the 17th century, archaeologist John Aubrey made the claim that Stonehenge was the work of druids, who had important religious, judicial and political roles in Celtic** society. This theory was widely popularised by the antiquarian William Stukeley, who had unearthed primitive graves at the site. Even today, people who identify as modern druids continue to gather at Stonehenge for the summer solstice. However, in the mid-20th century, radiocarbon dating demonstrated that Stonehenge stood more than 1,000 years before the Celts inhabited the region.

Many modern historians and archaeologists now agree that several distinct tribes of people contributed to Stonehenge, each undertaking a different phase of its construction. Bones, tools and other artefacts found on the site seem to support this hypothesis. The first stage was achieved by Neolithic agrarians who were likely to have been indigenous to the British Isles. Later, it is believed, groups with advanced tools and a more communal way of life left their mark on the site. Some believe that they were immigrants from the European continent, while others maintain that they were probably native Britons, descended from the original builders.

If the facts surrounding the architects and construction of Stonehenge remain shadowy at best, the purpose of the striking monument is even more of a mystery. While there is consensus among the majority of modern scholars that Stonehenge once served the function of burial ground, they have yet to determine what other purposes it had.

In the 1960s, the astronomer Gerald Hawkins suggested that the cluster of megalithic stones operated as a form of calendar, with different points corresponding to astrological phenomena such as solstices, equinoxes and eclipses occurring at different times of the year. While his theory has received a considerable amount of attention over the decades, critics maintain that Stonehenge’s builders probably lacked the knowledge necessary to predict such events or that England’s dense cloud cover would have obscured their view of the skies.

More recently, signs of illness and injury in the human remains unearthed at Stonehenge led a group of British archaeologists to speculate that it was considered a place of healing, perhaps because bluestones were thought to have curative powers.`;
const ielts18ReadingPassage2Test2 = `Powerful artificial intelligence (AI) needs to be reliably aligned with human values, but does this mean AI will eventually have to police those values?

This has been the decade of AI, with one astonishing feat after another. A chess-playing AI that can defeat not only all human chess players, but also all previous human-programmed chess machines, after learning the game in just four hours? That’s yesterday’s news. What’s next? True, these prodigious accomplishments are all in so-called narrow AI, where machines perform highly specialised tasks. But many experts believe this restriction is very temporary. By mid-century, we may have artificial general intelligence (AGI) – machines that can achieve human-level performance on the full range of tasks that we ourselves can tackle.

If so, there’s little reason to think it will stop there. Machines will be free of the physical constraints on human intelligence. Our brains run at slow biochemical processing speeds on the power of a light bulb, and their size is restricted by the dimensions of the human birth canal. It is remarkable what they accomplish, given these handicaps. But they may be as far from the physical limits of thought as our legs are from the incredibly powerful Webb Space Telescope.

Once machines are better than us at designing even smarter machines, progress towards these limits could accelerate. What would this mean for us? Could we ensure a safe and worthwhile coexistence with such machines? On the plus side, AI is already useful and profitable for many things, and super AI might be expected to be super useful, and super profitable. But the more powerful AI becomes, the more important it will be to specify its goals with great care. Folklore is full of tales of people who ask for the wrong thing, with disastrous consequences – King Midas, for example, might have wished he had touched his food before he touched his daughter.

So we need to create powerful AI machines that are ‘human-friendly’ – that have goals reliably aligned with our own values. One thing that makes this task difficult is that we are far from reliably human-friendly ourselves. We do many terrible things to each other and to many other creatures with whom we share the planet. If superintelligent machines don’t do a lot better than us, we’ll be in deep trouble. We’ll have powerful new intelligence amplifying the dark sides of our own fallible natures.

For safety’s sake, then, we want the machines to be ethically as well as cognitively superintelligent. We want them to aim for the moral high ground, not for the troughs in which many of us spend some of our time. Luckily, they’ll be smart enough for the job. If there are routes to the moral high ground, they’ll be better than us at finding them, and steering us in the right direction.

However, there are two big problems with this utopian vision. One is how we get the machines started on the journey, the other is what it would mean to reach this destination. The ‘getting started’ problem is that we need to tell the machines what they’re looking for with sufficient clarity that we can be confident they will find it – whatever ‘it’ actually turns out to be. This won’t be easy, given that we are tribal creatures and conflicted about the ideals ourselves. We often ignore the suffering of strangers, and even contribute to it, at least indirectly. How then, do we point machines in the direction of something better?

As for the ‘destination’ problem, we might, by putting ourselves in the hands of these moral guides and gatekeepers, be sacrificing our own autonomy – an important part of what makes us human. Machines who are better than us at sticking to the moral high ground may be expected to discourage some of the lapses we presently take for granted. We might lose our freedom to discriminate in favour of our own communities, for example.

Loss of freedom to behave badly isn’t always a bad thing, of course: denying ourselves the freedom to put children to work in factories, or to smoke in restaurants are signs of progress. But are we ready for ethical silicon police limiting our options? They might be so good at doing it that we won’t notice them; but few of us are likely to welcome such a future.

These issues seem far-fetched, but they are to some extent already here. AI already has some input into how resources are used in our National Health Service (NHS) here in the UK, for example. If it was given a greater role, it might do much more efficiently than humans can manage, and act in the interests of taxpayers and those who use the health system. However, we’d be depriving some humans (e.g. senior doctors) of the control they presently enjoy. Since we’d want to ensure that people are treated equally and that policies are fair, the goals of AI would need to be specified correctly.

We have a new powerful technology to deal with – itself, literally, a new way of thinking. For our own safety, we need to point these new thinkers in the right direction, and get them to act well for us. It is not yet clear whether this is possible, but if it is, it will require a cooperative spirit, and a willingness to set aside self-interest.

Both general intelligence and moral reasoning are often thought to be uniquely human capacities. But safety seems to require that we think of them as a package: if we are to give general intelligence to machines, we’ll need to give them moral authority, too. And where exactly would that leave human beings? All the more reason to think about the destination now, and before we allow ourselves to be swept along.`;
const ielts18ReadingPassage3Test2 = `The word ‘genius’ is universally associated with the name of Leonardo da Vinci. A true Renaissance man, he embodied scientific spirit, artistic talent and humanist sensibilities. Five hundred years have passed since Leonardo died in his home at Château du Clos Lucé, outside Tours, France. Yet far from fading into insignificance, his thinking has carried down the centuries and still surprises today.

The Renaissance marked the transition from the 15th century to the 16th and took place after the spread of the plague in the 14th century, which caused a global crisis resulting in some 200 million deaths across Europe and Asia. Today, the world is on the cusp of a climate crisis, which is predicted to cause widespread displacement, extinctions and death, if left unaddressed. Then, as now, radical solutions were called for to revolutionise the way people lived and safeguard humanity against catastrophe.

Around 1486 – after a pestilence that killed half the population in Milan, Italy – Leonardo turned his thoughts to urban planning problems. Following a typical Renaissance trend, he began to work on an ‘ideal city’ project, which – due to its excessive costs – would remain unfulfilled. Yet given that unsustainable urban models are a key cause of global climate change today, it’s only natural to wonder how Leonardo might have changed the shape of modern cities.

Although the Renaissance is renowned as an era of incredible progress in art and architecture, it is rarely noted that the 15th century also marked the birth of urbanism as a true academic discipline. The rigour and method behind the conscious conception of a city had been largely missing in Western thought until the moment when prominent Renaissance men pushed forward large-scale urban projects in Italy, such as the reconfiguration of the town of Pienza and the expansion of the city of Ferrara. These works surely inspired Leonardo’s decision to rethink the design of medieval cities, with their winding and overcrowded streets and with houses piled against one another.

It is not easy to identify a coordinated vision of Leonardo’s ideal city because of his disordered way of working with notes and sketches. But from the largest collection of Leonardo’s papers ever assembled, a series of innovative thoughts can be reconstructed regarding the foundation of a new city along the Ticino River, which runs from Switzerland into Italy and is 248 kilometres long. He designed the city for the easy transport of goods and clean urban spaces, and he wanted a comfortable and spacious city, with well-ordered streets and architecture. He recommended ‘high, strong walls’, with ‘towers and battlements of all necessary and pleasant beauty’.

His plans for a modern and ‘rational’ city were consistent with Renaissance ideals. But, in keeping with his personality, Leonardo included several innovations in his urban design. Leonardo wanted the city to be built on several levels, linked with vertical outdoor staircases. This design can be seen in some of today’s high-rise buildings but was unconventional at the time. Indeed, this idea of taking full advantage of the interior spaces wasn’t implemented until the 1920s and 1930s, with the birth of the Modernist movement.

While in the upper layers of the city, people could walk undisturbed between elegant palaces and streets, the lower layer was the place for services, trade, transport and industry. But the true originality of Leonardo’s vision was its fusion of architecture and engineering. Leonardo designed extensive hydraulic plants to create artificial canals throughout the city. The canals, regulated by clocks and basins, were supposed to make it easier for boats to navigate inland. Leonardo also thought that the width of the streets ought to match the average height of the adjacent houses: a rule still followed in many contemporary cities across Italy, to allow access to sun and reduce the risk of damage from earthquakes.

Although some of these features existed in Roman cities, before Leonardo’s drawings there had never been a multi-level, compact modern city which was thoroughly technically conceived. Indeed, it wasn’t until the 19th century that some of his ideas were applied. For example, the subdivision of the city by function – with services and infrastructures located in the lower levels and wide and well-ventilated boulevards and walkways above for residents – is an idea that can be found in Georges-Eugène Haussmann’s renovation of Paris under Emperor Napoleon III between 1853 and 1870.

Today, Leonardo’s ideas are not simply valid, they actually suggest a way forward for urban planning. Many scholars think that the compact city, built upwards instead of outwards, integrated with nature (especially water systems), with efficient transport infrastructure, could help modern cities become more efficient and sustainable. This is yet another reason why Leonardo was aligned so closely with modern urban planning and centuries ahead of his time.`;

export const ielts18Test2Lessons: Lesson[] = [
  // Test 2
  {
    id: 'b18-t2-l0',
    title: 'Test 2: Listening P1-2',
    section: Section.LISTENING,
    parts: [
      { // Part 1
        questions: [
          { id: 'b18t2lq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p1.mp3', questionText: 'Benefits: 1 ___ provided for all staff', correctAnswers: ['training'], transcript: "all employees get training – even temporary staff.", transcriptHighlight: "training" },
          { id: 'b18t2lq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p1.mp3', questionText: '2 ___ during weekdays at all Milo’s Restaurants', correctAnswers: ['discount'], transcript: "you can get a discount at any of their restaurants.", transcriptHighlight: "discount" },
          { id: 'b18t2lq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p1.mp3', questionText: '3 ___ provided after midnight', correctAnswers: ['taxi'], transcript: "if you have to do a late shift and finish work after midnight, the company will pay for you to get a taxi home.", transcriptHighlight: "taxi" },
          { id: 'b18t2lq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p1.mp3', questionText: 'Person specification: must care about maintaining a high standard of 4 ___', correctAnswers: ['service'], transcript: "The last place I worked for was quite demanding too. We were expected to give a really high level of service.", transcriptHighlight: "service" },
          { id: 'b18t2lq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p1.mp3', questionText: 'must have a qualification in 5 ___', correctAnswers: ['English'], transcript: "So, you’ll need to have a certificate in English. Sure.", transcriptHighlight: "English" },
          { id: 'b18t2lq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t2-p1.mp3', questionText: 'Location: 6 ___ Street', correctAnswers: ['Wivenhoe'], transcript: "OK. Let’s have a look at the current job vacancies at Milo’s. The first one is in Wivenhoe Street. Wivenhoe, W-I-V-E-N-H-O-E.", transcriptHighlight: "Wivenhoe" },
          { id: 'b18t2lq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t2-p1.mp3', questionText: 'Responsibilities include: Making sure 7 ___ is clean', correctAnswers: ['equipment'], transcript: "Obviously checking all the portions are correct, etc., and then things like checking all the procedures for cleaning the equipment are being followed.", transcriptHighlight: "equipment" },
          { id: 'b18t2lq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t2-p1.mp3', questionText: 'Pay and conditions: Starting salary £___ per hour', correctAnswers: ['9.75'], transcript: "Well, to begin with, you’d be getting £9.75 but that goes up to £11.25 after three months.", transcriptHighlight: "9.75" },
          { id: 'b18t2lq9', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t2-p1.mp3', questionText: 'Maintaining stock and organising 9 ___', correctAnswers: ['deliveries'], transcript: "Right, well obviously this role would involve supporting the sous chef and other senior staff. And you’d be responsible for making sure there’s enough stock each week – and sorting out all the deliveries.", transcriptHighlight: "deliveries" },
          { id: 'b18t2lq10', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the table below. Write ONE WORD AND/OR A NUMBER.', audioUrl: 'ielts-18/t2-p1.mp3', questionText: 'No work on a 10 ___ once a month', correctAnswers: ['Sunday'], transcript: "The usual. I think. There’s a lot of evening and weekend work, but they’re closed on Mondays. But you do get one Sunday off every four weeks.", transcriptHighlight: "Sunday" },
        ],
      },
      { // Part 2
        questions: [
          { id: 'b18t2lq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'What are the TWO main reasons why this site has been chosen for the housing development?', maxSelections: 2, audioUrl: 'ielts-18/t2-p2.mp3', questionText: 'Choose TWO letters, A-E.', options: ['A It has suitable geographical features.', 'B There is easy access to local facilities.', 'C It has good connections with the airport.', 'D The land is of little agricultural value.', 'E It will be convenient for workers.'], correctAnswers: ['B There is easy access to local facilities.', 'E It will be convenient for workers.'], transcript: "At present it’s being used for farming, like much of the land around Nunston. But because of the new industrial centre in Nunston, there’s a lot of demand for housing for employees in the region... We were more interested in the fact that there’s an excellent hospital just 15 kilometres away, and a large secondary school even closer than that.", transcriptHighlight: "demand for housing for employees... excellent hospital... large secondary school" },
          { id: 'b18t2lq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO aspects of the planned housing development have people given positive feedback about?', maxSelections: 2, audioUrl: 'ielts-18/t2-p2.mp3', questionText: 'Choose TWO letters, A-E.', options: ['A the facilities for cyclists', 'B the impact on the environment', 'C the encouragement of good relations between residents', 'D the low cost of all the accommodation', 'E the rural location'], correctAnswers: ['B the impact on the environment', 'C the encouragement of good relations between residents'], transcript: "the designs for the layout of the development, with the majority of people saying it generally made a good impression and blended in well with the natural features of the landscape, with provision made for protecting trees and wildlife on the site... we’ll look at that, but the overall feedback has been that the design and facilities of the development make it seem a place where people of all ages can live together happily.", transcriptHighlight: "blended in well with the natural features of the landscape... a place where people of all ages can live together happily" },
          { id: 'b18t2lq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Label the map below. Write the correct letter, A-I.', imageUrl: 'ielts-18/ielts-18-t2-p2-map.png', audioUrl: 'ielts-18/t2-p2.mp3', questionText: '15 School', options: ['A','B','C','D','E','F','G','H','I'], correctAnswers: ['G'], transcript: "There’ll also be a school for children up to 11 years old. If you look at the South Entrance at the bottom of the map, there’s a road from there that goes right up through the development. The school will be on that road, at the corner of the second turning to the left.", transcriptHighlight: "at the corner of the second turning to the left" },
          { id: 'b18t2lq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Label the map below. Write the correct letter, A-I.', imageUrl: 'ielts-18/ielts-18-t2-p2-map.png', audioUrl: 'ielts-18/t2-p2.mp3', questionText: '16 Sports centre', options: ['A','B','C','D','E','F','G','H','I'], correctAnswers: ['C'], transcript: "A large sports centre is planned with facilities for indoor and outdoor activities. This will be on the western side of the development, just below the road that branches off from London Road.", transcriptHighlight: "western side of the development, just below the road" },
          { id: 'b18t2lq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Label the map below. Write the correct letter, A-I.', imageUrl: 'ielts-18/ielts-18-t2-p2-map.png', audioUrl: 'ielts-18/t2-p2.mp3', questionText: '17 Clinic', options: ['A','B','C','D','E','F','G','H','I'], correctAnswers: ['D'], transcript: "There’ll be a clinic where residents can go if they have any health problems. Can you see the lake towards the top of the map? The clinic will be just below this, to the right of a street of houses.", transcriptHighlight: "just below this, to the right of a street of houses" },
          { id: 'b18t2lq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Label the map below. Write the correct letter, A-I.', imageUrl: 'ielts-18/ielts-18-t2-p2-map.png', audioUrl: 'ielts-18/t2-p2.mp3', questionText: '18 Community centre', options: ['A','B','C','D','E','F','G','H','I'], correctAnswers: ['B'], transcript: "There’ll also be a community centre for people of all ages. On the northeast side of the development, there’ll be a row of specially designed houses specifically for residents over 65, and the community centre will be adjoining this.", transcriptHighlight: "northeast side... adjoining this" },
          { id: 'b18t2lq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Label the map below. Write the correct letter, A-I.', imageUrl: 'ielts-18/ielts-18-t2-p2-map.png', audioUrl: 'ielts-18/t2-p2.mp3', questionText: '19 Supermarket', options: ['A','B','C','D','E','F','G','H','I'], correctAnswers: ['H'], transcript: "We haven’t forgotten about shopping. There’ll be a supermarket between the two entrances to the development. We’re planning to leave the three large trees near London Road, and it’ll be just to the south of these.", transcriptHighlight: "between the two entrances... just to the south of these" },
          { id: 'b18t2lq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Label the map below. Write the correct letter, A-I.', imageUrl: 'ielts-18/ielts-18-t2-p2-map.png', audioUrl: 'ielts-18/t2-p2.mp3', questionText: '20 Playground', options: ['A','B','C','D','E','F','G','H','I'], correctAnswers: ['A'], transcript: "It’s planned to have a playground for younger children. If you look at the road that goes up from the South Entrance, you’ll see it curves round to the left at the top, and the playground will be in that curve, with nice views of the lake.", transcriptHighlight: "in that curve, with nice views of the lake" },
        ],
      }
    ]
  },
  {
    id: 'b18-t2-l1',
    title: 'Test 2: Listening P3-4',
    section: Section.LISTENING,
    parts: [
      { // Part 3
        questions: [
          { id: 'b18t2lq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t2-p3.mp3', questionText: 'Why do the students think the Laki eruption of 1783 is so important?', options: ['A It was the most severe eruption in modern times.', 'B It led to the formal study of volcanoes.', 'C It had a profound effect on society.'], correctAnswers: ['C It had a profound effect on society.'], transcript: "it really gives you a sense of how catastrophic the volcano was. People were really trying to make sense of the science for the first time. That’s right. But what I found more significant was how it impacted directly and indirectly on political events, as well as having massive social and economic consequences.", transcriptHighlight: "massive social and economic consequences" },
          { id: 'b18t2lq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t2-p3.mp3', questionText: 'What surprised Adam about observations made at the time?', options: ['A the number of places producing them', 'B the contradictions in them', 'C the lack of scientific data to support them'], correctAnswers: ['A the number of places producing them'], transcript: "Yeah – I was surprised there were so many weather stations established by that time – so, you know, you can see how the weather changed, often by the hour.", transcriptHighlight: "surprised there were so many weather stations" },
          { id: 'b18t2lq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t2-p3.mp3', questionText: 'According to Michelle, what did the contemporary sources say about the Laki haze?', options: ['A People thought it was similar to ordinary fog.', 'B It was associated with health issues.', 'C It completely blocked out the sun for weeks.'], correctAnswers: ['B It was associated with health issues.'], transcript: "Reports from the period blamed the haze for an increase in headaches, respiratory issues and asthma attacks.", transcriptHighlight: "increase in headaches, respiratory issues and asthma attacks" },
          { id: 'b18t2lq24', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Part 3: Choose the correct letter, A, B or C.', audioUrl: 'ielts-18/t2-p3.mp3', questionText: 'Adam corrects Michelle when she claims that Benjamin Franklin', options: ['A came to the wrong conclusion about the cause of the haze.', 'B was the first to identify the reason for the haze.', 'C supported the opinions of other observers about the haze.'], correctAnswers: ['B was the first to identify the reason for the haze.'], transcript: "At first no one realised that the haze was caused by the volcanic eruption in Iceland. It was Benjamin Franklin who realised that before anyone else. He’s often credited with that. Apparently, but a French naturalist beat him to it – I can’t remember his name.", transcriptHighlight: "a French naturalist beat him to it" },
          { id: 'b18t2lq25', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Which TWO issues following the Laki eruption surprised the students?', maxSelections: 2, audioUrl: 'ielts-18/t2-p3.mp3', questionText: 'Choose TWO letters, A-E.', options: ['A how widespread the effects were', 'B how long-lasting the effects were', 'C the number of deaths it caused', 'D the speed at which the volcanic ash cloud spread', 'E how people ignored the warning signs'], correctAnswers: ['A how widespread the effects were', 'B how long-lasting the effects were'], transcript: "Mmm. You’d expect that, but the fact that the volcanic ash drifted so swiftly – but not that the effects would go on for so long. Or that two years after the eruption, strange weather events were being reported as far away as North America and North Africa.", transcriptHighlight: "effects would go on for so long... as far away as North America and North Africa" },
          { id: 'b18t2lq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'What comment do the students make about the impact of the Laki eruption on the following countries?', audioUrl: 'ielts-18/t2-p3.mp3', questionText: '27 Iceland', options: ['A This country suffered the most severe loss of life.', 'B The impact on agriculture was predictable.', 'C There was a significant increase in deaths of young people.', 'D Animals suffered from a sickness.', 'E This country saw the highest rise in food prices in the world.', 'F It caused a particularly harsh winter.'], correctAnswers: ['D Animals suffered from a sickness.'], transcript: "Mmm. One of the most dramatic things there was the effect on livestock as they grazed in the fields. They became poisoned because they ate vegetation that had been contaminated with fluorine as a result of the volcanic fallout.", transcriptHighlight: "effect on livestock" },
          { id: 'b18t2lq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'What comment do the students make about the impact of the Laki eruption on the following countries?', audioUrl: 'ielts-18/t2-p3.mp3', questionText: '28 Egypt', options: ['A This country suffered the most severe loss of life.', 'B The impact on agriculture was predictable.', 'C There was a significant increase in deaths of young people.', 'D Animals suffered from a sickness.', 'E This country saw the highest rise in food prices in the world.', 'F It caused a particularly harsh winter.'], correctAnswers: ['A This country suffered the most severe loss of life.'], transcript: "In Egypt, the bizarre weather patterns led to a severe drought and as a result the Nile didn’t flood, which meant the crops all failed. It’s so far from where the eruption happened and yet the famine there led to more people dying than any other country.", transcriptHighlight: "more people dying than any other country" },
          { id: 'b18t2lq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'What comment do the students make about the impact of the Laki eruption on the following countries?', audioUrl: 'ielts-18/t2-p3.mp3', questionText: '29 UK', options: ['A This country suffered the most severe loss of life.', 'B The impact on agriculture was predictable.', 'C There was a significant increase in deaths of young people.', 'D Animals suffered from a sickness.', 'E This country saw the highest rise in food prices in the world.', 'F It caused a particularly harsh winter.'], correctAnswers: ['C There was a significant increase in deaths of young people.'], transcript: "OK. Then in the UK the mortality rate went up a lot – presumably from respiratory illnesses. According to one report it was about double the usual number and included an unusually high percentage of people under the age of 25.", transcriptHighlight: "unusually high percentage of people under the age of 25" },
          { id: 'b18t2lq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'What comment do the students make about the impact of the Laki eruption on the following countries?', audioUrl: 'ielts-18/t2-p3.mp3', questionText: '30 USA', options: ['A This country suffered the most severe loss of life.', 'B The impact on agriculture was predictable.', 'C There was a significant increase in deaths of young people.', 'D Animals suffered from a sickness.', 'E This country saw the highest rise in food prices in the world.', 'F It caused a particularly harsh winter.'], correctAnswers: ['F It caused a particularly harsh winter.'], transcript: "Mmm. I think people will be surprised to hear that the weather in the USA was badly affected too. George Washington even makes a note in his diary that they were snowbound until March in Virginia. That was before he became president. Yes, and there was ice floating down the Mississippi, which was unprecedented.", transcriptHighlight: "snowbound until March... ice floating down the Mississippi" },
        ]
      },
      { // Part 4
        questions: [
          { id: 'b18t2lq31', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p4.mp3', questionText: 'Reason for choice of subject: They are 31 ___ but can be overlooked by consumers and designers.', correctAnswers: ['convenient'], transcript: "I decided to focus on a rather small area of clothing and that’s pockets. I chose pockets for two reasons, really. We all have them – in jeans, jackets, coats, for example – and even though we often carry bags or briefcases as well, nothing is quite as convenient as being able to pop your phone or credit card into your pocket.", transcriptHighlight: "convenient" },
          { id: 'b18t2lq32', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p4.mp3', questionText: 'Pockets in men’s clothes: Men started to wear 32 ___ in the 18th century.', correctAnswers: ['suits'], transcript: "It’s certainly very interesting to go back in time and see how pockets developed for men and women. In the 18th century, fashions were quite different from the way they are now, and pockets were too. If we think about male fashion first, that was the time when suits became popular.", transcriptHighlight: "suits" },
          { id: 'b18t2lq33', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p4.mp3', questionText: 'A 33 ___ sewed pockets into the lining of the garments.', correctAnswers: ['tailor'], transcript: "trousers were knee-length only and referred to as ‘breeches’. The waistcoats were short and the jackets were long, but all three garments were lined with material and pockets were sewn into this cloth by whichever tailor the customer used.", transcriptHighlight: "tailor" },
          { id: 'b18t2lq34', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p4.mp3', questionText: 'Bigger pockets might be made for men who belonged to a certain type of 34 ___ .', correctAnswers: ['profession'], transcript: "Cool pockets became increasingly decorative on the outside, for men who wanted to look stylish, but they were often larger but plainer if the wearer was someone with a profession who needed to carry medical instruments – a doctor or physician, for example.", transcriptHighlight: "profession" },
          { id: 'b18t2lq35', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p4.mp3', questionText: "Pockets in women's clothes: Women's pockets were less 35 ___ than men's.", correctAnswers: ['visible'], transcript: "As the development of women’s pockets. For one thing, they weren’t nearly as visible or as easy to reach as men’s.", transcriptHighlight: "visible" },
          { id: 'b18t2lq36', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p4.mp3', questionText: 'Pockets were produced in pairs using 36 ___ to link them together.', correctAnswers: ['string(s)'], transcript: "Women were more vulnerable to theft and wealthy women, in particular, worried constantly about pickpockets. So...what they did was to have a pair of pockets made that were tied together with string.", transcriptHighlight: "string" },
          { id: 'b18t2lq37', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p4.mp3', questionText: "Pockets hung from the women's 37 ___ under skirts and petticoats.", correctAnswers: ['waist(s)'], transcript: "Women tied the pockets around their waists so that they hung beneath their clothes.", transcriptHighlight: "waists" },
          { id: 'b18t2lq38', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p4.mp3', questionText: 'Items such as 38 ___ could be reached through a gap in the material.', correctAnswers: ['perfume'], transcript: "Women then tied the pockets around their waists so that they hung beneath their clothes... They would have an opening in the folds of their skirts through which they could reach whatever they needed, like their perfume.", transcriptHighlight: "perfume" },
          { id: 'b18t2lq39', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p4.mp3', questionText: 'When dresses changed shape, hidden pockets had a negative effect on the 39 ___ of women.', correctAnswers: ['image'], transcript: "That’s when dresses became tighter and less bulky, and the pairs of pockets became very noticeable – they stood out too much and detracted from the woman’s image.", transcriptHighlight: "image" },
          { id: 'b18t2lq40', type: QuestionType.SHORT_ANSWER, prompt: 'Part 4: Complete the notes. Write ONE WORD ONLY.', audioUrl: 'ielts-18/t2-p4.mp3', questionText: "Bags called 'pouches' became popular, before women carried a 40 ___ .", correctAnswers: ['handbag'], transcript: "That was when small bags, or pouches as they were known, came into fashion and, of course, they inevitably led on to the handbag of more modern times", transcriptHighlight: "handbag" },
        ]
      }
    ]
  },
  {
    id: 'b18-t2-r2',
    title: 'Test 2: Reading P1',
    section: Section.READING,
    parts: [{
      questions: [
        { id: 'b18t2rq1', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose NO MORE THAN TWO WORDS.', passage: ielts18ReadingPassage1Test2, questionText: 'Stage 1: the ditch and henge were dug, possibly using tools made from 1 ___', correctAnswers: ['(deer) antlers'], passageHighlight: "used primitive tools, which may have been fashioned out of deer antlers, to dig a massive circular ditch and bank" },
        { id: 'b18t2rq2', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose NO MORE THAN TWO WORDS.', passage: ielts18ReadingPassage1Test2, questionText: '2 ___ may have been arranged in deep pits inside the circle', correctAnswers: ['(timber) posts'], passageHighlight: "pits... may have once held a ring of timber posts" },
        { id: 'b18t2rq3', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose NO MORE THAN TWO WORDS.', passage: ielts18ReadingPassage1Test2, questionText: 'theories about the transportation of the bluestones - archaeological: builders used 3 ___ to make sledges and rollers', correctAnswers: ['tree trunks'], passageHighlight: "fashioned sledges and rollers out of tree trunks" },
        { id: 'b18t2rq4', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose NO MORE THAN TWO WORDS.', passage: ielts18ReadingPassage1Test2, questionText: '4 ___ pulled them on giant baskets', correctAnswers: ['oxen'], passageHighlight: "hauled by oxen" },
        { id: 'b18t2rq5', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose NO MORE THAN TWO WORDS.', passage: ielts18ReadingPassage1Test2, questionText: 'geological: they were brought from Wales by 5 ___', correctAnswers: ['glaciers'], passageHighlight: "it was glaciers, not humans, that carried the bluestones" },
        { id: 'b18t2rq6', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose NO MORE THAN TWO WORDS.', passage: ielts18ReadingPassage1Test2, questionText: 'Builders: a theory arose in the 17th century that its builders were Celtic 6 ___', correctAnswers: ['druids'], passageHighlight: "Stonehenge was the work of druids" },
        { id: 'b18t2rq7', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose NO MORE THAN TWO WORDS.', passage: ielts18ReadingPassage1Test2, questionText: 'Purpose: many experts agree it has been used as a 7 ___ site', correctAnswers: ['burial'], passageHighlight: "served the function of burial ground" },
        { id: 'b18t2rq8', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the notes below. Choose NO MORE THAN TWO WORDS.', passage: ielts18ReadingPassage1Test2, questionText: 'in the 1960s, it was suggested that it worked as a kind of 8 ___', correctAnswers: ['calendar'], passageHighlight: "operated as a form of calendar" },
        { id: 'b18t2rq9', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1Test2, questionText: 'During the third phase of construction, sandstone slabs were placed in both the outer areas and the middle of the Stonehenge site.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "sandstone slabs – known as ‘sarsens’ – were arranged into an outer crescent or ring; some were assembled into the iconic three-pieced structures called trilithons that stand tall in the centre of Stonehenge." },
        { id: 'b18t2rq10', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1Test2, questionText: 'There is scientific proof that the bluestones stood in the same spot until 1600 BCE.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "work continued at Stonehenge until roughly 1600 BCE, with the bluestones in particular being repositioned multiple times." },
        { id: 'b18t2rq11', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1Test2, questionText: 'John Aubrey’s theory about Stonehenge was supported by 20th-century findings.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "in the mid-20th century, radiocarbon dating demonstrated that Stonehenge stood more than 1,000 years before the Celts inhabited the region." },
        { id: 'b18t2rq12', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1Test2, questionText: 'Objects discovered at Stonehenge seem to indicate that it was constructed by a number of different groups of people.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "Bones, tools and other artefacts found on the site seem to support this hypothesis." },
        { id: 'b18t2rq13', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage1Test2, questionText: "Criticism of Gerald Hawkins' theory about Stonehenge has come mainly from other astronomers.", options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'], reason: "The passage mentions 'critics' but does not specify their profession." },
      ]
    }]
  },
  {
    id: 'b18-t2-r3',
    title: 'Test 2: Reading P2-3',
    section: Section.READING,
    parts: [
      { // Reading Passage 2
        questions: [
          { id: 'b18t2rq14', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test2, questionText: '14 What point does the writer make about AI in the first paragraph?', options: ['A It is difficult to predict how quickly AI will progress.', 'B Much can be learned about the use of AI in chess machines.', 'C The future is unlikely to see limitations on the capabilities of AI.', 'D Experts disagree on which specialised tasks AI will be able to perform.'], correctAnswers: ['C The future is unlikely to see limitations on the capabilities of AI.'], passageHighlight: "If so, there’s little reason to think it will stop there." },
          { id: 'b18t2rq15', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test2, questionText: '15 What is the writer doing in the second paragraph?', options: ['A explaining why machines will be able to outperform humans', 'B describing the characteristics that humans and machines share', 'C giving information about the development of machine intelligence', 'D indicating which aspects of humans are the most advanced'], correctAnswers: ['A explaining why machines will be able to outperform humans'], passageHighlight: "Machines will be free of the physical constraints on human intelligence." },
          { id: 'b18t2rq16', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test2, questionText: '16 Why does the writer mention the story of King Midas?', options: ['A to compare different visions of progress', 'B to illustrate that poorly defined objectives can go wrong', 'C to emphasise the need for cooperation', 'D to point out the financial advantages of a course of action'], correctAnswers: ['B to illustrate that poorly defined objectives can go wrong'], passageHighlight: "Folklore is full of tales of people who ask for the wrong thing, with disastrous consequences – King Midas, for example" },
          { id: 'b18t2rq17', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test2, questionText: '17 What challenge does the writer refer to in the fourth paragraph?', options: ['A encouraging humans to behave in a more principled way', 'B deciding which values we want AI to share with us', 'C creating a better world for all creatures on the planet', 'D ensuring AI is more human-friendly than we are ourselves'], correctAnswers: ['D ensuring AI is more human-friendly than we are ourselves'], passageHighlight: "If superintelligent machines don’t do a lot better than us, we’ll be in deep trouble." },
          { id: 'b18t2rq18', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test2, questionText: '18 What does the writer suggest about AI in the fifth paragraph?', options: ['A The safety of machines will become a key issue.', 'B It is hard to know what impact AI will have on the world.', 'C Machines will be superior to humans in certain respects.', 'D Many humans will be happy to see new thinkers in the right direction'], correctAnswers: ['C Machines will be superior to humans in certain respects.'], passageHighlight: "they’ll be better than us at finding them, and steering us in the right direction." },
          { id: 'b18t2rq19', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Choose the correct letter, A, B, C or D.', passage: ielts18ReadingPassage2Test2, questionText: '19 Which of the following best summarises the writer’s argument in the sixth paragraph?', options: ['A More intelligent machines will result in greater abuses of power.', 'B Machine learning will share very few features with human learning.', 'C There are a limited number of people with the knowledge to program machines.', 'D Human shortcomings will make creating the machines we need more difficult.'], correctAnswers: ['D Human shortcomings will make creating the machines we need more difficult.'], passageHighlight: "This won’t be easy, given that we are tribal creatures and conflicted about the ideals ourselves." },
          { id: 'b18t2rq20', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer?', passage: ielts18ReadingPassage2Test2, questionText: '20 Machines with the ability to make moral decisions may prevent us from promoting the interests of our communities.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "We might lose our freedom to discriminate in favour of our own communities, for example." },
          { id: 'b18t2rq21', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer?', passage: ielts18ReadingPassage2Test2, questionText: '21 Silicon police would need to exist in large numbers in order to be effective.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'] },
          { id: 'b18t2rq22', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer?', passage: ielts18ReadingPassage2Test2, questionText: '22 Many people are comfortable with the prospect of their independence being restricted by machines.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['NO'], passageHighlight: "but few of us are likely to welcome such a future." },
          { id: 'b18t2rq23', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the claims of the writer?', passage: ielts18ReadingPassage2Test2, questionText: '23 If we want to ensure that machines act in our best interests, we all need to work together.', options: ['YES', 'NO', 'NOT GIVEN'], correctAnswers: ['YES'], passageHighlight: "it will require a cooperative spirit, and a willingness to set aside self-interest." },
          { id: 'b18t2rq24', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-F.', passage: ielts18ReadingPassage2Test2, questionText: 'AI currently has a limited role in the way 24 ___ are allocated in the health service.', options: ['A medical practitioners', 'B specialised tasks', 'C available resources', 'D reduced illness', 'E professional authority', 'F technology experts'], correctAnswers: ['C available resources'], passageHighlight: "AI already has some input into how resources are used in our National Health Service" },
          { id: 'b18t2rq25', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-F.', passage: ielts18ReadingPassage2Test2, questionText: 'However, such a change would result, for example, in certain 25 ___ not having their current level of', options: ['A medical practitioners', 'B specialised tasks', 'C available resources', 'D reduced illness', 'E professional authority', 'F technology experts'], correctAnswers: ['A medical practitioners'], passageHighlight: "we’d be depriving some humans (e.g. senior doctors) of the control they presently enjoy." },
          { id: 'b18t2rq26', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Complete the summary using the list of phrases, A-F.', passage: ielts18ReadingPassage2Test2, questionText: '26 ___.', options: ['A medical practitioners', 'B specialised tasks', 'C available resources', 'D reduced illness', 'E professional authority', 'F technology experts'], correctAnswers: ['E professional authority'], passageHighlight: "depriving some humans (e.g. senior doctors) of the control they presently enjoy." },
        ]
      },
      { // Reading Passage 3
        questions: [
          { id: 'b18t2rq27', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage3Test2, questionText: '27 People first referred to Leonardo da Vinci as a genius 500 years ago.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'] },
          { id: 'b18t2rq28', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage3Test2, questionText: '28 The current climate crisis is predicted to cause more deaths than the plague.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'] },
          { id: 'b18t2rq29', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage3Test2, questionText: '29 Some of the challenges we face today can be compared to those of earlier times.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "Then, as now, radical solutions were called for" },
          { id: 'b18t2rq30', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage3Test2, questionText: "30 Leonardo da Vinci's 'ideal city' was constructed in the 15th century.", options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "would remain unfulfilled" },
          { id: 'b18t2rq31', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage3Test2, questionText: '31 Poor town planning is a major contributor to climate change.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['TRUE'], passageHighlight: "unsustainable urban models are a key cause of global climate change today" },
          { id: 'b18t2rq32', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage3Test2, questionText: '32 In Renaissance times, local people fought against the changes to Pienza and Ferrara.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['NOT GIVEN'] },
          { id: 'b18t2rq33', type: QuestionType.MULTIPLE_CHOICE, prompt: 'Do the following statements agree with the information in the passage?', passage: ielts18ReadingPassage3Test2, questionText: '33 Leonardo da Vinci kept a neat, organised record of his designs.', options: ['TRUE', 'FALSE', 'NOT GIVEN'], correctAnswers: ['FALSE'], passageHighlight: "his disordered way of working with notes and sketches" },
          { id: 'b18t2rq34', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3Test2, questionText: 'This was to provide better 34 ___ for trade', correctAnswers: ['transport'], passageHighlight: "designed the city for the easy transport of goods" },
          { id: 'b18t2rq35', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3Test2, questionText: 'They included features that can be seen in some tower blocks today, such as 35 ___ on the exterior of a building.', correctAnswers: ['staircases'], passageHighlight: "linked with vertical outdoor staircases. This design can be seen in some of today’s high-rise buildings" },
          { id: 'b18t2rq36', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3Test2, questionText: 'Leonardo da Vinci wasn’t only an architect. His expertise in 36 ___ was evident in his plans for artificial canals within his ideal city.', correctAnswers: ['engineering'], passageHighlight: "Leonardo designed extensive hydraulic plants to create artificial canals" },
          { id: 'b18t2rq37', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3Test2, questionText: 'He also believed that the height of houses should relate to the width of streets to reduce the risk of earthquakes. The design of many cities in Italy today follows this 37 ___ .', correctAnswers: ['rule'], passageHighlight: "a rule still followed in many contemporary cities across Italy, to allow access to sun and reduce the risk of damage from earthquakes" },
          { id: 'b18t2rq38', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3Test2, questionText: 'While some cities from 38 ___ times have aspects that can also be found in Leonardo’s designs...', correctAnswers: ['Roman'], passageHighlight: "Although some of these features existed in Roman cities" },
          { id: 'b18t2rq39', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3Test2, questionText: '... 39 ___ is one example of a city that was redesigned in the 19th century in the way that Leonardo had envisaged.', correctAnswers: ['Paris'], passageHighlight: "an idea that can be found in Georges-Eugène Haussmann’s renovation of Paris under Emperor Napoleon III between 1853 and 1870" },
          { id: 'b18t2rq40', type: QuestionType.SHORT_ANSWER, prompt: 'Complete the summary. Choose ONE WORD ONLY.', passage: ielts18ReadingPassage3Test2, questionText: 'His ideas are also relevant to today’s world, where building 40 ___ no longer seems to be the best approach.', correctAnswers: ['outwards'], passageHighlight: "Many scholars think that the compact city, built upwards instead of outwards, integrated with nature" },
        ]
      }
    ]
  },
  {
    id: 'b18-t2-w4',
    title: 'Test 2: Writing T1-2',
    section: Section.WRITING,
    parts: [
      {
        questions: [{
          id: 'b18t2wq1',
          type: QuestionType.WRITING_TASK,
          prompt: 'You should spend about 20 minutes on this task.',
          imageUrl: 'ielts-18/ielts-18-t2-w1-chart.png',
          task: "The chart below shows the number of households in the US by their annual income in 2007, 2011 and 2015.\n\nSummarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\nWrite at least 150 words.",
          sampleAnswer: "The graph illustrate the data of different levels of annual wage of families in the united states in 2007, 2011 and 2015.\n\nAs far as the number of families whose annual income was less than $25,000, it began with around 25 million in 2007, then increased to approximately 27 million in 2011, but decreased by 2 million 4 years later. Similarly, those of families that earned $25,000 to $49,999 were about 25 million in 2007, after that it rose to nearly 30 million in 2011. Finally it decreased to around 27 million in 2015.\n\nBy contrast, the groups of families which have high income, including $75,000 to $99,999 and $100,000 or more, experienced a drop in 2011, but their data went up in 2015.\n\nInteresting things could be seen in the group of middle income, the data remain the same in 2007, 2011 and 2015.",
          sampleAnswerBand: 5.5,
          examinerComment: "This response does present most of the data within the bar chart and the key features required. To improve the response, an overview of the information should be included, for example: Across the 8 years, households with incomes below $50,000 rose, then fell back slightly, households with incomes of over $75,000 fell slightly then increased and those with the mid-level incomes remained the same. The information is arranged coherently, starting with the details for the lower-income households, then the higher, then the mid-section. There are some effective cohesive devices [As far as | Similarly | By contrast]. The vocabulary is suitable for the task, but there is an error [>5 million / 25 million] which is not helpful when reporting the details. There is a mix of simple and complex structures, with sentences that contain multiple clauses. There are some examples of missing capitalisation [united states / United States] with some errors [remain / remained]. To improve the response, it is important to re-read to check for small errors with vocabulary and to include an overview or summary of the salient information."
        }]
      },
      {
        questions: [{
          id: 'b18t2wq2',
          type: QuestionType.WRITING_TASK,
          prompt: "You should spend about 40 minutes on this task. Write about the following topic:",
          task: "Some university students want to learn about other subjects in addition to their main subjects. Others believe it is more important to give all their time and attention to studying for a qualification.\n\nDiscuss both these views and give your own opinion.\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.",
          sampleAnswer: "Students attend university to improve their prospects and find suitable employment after graduation. For this reason, some feel that they should focus all their energy on their main subjects to gain a relevant qualification. Others want a more well-rounded education, so they try to learn about additional subjects.\n\nIt is perfectly reasonable for students to want to enter university with a strong sense of curiosity and a desire to learn as much as possible. Unfortunately, we tend to put subjects into artificial boxes, suggesting that business, art and science are not connected. If students become too focused on a single area, it may stifle their initial curiosity, limiting their potential to graduate with a very narrow skill set that doesn’t translate well to the current job market, which often favours those who have taken a multidisciplinary approach to their studies.\n\nDespite this, caution is certainly needed. If we learn about a subject, the more complex it becomes. Gaining an in-depth, specialist knowledge of a subject requires a certain level of focus and dedication over a long period. If we try to learn about too many things at once, our knowledge may lack the depth required to obtain a qualification. If they are not careful, young people could begin to lose interest in their main subjects, which would be detrimental to their studies.\n\nWhile learning about other subjects is not necessarily a bad thing, I believe university students should ensure that their main subjects remain the priority so that they do not lose sight of their objective: gaining a qualification. Then they can calculate how much time, energy and headspace they have left for learning about other topics.",
        }]
      }
    ]
  },
  {
    id: 'b18-t2-s5',
    title: 'Test 2: Speaking P1-3',
    section: Section.SPEAKING,
    parts: [
      {
        questions: [{
          id: 'b18t2sq1',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 1: Example',
          question: 'Science\n\n- Did you like studying science when you were at school? [Why/Why not?]\n- What do you remember about your science teachers at school?\n- How interested are you in science now? [Why/Why not?]\n- What do you think has been an important recent scientific development? [Why?]',
          sampleAnswer: `**1. Did you like studying science when you were at school?**\n"Yes, I really did, especially biology and chemistry. I was fascinated by how the natural world worked, from the smallest cells to entire ecosystems. Physics was a bit more challenging for me, but I enjoyed the practical experiments we did in the lab. It felt like we were uncovering secrets about how the universe operates."\n\n**2. What do you remember about your science teachers at school?**\n"I remember my biology teacher, Mrs. Evans, very clearly. She was so passionate about her subject and had a great way of making complex topics easy to understand. She used lots of real-life examples, which made the lessons much more engaging. Her enthusiasm was infectious, and she’s a big reason why I enjoyed science so much."\n\n**3. How interested are you in science now?**\n"I'm still very interested, although I don't study it formally anymore. I enjoy reading popular science articles online and watching documentaries about space exploration or new medical breakthroughs. I think it’s important to have a basic understanding of scientific issues, as they affect so many aspects of our lives, from health to the environment."\n\n**4. What do you think has been an important recent scientific development?**\n"I think the development of mRNA vaccines has been incredibly important. The speed at which they were created and deployed during the pandemic was a monumental scientific achievement. It has not only saved millions of lives but has also opened up new possibilities for treating other diseases in the future. It’s a real game-changer for medicine."`
        }]
      },
      {
        questions: [{
          id: 'b18t2sq2',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 2: Cue Card',
          question: 'Describe a tourist attraction in your country that you would recommend.\nYou should say:\n- what the tourist attraction is\n- where in your country this tourist attraction is\n- what visitors can see and do at this tourist attraction\n- and explain why you would recommend this tourist attraction.',
          sampleAnswer: `I would definitely recommend visiting the Giant's Causeway in Northern Ireland. It's a truly unique and spectacular natural wonder.\n\nIt's located on the north coast of County Antrim, right on the edge of the Atlantic Ocean. The landscape there is very dramatic, with rugged cliffs and beautiful coastal views.\n\nWhen visitors go there, they can see an incredible area of about 40,000 interlocking basalt columns, which are mostly hexagonal in shape. They look like giant stepping stones leading from the cliff foot and disappearing under the sea. It was formed by an ancient volcanic eruption, although legend says it was built by a giant. You can walk right out onto the columns, explore the different formations, and there are also some fantastic coastal hiking trails with amazing views of the coastline.\n\nI'd recommend it because it's like nothing else I've ever seen. The geometric patterns of the stones are so perfect that they look man-made, but they're completely natural. It's a UNESCO World Heritage Site, and it's just a very awe-inspiring and beautiful place. It makes you appreciate the power and beauty of nature, and the visitor centre there does a great job of explaining both the science and the myths behind it.`
        }]
      },
      {
        questions: [{
          id: 'b18t2sq3',
          type: QuestionType.SPEAKING_TASK,
          prompt: 'Part 3: Discussion topics',
          question: "Museums and art galleries\n- What are the most popular museums and art galleries in ... / where you live?\n- Do you believe that all museums and art galleries should be free?\n- What kinds of things make a museum or art gallery an interesting place to visit?\n\nThe holiday industry\n- Why, do you think, do some people book package holidays rather than travelling independently?\n- Would you say that large numbers of tourists cause problems for local people?\n- What sort of impact can large numbers of tourists have on the environment?",
          sampleAnswer: `**Museums and art galleries**\n\n**1. What are the most popular museums and art galleries in where you live?**\n"In my city, the most popular museum is probably the National Museum, which covers the country's history and culture. For art, the Gallery of Modern Art is very popular, as it has a great collection of both national and international artists. They both attract a lot of tourists as well as locals."\n\n**2. Do you believe that all museums and art galleries should be free?**\n"Yes, I strongly believe they should be. They are important cultural and educational institutions that preserve our heritage. Making them free ensures that everyone, regardless of their income, has access to them. It encourages learning and cultural enrichment for the whole society, which I think is a public good."\n\n**3. What kinds of things make a museum or art gallery an interesting place to visit?**\n"For me, interactive exhibits make a huge difference, especially in museums. They make the experience more engaging than just looking at objects in glass cases. Well-curated special exhibitions are also a big draw, as they offer something new and topical. A good café and shop also add to the overall experience, making it a nice place to spend a few hours."\n\n**The holiday industry**\n\n**4. Why, do you think, do some people book package holidays rather than travelling independently?**\n"I think the main reasons are convenience and peace of mind. With a package holiday, everything is organised for you – flights, transfers, accommodation. It removes a lot of the stress and uncertainty of planning. It can also be more budget-friendly, as tour operators can get bulk discounts. It's a simple, hassle-free option for people who just want to relax."\n\n**5. Would you say that large numbers of tourists cause problems for local people?**\n"Yes, they certainly can. Overtourism can lead to overcrowding in popular areas, which makes daily life difficult for residents. It can also drive up the cost of living, particularly housing, as properties are converted into holiday rentals. While tourism brings money into the local economy, it needs to be managed carefully to avoid these negative impacts."\n\n**6. What sort of impact can large numbers of tourists have on the environment?**\n"The environmental impact can be significant. Increased flights contribute to carbon emissions. Popular natural sites, like beaches or national parks, can suffer from erosion, pollution, and damage to fragile ecosystems from too many visitors. There's also the issue of increased waste and water consumption, which can put a strain on local resources."`
        }]
      }
    ]
  }
];